### ISSUE TITLE
Cannot hide base station or keypad from HomeKit favourites

### ISSUE THREAD

**Issue by stephendowning** [dgreif/ring#187] opened 2019-11-24 22:08 UTC
Hi, I cannot get the base station or the keypad to hide from my HomeKit favourites screen - am I doing something wrong?

I'm using the alarm and to be honest I'd like to hide everything apart from the switch to control the mode the alarm is in - I don't need to see any of the sensors in HomeKit.

Thanks!

**Comment by twennywonn** [comment] 2019-11-25 06:47
You can you just have to keep trying.  I think I ended up moving it to a room and waiting before hitting the "X" to close out.  I was able to remove them from my favorites but it took a bit.

**Comment by dgreif** [comment] 2019-11-26 03:13
This is a duplicate of #169.  I'm not sure exactly why HomeKit is so weird with these two (possible because they aren't "supported" services.  I'll consider adding a toggle to hide them, but I feel like I have way to many "hide" settings as it is.  iOS 13 seemed to do a great job with grouping devices and it seems like you could just hide them in a spare room.  Any particular reason why you want them to be hidden?

**Closed** 2019-11-30 20:51 UTC
Labels: discussion, duplicate

**Comment by dgreif** [comment] 2019-11-30 20:55
I added a new `hideUnsupportedServices` option in v`5.10.0` which will hide the base station and keypad
