### ISSUE TITLE
Large number of ‘Snapshot request handler provided empty image buffer’ - messages in the log.

### ISSUE THREAD

**Issue by nodecentral** [dgreif/ring#594] opened 2021-03-18 09:52 UTC
# Bug Report

### Describe the Bug

I’m constantly receiving loads of “Snapshot request handler provided  empty image buffer " and the Home App did not always show an image 

### To Reproduce

Nothing really, the plug-in was installed and it seems to get images - but I can see loads of this type of ‘snapshot request handler ‘ messages in the log.

### Expected behavior

I expected it would be more tolerant, and obtain image updates without issue.

### Screenshots/Logs

I have a screenshot, but can’t seem to see how to post it here?

### Homebridge Ring Config

It’s no longer installed.

### Environment
 - OS: QNAP NAS
 - Node.js:  v14.15.3
 - NPM: v6.14.9
 - homebridge-ring: v9.15.4
 - homebridge: v1.3.3

**Comment by dgreif** [comment] 2021-03-18 15:40
This is a duplicate of #592.  These messages are generated by homebridge and not something I have direct control over.  I'm working with the homebridge developers to see if there is a way to get around them, but no promises.  As far as snapshots not always being available, please read through https://github.com/dgreif/ring/wiki/Snapshot-Limitations for more information on why that's the case.

**Closed** 2021-03-19 04:31 UTC
Labels: bug

**Comment by dgreif** [comment] 2021-03-19 04:35
I talked to the homebridge developers and we were able to find a workaround to get rid of these logs.  Released in v`9.15.5`

**Comment by nodecentral** [comment] 2021-03-19 08:37
Hi @dgreif - great many thanks !
