### ISSUE TITLE
[Streaming]: 

### ISSUE THREAD

**Issue by DazzR99** [dgreif/ring#1174] opened 2023-02-26 19:59 UTC
### Streaming Issue

Ring Video Doorbell 2 is showing as “no response” in Apple Home since updating to latest version of this plugin. All worked previously to this. Not a network issue, rebooted everything just in case. 

### Proposed Solution

I wish I could help, but I’m not a code-writer! Just making you aware of this issue, which I believe is a bug. Apologies if I’m wrong!

### Environment

HOOBS

### What operating system are you on?

Mac

### Relevant log output

```shell
26/02/2023, 19:57:10HOOBS Ring BridgeRingPreparing Live Stream for Front Door
26/02/2023, 19:57:11HOOBS Ring BridgeRingStream Prepared for Front Door (0.661s)
26/02/2023, 19:57:11HOOBS Ring BridgeRingActivating stream for Front Door (0.744s)
26/02/2023, 19:57:13HOOBS Ring BridgeRingiceConnectionStateChange: completed
26/02/2023, 19:57:13HOOBS Ring BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
26/02/2023, 19:57:13HOOBS Ring BridgeRingconnectionStateChange: closed
26/02/2023, 19:57:13HOOBS Ring BridgeRingiceConnectionStateChange: closed
26/02/2023, 19:57:13HOOBS Ring BridgeRingERRORFailed to activate stream
26/02/2023, 19:57:13HOOBS Ring BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment] 2023-02-26 23:03
This is a duplicate of #1108

**Closed by dgreif** 2023-02-26 23:03 UTC
Labels: duplicate, live-streaming
