### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#114] opened 2019-08-24 21:23 UTC
I've updated, but no sound? do I need to change anything else?

**Comment by dgreif** [comment] 2019-08-24 21:24
https://github.com/dgreif/ring/wiki/FFmpeg#homebridge-audio-support

**Comment by dgreif** [comment] 2019-08-24 21:33
@adavison007 are you willing to test something out for me?  I have ffmpeg built already and I'm thinking about shipping it with the node module.  Are you running on a raspberry pi?  If so, hold off on running those install commands I linked you to.

**Comment by adavison007** [comment] 2019-08-24 22:04
@dgreif happy to try beta :) I'm running RPI and Hoobs.org

**Comment by dgreif** [comment] 2019-08-24 22:27
@adavison007 I released an alpha version that has the ffmpeg binary included.  You should be able to install it with `npm i -g  homebridge-ring@5.7.0-alpha.0` (maybe with a `sudo ` at the beginning).  If everything is good, you should have sound with not additional changes or installs.  Let me know how it works!

**Comment by adavison007** [comment] 2019-08-24 22:33
@dgreif Thats for the Alpha, installed successfully (used Sudo), but no sound still...

**Comment by adavison007** [comment] 2019-08-24 22:36
@dgreif 
<img width="2551" alt="image" src="https://user-images.githubusercontent.com/47482260/63643433-e8eabc00-c6c7-11e9-8463-93900e240cfa.png">

**Comment by dgreif** [comment] 2019-08-24 22:37
I appreciate the screenshots!  Did you restart homebridge after updating the plugin?  If so...not sure this approach will work.  I'm out of time for the day so I'll follow up tomorrow or Monday based on your response.  Thanks for testing it out!

**Comment by adavison007** [comment] 2019-08-24 22:49
@dgreif yes I did restart

**Comment by black01gt** [comment] 2019-08-24 23:54
I have no sound on my iMac install.

**Comment by Venger2005** [comment] 2019-08-25 06:38
Having same problem running on a pi after completing the install commands and rebooting - log shows same error of "streaming video only - ffmpeg was not found"

**Comment by divemasterjm** [comment] 2019-08-25 07:09
Hi, i have ffmpeg installed on my mac mini long time ago for other cameras, updated plugin and is working like a charm, no issues, only waiting for recording switch!!!!, if you need some test just tell me.

**Comment by adavison007** [comment] 2019-08-25 09:21
> https://github.com/dgreif/ring/wiki/FFmpeg#homebridge-audio-support

@dgreif did you want me to install FFMPEG, or wait for next Alpha?

**Comment by dgreif** [comment] 2019-08-25 15:31
@adavison007 I’m not sure i will be able to get a pre bundled ffmpeg to work. I think it needs other libraries from the install process that I didn’t include. If you want audio quickly, just go ahead with the install steps. Sorry for the extra work, not sure if there is a way around it at this point. I talked to the HOOBS team and they are considering having it preinstalled in their v3 image, but until then I think it’s going to be manual install for anyone who wants it. Thanks for testing the alpha!

**Comment by mikesalz** [comment] 2019-08-25 16:02
Anyone have any suggestions how to build ffmpeg with enable-libfdk-aac for a Synology docker Homebridge installation?

**Comment by adavison007** [comment] 2019-08-25 17:32
> @adavison007 I’m not sure i will be able to get a pre bundled ffmpeg to work. I think it needs other libraries from the install process that I didn’t include. If you want audio quickly, just go ahead with the install steps. Sorry for the extra work, not sure if there is a way around it at this point. I talked to the HOOBS team and they are considering having it preinstalled in their v3 image, but until then I think it’s going to be manual install for anyone who wants it. Thanks for testing the alpha!

@dgreif your instructions to install FFMPEG were perfect!  thanks, installed, using current version again and HAVE SOUND! well done, nice work!

**Comment by adavison007** [comment] 2019-08-26 17:40
> I too get the no ffmpeg error. Could it be because I run Homebridge in docker? I installed ffmpeg via SSH, but the dockerized Homebridge has its own terminal via the config UI, should I be installing it there instead? I'm confused

@ifeign I use Hoobs, I went to the hoops cli and used these instructions (hoobs is docker too) and it worked fine, took about 45 minutes.. https://github.com/dgreif/ring/wiki/FFmpeg#homebridge-audio-support

**Comment by adavison007** [comment] 2019-08-26 17:43
> > @ifeign ffmpeg does need to be available _inside_ the docker image as it can't reach outside of it's shell (intentionally). Which docker image are you using?
> 
> https://github.com/oznu/docker-homebridge

No idea, but you commands don't look like the ones from the instructions... the first one should be sudo apt-get install git pkg-config autoconf automake libtool libx264-dev

**Comment by adavison007** [comment] 2019-08-26 17:44
> > > > @ifeign ffmpeg does need to be available _inside_ the docker image as it can't reach outside of it's shell (intentionally). Which docker image are you using?
> > > 
> > > 
> > > https://github.com/oznu/docker-homebridge
> > 
> > 
> > No idea, but you commands don't look like the ones from the instructions... the first one should be sudo apt-get install git pkg-config autoconf automake libtool libx264-dev
> 
> my commands are simply to demonstrate that ffmpeg is installed.

Sorry, no idea, I just cut and paste each of the 15 or so commands one by one and it worked fine, sorry

**Comment by ifeign** [comment] 2019-08-28 23:06
I got it working! Though it seems like I had to make a bunch of compromises. The docker container I use runs Alpine Linux, and I just couldn't figure out how to enable OMX and MMAL. I'm probably going to switch to a native install of Homebridge soon, due to a few other things I want to do... however, for the curious, this is what I did:
```

# access docker container shell
cd /home/pi/homebridge
docker-compose exec homebridge sh

# install build tools
apk add git pkgconfig autoconf automake libtool x264-dev

# download and build fdk-aac
git clone https://github.com/mstorsjo/fdk-aac.git
cd fdk-aac
./configure --prefix=/usr/local --enable-shared --enable-static
make -j4
sudo make install
sudo ldconfig
cd ..

# download and build ffmpeg
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
./configure --prefix=/usr/local --arch=armel --target-os=linux --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp

```

**Comment by dgreif** [comment] 2019-08-28 23:13
@ifeign glad you got it working! Technically I don't think we have to have OMX or MMAL.  I lifted that install script from https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI and didn't change it at all.  My hope was that I would save people the headache of rebuilding everything with OMX if they needed it for another camera plugin...plus I didn't take the time to figure out _exactly_ which options we need.

As far as adding it to the wiki, I think it could be useful.  Looks like you are missing a couple steps like `./autogen.sh` and the `make` steps under ffmpeg.  Did you get it to work without those?

**Comment by ifeign** [comment] 2019-08-28 23:18
@dgreif whoops, I forgot to paste those in. Updated my previous comment to be correct. I can add it to the wiki, might as well.

After doing all this, I did find a potentially simpler method, but I don't want to undo everything just to test it (maybe later). Any other docker users out there want to give this a try? https://github.com/oznu/docker-homebridge/issues/82#issuecomment-374497842

**Comment by dgreif** [comment] 2019-08-28 23:45
[Wiki](https://github.com/dgreif/ring/wiki/FFmpeg) updated ✅.  I added MacOS, and opened up the wiki for public editing.  If anyone is able to successfully run the abbreviated alpine commands or the MacOS commands, please let me know.  I think the instructions are good enough at this point that we can close this issue.  I appreciate any help I can get from the community to improve that wiki and make it easier for others.  Big thanks @ifeign and @adavison007 for your help!

**Closed by dgreif** 2019-08-28 23:45 UTC
Labels: setup-issue

**Comment by krazyflipj** [comment] 2019-08-29 13:41
> [Wiki](https://github.com/dgreif/ring/wiki/FFmpeg) updated ✅. I added MacOS, and opened up the wiki for public editing. If anyone is able to successfully run the abbreviated alpine commands or the MacOS commands, please let me know. I think the instructions are good enough at this point that we can close this issue. I appreciate any help I can get from the community to improve that wiki and make it easier for others. Big thanks @ifeign and @adavison007 for your help!

I can confirm your MacOS commands work. I actually used those directions yesterday

**Comment by nicholasrobinson** [comment] 2019-09-01 05:35
> Anyone have any suggestions how to build ffmpeg with enable-libfdk-aac for a Synology docker Homebridge installation?

I was encountering this issue myself, running an alpine [docker-homebridge](https://www.github.com/oznu/docker-homebridge) based image on Synology. To resolve the issue I built a new docker image based on [oznu/docker-homebridge](https://hub.docker.com/r/oznu/homebridge/) with FFmpeg copied from [alfg/ffmpeg](https://hub.docker.com/r/alfg/ffmpeg).

See [https://hub.docker.com/r/nicholasrobinson/ffmpeg-homebridge](https://hub.docker.com/r/nicholasrobinson/ffmpeg-homebridge) or https://www.github.com/nicholasrobinson/ffmpeg-homebridge for more details. To get the fix on Synology, just stop your existing homebridge container and replace it with `nicholasrobinson/ffmpeg-homebridge`.

**Comment by shred86** [comment] 2019-11-25 04:30
> @ifeign glad you got it working! Technically I don't think we have to have OMX or MMAL. I lifted that install script from https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI and didn't change it at all. My hope was that I would save people the headache of rebuilding everything with OMX if they needed it for another camera plugin...plus I didn't take the time to figure out _exactly_ which options we need.

For anyone else in a similar situation, I'm running a RPi 3B with DietPi. Got to the following step:

`./configure --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp`

But was receiving an error that mmal and OMX was not found. It wasn't until I found this thread I realized I could remove `--enable-omx-rpi` and `--enable-mmal`. Everything compiles fine now and I have working audio! :)
