### ISSUE TITLE
Support for Ring Retro kit

### ISSUE THREAD

**Issue by mattb112** [dgreif/ring#248] opened 2020-01-29 16:08 UTC
# Feature Request

### Description
 A clear and concise description of the problem or missing capability... I'd like the ring retro kit to be seen by home assistant

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instuctions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dgreif** [comment] 2020-01-31 00:53
@mattb112 this is a duplicate of #192.  I'd love to get it implemented, but I need someone to run my data tool and upload the results.  Would you be willing to follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and upload the results in #192?

**Closed by dgreif** 2020-01-31 00:53 UTC
Labels: duplicate, enhancement

**Comment by mattb112** [comment] 2020-01-31 03:20
I have the Hassio integration add-on installed. If you can explain how to pull the data. I am very willing to help.On Jan 30, 2020 6:53 PM, Dusty Greif <notifications@github.com> wrote:@mattb112 this is a duplicate of #192.  I'd love to get it implemented, but I need someone to run my data tool and upload the results.  Would you be willing to follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and upload the results in #192?

**Comment by dgreif** [comment] 2020-01-31 15:30
The directions are in https://github.com/dgreif/ring/wiki/Data-Discovery

**Comment by mattb112** [comment] 2020-01-31 16:41
oops I didn't notice the non-homebridge part of the instructions. I hope this helps. Thanks for looking into it also if you need anything else let me know!
{"requiresTrust":false}},"deviceFoundTime":1580001551159,"deviceType":"sensor.contact","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true},"tampered":{"trusted":true},"tampered-cleared":{"trusted":true}},"lastCommTime":1580484998938,"lastUpdate":1580484999006,"managerId":"zwave","manufacturerName":"Ring","name":"Front Door","nextExpectedWakeup":1580498955399,"pollInterval":43200,"roomId":4,"setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":1,"tags":["sleepy","ota-lock","scanned","kitted"],"tamperStatus":"ok","zid":"5dc4384d-2038-uuid","faulted":false},{"adapterType":"zwave","batteryLevel":100,"batteryStatus":"full","categoryId":5,"commStatus":"ok","commandTypes":{"communication-poll":{"requiresTrust":false},"reconfigure.start":{"requiresTrust":false},"update-node-neighbors.start":{"requiresTrust":false}},"componentDevices":[{"rel":"4","zid":"ca6bdfba-bd3b-uuid"},{"rel":"8","zid":"f5f1f964-858b-uuid"},{"rel":"3","zid":"27ac3e7d-e5e7-uuid"},{"rel":"7","zid":"42d6f592-cbbf-uuid"},{"rel":"1","zid":"bd8e25f6-cc74-uuid"},{"rel":"5","zid":"f4862900-e57c-uuid"},{"rel":"6","zid":"c2867413-128a-uuid"},{"rel":"2","zid":"d7a4913e-5d55-uuid"}],"deviceFoundTime":1580247996754,"deviceType":"bridge.flatline","impulseTypes":{"comm.ping.received":{"trusted":false},"tampered":{"trusted":true},"tampered-cleared":{"trusted":true}},"lastCommTime":1580487782066,"lastUpdate":1580487782273,"managerId":"zwave","manufacturerName":"Ring","name":"Retrofit Alarm Kit","nextExpectedWakeup":1580514202049,"pollInterval":43200,"roomId":10,"setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":0,"tags":["sleepy","scanned","kitted"],"tamperStatus":"ok","zid":"41524824-d068-uuid"},{"adapterType":"zwave","batteryStatus":"none","categoryId":5,"commStatus":"ok","commandTypes":{"detection-test-mode.cancel":{"requiresTrust":false},"detection-test-mode.start":{"requiresTrust":false},"detection.disable":{"requiresTrust":false}},"deviceFoundTime":1580247997425,"deviceType":"sensor.zone","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true}},"lastCommTime":0,"lastUpdate":1580248074495,"managerId":"zwave","name":"Zone 4","parentZid":"41524824-d068-uuid","pollInterval":0,"relToParentZid":"4","roomId":10,"rootDevice":"41524824-d068-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":1,"tags":["hidden","sleepy","kitted","scanned"],"tamperStatus":"ok","zid":"ca6bdfba-bd3b-uuid","faulted":false,"status":"disabled"},{"adapterType":"zwave","batteryStatus":"none","categoryId":5,"commStatus":"ok","commandTypes":{"detection-test-mode.cancel":{"requiresTrust":false},"detection-test-mode.start":{"requiresTrust":false},"detection.disable":{"requiresTrust":false}},"deviceFoundTime":1580247998258,"deviceType":"sensor.zone","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true}},"lastCommTime":0,"lastUpdate":1580248074648,"managerId":"zwave","name":"Zone 8","parentZid":"41524824-d068-uuid","pollInterval":0,"relToParentZid":"8","roomId":10,"rootDevice":"41524824-d068-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":1,"tags":["hidden","sleepy","kitted","scanned"],"tamperStatus":"ok","zid":"f5f1f964-858b-uuid","faulted":false,"status":"disabled"},{"adapterType":"zwave","batteryStatus":"none","categoryId":5,"commStatus":"ok","commandTypes":{"detection-test-mode.cancel":{"requiresTrust":false},"detection-test-mode.start":{"requiresTrust":false},"detection.disable":{"requiresTrust":false}},"deviceFoundTime":1580247998719,"deviceType":"sensor.zone","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true}},"lastCommTime":0,"lastUpdate":1580248075476,"managerId":"zwave","name":"Zone 3","parentZid":"41524824-d068-uuid","pollInterval":0,"relToParentZid":"3","roomId":10,"rootDevice":"41524824-d068-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":1,"tags":["hidden","sleepy","kitted","scanned"],"tamperStatus":"ok","zid":"27ac3e7d-e5e7-uuid","faulted":false,"status":"disabled"},{"adapterType":"zwave","batteryStatus":"none","categoryId":5,"commStatus":"ok","commandTypes":{"detection-test-mode.cancel":{"requiresTrust":false},"detection-test-mode.start":{"requiresTrust":false},"detection.disable":{"requiresTrust":false}},"deviceFoundTime":1580247999120,"deviceType":"sensor.zone","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true}},"lastCommTime":0,"lastUpdate":1580248075339,"managerId":"zwave","name":"Zone 7","parentZid":"41524824-d068-uuid","pollInterval":0,"relToParentZid":"7","roomId":10,"rootDevice":"41524824-d068-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":1,"tags":["hidden","sleepy","kitted","scanned"],"tamperStatus":"ok","zid":"42d6f592-cbbf-uuid","faulted":false,"status":"disabled"},{"adapterType":"zwave","batteryLevel":100,"batteryStatus":"full","categoryId":5,"commStatus":"ok","commandTypes":{"detection-test-mode.cancel":{"requiresTrust":false},"detection-test-mode.start":{"requiresTrust":false},"detection.disable":{"requiresTrust":false}},"deviceFoundTime":1580247999836,"deviceType":"sensor.zone","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true}},"lastCommTime":0,"lastUpdate":1580358747302,"managerId":"zwave","name":"Guest Room","parentZid":"41524824-d068-uuid","pollInterval":0,"relToParentZid":"1","roomId":10,"rootDevice":"41524824-d068-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":2,"tags":["sleepy","scanned","kitted"],"tamperStatus":"ok","zid":"bd8e25f6-cc74-uuid","faulted":false,"status":"enabled"},{"adapterType":"zwave","batteryStatus":"none","categoryId":5,"commStatus":"ok","commandTypes":{"detection-test-mode.cancel":{"requiresTrust":false},"detection-test-mode.start":{"requiresTrust":false},"detection.disable":{"requiresTrust":false}},"deviceFoundTime":1580248000098,"deviceType":"sensor.zone","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true}},"lastCommTime":0,"lastUpdate":1580248074910,"managerId":"zwave","name":"Zone 5","parentZid":"41524824-d068-uuid","pollInterval":0,"relToParentZid":"5","roomId":10,"rootDevice":"41524824-d068-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":1,"tags":["hidden","sleepy","kitted","scanned"],"tamperStatus":"ok","zid":"f4862900-e57c-uuid","faulted":false,"status":"disabled"},{"adapterType":"zwave","batteryStatus":"none","categoryId":5,"commStatus":"ok","commandTypes":{"detection-test-mode.cancel":{"requiresTrust":false},"detection-test-mode.start":{"requiresTrust":false},"detection.disable":{"requiresTrust":false}},"deviceFoundTime":1580248000494,"deviceType":"sensor.zone","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true}},"lastCommTime":0,"lastUpdate":1580248075050,"managerId":"zwave","name":"Zone 6","parentZid":"41524824-d068-uuid","pollInterval":0,"relToParentZid":"6","roomId":10,"rootDevice":"41524824-d068-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":1,"tags":["hidden","sleepy","kitted","scanned"],"tamperStatus":"ok","zid":"c2867413-128a-uuid","faulted":false,"status":"disabled"},{"adapterType":"zwave","batteryLevel":100,"batteryStatus":"full","categoryId":5,"commStatus":"ok","commandTypes":{"detection-test-mode.cancel":{"requiresTrust":false},"detection-test-mode.start":{"requiresTrust":false},"detection.disable":{"requiresTrust":false}},"deviceFoundTime":1580248000899,"deviceType":"sensor.zone","impulseTypes":{"clear":{"trusted":true},"fault":{"trusted":true}},"lastCommTime":0,"lastUpdate":1580393442193,"managerId":"zwave","name":"Dining Room","parentZid":"41524824-d068-uuid","pollInterval":0,"relToParentZid":"2","roomId":10,"rootDevice":"41524824-d068-uuid","setupByPluginStatus":"complete","setupByUserStatus":"complete","subCategoryId":5,"tags":["sleepy","scanned","kitted"],"tamperStatus":"ok","zid":"d7a4913e-5d55-uuid","faulted":true,"status":"enabled"}]}]
    On Friday, January 31, 2020, 09:30:09 AM CST, Dusty Greif <notifications@github.com> wrote:  
 
 
The directions are in https://github.com/dgreif/ring/wiki/Data-Discovery
