### ISSUE TITLE
API does not recover from loss of connection for cameras

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring#616] opened 2021-04-18 16:10 UTC
# Bug Report

### Describe the Bug
Hi @dgreif.  Over the last couple of months I've had an increase in the number of reports of ring-mqtt not recovering from loss of network connectivity.  I did some of my own investigation and found that upgrading from Node v12 to v14 resolved these issues with the alarm websocket and so now alarms are working again.

However, even on the latest Node v14 version, cameras do not consistently recover from loss of network connectivity.  There don't appear to be any errors or anything like that, just that you no longer received any updates from subscribed events (dings or data updates).

### To Reproduce
I was able to reproduce this using only a slightly modified version of your example.ts file.  It was modified just to add cameraStatusPollingSeconds so that I could easily subscribe to data polling events every 20 seconds without having to trigger motion/ding events.

Then I would interrupt the connection, wait about 5-10 minutes which of course causes polling events to start and then I would re-establish the internet connection.  Sometimes polling events would recover, but, most of the time you would get the message about the  websocket reconnecting, but never again receive any polling events for any cameras.  It seems like the longer the connectivity was lost the less the chance of recovery.

I believe these problems first started to surface sometime around the HTTP2 changes but reports have been sporadic so they've been difficult to narrow down and I've only recently had enough time to actually attempt to reproduce them.

### Expected behavior
I would expect cameras to recover without intervention, just like the websocket.  Any help or hints would be greatly appreciated it.  I tried to look through the code myself but it seems pretty straightforward and it wasn't clear to me what would cause this behavior.

### Environment
 - OS: multiple (test on CentOS 8 as well as Raspbian and HassOS (inside Docker)
 - Node.js: 14.16.1
 - ring-client-api: 9.16.0

**Comment by tsightler** [comment] 2021-04-18 17:58
Did a little digging and I think this is definitely somehow related to  the HTTP2.  If I edit rest-client.js and change `http2: true` to `http2: false` in defaultRequestOptions, the camera polling recovers in just a few seconds once the network connection is reestablished.

Obviously that's not a fix, but it at least seems to provide some clue as to a direction to look.  I'll keep digging.

**Comment by tsightler** [comment] 2021-04-21 04:03
I tried setting a timeout and retry in got, but this triggered different errors that appear to be coming from bugs in got itself that would cause the process to exit.  I could set retry=0 and a reasonable timeout, but this also triggered errors in http2-wrapper, although those appear to be recoverable.  What I've found is that http2 support in NodeJS is still definitely a work-in-progress and stability isn't quite to the level of good old http 1.1 yet.

However, I think I've managed to figure out a simple workaround that I can implement in my code, although I don't fully understand why it works.  Basically, when the network connection is interrupted and the code detects that polling has stopped (no data updates for at least 3 intervals) I start calling requestUpdate() directly every 20 seconds.  As long as the network connection is unavailable this just does nothing, however, once the network connection is reestablished, after a minute or so, somehow manually calling requestUpdate() eventually triggers a data event and, after that, automatic polling seems to resume as normal.

@dgreif Any idea why this works?  I've tested it pretty extensively at this point.  A network outage of 5 minutes will kill camera polling pretty much every time without the above hack, but I've blocked the network for an hour and, with the above hack polling starts again after <60 seconds.

**Comment by dgreif** [comment] 2021-04-21 04:17
@tsightler thanks for digging so deep into this issue!  I can't say for certain why the work-around helps, but it may be that it causes enough _failed_ requests to trigger some fallback mechanism in HTTP2.  Unfortunately I don't think we can flat-out remove HTTP2 because it helped solve some earlier issues where Ring was blocking requests that came in too frequently (HTTP2 keeps the stream open for more requests to go through).  I'll give it some more thought and see what I can find over the next couple weeks.  Haven't had much free time to dig into issues like this recently, and I think some of the streaming reliability issues are slightly higher priority.  Will let you know what I find!

**Comment by tsightler** [comment] 2021-04-21 13:09
Thanks @dgreif, I understand.  I think I at least have a simple to implement workaround so I'm going to do that in my next update and see if the users who are reporting occasional loss of function after network outages see an improvement.

**Comment by dxdc** [comment] 2021-04-24 15:18
Not sure if this is helpful or not, but I am seeing similar API issues (though haven't tested the proposed HTTP2 fix). For 2 days, I could not load snapshots or videos. And, not much in the log file at all, though I have debug off.

Still the timing of the failure is very curious with this sole log entry. Maybe, an unhandled exception?

```
[4/22/2021, 10:50:58 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_REFUSED_STREAM.  Trying again in 5 seconds...
```

Also, several days before this happened, I could see 1000's of these in the log, up to 100 or so per second even. I believe this was on an earlier version, so maybe fixed already/not related, but sharing in case.

```
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
homebridge-error__2021-04-17_16-39-36.log:[4/17/2021, 4:39:23 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/xxxxx-xxxxx-0.  getaddrinfo EAI_AGAIN app.ring.com app.ring.com:443.  Trying again in 5 seconds...
```

**Comment by tsightler** [comment] 2021-07-13 00:04
As this continues to be an issue and my code hacks turned out the be insufficient to workaround the issue, I've spent what little time I have had recently trying to dig into this but haven't made much progress.

What I've found for sure is that, during a network outage, polling stops because got hangs and, if the outage lasts more than a few minutes, it generally never returns.  I've tried using timeouts in got to timeout the http2 request, but this has proven to be unreliable at best because of various issues.  Some of these issues might be fixed in newer got and http2-wrapper (although I'm not sure of this).  However, these newer tools are built using ESM vs CommonJS and I haven't been able to get them to work with ring-client-api so far although after some reading today maybe I'm starting to understand what I need to do for that.  

For testing I built a super simple test.js file which does nothing but setup a single camera, subscribe to ding events, and output them to the console.  I added a few console outputs to the requestWithRetry function in rest-client.js so that I could see the requests and responses from the polling events and then I blocked the ports and waited for the requests to start hanging.  After the hang I wait 5-10 minutes and unblock the ports.  You can see HTTPS connections established to Ring servers on port 443, but the existing hung got processes remain hung so the polling never starts again.

Setting timeouts in got for HTTP2 seems unreliable, perhaps due to a known underlying bugs in Node that still appears to exist even in Node 16.  At this point I'm not sure what else I can do.  I thought about trying to replace got with something like fetch-h2, but I see similar reports of hangs without timeouts on it as well and it just uses http2-wrapper so I'm guessing I end up with the same basic issue.

My current thought is to simply implement a timeout in the upper layer, perhaps a wrapper function for got that includes a way to timeout and abort the request so that it won't continue to block future polling requests forever.  I also considered implementing a solution that tried to detect the issue in my code and just start a new API instance from scratch, but I can't figure out how to reliably detect when the problem happens as it's totally transparent at the application layer, I just silently stop receiving the events.

I was hoping perhaps someone smarter than me might have an idea because, while I think the approach with p-timeout could provide a crude workaround to the issue, it seems less than ideal.

**Comment by tsightler** [comment] 2021-07-14 02:28
For a very hackish "fix" for this I made a change to the requestWithRetry function in rest-client.ts by replacing the following:
```
      { headers, body } = (await got(options)) as {
        headers: Headers
        body: any
      },
```

with:
```
      { headers, body } = await Promise.race([
        got(options),
        new Promise(res => setTimeout(res, 20000)) 
      ]) as {
        headers: Headers
        body: any
      },
```

This is just a crude way to timeout the request even if the got call hangs forever, but this forces a retry of the request to occur and this seems to be all it takes to shake the connection loose once things come back.  So far I've only tested it with outages up to 15 minutes, but tomorrow I'll do more extensive outage testing and see what happens after it's blocked for a few hours.

However this is already quite an improvement as previously anything over about 5-10 minutes would pretty much always break ding events, and sometimes even a short outage of 1-2 minutes would be enough based on the exact nature of the issue and whether the nature of the outage caused the got request to hang.

Of course, I'm not saying this is a fix, I know it's hackish and probably not best way to handle this issue, but it was something super easy to implement to see if it addressed the problem and, so far, the results are promising.  I'll post a new update tomorrow after more extensive failure testing.

**Comment by tsightler** [comment] 2021-07-16 01:45
Just another update, my hackish fix above seems to work with all of my testing.  I've blocked the connection for up to 12 hours and then, as soon as I unblock, everything resumes within 60 seconds or so and notifications work from that point.  This would have never happened without it.  Based on this, I've pushed out a new version of ring-mqtt that pulls in a custom version of ring-client-api with this hack to see how it does with a broader base of users.  So far no issues, but of course it's only been 1 day so we'll see.

Now, I know that is probably not the best fix, and there are still problems with it, for example, got gives unhandled promise rejections in certain failure mode (silently blocking the connection seems OK, but doing things like rejecting packets with unreachable status cause various timeouts which produce unhandledRejection in got).  Still, I can deal with those vs the request hanging forever and blocking the polling pipeline.

I'm sure someone more skilled than I am can figure out a better method to fix this, but so far so god.  I'll update again in a few weeks after ring-mqtt users that were having the most issues with this report success or failure.

**Comment by dgreif** [comment] 2021-07-19 16:21
@tsightler I really appreciate all of your effort on this issue.  I looked into it some over the weekend and was able to consistently reproduce the `The `onCancel` handler was attached after the promise settled` error from https://github.com/sindresorhus/got/issues/1489.  Even with your "fix", I still see this error.  I started diving into the `got` and `p-cancelable` code, but haven't pinned down the root cause yet.  Hopefully I can get this tracked down soon!

**Comment by tsightler** [comment] 2021-07-19 17:04
@dgrief Indeed, as I noted the above this fix is really just a hack, it will still generate the onCancel error for some (most) failure cases (mostly any case that actually resets the TCP connection), but, really, those were not the worst of the problem, it was possible to just ignore the exception and move on.  However, the problem the fix addresses is that, in some cases, got will hang forever and never return (well, effectively forever, I suppose it might eventually return) so you never even get the onCancel error.  

The easiest way to reproduce that is to create a firewall rule with "drop" vs "reject" rule in the firewall.  If you use reject, which will close the TCP socket, you'll likely get the onCancel error immediately, however, if you use drop, and leave it that way for 5 minutes or so, the call to got will likely hang forever.  This blocks the pipeline from issuing any new polling requests and so you never even receive the error.  From the perspective of the API consumer, it just invisibly stopped receiving events because, underneath one call was hung forever.

I'm pretty convinced the issue could be fixed, perhaps in http2-wrapper as I don't really think it's a got issue per-se.  It doesn't happen with http/1, as far as I can tell, and, unless I'm misunderstanding the code in got, http2-wrapper is used so that got can use an identical API for both http/1 and http/2.  I even wonder if the problem is really in Node since it still has clear issues with http2.

Anyway, the "hackish fix" works for me because I can deal with the unhandledRejection on my side with no ill effects, but I'm super glad you are looking into it more deeply.  I had started to do this as well, but it's really pushing it for my skill level.  Good luck!

**Comment by dgreif** [comment] 2021-07-24 21:45
@tsightler thanks for being patient with me on this one!  I just did some more testing and I think I have a workable fix for now.  See https://github.com/dgreif/ring/commit/5fdc0b3247f2d682fd2226b52a5f7b4c97f0e77c.  By simply disabling retries (`retry: 0`) and telling `got` to timeout after 20 seconds, it appears we can avoid getting into the unhandled error scenario.  I'm already handling retries in the `RestClient`, so having `got` do retries is fairly redundant.  This fix is also in-line with your "hack fix", but I assume `got` handles the timeout more gracefully internally.  Give it a try with `9.18.3` and let me know if you are able to recreate any issues.

**Comment by tsightler** [comment] 2021-07-25 02:03
Hi @dgreif, this is where I actually started (using got with timeout 20 and retry 0), because that seemed like the clear fix, but I still had users running into cases where got seemed to hang forever, perhaps due to an error in node itself.  That's why I ended up with the hackish fix that timed out above got instead of depending on got itself.  The silly timeout I implemented caused the existing retry logic in ring-client-api to keep calling got and this seemed to somehow tickle got into timing out the earlier hung requests. 

Now, perhaps something has changed since then, I believe I remember reading that the issue was caused by a node bug, not really an issue in got.  I'll give it another try with latest node.

**Comment by dgreif** [comment] 2021-08-12 04:21
@tsightler I finally dropped http2 again in the latest release.  I know we had issues in the past without http2, so let me know if you run into anything after updating. I've been running it in a beta for the last few days and all seems well!

**Comment by dgreif** [comment] 2021-08-14 17:25
@tsightler I think we are good to close this.  Has everything been working for you?

**Comment by tsightler** [comment] 2021-08-15 01:41
It seems to be working.  I've been doing a good bit of testing with a ring-mqtt update I've been working on and so far, it always recovers after anything I throw at it.  I have a long running test going on right now, but I think it's probably good.

**Closed** 2021-08-15 03:28 UTC
Labels: bug
