### ISSUE TITLE
v 13.2 keeps crashing and restarting

### ISSUE THREAD

**Issue by cantchooseaname8** [dgreif/ring#1538] opened 2024-11-24 02:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Upgraded to v13.2 and it keeps crashing and restarting over and over. Downgrading back to v13.1 solves the issue. Below are the logs. Most irrelevant logs about my many accessories were removed to show the process ending and starting over and over.

### Expected behavior

v13.1 maintained a stable connection, but v13.2 keeps crashing.

### Relevant log output

```shell
[11/23/2024, 9:43:16 PM] [homebridge-ring] Restarting Process...
[11/23/2024, 9:43:16 PM] [homebridge-ring] Launched child bridge with PID 26870
[11/23/2024, 9:43:16 PM] [homebridge-ring] Loaded homebridge-ring v13.2.0 child bridge successfully
[11/23/2024, 9:43:16 PM] [homebridge-ring] Configuring cached accessory 00766504-6cd6-400b-b96b-93561375a6f0 Landscape
[11/23/2024, 9:43:16 PM] [homebridge-ring] Configuring cached accessory a906b654-740c-46bc-b52c-ff408680234e Garage Downlights
[11/23/2024, 9:43:18 PM] [homebridge-ring] Found the following locations:
[11/23/2024, 9:43:18 PM] [homebridge-ring]   locationId:
[11/23/2024, 9:43:18 PM] [homebridge-ring] Creating location socket.io connection - 
[11/23/2024, 9:43:21 PM] [homebridge-ring] Ring connected to socket.io server
[11/23/2024, 9:43:22 PM] [homebridge-ring] Configuring 0 cameras and 46 devices for location 
[11/23/2024, 9:43:22 PM] [homebridge-ring] Hidden accessory 8533af49-379c-4e96-b922-5c5391079255 chime_pro Chime Pro
[11/23/2024, 9:43:23 PM] [homebridge-ring] Child bridge process ended
[11/23/2024, 9:43:23 PM] [homebridge-ring] Process Ended. Code: 1, Signal: null
[11/23/2024, 9:43:30 PM] [homebridge-ring] Restarting Process...
[11/23/2024, 9:43:31 PM] [homebridge-ring] Launched child bridge with PID 26887
[11/23/2024, 9:43:31 PM] [homebridge-ring] Loaded homebridge-ring v13.2.0 child bridge successfully
[11/23/2024, 9:43:31 PM] [homebridge-ring] Configuring cached accessory 00766504-6cd6-400b-b96b-93561375a6f0 Landscape
[11/23/2024, 9:43:31 PM] [homebridge-ring] Configuring cached accessory a906b654-740c-46bc-b52c-ff408680234e Garage Downlights
[11/23/2024, 9:43:33 PM] [homebridge-ring] Found the following locations:
[11/23/2024, 9:43:33 PM] [homebridge-ring]   locationId:
[11/23/2024, 9:43:33 PM] [homebridge-ring] Creating location socket.io connection
[11/23/2024, 9:43:35 PM] [homebridge-ring] Ring connected to socket.io server
[11/23/2024, 9:43:36 PM] [homebridge-ring] Configuring 0 cameras and 46 devices for location "Thousand Oaks" - locationId: 9q5c2f-1r6ia-0
[11/23/2024, 9:43:36 PM] [homebridge-ring] Hidden accessory aa0bf53f-3312-493c-8626-39d9d17d91cc group.light-group.beams Floodlight
[11/23/2024, 9:43:38 PM] [homebridge-ring] Child bridge process ended
[11/23/2024, 9:43:38 PM] [homebridge-ring] Process Ended. Code: 1, Signal: null
```

### Homebridge Ring Config

```shell
{
    "refreshToken":
    "alarmOnEntryDelay": true,
    "hideLightGroups": true,
    "hideInHomeDoorbellSwitch": true,
    "hideAlarmSirenSwitch": true,
    "hideDeviceIds": [
        "b46a9713-19aa-4838-a2dc-fd19be8488e3",
        "aae08fdf-aa4f-4bd7-a74a-80cef405baa7",
        "8533af49-379c-4e96-b922-5c5391079255",
        "703d3582-101e-4e48-8f3b-ceeecfb17e4f",
        "ae1ab059-8693-4a44-b499-40593a8b4d27",
        "aaf20bb9-746f-4fad-bcc8-f595aa4711db",
        "def3dda1-16bb-4ea8-b175-bd27da4119a7",
        "07a04a55-6d97-4e25-a75c-3cdc40e67c4a",
        "2a6dd443-50e9-4a8f-b201-27e2a4d8ad83",
        "0f9ae647-c04b-49a2-9aea-4261143637a5",
        "b567fe23-f8b7-4d41-bb66-f326b4941c59",
        "ec9be2df-5b3f-49a0-954b-449cf2a4b6b1"
    ],
    "locationIds": ["
    ],
    "platform": "Ring",
    "_bridge": {
        "username":
        "port": 46745
    }
}
```

### OS

Ubuntu (using docker)

### Node.js Version

v20.18.0

### NPM Version

-

### Homebridge/HOOBs Version

v1.8.5

### Homebridge Ring Plugin Version

v13.2

### Operating System

Ubuntu (using docker)

**Comment by tsightler** [comment] 2024-11-24 03:06
Unfortunately, there is nothing useful in the log as there is no reason for the crash.  Without a stack trace there's not much to go on.

However, can you please try the 13.2.1-beta.0 released yesterday.  It might also be worth upgrading to NodeJS 22.

**Comment by cantchooseaname8** [comment] 2024-11-24 03:23
I did try 13.2.1-beta.0 and the same thing kept happening. I also just upgraded to nodejs 20 and tried both versions again with the same result. Reverting back to 13.1 fixes it.

**Comment by tsightler** [comment] 2024-11-24 03:26
Yes, I was hoping for Node 22 though.  I don't really understand what could have changed that would cause a crash like this, there really aren't any major changes between the two versions, just some very minor things and dependency updates.  Most of the significant changes are with cameras (like ffmpeg bump/werift) and you don't even appear to have cameras.

Regardless, without a trace of the crash, there's not anything actionable here, so I'm not sure how we can proceed.

**Comment by cantchooseaname8** [comment] 2024-11-24 03:31
Is there anything I can do on my end or any other logs I can try to pull that would help?

**Comment by tsightler** [comment] 2024-11-24 03:35
It would be really useful to see full logs, including base homebridge logs, not just the subset you shared.  Also, maybe there would be more information if you enabled debug in the Homebridge config and plugin config.

**Comment by cantchooseaname8** [comment] 2024-11-24 03:38
I also just noticed this the logs and appears to be coming from the ring plugin. No clue if it's related though.

`(node:3437) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ON_READY listeners added to [EventEmitter]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:593:17)
    at EventEmitter.addListener (node:events:611:10)
    at PushReceiver.on (/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/emitter.ts:19:23)
    at PushReceiver.onReady (/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:87:21)
    at /homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:113:34
    at new Promise (<anonymous>)
    at PushReceiver.connect (/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:112:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by cantchooseaname8** [comment] 2024-11-24 03:42
I enabled debug and this also shows

`Error: Client destroyed
    at PushReceiver.#clearReady (/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:197:32)
    at PushReceiver.destroy (/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:127:25)
    at PushReceiver.#socketRetry (/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:238:14)
    at PushReceiver.#handleSocketClose (/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:229:26)
    at TLSSocket.<anonymous> (/homebridge/node_modules/homebridge-ring/node_modules/@eneris/push-receiver/src/client.ts:108:63)
    at TLSSocket.emit (node:events:531:35)
    at node:net:339:12
    at TCP.done (node:_tls_wrap:648:7)`

**Comment by tsightler** [comment] 2024-11-24 04:00
Reading between the lines of those two errors, my suspicion is that this is caused by changes in push-receiver that were implemented to make it try to connect forever.  Full logs from both 13.1 and 13.2 would be useful to try to follow the flow as I can't do this with log snippets.

**Comment by tsightler** [comment] 2024-11-24 17:41
I did a bit of troubleshooting and can reproduce a crash if I reject connections on TCP port 5228 at my firewall.  My guess is you are leveraging some type of DNS based adblock that is blocking resolution of mtalk.google.com, maybe something like Adguard DNS or perhaps PiHole.  See https://github.com/dgreif/ring/issues/1306#issuecomment-1712405921 for a similar issue and how the user resolved it.

As to why it worked in versions prior to 13.1.0, those versions would have produced the connection error, but did not have the onReady promise that was introduced in upstream and, realistically, so push notifications were likely not working for your prior version either, but wouldn't have caused a crash as the older push-receiver library did not include a promise rejection for socket connection failures.  This wouldn't have caused any problem with functionality in your case because push notifications are not used for hub devices, only devices like cameras/intercoms, which you don't appear to have (this may change in the future as there is some useful information for alarm available in push notifications).

I think I can code up a simple fix to keep the crash from happening, but you should determine why your environment can't connect to TCP port 5228.

**Comment by cantchooseaname8** [comment] 2024-11-24 18:25
Interesting. I just searched my firewall logs for anything related to mtalk.google.com and all of that traffic flows through on TCP 5228 and not a single one is blocked. So TCP 5228 appears to be open and working as normal. I also turned off everything related to any type of ad blocking and I still get the crashes. It's seems to be something else happening.

**Comment by tsightler** [comment] 2024-11-24 18:34
Again, full logs would help, not just snippets that you believe are important.  We won't make much progress without them.  The error above is clearly from push-receiver having the socket connection closed.

**Comment by cantchooseaname8** [comment] 2024-11-24 18:51
Sure thing. Here are the logs with 13.1 running and then the switch to 13.2. Debug is turned on for the logs. Thanks for taking a look.
[homebridge-ring.log.txt](https://github.com/user-attachments/files/17894471/homebridge-ring.log.txt)

**Comment by tsightler** [comment] 2024-11-24 18:54
Thanks, I'll dig through them and see if I can get any other clues.  The issue here is that I can't actually figure out a way to trap this in ring-client-api, and we really need to fixes in the newer push-receiver, so now I'll probably have to open an issue in upstream and try to get yet another fix put in there.

**Comment by cantchooseaname8** [comment] 2024-11-24 18:55
If you need anything else on my end to troubleshoot, just let me know.

**Comment by tsightler** [comment] 2024-11-24 19:19
Logs show that 13.1.0 also crashes, just not as often, and there are still issues with connection from push receiver even there.  Maybe when you disabled adblock the DNS block results were still cached.   Not that we don't need to try to fix this crash, but something in your network is causing this behavior.  Maybe a router reboot or something would help.

It is weird that your not really seeing the full debug information I would expect.  Do you definitely have debug enabled in Homebrdige settings as well (and have restarted).  It might be interesting if you set the NODE_DEBUG=net environemnt on your docker container so we can see the network level debug data.

If you are uncomfortable sending full logs in an open forum, you can send them to me via email (same username at gmail).

**Comment by tsightler** [comment] 2024-11-24 19:28
A thought, perhaps this issue is not actually network level, but rather authentication with push receiver failing.  Have you fully re-initialized your authentication since upgrading to 13.x versions of the plugin, by stopping the plugin, deleting the device from Ring Control Center, and then re-authenticating?

**Comment by tsightler** [comment] 2024-11-24 19:45
If you set NODE_DEBUG in the docker compose I would still expect that extra debugging to appear in the Homebridge UI logs.

As I already explained, 13.2 includes a new push-receiver which creates an unhandled promise on socker disconnect, so that crash is happening every single time your push connection is disconnected, which should not happen often under normal operation.  That is different from the prior version, which would not create this crashing behavior, but there is still at least one crash in 13.1 in the logs you sent.

The problem is, the logs you sent don't include the crash traces in many cases, so it's very difficult to know the cause.  I'm not sure why your logs are missing these details.  It feels like maybe plugin logs vs full homebridge logs.

**Comment by cantchooseaname8** [comment] 2024-11-24 19:59
Ok I just emailed you the full homebridge logs after adding the environment variable to my docker compose and redeploying the stack.

**Comment by tsightler** [comment] 2024-11-24 20:54
Thanks, I received them, although I don't see the node debugging I would expect.

Regardless, one workaround you can use for now is to set "--unhandled-rejections none" in NODE_OPTIONS in the Homebridge settings.  That will keep the thrown error from causes the process to crash.  I've opened an upstream issue to try to get that resolved, but it will take time to get a fix upstream, get it incorporated into ring-client-api, etc.

**Comment by cantchooseaname8** [comment] 2024-11-24 20:59
Got it. I just set --unhandled-rejections none as you suggested, upgraded to 13.2 and the crashes stopped. I'll keep that setting for now. Thank you for your help with this.

**Comment by dgreif** [comment] 2024-12-02 18:06
@cantchooseaname8 would you mind giving `13.2.1-beta.1` a try? @tsightler added a fix which _should_ prevent these unhandled rejections from happening 🤞. You should be able to remove the ` --unhandled-rejections` option after updating

**Comment by cantchooseaname8** [comment] 2024-12-02 19:09
No problem. I just updated to that beta and removed --unhandled-rejections. I'm now getting a different error. This keeps repeating over and over:
[12/2/2024, 2:06:20 PM] [homebridge-ring] Client destroyed
[12/2/2024, 2:06:31 PM] [homebridge-ring] Connection to the push notification server has failed unexpectedly
[12/2/2024, 2:06:31 PM] [homebridge-ring] If this happens repeatedly, verify connections to TCP/5228 are allowed and that DNS Adblock rules allow gtalk.google.com
[12/2/2024, 2:06:31 PM] [homebridge-ring] Client destroyed

My firewall logs show that TCP 5228 has traffic passing through without anything being blocked, so I don't think that's the cause. Not sure if there's something else though. I also removed any adblocks just to be safe, but I still get that error repeating.

**Comment by tsightler** [comment] 2024-12-02 19:37
Yes, this is expected since the root cause of the problem is not solved, i.e. your system is unable to connect to the Firebase push notification servers, for whatever reason.  Previously however, this would cause the system to crash, now these errors are logged as they should be.  You must still troubleshoot the cause of the error in question.  This would have been happening silently even for previous versions of the plugin.  The crash itself was introduced in 13.2.0, due to upstream changes, but the problem would have existed in previous versions and simply failed to be logged.  With 13.2.1-beta.1 the crash is prevented, but the malfunction is logged.

In the end, *something* is causing the websocket connection to FCM servers to fail.  I've seen this in probably a dozen other cases and it has, to this point, never failed to be network related.  I've seen some people get this because they are running servers in clouds or VPNs, which FCM servers may block.

Assuming you haven't already followed the standard [Notification Troubleshooting Steps](https://github.com/dgreif/ring/wiki/Notification-Troubleshooting), you could try those as that will reset the push credentials in case that is the issue, but normally, if credentials where the issue, it would not even get to the point of attempting to establish the websocket connection.

**Comment by cantchooseaname8** [comment] 2024-12-02 19:59
Understood. I'll take a close look at my network and firewall to make sure everything is routing correctly. Thanks for your help!

**Comment by tsightler** [comment] 2024-12-02 20:09
@cantchooseaname8 As another way to troubleshoot and see if it's at least making the initial connection, you can open the terminal in the Homebridge UI and run the following:

```
$ ping mtalk.google.com
PING mobile-gtalk.l.google.com (108.177.122.188) 56(84) bytes of data.
64 bytes from ym-in-f188.1e100.net (108.177.122.188): icmp_seq=1 ttl=56 time=11.8 ms
64 bytes from ym-in-f188.1e100.net (108.177.122.188): icmp_seq=2 ttl=56 time=14.9 ms
64 bytes from ym-in-f188.1e100.net (108.177.122.188): icmp_seq=3 ttl=56 time=14.6 ms
```

Obviously you might get a different IP address.  One thing I've seen in some other cases, mtalk.google.com will resolve to IPv6 addresses, but I've seen tons of firewalls not configured properly for IPv6.  For example, some will silently drop the packets, which will make the socket connection take too long to start up and it will timeout, causing the process to repeat.  So that's one thing to check.  Or maybe the IPv6 rules don't allow 5228, for example.

If a ping looks good and is resolving to valid IP addresses, then you can try this:

`$ (echo >/dev/tcp/mtalk.google.com/5228) &>/dev/null && echo "Port is open" || echo "Port is closed"`

This will attempt to connect to port 5228 and should report if it least the base level TCP connection can be estabished.

I've also had one report of a customers firewall, which had an IPS/IDS (Intrusion Detection/Prevention) setup running which was actually blocking the connection later in the process so perhaps that's something to check.  In that case it was some Snort rule.  A few users have reported just a router reboot/power cycle solved the problem.

I'm happy to try to help more, but there's not much going on here at a basic level, the code just gets the auth data and calls the API to open a websocket, the websocket either stays connected or it doesn't, and, every time the connection fails, it tries again.

**Comment by cantchooseaname8** [comment] 2024-12-03 06:26
Thank you! I put my firewall into “emergency access” mode which basically just pauses all rules, routes, etc. The error disappeared after doing that so it’s definitely something with my firewall. Even though it’s not blocking that particular port, there must still be something going on at some point in the process that is making it finicky. I’ll go through and start bringing everything back one by one to hopefully narrow it down.

**Comment by tsightler** [comment] 2024-12-03 14:12
Thanks for reporting back.  Would love to hear what the final solution turns out to be as, while issues with push service connectivity are fairly rare, they do happen, and it seems like the cause is always something unexpected.

**Comment by cantchooseaname8** [comment] 2024-12-05 16:51
I'm honestly not sure where the issue was. It might have been buried in a list or custom route somewhere in my firewall. I ended up just adding a new custom route for that specific traffic so I know it's being handled exactly as it should be. Everything is still working great now. Thanks again for all of your help with this!

**Closed** 2024-12-05 16:55 UTC
Labels: bug

**Comment by rionshin** [comment] 2024-12-08 20:58
@tsightler  I am using 13.2.1 and  I am getting the same error, however my firewall is open and custom routing is created. 


When i run the command i can see the port is open 
homebridge@yasha:/var/lib/homebridge $ (echo >/dev/tcp/mtalk.google.com/5228) &>/dev/null && echo "Port is open" || echo "Port is closed"
**Port is open**


I stoped the Network Intrusion detection and DNS filtering but behavior continue, and i keep getting the error.  
you can see the DNS is responding :
homebridge@yasha:/var/lib/homebridge $ ping mtalk.google.com
PING mobile-gtalk.l.google.com (142.251.175.188) 56(84) bytes of data.
64 bytes from mtalk.google.com (142.251.175.188): icmp_seq=1 ttl=60 time=325 ms
64 bytes from mtalk.google.com (142.251.175.188): icmp_seq=2 ttl=60 time=326 ms
64 bytes from mtalk.google.com (142.251.175.188): icmp_seq=3 ttl=60 time=326 ms
64 bytes from mtalk.google.com (142.251.175.188): icmp_seq=4 ttl=60 time=326 ms
64 bytes from mtalk.google.com (142.251.175.188): icmp_seq=5 ttl=60 time=326 ms
64 bytes from mtalk.google.com (142.251.175.188): icmp_seq=6 ttl=60 time=326 ms
64 bytes from mtalk.google.com (142.251.175.188): icmp_seq=7 ttl=60 time=325 ms
64 bytes from mtalk.google.com (142.251.175.188): icmp_seq=8 ttl=60 time=326 ms
^C
--- mobile-gtalk.l.google.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7000ms
rtt min/avg/max/mdev = 325.437/325.616/325.702/0.089 ms
 

@cantchooseaname8  what custom rule do you add, i use Unifi and added custom rule by domain from my internal network to all connection to mtalk.google.com .

**Comment by rionshin** [comment] 2024-12-08 21:04
I found the reason for the issue -  its the DNS that return the IP for the mtalk.google.com - some of them are not responsive. Clearing cache of DNS fix the issue 
homebridge@yasha:/var/lib/homebridge $ ping mtalk.google.com
PING mobile-gtalk.l.google.com (173.194.79.188) 56(84) bytes of data.
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=1 ttl=60 time=35.9 ms
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=2 ttl=60 time=36.3 ms
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=3 ttl=60 time=36.2 ms
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=4 ttl=60 time=36.3 ms
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=5 ttl=60 time=35.8 ms
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=6 ttl=60 time=35.9 ms
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=7 ttl=60 time=36.0 ms
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=8 ttl=60 time=36.0 ms
64 bytes from eg-in-f188.1e100.net (173.194.79.188): icmp_seq=9 ttl=60 time=35.8 ms

**Comment by tsightler** [comment] 2024-12-08 21:09
> time=326 ms

I was going to ask why ping was so high, like it's picking some server far away from you.  As mtalk.google.com is a highly distributed service, I would expect low latency pings for pretty much anyone.

Also, the DNS lifetime for mtalk.google.com is only 180 seconds so that would imply some local DNS caching is not honoring the lifetime.  You can always use dig and other tools to further into DNS issues.

**Comment by rionshin** [comment] 2024-12-08 21:32
> > time=326 ms
> 
> I was going to ask why ping was so high, like it's picking some server far away from you. As mtalk.google.com is a highly distributed service, I would expect low latency pings for pretty much anyone.
> 
> Also, the DNS lifetime for mtalk.google.com is only 180 seconds so that would imply some local DNS caching is not honoring the lifetime. You can always use dig and other tools to further into DNS issues.

Yeah , it appears some of the DoH servers was returning address that is far away from me.  I notice when pinging from my UniFi router I always have 30ms and IP located on google regional network, and for some reason the raspberry where is HB had  cached this IP and always ping it and try to connect it - and most probably it was IP not for my region and it rejects me.  I have such behavior in the past when using DoH servers and not my provider DNS sometimes they don’t honor where I am located and give me IP which if for Asia Pacific for example . 
 
Thank you and have a great evening !

**Comment by tsightler** [comment] 2024-12-09 00:54
Out of curiosity, where were you configuring DoH?  Something on Unifi or some internal DNS proxy like PiHole or something else?  Just kind of curious as it might help future users as well.

**Comment by rionshin** [comment] 2024-12-09 10:38
> Thanks for sharing! Out of curiosity, where were you configuring DoH? Something on Unifi or some internal DNS proxy like PiHole or something else? Just kind of curious as it might help future users as well.

Both options are possible in Unifi router, in Unifi Settngs - Security you can use build in list of SoH servers or you can add your own server which can be Adguard or Pihole.  I use  build in servers as they are kinda the same as in AdGuard.   
I disable DOH for testing to get the  DNS reply from my provider DNS , and  clear dns cache on the client (my Raspberry). 

![Screenshot 2024-12-09 at 12 36 58](https://github.com/user-attachments/assets/49c99298-5ff6-4e88-926b-69eeae8a52bb)
