### ISSUE TITLE
Notifications issue

### ISSUE THREAD

**Issue by dpamping** [dgreif/ring#1360] opened 2023-11-13 18:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When the doorbell is pressed HomePods do the ding sound but no notification is send on the phones. Before it appeared, but a week ago it stopped. Maybe because I was on the month trial of the ring plan? I've tried to reinstall the plugin but same issue.

### Expected behavior

Notification should appear on phones when the doorbell is pressed.

### Homebridge Ring Config

```shell
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "refreshToken": "",
            "hideAlarmSirenSwitch": true
        }
    ]
}
```

### OS

--------

### Node.js Version

16.14.2

### NPM Version

------

### Homebridge/HOOBs Version

1.4.0

### Homebridge Ring Plugin Version

12.0.1

### Operating System

-----

**Comment by tsightler** [comment] 2023-11-13 18:54
If the homepods "do the ding sound" then it seems like the plugin is receiving the event and notifying Homekit and I don't think there's anything that can be done from the plugin perspective to help your case.  You can double check the logs to see what exactly is happening on a ding and that might provide some clues but, overall, if the logs show the event, then the problem is not in the plugin.

**Comment by tsightler** [comment] 2023-11-14 00:15
This might be normal if you have a battery/low-power doorbell because those cameras can't take a snapshot while recording so the code as written waits for a notification that contains the UUID, however, you will never get such a notification if you don't have a subscription since Ring requires a subscription to get push notifications with images.  You didn't specify your camera model so I don't know for sure if this applies to you or not, but that's the only thing I could think of that might cause a delay.

**Comment by dpamping** [comment] 2023-11-14 00:21
I have the ring wired doorbell

**Comment by tsightler** [comment] 2023-11-14 00:56
Ring has several wired doorbells and a confusing list of models, not all are created equal, it sounds like you mean this one:

https://ring.com/products/video-doorbell-wired

That is basically a battery doorbell without the battery (it's the low-powered battery based hardware, with a think a super capacitor that trickle charges) so you will get delayed notifications without a subscription.   The code normally tries to detect if a camera is operating in battery mode, but because that camera pretends to be a wired camera even though it has all the limitations of a battery camera, the check fails so it ends up trying to take a snapshot when it can't and has to time out before sending the notification.

There is a queued up PR https://github.com/dgreif/ring/pull/1280 from another user that at least would make the notifications go faster (with no image) in this case, but I haven't had time to put together a new version or review all of this stuff lately.

Recommend just using the Ring app in the interim, or get a subscription (Ring cameras are quite limited without one, especially the battery/low-powered devices).

Since the problem is understood and there is a fix pending I'm going to close this as by design for now.  It may say "won't fix" but we will try to fix it in the future, just don't know how long it will be before there is time to pull a new release together, there's quite a backlog at the moment.

**Closed by tsightler** 2023-11-14 00:56 UTC
