### ISSUE TITLE
MaxListenersExceededWarning No events are triggering

### ISSUE THREAD

**Issue by 97WaterPolo** [dgreif/ring#1306] opened 2023-09-05 04:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

So starting about a week ago all events stopped going to my application, it hasn't changed in the last year or so but something happened (not sure what day exactly) where all the events are coming through. I first thought that there was an update to the Ring API and I'd have to update the ring-api-cli npm version (which I've done in the past and it works), but this time I was debugging locally and on the deployed server and I am getting a warning stating "MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ON_READY listeners added to [PushReceiver]. Use emitter.setMaxListeners() to increase limit", I ran it with --trace-warnings and got the following stacktrace.

Looks like it has something to do with the @eneris\push-receiver library, my package.json is pretty clean with only this library and axios as a depedency. Any help would be appreciated.

```
{
  "name": "ringlistener",
  "version": "1.0.0",
  "description": "",
  "main": "server.mjs",
  "dependencies": {
    "axios": "^0.21.1",
    "ring-client-api": "^12.0.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

```

```
import {RingApi} from 'ring-client-api'
import * as ringTokenLoader from './RingTokenLoader.js';
import * as configLoader from './ConfigLoader.js';
import * as webPost from './WebPost.js';
var config = configLoader.generateConfig();
var currentToken = ringTokenLoader.generateConfig();
var lastRunTime = new Date();
start();
async function start() {
    console.log("Starting Ring Listener at the time " + (new Date()).toISOString());
    if (currentToken == null){
        console.log("Current Token is null");
        return;
    }
    const ringApi = new RingApi({
        refreshToken: currentToken,
        cameraDingsPollingSeconds: 2
    });
    const allCameras = await ringApi.getCameras();
    console.log(
        `Found ${allCameras.length} camera(s).`
    )

    ringApi.onRefreshTokenUpdated.subscribe(
        async ({newRefreshToken, oldRefreshToken}) => {
            console.log('Refresh Token Updated: ');
            if (!oldRefreshToken) {
                console.log("It returned cause not oldRefreshToken: " + oldRefreshToken);
                return
            }
            currentToken = ringTokenLoader.writeRefreshToken(newRefreshToken);
        }
    )
    if (allCameras.length) {
        allCameras.forEach((camera) => {
            camera.onMotionDetected.subscribe((data) => {
               console.log("Motion was detected AT " + (new Date()).toISOString());
            });
            camera.onDoorbellPressed.subscribe((data) => {
                console.log(
                    `Ring doorbell pressed on ${camera.name} camera. Ding id ${
                        data.ding.riid
                    }.  Received at ${new Date()}`
                )
            })
        })

        console.log('Listening for motion and doorbell presses on your cameras.')
    }
}
```

### To Reproduce

Not sure but I stripped my application down to the bare minimum, just events listing for tokenRefresh, motion, and doorbell press. Leaving the application running triggers the stacktrace below after about 30 seconds, and any event committed on the ring device shows up on my phone, but nothing is received on these events from the node app.

Also the two "Motion was detected AT*" messages happen on every startup, regardless if there is motion or any other type of ding. It doesn't actually signify a motion that was recorded

```
Configuration file found at /mnt/RingConfig.json
Configuration file found at /mnt/RingListener.cfg
Starting Ring Listener at the time 2023-09-05T04:02:31.041Z
Found 2 camera(s).
Refresh Token Updated: 
Updated new refresh token
Motion was detected AT 2023-09-05T04:02:31.967Z
Motion was detected AT 2023-09-05T04:02:31.967Z
Listening for motion and doorbell presses on your cameras.
(node:23020) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ON_READY listeners added to [PushReceiver]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at PushReceiver.addListener (node:events:605:10)
    at PushReceiver.on (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:78:51)
    at PushReceiver.onReady (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:96:14)
    at Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:127:34
    at new Promise (<anonymous>)
    at Timeout.connect [as _onTimeout] (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:126:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected behavior

That the events fire and I get the message logged to console.

### Relevant log output

```shell
Configuration file found at /mnt/RingConfig.json
Configuration file found at /mnt/RingListener.cfg
Starting Ring Listener at the time 2023-09-05T04:02:31.041Z
Found 2 camera(s).
Refresh Token Updated: 
Updated new refresh token
Motion was detected AT 2023-09-05T04:02:31.967Z
Motion was detected AT 2023-09-05T04:02:31.967Z
Listening for motion and doorbell presses on your cameras.
(node:23020) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ON_READY listeners added to [PushReceiver]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at PushReceiver.addListener (node:events:605:10)
    at PushReceiver.on (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:78:51)
    at PushReceiver.onReady (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:96:14)
    at Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:127:34
    at new Promise (<anonymous>)
    at Timeout.connect [as _onTimeout] (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:126:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional context

Not sure, its correctly authenticating since I saw it fail with invalid refresh token when I first started, but I never see the refresh token update or get a new one, which makes me think its never actually listening to any events from Ring as I know the refresh tokens expires pretty fast once its used.

### OS

Windows, Docker

### Node.js Version

v18.14.1

### NPM Version

v9.5.0

### ring-client-api

v12.0.0

### Operating System

Docker

**Comment by tsightler** [comment] 2023-09-05 13:54
I think the `MaxListenersExceededWarning` is just a red herring as it is just a warning which is issued any time there are more than 10 listeners for the same event emitter.  The warning is issued only because some NodeJS developers arbitrarily decided that more than 10 listeners for the same event **_might_** be indicative of a leak, which is technically true, it might be, but in this case it is not (not saying the could couldn't potentially be improved).  However, it is just a warning and there is no actual limit on the number of listeners so there should be no negative side effects caused by this message as Node does not actually stop more listeners.

This theory is bolstered by the fact that push-receiver has been used as part of ring-client-api since v11 was introduced, with relatively few changes (a few minor bug fixes), but you state that the problem occurred only recently.

As it did happen recently, my guess is that you are impacted by the changes that were introduced in the Ring API back in May or so.  These changes meant that, any time a re-authentication occurred, push messages would stop working because ring-client-api versions prior to v11.8.0 did not persistently store the GCM/FCM registration credentials.  In v11.8.0 and later these credentials are generated during the initial connection to the Ring API after initial token generation, and are stored as part of updated refresh tokens.

So, my questions, did you follow the [Steps to fix notifications](https://github.com/dgreif/ring/wiki/Notification-Troubleshooting#steps-to-fix-notifications) documented in the wiki already (you didn't mention them)?  It is critical that you do this **_after_** you updated to ring-client-api v11.8.0 or later (ideally v12.0.0 at this point).  If you did it before, it's no good as the GCM/FCM would already be lost.  Also, you _**must**_ listen for `onRefreshTokenUpdated` and save the updated tokens for future use, otherwise, notifications will break again on the next restart of your application because you will lose the persistent GCM/FCM token.

**Comment by 97WaterPolo** [comment] 2023-09-06 03:51
Thanks for the heads up about MaxListenersExceededWarning, I wasn't sure as that was the only error that popped up.

I went through the notification wiki and performed all the steps, I removed all devices (it was right there was a lot of ring-client-api) and then regenerated the refreshToken with the ring-cli. It prompted me for the 2fa code and I once again see a single entry of "ring-client-api" in the Control Center.

I tried restarting my application, and testing it using my docker container on Windows and Linux, still the same issue. It is correctly authenticating as the old refreshToken threw an error, but it has the same issue, no notifications are coming through. The only difference in the logs below is that the RefreshTokenUpdated event is called twice compared to before the change where it was only called once.

```
Configuration file found at /mnt/RingConfig.json
Configuration file found at /mnt/RingListener.cfg
Starting Ring Listener at the time 2023-09-06T03:42:37.302Z
Found 2 camera(s).
Refresh Token Updated: 
Updated new refresh token
Motion was detected AT 2023-09-06T03:42:38.204Z
Motion was detected AT 2023-09-06T03:42:38.204Z
Listening for motion and doorbell presses on your cameras.
Refresh Token Updated: 
Updated new refresh token
(node:9496) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ON_READY listeners added to [PushReceiver]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at PushReceiver.addListener (node:events:605:10)
    at PushReceiver.on (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:78:51)
    at PushReceiver.onReady (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:96:14)
    at Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:127:34
    at new Promise (<anonymous>)
    at Timeout.connect [as _onTimeout] (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:126:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

Any other thoughts or suggestions on what I can provide to help reliably create this and figure out what's happening?

**Comment by tsightler** [comment] 2023-09-06 12:19
Hi, thanks for the details.  I do find it interesting that you are seeing this EventEmitter message with only 2 cameras as I've never seen it with such a small number of devices.

One strange observation/question, why are you using such an outdated axios version?  The push-receiver package also uses Axios, but much newer version (1.4.0, current is 1.5.0).  I'm not saying that is the issue here, but sometimes those old versions have unexpected behavior when interacting with newer code.

I will attempt to reproduce on my own system and see what happens.

**Comment by 97WaterPolo** [comment] 2023-09-07 03:57
I updated package.json to latest axios, also cleared out all of the devices again (except my phone) and regenerated the refresh token, still not working sadly.
```

{
  "name": "ringlistener",
  "version": "1.0.0",
  "description": "",
  "main": "server.mjs",
  "dependencies": {
    "axios": "^1.5.0",
    "ring-client-api": "^12.0.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

```

**Comment by tsightler** [comment] 2023-09-07 04:53
I ran your code as close as I could to exactly what you posted above.  I obviously had to make some minor modifications since I don't have the include files, but the code works perfectly for me.

So then I took a little deeper look at your trace and realized that it appears to be timing out talking to the mtalk.google.com server.  Do you have any firewalls, are perhaps a VPN, that would be blocking your access to port 5228?  I know some "privacy" firewalls and tools block this by default because Chrome uses this to sync user settings, etc.

What happens if you run `telnet mtalk.google.com 5228` from the command line on the same host you are running your application?

**Comment by tsightler** [comment] 2023-09-07 13:44
@97WaterPolo I was able to reproduce your issue if I set a firewall rule that rejects, not just blocks, connections to mtalk.google.com on port 5228.  I get behavior identical to what you describe, code starts, and ~30 seconds in, the MaxListenersExceededWarning is logged.  The warning itself may indicate a bug in push-receiver, as it happens after exactly 11 retries, but the retries happen because the code is unable to connect to mtalk.google.com on port 5228, which is required.

You can see this more clearly if you enable verbose logging for push-receiver.  To do this you can edit `node_modules/ring-client-api/lib/api.js` file, look around line 128 and you will see a line with `logLevel: 'NONE'` change it to `logLevel: 'VERBOSE'` and then rerun your code.  Here's a little more context to help you find the line you need to change:

```    
async registerPushReceiver(cameras, intercoms) {
        const credentials = this.restClient._internalOnly_pushNotificationCredentials, pushReceiver = new push_receiver_1.default({
            credentials,
            logLevel: 'NONE',
            senderId: '876313859327', // for Ring android app.  703521446232 for ring-site
        })
```

After you change the logging level to verbose you should get output more like this:
```
[PUSH_RECEIVER_DEBUG] emit ON_DISCONNECT
[PUSH_RECEIVER_VERBOSE] connect
[PUSH_RECEIVER_VERBOSE] checkin
[PUSH_RECEIVER_DEBUG] emit ON_DISCONNECT
[PUSH_RECEIVER_VERBOSE] connect
[PUSH_RECEIVER_VERBOSE] checkin
[PUSH_RECEIVER_DEBUG] emit ON_DISCONNECT
[PUSH_RECEIVER_VERBOSE] connect
[PUSH_RECEIVER_VERBOSE] checkin
[PUSH_RECEIVER_DEBUG] emit ON_DISCONNECT
[PUSH_RECEIVER_VERBOSE] connect
[PUSH_RECEIVER_VERBOSE] checkin
```
After the 11th try, you'll likely see the error.  Now, I would agree that this probably does indicate that there is a bug in push-receiver that causes it to add listeners on every retry which is what triggers the warning message, but this is not a fatal error.  The actual issue that needs to be solved is the failure to connect to the Google mtalk server.

**Comment by 97WaterPolo** [comment] 2023-09-08 22:30
@tsightler Yes you are right, 11th attempt triggers the warning, now that I verified it I'll try to dig in and see why its happening!

![image](https://github.com/dgreif/ring/assets/6467276/a8d02be9-10d5-4db3-b403-a71f05667351)

**Comment by tsightler** [comment] 2023-09-09 03:36
OK, well, I'm going to close this issue since this is clearly not a code problem but an environmental issue.  For push notification to work the code must be able to connect to mtalk.google.com on TCP port 5228.  If you resolve that issue I'd guess things will work fine, but if for some reason it still doesn't work after you resolve the connectivity issue, feel free to post your results and we can re-open.

**Closed by tsightler** 2023-09-09 03:36 UTC
Labels: bug

**Comment by 97WaterPolo** [comment] 2023-09-09 04:00
You are amazing with that diagnostic, how did you realize it was the mtalk.google.com that was causing it to fail?

When the telnet failed I went to my AdGuard DNS to check if any of the ad blocklist I have had it and low and behold its right there on the front page hahaha.
![image](https://github.com/dgreif/ring/assets/6467276/702cc0fe-83d3-48dd-94ba-3b38892230a5)

The weird part is that blocklist hasn't been touched in years (mtalk.google.com was indeed on it) so I'm not sure what suddenly caused it to start requesting and going through that domain, especially with the application/library not having any updates and no other changes made.

Once I removed the "mtalk.google.com" unsurprisingly everything started working again, I reverted back to the older version and that started working as well!

**Comment by tsightler** [comment] 2023-09-09 15:09
> You are amazing with that diagnostic, how did you realize it was the mtalk.google.com that was causing it to fail?

Ha, well, there's nothing really complex here, you already did a good bit of work by stripping the code down to minimum, clearly describing the behavior, including that the trace happened after 30 seconds, and then providing the trace.  As you noted, the trace indicated push-receiver, and there was a very clear indicator:

`at Timeout.connect [as _onTimeout] (Z:\Docker\RingListener\node_modules\@eneris\push-receiver\dist\client.js:126:16)`

Timeout.connect was a pretty strong indicator that there was a connectivity issue and, if you look at line 126 in the client.js code for push-receiver, you see that this the return from the [PushReceiver.connect](https://github.com/Eneris/push-receiver/blob/master/src/client.ts#L112) function.  That function is responsible for establishing the connection to Google/Firebase Cloud Messaging, which is via mtalk.google.com on port 5228.  The trace made it clear that the attempt to connect to that socket was timing out.  I then blocked the port on my firewall and reproduced the identical behavior.

Now, I would still say that the warning is something that could be fixed in the code, but it's a non-critical message, triggered only by the fact that the code couldn't connect to the listener, but, honestly, the warning was useful as, without it, it would have been more difficult to find the actual source of the issue.
