### ISSUE TITLE
Make Video Orientation of Rind Videodoorbell changeable at 90°

### ISSUE THREAD

**Issue by woccam** [dgreif/ring#1037] opened 2022-08-31 05:26 UTC
# Feature Request

### Description
In Germany the orientation of doorbell boards is often landscape. In order to use the existing doorbell board i had to install the Ring Video Doorbell 90° turned. Now the video is also 90° turned. Would love to be able to change the orientation of the video output by 90°. Tricky part is, that the direction of the turn must be choosable too

### Describe the solution you'd like
add the ability to turn the video output orientation by 90° right or left

### Device data
{"locations":[{"name":"Nürnberg","cameras":[{"description":"Haustür","subscribed":true,"subscribed_motions":true,"battery_life":null,"external_connection":false,"firmware_version":"Up to Date","kind":"lpd_v2","settings":{"cv_settings":{"detection_types":{"human":{"enabled":false,"mode":"none","record":null,"notification":false},"loitering":{"enabled":false,"mode":"none","record":null,"notification":false},"motion":{"enabled":true,"mode":"edge","record":null,"notification":true},"moving_vehicle":{"enabled":false,"mode":"none","record":null,"notification":false},"other_motion":{"enabled":false,"mode":"none","record":null,"notification":false},"package_delivery":{"enabled":false,"mode":"none","record":null,"notification":false},"package_pickup":{"enabled":false,"mode":"none","record":null,"notification":false}},"threshold":{"loitering":10,"package_delivery":2},"triggers":[]},"cv_paid_features":{"baby_cry":true,"car_alarm":true,"co2_smoke_alarm":true,"dog_bark":true,"general_sound":true,"glass_break":true,"human":true,"loitering":true,"motion":true,"other_motion":true,"package_delivery":true,"package_pickup":true,"cv_triggers":true},"concierge_settings":{"mode":"disabled"},"other_paid_features":{"alexa_concierge":true,"sheila_cv":true,"sheila_recording":true},"sheila_settings":{"cv_processing_enabled":false,"local_storage_enabled":false},"server_settings":{"ring_media_server_enabled":true},"zone_settings":{"motion":[{"name":"Default Zone","state":"enabled","properties":{"detection_types":["motion"]},"vertices":[{"x":0.058,"y":0.199},{"x":0.5,"y":0.199},{"x":0.94,"y":0.199},{"x":0.94,"y":0.5},{"x":0.94,"y":0.797},{"x":0.5,"y":0.797},{"x":0.058,"y":0.797},{"x":0.058,"y":0.5}]}]},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":1,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":true,"frequency_secs":180,"resolution_p":360},"enable_vod":true,"motion_zones":{"enable_audio":false,"active_motion_filter":1,"sensitivity":5,"advanced_object_settings":{"human_detection_confidence":{"day":0.8,"night":0.8},"motion_zone_overlap":{"day":0.2,"night":0.3},"object_time_overlap":{"day":0.2,"night":1.2},"object_size_minimum":{"day":0.04,"night":0.07},"object_size_maximum":{"day":0.7,"night":0.7}},"zone1":{"name":"Default Zone","state":2,"vertex1":{"x":0.058,"y":0.199},"vertex2":{"x":0.5,"y":0.199},"vertex3":{"x":0.94,"y":0.199},"vertex4":{"x":0.94,"y":0.5},"vertex5":{"x":0.94,"y":0.797},"vertex6":{"x":0.5,"y":0.797},"vertex7":{"x":0.058,"y":0.797},"vertex8":{"x":0.058,"y":0.5}},"zone2":{"name":"Zone 2","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"Zone 3","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}}},"motion_snooze_preset_profile":"low","live_view_preset_profile":"highest","live_view_presets":["low","middle","high","highest"],"motion_snooze_presets":["none","low","medium","high"],"doorbell_volume":11,"chime_settings":{"type":2,"enable":true,"duration":10},"video_settings":{"ignore_zones":{"zone1":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"birton":null,"brightness":16,"contrast":80,"saturation":48,"ae_level":32,"ae_mode":0,"ae_mask":null,"encryption_enabled":false,"encryption_method":null,"clip_length_min":null,"clip_length_max":120},"motion_announcement":false,"stream_setting":0,"advanced_motion_detection_enabled":true,"advanced_motion_detection_human_only_mode":false,"luma_night_threshold":0,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":{"zone1":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"enable_rich_notifications":true,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":[],"motion_detection_enabled":false,"rich_notifications_scene_source":"firmware","rich_notifica-uuid":false},"features":{"motion_zone_recommendation":false,"motions_enabled":true,"show_recordings":true,"advanced_motion_enabled":false,"people_only_enabled":false,"shadow_correction_enabled":false,"motion_message_enabled":true,"night_vision_enabled":false,"rich_notifications_eligible":true,"show_24x7_lite":true,"show_offline_motion_events":false,"cfes_eligible":true,"sheila_camera_eligible":true,"sheila_camera_processing_eligible":true},"owned":true,"alerts":{"connection":"online","ota_status":"timeout"},"motion_snooze":null,"stolen":false,"is_sidewalk_gateway":true,"created_at":"2021-03-22T13:42:32Z","shared_at":null,"active_schedule_uuid":null,"health":{"device_type":"lpd_v2","last_update_time":1661905577,"connected":true,"rss_connected":true,"sidewalk_connection":false,"floodlight_on":false,"white_led_on":false,"siren_on":false,"packet_loss":-1,"packet_loss_category":"NA","rssi":-63,"transformer_voltage":17,"transformer_voltage_category":"good","ota_status":"timeout","network_connection_value":"wifi","ac_power":0,"external_connection":false,"battery_percentage_category":"unknown","battery_voltage":4026,"battery_voltage_category":"very_good","firmware_version":"10.0.18","rssi_category":"good","second_battery_percentage_category":"unknown","second_battery_voltage_category":"unknown","firmware_version_status":"Up to Date","stream_resolution":66,"tx_rate":81,"bandwidth_last_time":1661905577,"bandwidth":14991,"status_time":54457321950325,"uptime_sec":355164,"channel":"100","firmware_avg_bitrate":"1318608","video_packets_total":"17904","stream_profile":"720_avc_15fps","iperf_tcp_throughput":"23059 Kbps"},"deactivated_at":null,"night_mode_status":"unknown"}],"chimes":[{"description":"Obergeschoss","firmware_version":"Up to Date","kind":"chime_v2","settings":{"volume":11,"status_led_enable":true},"features":{"ringtones_enabled":true,"cfes_eligible":false},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"do_not_disturb":{"seconds_left":0},"stolen":false,"is_sidewalk_gateway":false,"created_at":"2021-03-26T10:31:00Z","shared_at":null,"deactivated_at":null},{"description":"Untergeschoss","firmware_version":"Up to Date","kind":"chime_v2","settings":{"volume":11,"status_led_enable":true},"features":{"ringtones_enabled":true,"cfes_eligible":false},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"do_not_disturb":{"seconds_left":0},"stolen":false,"is_sidewalk_gateway":false,"created_at":"2021-03-23T18:09:17Z","shared_at":null,"deactivated_at":null}],"devices":[]}],"amazonKeyLocks":[]}

**Comment by dgreif** [comment] 2022-08-31 17:14
Thanks for providing a clear write-up and the device data! This is actually a duplicate of #504. Please see [my comment there](https://github.com/dgreif/ring/issues/504#issuecomment-734962876), which explains why this is not a simple change, and isn't something I'm currently looking to add.

**Closed by dgreif** 2022-08-31 17:14 UTC
Labels: enhancement
