### ISSUE TITLE
Fails to connect on latest Homebridge version

### ISSUE THREAD

**Issue by earlthesquirrel** [dgreif/ring#458] opened 2020-09-23 22:22 UTC
# Live Streaming Issue

### Describe the live streaming issue

It was working fine, but with lastest set of updates it now fails on streaming (and I also don't get static picture)
Fails to even start.In Home App it generates a "No Response.  This camera is not responding"

Homebridge : 1.2.3
Ring Plugin : 9.9.0
Homebridge Confix UI X : 4.27.1
Homebridge Camera FFMPG : 3.0.3

(I use the FFMPG for two raspberry pi cameras)

### Screenshots/Logs

It immediately throws an error log when trying to start.  Shown below:

[9/23/2020, 18:12:33] [Ring] Preparing Live Stream for Front Door
[9/23/2020, 18:12:34] [Ring] Failed to parse SDP from Ring
[9/23/2020, 18:12:34] [Ring] v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4 
s=Wantajobinstead?
c=IN IP4 34.192.91.110
t=0 0

m=audio 32037 RTP/SAVPF 0
a=rtpmap:0 PCMU/8000
a=rtcp:54586 IN IP4 34.192.91.110
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:68Cgakv3vzkTokWd5bnaxArRfg3G3InrUxiMvfln
a=ptime:20

m=video 60042 RTP/SAVPF 99
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42000a
a=rtcp:21326 IN IP4 34.192.91.110
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:MUtLqt71Ga9ygMbQMozoWRPd4dvc+0TQPDmrh4/N

[9/23/2020, 18:12:34] [Ring] Failed to prepare stream for Front Door (0.258s)
[9/23/2020, 18:12:34] [Ring] TypeError: Cannot read property 'match' of undefined
    at getRtpDescription (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:24:54)
    at parseRtpDescription (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:36:16)
    at SipCall.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:204:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Recommended solution

Looks like code issue.  Can't find a property...

### Environment

 - Ring Camera: Pro - Hardwired
 - OS: Raspiban - From Homebridge Disk image install.
 - Node.js: Whatever comes with Hombridge Disk Image.  This machine ONLY runs Homebridge
 - NPM: Ditto
 - homebridge-ring :9.9.0
 - homebridge : 1.2.3

### Network Environment

I doubt it's anything in network... it looks like code issue.  Fairly simple wifi network using Unifi equipment.
It was working until the latest update, so that makes me believe it's a code issue.  Or dependency clash.

**Comment by dgreif** [comment] 2020-09-23 22:29
Duplicate of #447.  I'm still working to find a solution

**Comment by earlthesquirrel** [comment] 2020-09-23 22:29
Did find a duplicate -- 427

Here is JSON output

{"locations":[{"name":"Alpharetta","cameras":[{"description":"Front Door","subscribed":true,"subscribed_motions":true,"battery_life":"4011","external_connection":false,"firmware_version":"Up to Date","kind":"lpd_v1","settings":{"cv_settings":{"detection_types":{"human":{"enabled":false,"mode":null,"record":null},"motion":{"enabled":false,"mode":"edge","record":null}},"threshold":{}},"cv_paid_features":{},"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":1,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":false,"frequency_secs":180,"resolution_p":360},"enable_vod":true,"motion_zones":{"enable_audio":false,"active_motion_filter":1,"sensitivity":5,"advanced_object_settings":{"human_detection_confidence":{"day":0.8,"night":0.8},"motion_zone_overlap":{"day":0.2,"night":0.3},"object_time_overlap":{"day":0.2,"night":1.2},"object_size_minimum":{"day":0.01,"night":0.01},"object_size_maximum":{"day":0.7,"night":0.7}},"zone1":{"name":"Zone 1","state":2,"vertex1":{"x":0.16548415,"y":0.19614244},"vertex2":{"x":0.33555928,"y":0.20949554},"vertex3":{"x":0.4755843,"y":0.19762611},"vertex4":{"x":0.48309684,"y":0.49851632},"vertex5":{"x":0.46640235,"y":0.9537092},"vertex6":{"x":0.2996661,"y":0.97151333},"vertex7":{"x":0.19720367,"y":0.8439169},"vertex8":{"x":0.18969116,"y":0.4480712}},"zone2":{"name":"Zone 2","state":2,"vertex1":{"x":0.47683638,"y":0.1694362},"vertex2":{"x":0.6293823,"y":0.14569733},"vertex3":{"x":0.8545492,"y":0.14569733},"vertex4":{"x":0.85955757,"y":0.5756677},"vertex5":{"x":0.8537145,"y":0.93590504},"vertex6":{"x":0.654424,"y":0.9922849},"vertex7":{"x":0.48601836,"y":0.9804154},"vertex8":{"x":0.48768783,"y":0.4925816}},"zone3":{"name":"Zone 3","state":2,"vertex1":{"x":0.8666527,"y":0.27181008},"vertex2":{"x":0.91318864,"y":0.24362017},"vertex3":{"x":1,"y":0.14866468},"vertex4":{"x":1,"y":0.6083086},"vertex5":{"x":0.9931135,"y":0.9655786},"vertex6":{"x":0.9073456,"y":0.968546},"vertex7":{"x":0.8616444,"y":0.8810089},"vertex8":{"x":0.86999166,"y":0.55934715}}},"motion_snooze_preset_profile":"low","live_view_preset_profile":"highest","live_view_presets":["low","middle","high","highest"],"motion_snooze_presets":["none","low","medium","high"],"doorbell_volume":11,"chime_settings":{"type":0,"enable":false,"duration":10},"video_settings":{"ignore_zones":{"zone1":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"birton":"","brightness":16,"contrast":80,"saturation":48,"ae_level":32,"ae_mode":null,"ae_mask":null,"encryption_enabled":null},"motion_announcement":false,"stream_setting":0,"advanced_motion_detection_enabled":false,"advanced_motion_detection_human_only_mode":false,"luma_night_threshold":0,"enable_audio_recording":true,"people_detection_eligible":true,"live_view_disabled":false,"ignore_zones":{"zone1":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"enable_rich_notifications":null,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":[],"motion_detection_enabled":true,"rich_notifications_scene_source":"cloud","recording_storage_type":"default_s3","rich_notifica-uuid":null},"features":{"motions_enabled":true,"show_recordings":true,"advanced_motion_enabled":false,"people_only_enabled":false,"shadow_correction_enabled":false,"motion_message_enabled":false,"night_vision_enabled":false,"rich_notifications_eligible":false,"show_24x7_lite":false,"show_offline_motion_events":false,"cfes_eligible":null},"owned":true,"alerts":{"connection":"online","ota_status":"successful"},"motion_snooze":null,"stolen":false,"is_sidewalk_gateway":false,"created_at":"2017-06-11T01:40:06Z","shared_at":null,"night_mode_status":"unknown"}],"chimes":[],"devices":[]}],"amazonKeyLocks":[]}

**Closed by dgreif** 2020-09-23 22:29 UTC
Labels: duplicate
