### ISSUE TITLE
Error connecting to API

### ISSUE THREAD

**Issue by rcoletti116** [dgreif/ring#373] opened 2020-06-21 14:11 UTC
New issue for me this morning. Devices won't respond. Logs show me these errors:
Just me?
---
[6/21/2020, 1:13:02 PM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 406. Response body: 406 Not Acceptable

[6/21/2020, 1:13:02 PM] [Ring] Error connecting to API
[6/21/2020, 1:13:02 PM] [Ring] { HTTPError: Response code 406 (Not Acceptable)
    at onResponse (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:124:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  code: undefined,
  timings:
   { start: 1592745182356,
     socket: 1592745182489,
     lookup: 1592745182489,
     connect: 1592745182489,
     secureConnect: 1592745182489,
     upload: 1592745182489,
     response: 1592745182529,
     end: 1592745182536,
     error: undefined,
     abort: undefined,
     phases:
      { wait: 133,
        dns: 0,
        tcp: 0,
        tls: 0,
        request: 0,
        firstByte: 40,
        download: 7,
        total: 180 } } }

**Comment by henkied** [comment] 2020-06-21 14:36
same issue here

**Comment by swampsnake1961** [comment] 2020-06-21 14:49
And here - Logs nearly identical but the timing values are slightly different.

**Comment by firefly2334** [comment] 2020-06-21 15:02
Same here anyone get a response yet?

**Comment by SSutherland94** [comment] 2020-06-21 15:24
Had a separate, recurring issue that was just replaced, or maybe even supplemented by this issue. Hope this gets checked out soon

**Comment by JT-EOD** [comment] 2020-06-21 15:38
Same issue here. Using the RPI homebridge image on a pi 4. Only thing I changed was installing ffmpeg 2.0.0, and rebooted the pi.

**Comment by dgreif** [comment] 2020-06-21 15:50
Lots of reports of this issue today. It’s usually a rate limiting situation where a different homebridge plugin caused your homebridge server to crash over and over again. Ring doesn’t show any issues on their status page currently. It is possible that they tweaked their rate limiting. I’m unable to look into it today, but hopefully the issue will resolve on its own in the next 24 hours

**Comment by yardbird917** [comment] 2020-06-21 15:51
Running into the same issue. Plugin seems unable to connect to the API. Forcing a refresh token update / unlinking + reconnecting the Ring account did not solve the issue (not even temporarily). API has been disconnected for me as of 50 minutes ago (last snapshot update from wired floodlight cam).

**Comment by cleanev** [comment] 2020-06-21 16:54
I started getting the same error since yesterday. Took all usual steps to no resolution. 
Have old image that was working early May so restored it and all seems working again. My guess is this may not have anything to do with API as old version works.

BTW, upon restoring I see Ring plugin version 7.2.5 and there is no offer for update either. I have Bond plugin that was available for update, updated Bond and rebooted and all seeems to work. Guess there is something that changed for Ring plugin version 9.3.2.

**Comment by xatrix78** [comment] 2020-06-21 16:54
Same issue.

**Comment by sjiampojamarn** [comment] 2020-06-21 17:59
Same here. 
HTTPError: Response code 406 (Not Acceptable)

I started to notice this after a restart. I'm not sure if the issue also happened before the restart.

**Comment by stephendowning** [comment] 2020-06-21 18:27
Yup same issue

**Comment by LordJohnWhorfin** [comment] 2020-06-21 19:18
Just installed this today and had the same problem.

**Comment by evergoodstudios** [comment] 2020-06-21 19:52
Same problem here, upgraded all, was working fine before now, comes up with same error, no longer able to use the ring devices

**Comment by cclarke99** [comment] 2020-06-21 20:07
@dgreif I am able to get this working again on plugin version 8.2.0 but everything back to 9.0.0 are broken for me on a pretty generic Homebridge installation. Happy to help with any troubleshooting if needed.

**Comment by jsrivatsan** [comment] 2020-06-21 20:15
Same issues here as well. It started sometime yesterday night based on the logs. Everything seems to be working well before that. I am on version 9.1.0. Happy to help with any debug or logs.

**Comment by JeremyLaurenson** [comment] 2020-06-21 20:32
Ditto.

**Comment by joepool** [comment] 2020-06-21 20:37
Same here, on version 9.1.0 (also tried on the latest version but encountered the same problem)

**Comment by dgreif** [comment] 2020-06-21 20:48
@cclarke99  thanks for the info on versions that work. Would you mind trying 8.2.0 and 9.0.0 both again to 100% confirm that’s where they line is? If so, that should definitely help narrow it down. 

For everyone else, please no more “same here” or “ditto” posts. 2 or 3 are useful to confirm that it’s a wide spread issue, but beyond that it is just extra noise in this thread. I encourage you to add comments if you have something constructive to add to the conversation. 

I’m not able to look into this issue today so everyone will need to be a little patient. If someone is able to dig into it and open a pull request, I’d be happy to take a look at it and get an update out ASAP

**Comment by cclarke99** [comment] 2020-06-21 21:41
> @cclarke99 thanks for the info on versions that work. Would you mind trying 8.2.0 and 9.0.0 both again to 100% confirm that’s where they line is? If so, that should definitely help narrow it down.
> 
> For everyone else, please no more “same here” or “ditto” posts. 2 or 3 are useful to confirm that it’s a wide spread issue, but beyond that it is just extra noise in this thread. I encourage you to add comments if you have something constructive to add to the conversation.
> 
> I’m not able to look into this issue today so everyone will need to be a little patient. If someone is able to dig into it and open a pull request, I’d be happy to take a look at it and get an update out ASAP

Testing now, will post results shortly.

**Comment by cclarke99** [comment] 2020-06-21 21:51
> @cclarke99 thanks for the info on versions that work. Would you mind trying 8.2.0 and 9.0.0 both again to 100% confirm that’s where they line is? If so, that should definitely help narrow it down.
> 
> For everyone else, please no more “same here” or “ditto” posts. 2 or 3 are useful to confirm that it’s a wide spread issue, but beyond that it is just extra noise in this thread. I encourage you to add comments if you have something constructive to add to the conversation.
> 
> I’m not able to look into this issue today so everyone will need to be a little patient. If someone is able to dig into it and open a pull request, I’d be happy to take a look at it and get an update out ASAP

Ok, confirmed again that 8.2.0 works but 9.0.0 fails with the following error. Now, here's the interesting thing. I've been using the 9.x version for some time and updated to 9.3.2 the other day and it worked fine until this morning. Again, happy to help do whatever testing needed. I've turned debug logging on as well and will leave it on.

This error comes in immediately following the load of cached Ring accessories.
`[6/21/2020, 2:47:21 PM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status 406. Response body: 406 Not Acceptable

[6/21/2020, 2:47:21 PM] [Ring] Error connecting to API
[6/21/2020, 2:47:21 PM] [Ring] HTTPError: Response code 406 (Not Acceptable)
    at onResponse (/usr/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 {
  code: undefined,
  timings: {
    start: 1592776040699,
    socket: 1592776040925,
    lookup: 1592776040925,
    connect: 1592776040925,
    secureConnect: 1592776040925,
    upload: 1592776040925,
    response: 1592776041000,
    end: 1592776041002,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 226,
      dns: 0,
      tcp: 0,
      tls: 0,
      request: 0,
      firstByte: 75,
      download: 2,
      total: 303
    }
  }
}`

**Comment by dgreif** [comment] 2020-06-21 22:55
Should be fixed in v`9.3.3`. Ring is now requiring a user-agent header now. Doesn't need to be anything specific, just present.  Huge thanks to @cclarke99, knowing the versions really helped narrow it down.  Let me know if the update fixes it for you.

**Comment by jsrivatsan** [comment] 2020-06-21 23:12
Just updated to 9.3.3 and the issue seems to be fixed. Thanks a ton for the quick fix!!!

**Closed** 2020-06-21 23:13 UTC
Labels: bug

**Comment by cclarke99** [comment] 2020-06-21 23:24
> Should be fixed in v`9.3.3`. Ring is now requiring a user-agent header on some requests. Doesn't need to be anything specific, just present. Huge thanks to @cclarke99, knowing the versions really helped narrow it down. Let me know if the update fixes it for you.

@dgreif Looks good after the 9.3.3 update. Thank you, thank you!!
