### ISSUE TITLE
Ring Sensors delayed on ring Base Station

### ISSUE THREAD

**Issue by JSAG3022** [dgreif/ring#1234] opened 2023-06-04 21:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

After installing Ring- Homebridge, all contact sensors do not register an event ie. Opening Front door. Base station won't chime and Ring native app wont reflect the event. It will still show the sensor as closed if its open. 
Often times it will reflect the event about 60-120 seconds after it happens, other times it wont reflect the event at all. 

Restarted base station, 
Restarted homebridge, 
Downgraded to previous version 

### Expected behavior

Base station to reflect contact sensor changes 

### Homebridge Ring Config

```shell
"hideLightGroups": true,
    "hideDoorbellSwitch": true,
    "hideCameraLight": true,
    "hideCameraMotionSensor": true,
    "hideCameraSirenSwitch": true,
    "hideInHomeDoorbellSwitch": true,
    "showPanicButtons": true,
    "nightModeBypassFor": "some",
    "platform": "Ring"
```

### OS

macOS

### Node.js Version

18.16.0

### NPM Version

?

### Homebridge/HOOBs Version

?

### Homebridge Ring Plugin Version

11.7.7

### Operating System

macOS

**Comment by tsightler** [comment] 2023-06-05 04:04
> Base station won't chime and Ring native app wont reflect the event.

I would say this indicates that this cannot be caused by ring-homebridge as nothing it can do should have any way to interfere with the operation of the base station or the official Ring app the code doesn't talk to the base station directly, only the Ring servers.

**Comment by JSAG3022** [comment] 2023-06-05 04:46
Thats exactly what I would've thought, however, as soon as I deleted the plugin and removed the token from my account it worked flawlessly again.

**Comment by dgreif** [comment] 2023-06-05 22:44
This is the first I've heard a report like this. I appreciate you trying a number of things before deleting the plugin. Would you be willing to install it again and see if the problem starts again?

**Comment by tsightler** [comment] 2023-06-05 22:55
I don't see any way just having a token could possibly impact it.

For a super longshot, I have seen a few cases where ring-client-api seems to "spin away" sending requests over and over, flooding outbound traffic with DNS and HTTP queries.  I haven't seen this in quite a while, but I tracked a few of them a few years ago.  I could imagine a case where a user might have limited upload bandwidth (DSL or poor cable) where this could flood the uplink.

I'm not saying this is what happened here, but it's just about the only thing I can think of that could ever create this kind of behavior.

I do think it's important to note that Ring has some serious issues on June 3rd, especially around event processing.  The only thing they listed on the status page is "problems deleting events", but I know for a fact that problems impacted other behaviors around events in general.

**Comment by dgreif** [comment] 2023-06-07 23:13
Glad to hear it's working! I'm going to close this issue, but let me know if you see anything like this again

**Closed by dgreif** 2023-06-07 23:13 UTC
Labels: bug
