### ISSUE TITLE
Ring Doorbell Video Crashes Ring Bridge

### ISSUE THREAD

**Issue by alvinpetitt** [dgreif/ring#1061] opened 2022-09-26 12:08 UTC
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...

While in Home.app on iOS (16.0.2) and macOS (12.6) and selecting the Ring Doorbell feed, I get a message that the Ring Bridge has stopped. After about 5-10 seconds, the bridge restarts.

### To Reproduce
 - Running HOOBS (4.2.8) and Ring Plugin (11.2.1)
 - Select Ring Doorbell camera
 - Message that Ring Bridge has stopped. After about 5-10 seconds message that Ring Bridge has started
 - I have screenshot the errors in the log.

### Expected behavior
 A clear and concise description of what you expected to happen.

Expecting live feed of Ring Doorbell camera

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

<img width="1833" alt="screenshot_93" src="https://user-images.githubusercontent.com/54726858/192269648-5fb5ccf3-2427-4095-abbc-8860c8d0140c.png">

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

"platform": "Ring",
    "refreshToken":
"beamDurationSeconds": 300,
    "hideLightGroups": true,
    "hideAlarmSirenSwitch": true,
    "sendDoorbellMotionNotificationsToTv": false

```

### Environment

 - OS: Ubuntu (21.04)
 - Node.js: 16.17.1
 - NPM: 8.15.0
 - homebridge-ring: 11.2.1
 - homebridge: N/A
 - hoobs: 1.5.0

**Comment by tsightler** [comment] 2022-09-26 23:25
A strange question but by any chance are you using an account other than the primary Ring account?

**Comment by alvinpetitt** [comment] 2022-09-26 23:46
No, it’s my main, and only, account* Sent from my rotary phone *Alvin ***@***.***/WRJY956On Sep 26, 2022, at 7:26 PM, tsightler ***@***.***> wrote:﻿
A strange question but by any chance are you using an account other than the primary Ring account?

**Comment by dgreif** [comment] 2022-09-27 17:08
This looks like a duplicate of #1057

**Closed by dgreif** 2022-09-27 17:08 UTC
Labels: bug

**Comment by alvinpetitt** [comment] 2022-09-29 16:40
> This looks like a duplicate of #1057

How is this a duplicate? Doesn’t appear to be at all.
