### ISSUE TITLE
Notifications on iPhone and Apple TV stopped

### ISSUE THREAD

**Issue by shaileshck** [dgreif/ring#1511] opened 2024-10-20 16:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Do not get notification on iPhone and Apple TV

### Expected behavior

notifications and alerts of camera expected

### Relevant log output

```shell
[20/10/2024, 21:13:57] [homebridge-ring] UNKNOWN MESSAGE
[20/10/2024, 21:13:57] [homebridge-ring] {
  body: {
    doorbot_id: 29850684,
    session_id: 'eyJraWQiOiJTaWduYWxsaW5nIiwiYWxnIjoiSFMyNTYifQ.eyJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjoyOTg1MDY4NCwicGluZ19pbnRlcnZhbCI6MTAsImRpbmdfaWQiOiI3NDI3ODg0MTAwMDc1NjE3MzQwIiwiaXAiOiIxMy4xMjYuMjEuMTE3IiwiY3JlYXRlZF9hdCI6MTcyOTQzOTAzNjYyNiwicm1zX2ZxZG4iOiIxMy0xMjYtMjEtMTE3LjYwODA3MDMyMjU0Ni5hcC1zb3V0aC0xLnByb2Qucm1zLnJpbmcuZGV2aWNlcy5hMnouY29tIiwic2Vzc2lvbl9pZCI6ImJhZjg2MTdlLWI1OWItNDQ4YS1iNzhmLTQ0NzViNmYyMWRhZCIsImV4cCI6MTcyOTUyNTQzNiwiaWF0IjoxNzI5NDM5MDM2LCJybXNfdmVyc2lvbiI6ImUyZjkzN2VhIn0.ywRhNOhK0sE8CniJGFsUH6mqNGYSd5EsXO7QQ-jO67w'
  },
  dialog_id: 'c014e234-4c0f-43da-8f7f-0ef2c6ac766d',
  method: 'camera_started'
```

### Homebridge Ring Config

```shell
"unbridgeCameras": false,
    "hideLightGroups": true,
    "hideDoorbellSwitch": true,
    "hideCameraLight": true,
    "hideCameraSirenSwitch": true,
    "hideAlarmSirenSwitch": true,
    "_bridge": {
        "username": "0E:B9:A0:82:6B:F4",
        "port": 33235
    },
    "platform": "Ring"
```

### OS

Rasbian

### Node.js Version

20.18.0

### NPM Version

10.8.2

### Homebridge/HOOBs Version

v1.8.4

### Homebridge Ring Plugin Version

v13.1.0

### Operating System

Raspian

**Comment by tsightler** [comment] 2024-10-20 16:58
Please verify if you have followed the [Notification Troubleshooting](https://github.com/dgreif/ring/wiki/Notification-Troubleshooting) steps from the wiki as this should fix the issue in almost all cases.

**Comment by shaileshck** [comment] 2024-10-21 16:51
Hi,

Thanks for the response. Have tried those steps earlier but did try once
again removing all authorised clients and refreshing new token.
from Home App i can see the camera and also when accessed i can see live
view.
Issue it has stopped homekit notifications even though enabled and also
when trying to go in live view the error message shared earlier also shows
on terminal.

**Comment by tsightler** [comment] 2024-10-25 01:41
> when trying to go in live view the error message shared earlier also shows
> on terminal.

That is not an error message, it's just an unknown message.  There are many control messages we don't currently parse so we log them for informational purposes.

Please post logs from the time period of a motion/ding event.  Without this there is nothing we can do

**Comment by tr1um9h** [comment] 2024-10-30 16:17
I have not been getting motion notifications either only get them when the doorbell is rung

**Comment by CASCSX** [comment] 2024-11-07 11:01
I noticed the same issue. If i go to Homekit Settings and choose "Camera & Doorbell", i can just see my Doorbell in this Tab. The Cameras are missing.
If i go directly to my cameras in Homekit  and check the status, the notification settings are also missing.

**Comment by TravellingTechGuy** [comment] 2024-11-07 15:29
I can confirm I am seeing the same problem. Before the doorbell rings would go through my HomePods and I would get alerts on AppleTV. Since this UNKOWN MESSAGE started to happen, none of those is working anymore.

**Comment by tsightler** [comment] 2024-11-07 17:50
Again, the unknown message has nothing to do with notifications, it's just for streaming.  Can you provide more details about what you are seeing?

**Comment by CASCSX** [comment] 2024-11-07 17:56
Ive made some screenshots. Unfortunately its in german. But as u can see we are missing some
Options in the camera setting like alerts when detect. In the Screenshot where i select my doorbell i can configure these settings. Just for cameras there are nit available.
![IMG_0685](https://github.com/user-attachments/assets/426ee492-373a-46d7-9a02-c8ea346e12bf)
![IMG_0684](https://github.com/user-attachments/assets/ca3b5e9c-7a34-409a-af4a-2cc6d4091171)
![IMG_0683](https://github.com/user-attachments/assets/b6ebb1e3-d636-4ec9-a055-3b4f3248f868)

**Comment by CASCSX** [comment] 2024-11-07 17:59
Bzw i noticed that the switch button of the doorbell is not working properly. If i switch the button on and go back its still turned off
![IMG_0686](https://github.com/user-attachments/assets/66750714-0cce-4473-b768-bc6603b458a9)
(The first iption)

**Comment by tsightler** [comment] 2024-11-07 18:38
Logs of doorbell presses and configs are useful.  In the OP, it doesn't appear that the user followed the advice to unbridge and reconfigure cameras.

**Comment by tsightler** [comment] 2024-11-08 00:39
To be clear, if no one experiencing the issues here can provide any logs from the plugin, then this is mostly an unsolvable issue and I will have to close it.  Please provide complete logs from a period where doorbell dings happen as screenshots of Homekit aren't really going to help resolve the problem.  I'm not trying to be rude, but really, there's nothing to go on here as no one has provided any detailed logging from the plugin, just one log snippet which has nothing to do with notifications, at least not directly.

Based on the few lines of logs posted, they indicate a camera that is actively streaming.  One thing that is very important is that Ring cameras will not send notifications when they are streaming, so perhaps this is a hint at the issue, perhaps Homekit is keeping the streams constantly active, but that is just a theory.  Only logs can help confirm this, and, even if that is the case, there is little that we as plugin developers can do about it, but we need logs to confirm as I do not see this behavior at all, everything works just as it always has.

**Comment by mistermakc** [comment] 2024-11-13 16:42
I will send you Logs per PM. @tsightler

**Comment by TravellingTechGuy** [comment] 2024-11-28 20:26
@tsightler i can provide logs tomorrow as well if that is still helpful to you

**Comment by TravellingTechGuy** [comment] 2024-11-29 08:37
I have been doing all the following:

- Resetting the accessories in the Plug in - no joy
- Removing the Front Door Camera from Homekit and reading - no joy
- Removing the Ring Plugin bridge from Home kit and re-adding - no joy
- Uninstalling the plugin, removing the bridge from homekit, re-adding all accessories - no joy

The cams are in unbridged mode.

Debug logs for the plugin don't give anything.

You can see I opened the Front Door to go push the doorbell... nothing is logged....

`[11/29/2024, 8:24:40 AM] [homebridge-ring] Found the following locations:
[11/29/2024, 8:24:40 AM] [homebridge-ring]   locationId: [REDACTED]
[11/29/2024, 8:24:40 AM] [homebridge-ring] Creating location socket.io connection - [REDACTED]
[11/29/2024, 8:24:41 AM] [homebridge-ring] Ignoring push notification received in first two seconds after starting up
[11/29/2024, 8:24:41 AM] [homebridge-ring] Ignoring push notification received in first two seconds after starting up
[11/29/2024, 8:24:41 AM] [homebridge-ring] Ignoring push notification received in first two seconds after starting up
[11/29/2024, 8:24:41 AM] [homebridge-ring] Ring connected to socket.io server
[11/29/2024, 8:24:42 AM] [homebridge-ring] Configuring 4 cameras and 25 devices for location[REDACTED]
[11/29/2024, 8:24:42 AM] [homebridge-ring] Hidden accessory [REDACTED] siren.outdoor-strobe Outdoor Siren
[11/29/2024, 8:24:42 AM] [homebridge-ring] Configured camera [REDACTED] doorbell_v4 Front Door
[11/29/2024, 8:24:42 AM] [homebridge-ring] Configured camera [REDACTED] cocoa_camera Office Frederick
[11/29/2024, 8:24:42 AM] [homebridge-ring] Configured camera [REDACTED] hp_cam_v2 Garden
[11/29/2024, 8:24:42 AM] [homebridge-ring] Configured camera [REDACTED] Carpark
[11/29/2024, 8:24:42 AM] Front Door A70C is running on port 41613.
[11/29/2024, 8:24:42 AM] Please add [Front Door A70C] manually in Home app. Setup Code: [REDACTED]
[11/29/2024, 8:24:42 AM] Office Frederick B6A6 is running on port 34455.
[11/29/2024, 8:24:42 AM] Please add [Office Frederick B6A6] manually in Home app. Setup Code: [REDACTED]
[11/29/2024, 8:24:42 AM] Garden B1A9 is running on port 35525.
[11/29/2024, 8:24:42 AM] Please add [Garden B1A9] manually in Home app. Setup Code: [REDACTED]
[11/29/2024, 8:24:42 AM] Carpark 7863 is running on port 36161.
[11/29/2024, 8:24:42 AM] Please add [Carpark 7863] manually in Home app. Setup Code: [REDACTED]
[11/29/2024, 8:27:07 AM] [homebridge-ring] No snapshot cached for Garden
[11/29/2024, 8:27:07 AM] [homebridge-ring] Loading new snapshot into cache for Garden
[11/29/2024, 8:27:07 AM] [homebridge-ring] No snapshot cached for Carpark
[11/29/2024, 8:27:07 AM] [homebridge-ring] Loading new snapshot into cache for Carpark
[11/29/2024, 8:27:07 AM] [homebridge-ring] No snapshot cached for Front Door
[11/29/2024, 8:27:07 AM] [homebridge-ring] Loading new snapshot into cache for Front Door
[11/29/2024, 8:27:07 AM] [homebridge-ring] Snapshot cached for Garden (0.675s)
[11/29/2024, 8:27:07 AM] [homebridge-ring] Snapshot cached for Carpark (0.659s)
[11/29/2024, 8:27:08 AM] [homebridge-ring] Snapshot cached for Front Door (0.784s)
[11/29/2024, 8:27:17 AM] [homebridge-ring] Used cached snapshot for Garden
[11/29/2024, 8:27:17 AM] [homebridge-ring] Loading new snapshot into cache for Garden
[11/29/2024, 8:27:17 AM] [homebridge-ring] Used cached snapshot for Carpark
[11/29/2024, 8:27:17 AM] [homebridge-ring] Loading new snapshot into cache for Carpark
[11/29/2024, 8:27:17 AM] [homebridge-ring] Used cached snapshot for Front Door
[11/29/2024, 8:27:17 AM] [homebridge-ring] Loading new snapshot into cache for Front Door
[11/29/2024, 8:27:17 AM] [homebridge-ring] Snapshot cached for Carpark (0.558s)
[11/29/2024, 8:27:18 AM] [homebridge-ring] Snapshot cached for Garden (0.784s)
[11/29/2024, 8:27:18 AM] [homebridge-ring] Snapshot cached for Front Door (0.576s)
[11/29/2024, 8:27:27 AM] [homebridge-ring] Used cached snapshot for Garden
[11/29/2024, 8:27:27 AM] [homebridge-ring] Loading new snapshot into cache for Garden
[11/29/2024, 8:27:27 AM] [homebridge-ring] Used cached snapshot for Carpark
[11/29/2024, 8:27:27 AM] [homebridge-ring] Loading new snapshot into cache for Carpark
[11/29/2024, 8:27:27 AM] [homebridge-ring] Used cached snapshot for Front Door
[11/29/2024, 8:27:27 AM] [homebridge-ring] Loading new snapshot into cache for Front Door
[11/29/2024, 8:27:27 AM] [homebridge-ring] Snapshot cached for Garden (0.586s)
[11/29/2024, 8:27:28 AM] [homebridge-ring] Snapshot cached for Carpark (0.777s)
[11/29/2024, 8:27:31 AM] [homebridge-ring] Snapshot cached for Front Door (4.091s)
[11/29/2024, 8:27:37 AM] [homebridge-ring] Used cached snapshot for Garden
[11/29/2024, 8:27:37 AM] [homebridge-ring] Loading new snapshot into cache for Garden
[11/29/2024, 8:27:37 AM] [homebridge-ring] Used cached snapshot for Carpark
[11/29/2024, 8:27:37 AM] [homebridge-ring] Loading new snapshot into cache for Carpark
[11/29/2024, 8:27:37 AM] [homebridge-ring] Used cached snapshot for Front Door
[11/29/2024, 8:27:38 AM] [homebridge-ring] Snapshot cached for Carpark (0.769s)
[11/29/2024, 8:27:38 AM] [homebridge-ring] Snapshot cached for Garden (1.105s)
[11/29/2024, 8:28:00 AM] [homebridge-ring] Received push notification in unknown format
[11/29/2024, 8:28:00 AM] [homebridge-ring] {"data":{"gcmData":"{\"aps\":{\"alert\":\"[REDACTED] Front Door in Entry opened at 29.11.24 09:27\"},\"action\":\"com.ring.push.HANDLE_NEW_SENSOR_CONTACT_FAULT_NOTICE\",\"alarm_meta\":{\"location_id\":\[REDACTED]\"}}"},"from":"876313859327","priority":"normal","fcmMessageId":"363ce6a0-ada3-4cc1-bdcb-bacde45e25ac"}
`

**Comment by TravellingTechGuy** [comment] 2024-11-29 08:55
Not related probably... but I keep getting this:

`WARNING: Duplicate device name Front Door - Battery Service
WARNING: Duplicate device name motion_switch - Switch
WARNING: Duplicate device name motion_switch - Switch
ERROR: Parsing failed, duplicate uniqueID. motion_switch - Switch
ERROR: Parsing failed, duplicate uniqueID. motion_switch - Switch`

Even after re-installing everything.

**Comment by tsightler** [comment] 2024-12-06 21:38
@TravellingTechGuy

Thanks for providing logs.  Interestingly enough, none of the steps you listed are the actual steps from the [Notification Troubleshooting](https://github.com/dgreif/ring/wiki/Notification-Troubleshooting).  Simple removing and re-installing things on the Homebridge/Homekit side are unlikely to do anything if you are not receiving push notifications.  The documented steps are about removing the registrations for the app on the *Ring side*, which forces the app to re-register as a new device with new push notification credentials.

Now, in the end, in your case I'm still not sure that is the issue, because you are receiving at least some push notifications, although they are in the old, pre-FCM v1 format, which is a bit strange, so maybe forcing re-registration will help.

Also, it would help if you could post details about your camera settings, i.e. notification settings in the Ring app, etc.  Especially if you've enabled any of the new features.

**Comment by tsightler** [comment] 2024-12-06 21:47
@mistermakc Based on the logs your provided, your issues are completely different.  You don't have a working plugin so of course notifications will not work.  It looks like you were still on 12.x, which we know notifications will no longer work since the old FCM API was dead after July 2023.  Then you updated to 13.1, but had issues with fetch failures.  You should try with 13.2.0, or, even 13.2.1-beta.1 which have code which attempts to workaround the issues with the fetch failures.  However, you may also need to update to latest NodeJS LTS release to get it to reliable state.  Please try these steps and provide new logs if it is still not working.

**Comment by TravellingTechGuy** [comment] 2024-12-06 21:53
I should have mention of course, but the basic troubleshooting steps is what I did multiple times off course.

Wouldn't even take the effort of writings comments on Github if the documented steps were not done yet.

Only added these as wild guess of trying other stuff while out of other options.

Anyway, don't worry too much about it. Planning on migrating to another vanilla server soon and will do a totally new setup.

As you could not replicate yet, chances are all will work again.

**Comment by tsightler** [comment] 2024-12-07 00:36
@TravellingTechGuy Well, you would be 1 of a 100 then!  Appreciate the update.  Realistically, if the push notifications are not arriving, it's nearly impossible to figure out what to do with that as there are not separate push-receivers per-cameras/device, it's  just a single push-receiver per homebridge-ring instance.  In you case, it's clear some messages are arriving, but if there's none from a ding, then it feels like it can only be due to no notification being sent by Ring.

I suppose it's possible that Ring has changed something with specific cameras, or perhaps in specific countries, but if it's really not sending push notifications, I have no idea what we can do with that.  If it still doesn't work after you change servers, and you are willing to dig this deep into it, feel free to open a new issue.

I'm probably going to close this issue now as there was never proper logs provided by OP and the only other logs that were provided were for an entirely not working plugin, which is not what this issue is about.

**Closed by tsightler** 2024-12-07 00:36 UTC
Labels: bug
