### ISSUE TITLE
Homebridge restarting when trying to view camera

### ISSUE THREAD

**Issue by arturlukosek** [dgreif/ring#1164] opened 2023-02-19 12:41 UTC
# Bug Report

### Describe the Bug
Many times when trying to view cameras from homekit homebridge throw errors and restaring

### To Reproduce
 - Start Homebridge
 - Click on the camera in home app
 - See error from homebridge pased below

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs

[19/02/2023, 10:34:13] [Ring] Received stream data from Nagyatád Entrance (4.105s)
[19/02/2023, 10:34:13] [Ring] Stream Prepared for Nagyatád Garden (0.666s)
[19/02/2023, 10:34:13] [Ring] Preparing Live Stream for Nagyatád Side
[19/02/2023, 10:34:13] Error: negotiate codecs failed.
    at RTCPeerConnection.setRemoteRTP (/usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1022:13)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:890:14
    at Array.map (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:855:38)
    at WeriftPeerConnection.createAnswer (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)
    at WebrtcConnection.handleMessage (/usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25
    at doInnerSub (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at WebSocket.handler (/usr/local/lib/node_modules/homebridge-ring/node_modules/rxjs/src/internal/observable/fromEvent.ts:288:52)
    at callListener (/usr/local/lib/node_modules/homebridge-ring/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/usr/local/lib/node_modules/homebridge-ring/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/homebridge-ring/node_modules/ws/lib/websocket.js:1180:20)
[19/02/2023, 10:34:13] Got SIGTERM, shutting down Homebridge...

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: 16.13.2
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: 11.7.1
 - homebridge: 1.6

**Comment by tsightler** [comment] 2023-02-19 23:57
This is a duplicate of https://github.com/dgreif/ring/issues/1145.  Ring is doing crazy things randomly enabled HEVC/H.265 and causing all kinds of problems (See Ring community forum).  You will need to enable Legacy Video mode.

@dgreif One thing I will say about this, since I'm starting to see the same issue in ring-mqtt, is that you might want to consider trapping the error so that at least the process doesn't crash.  For ring-mqtt modified the sdp message handler in webrtc-connection.js to wrap the createAnswer call with a try/catch and log an error about codec mistmatch and checking for legacy mode.  Otherwise you the error crashes the entire process.

I'm not sure what to do about this long term though, I've been considering adding H.265 and just let it pass through, but there are so many downstream browsers and devices that don't have support.  The best thing is for users to enable Legacy Mode.  I've even been considering detecting and forcing this mode during device discovery.

**Comment by bettsns** [comment] 2023-02-23 15:47
I am seeing this as well. I enabled Legacy Mode on one of my newer cameras and it seemed to have fixed it for a couple of days and now back to not working.

**Comment by dgreif** [comment] 2023-02-25 16:26
Thanks for the feedback @tsightler. I've updated the code to handle codec negotiation failures more gracefully. It will trigger an `onCallEnded` event as soon as negotiation fails, but won't crash the process anymore

**Closed** 2023-05-13 14:54 UTC
Labels: bug
