### ISSUE TITLE
Below error issues observed off late.

### ISSUE THREAD

**Issue by shaileshck** [dgreif/ring#686] opened 2021-07-07 09:37 UTC
Off late observing not getting notifications on phone for ring motion or doorbell. 

Can see following in logs. 

3:04 4
Homebridge
[07/07/2021, 14:24:461
[Ring] Preparing
工i
ve Stream for Front Door
[07/07/2021, 14:24:471
[Ring] Waiting for
stream data
from Front Door (0.673s)
[07/07/2021, 14:24:47] [Ring] Received str
eam data from Front Door (0.705s)
[07/07/2021, 14:24:47] [Ring] Streaming ac
tive for Front Door
[07/07/2021, 14:24:481
[Ring] Stopped Live
Stream for Front Door
(node: 28713) UnhandledPromiseRejectionwarn
ing: Error: SIP request made after call wa
S
destroyed
at SipCall.request (/usr/local/lib/nod
e
modules/homebridge-ring/lib/api/sip-call
. js:117:35)
at SipCall.sendKeyFrameRequest
(/usr/l
ocal/lib/node modules/homebridge-ring/lib/
api/sip-call.js:188:21/
at SipCall.
•‹anonymous> (/usr/local/lib
/node modules/homebridge-ring/lib/api/sip-
call.js:216:24)
at Generator.next (<anonymous>)
at fulfilled (/usr/local/lib/node modu
les/homebridge-ring/lib/api/sip-call.js:5:
58)
(node: 28713) UnhandledPromiseRejectionwarn
ing: Unhandled promise rejection. This err
or originated either by throwing inside of
an async function without a catch block,
or by rejecting a promise which was not ha
ndled with •catch). To terminate the node
process on unhandled promise rejection,
u
se the CLI flag
--unhandled-rejections=st
rict'
(see https://nodejs.org/api/cli.html
#cli unhandled rejections mode). (rejectio
n id: 247)
[07/07/2021, 14:24:581
[Ring] Preparing Li
ve Stream for Front Door
[07/07/2021, 14:24:59] [Ring] Waiting for
stream data from Front Door (0.838s)
[07/07/2021, 14:24:59] [Ring] Received str
eam
da+
C-Am
Ivant
Maa~
001-1
<
homebridge.local

**Comment by dgreif** [comment] 2021-07-26 04:30
This is likely caused by #616, which should hopefully be fixed in the latest release.

**Closed by dgreif** 2021-07-26 04:30 UTC
Labels: bug, duplicate
