### ISSUE TITLE
Stream Ring to RTSP - always getting "Call has ended" after very short time - not with Homebridge

### ISSUE THREAD

**Issue by BAngel87** [dgreif/ring#559] opened 2021-01-28 21:12 UTC
A little bit off topic but I hope you can help me. First thank for this great Work!

I have ring on my raspberry running incl. Homebridge (everything is fine incl. Auth.)

Now I try to add the camera to a rasp stream like mentioned here:
[https://github.com/dgreif/ring/issues/136#issuecomment-634516280](url)

What I did:

I cloned ring from git
I seted up browser-example like it was mentioned in the link.

(I have 
npm install -g typescript
npm install -g ts-node
installed)

And now trying to run the script inside the Folder with:

ts-node browser-example.ts

I get the following errors:

`

/usr/lib/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
browser-example.ts:3:27 - error TS2307: Cannot find module 'util' or its corresponding type declarations.

3 import { promisify } from 'util'
                            ~~~~~~
browser-example.ts:4:12 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

4 const fs = require('fs'),
             ~~~~~~~
browser-example.ts:5:10 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

5   path = require('path'),
           ~~~~~~~
browser-example.ts:6:13 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

6   express = require('express')
              ~~~~~~~
browser-example.ts:16:21 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

16       refreshToken: process.env.RING_REFRESH_TOKEN!,
                       ~~~~~~~
browser-example.ts:59:5 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

59     process.exit()
       ~~~~~~~

    at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)`

And I'm a beginner so I don't really know how to get a script correctly running or what I'm doing wrong.

Is it right to run the example in a different folder than the hombridge ring folder?

Where is my mistake? Thanks in advance,

Greetings from Corona Germany.....

**Comment by bachdinhnhan** [comment] 2021-01-28 21:16
After cloning Ring from github, did you run the command “npm install” yet?

**Comment by BAngel87** [comment] 2021-01-28 21:18
No, because I did installed it originally through Homebridge incl. Setup (Homebridge-UI) and there it is working

**Comment by BAngel87** [comment] 2021-01-28 21:18
I just did the clone for the examples

**Comment by bachdinhnhan** [comment] 2021-01-28 21:33
Sorry but I’m not familiar with Home Bridge. I work directly with Ring project.

Just a quick note: Look at package.json located in Ring project, try to install one by one from devDependences to figure out what’s missing.
To me, I would start with packages beginning by “@types”
`  "devDependencies": {
    "@nestjs/common": "7.6.5",
    "@nestjs/core": "7.6.5",
    "@types/debug": "4.1.5",
    "@types/jest": "26.0.20",
    "@types/node": "14.14.20",
    "@types/socket.io-client": "1.4.34",
    "@types/uuid": "8.3.0",
    "@typescript-eslint/eslint-plugin": "4.12.0",
    "@typescript-eslint/parser": "4.12.0",
    "conventional-github-releaser": "3.1.5",
    "dotenv": "8.2.0",
    "eslint": "7.17.0",
    "eslint-config-prettier": "7.1.0",
    "eslint-plugin-jest": "24.1.3",
    "eslint-plugin-prettier": "3.3.1",
    "express": "4.17.1",
    "homebridge": "1.1.7",
    "homebridge-config-ui-x": "4.36.0",
    "jest": "26.6.3",
    "prettier": "2.2.1",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "standard-version": "9.1.0",
    "ts-jest": "26.4.4",
    "typescript": "4.1.3"
  }, `

**Comment by BAngel87** [comment] 2021-01-28 21:44
I'm no getting (trying to run example.ts first:

SError: ⨯ Unable to compile TypeScript:
example.ts:11:21 - error TS2304: Cannot find name 'eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ'.

11       refreshToken: eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTE4Njk3OTYsInJlZnJlc2hfY2lk9vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6NTU5MDQyNywicm5kIjoiZDhIRUtRWnZNTXhhUWciLCJzZXNzaW9uX2lkIjoiYTZmNDRlNWEtZjQxMS00YTFhLTkzM2UtMjhjNWQ1NTU2MGVlIiwidHlwZSI6InJlZnJlc2gtdG9rZW4ifQ.CSVQDIeqBHvhGNFyC8nptloBELsOB2fo8IPx0OLRiLhR8YsQlJWbEieFB4Il1wD6W47syYN0EHxnVa400M5u9w,
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)


How do I need to put in the refresh token in the example?

**Comment by BAngel87** [comment] 2021-01-28 21:44
I did:
// Replace with your refresh token
      refreshToken: env.RING_REFRESH_TOKEN!,
to
// Replace with your refresh token
      refreshToken: eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTE4Njk3OTYsInJlZnJlc2M5u9w,

**Comment by bachdinhnhan** [comment] 2021-01-28 21:48
> I did:
> // Replace with your refresh token
> refreshToken: env.RING_REFRESH_TOKEN!,
> to
> // Replace with your refresh token
> refreshToken: eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTE4Njk3OTYsInJlZnJlc2M5u9w,

Put your string in a quote, for example: “ eyJhbGciOiJI.....”

**Comment by BAngel87** [comment] 2021-01-29 07:23
Thank you! Now the example.ts is working:

Found 1 location(s) with 1 camera(s).
Refresh Token Updated:  eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MTE5MDQ5MzQsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6NTU5MDQyNywicm5kIjoidnltTEFqMkpRSTlrN3ciLCJzZXNzaW9uX2lkIjoiYTZmNDRlNWEtZjQxMS00YTFhLTkzM2UtMjhjNWQ1NTU2MGVlIiwidHlwZSI6InJlZnJlc2gtdG9rZW4ifQ.eU5Vedb3LcoOgxdNS4rcrnoQTO3isG2LX5DbkeDCgfASuV59awGAPvCl270ZM7vhpXhT_nAlCwjW48ubFVSeSA

Location My Location (u0wv00-5ajcr-0) has the following 1 camera(s):
- 6400490: Haustür (lpd_v2)

Location My Location (u0wv00-5ajcr-0) has the following 0 device(s):
Listening for motion and doorbell presses on your cameras.
(node:7843) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.env'
(node:7843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Now I will try to get the stream running! and come back here :-)

**Comment by BAngel87** [comment] 2021-01-29 13:37
Hey, now it is working (initially) but I always get after a very short time the error: Call has ended

So I can stream for about 10- 15 Seconds,...

**Comment by BAngel87** [comment] 2021-01-29 13:51
And, if I try it in the Homebridge App the streaming is constantly working so this should be a problem of the Script,....

**Comment by BAngel87** [comment] 2021-01-29 14:32
Always after fact 1 Minute also with the following example:

`import 'dotenv/config'
import { RingApi } from '../api'
import * as path from 'path'
import { cleanOutputDirectory, outputDirectory } from './util'

/**
 * This example streams to files, each with 10 seconds of video.
 * The output will be in output/part${part #}.mp4
 **/

async function example() {
  const ringApi = new RingApi({
      // Replace with your refresh token
      refreshToken: "eyJhbGciOiJIUzUxMiIsImprdSI6IiZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6NTU5MDQyNywicm5kIjoiZDhIRUtRWnZNTXhhUWciLCJzZXNzaW9uX2lkIjoiYTZmNDRlNWEtZjQxMS00YTFhLTkzM2UtMjhjNWQ1NTU2MGVlIiwidHlwZSI6InJlZnJlc2gtdG9rZW4ifQ.CSVQDIeqBHvhGNFyC8nptloBELsOB2fo8IPx0OLRiLhR8YsQlJWbEieFB4Il1wD6W47syYN0EHxnVa400M5u9w",
      debug: true,
    }),
    [camera] = await ringApi.getCameras()

  if (!camera) {
    console.log('No cameras found')
    return
  }

  await cleanOutputDirectory()

  console.log('Starting Video...')
  const sipSession = await camera.streamVideo({
    // save video 10 second parts so the mp4s are playable and not corrupted:
    // https://superuser.com/questions/999400/how-to-use-ffmpeg-to-extract-live-stream-into-a-sequence-of-mp4
    output: [
      '-flags',
      '+global_header',
      '-f',
      'segment',
      '-segment_time',
      '10', // 10 seconds
      '-segment_format_options',
      'movflags=+faststart',
      '-reset_timestamps',
      '1',
      path.join(outputDirectory, 'part%d.mp4'),
    ],
  })
  console.log('Video started, streaming to part files...')

  sipSession.onCallEnded.subscribe(() => {
    console.log('Call has ended')
    process.exit()
  })

  setTimeout(function () {
    console.log('Stopping call...')
    sipSession.stop()
  }, 60 * 5000) // Stop after 5 minute
}

example()
`

**Comment by dgreif** [comment] 2021-01-29 14:57
@BAngel87 RTSP streaming isn't something that I have tried to officially support.  The other issue that you linked has details on my reasoning.  

Just a security note, you posted your refresh token in multiple comments.  This can be used by anyone to access your streams and shouldn't be posted anywhere public.  I recommend you go into the "Control Center" in the Ring app and revoke access to any sessions that may have been created with that refresh token, just to be on the safe side.

Regarding the timeout, it's likely caused by lack of communication back to Ring.  Ring is expecting to receive RTCP back from the client. RTCP describes how many packets have been received by the client over time, but in this case Ring uses it as a keep-alive as well.  In Homebridge, the RTCP is generated by HomeKit and the plugin simply forwards those packets to the Ring server.  There is still a bug with the newer Ring servers (See #479), and I haven't had a chance to circle back on that.  Once I do, it may fix your issues.

**Comment by BAngel87** [comment] 2021-01-29 15:00
> @BAngel87 RTSP streaming isn't something that I have tried to officially support. The other issue that you linked has details on my reasoning.
> 
> Just a security note, you posted your refresh token in multiple comments. This can be used by anyone to access your streams and shouldn't be posted anywhere public. I recommend you go into the "Control Center" in the Ring app and revoke access to any sessions that may have been created with that refresh token, just to be on the safe side.
> 
> Regarding the timeout, it's likely caused by lack of communication back to Ring. Ring is expecting to receive RTCP back from the client. RTCP describes how many packets have been received by the client over time, but in this case Ring uses it as a keep-alive as well. In Homebridge, the RTCP is generated by HomeKit and the plugin simply forwards those packets to the Ring server. There is still a bug with the newer Ring servers (See #479), and I haven't had a chance to circle back on that. Once I do, it may fix your issues.

Thank you, my refresh token was always shortened by me #266 

Do you have a time plan when to update / fix this problem? But I also have this problem when recording or so, and if I look to the discussions it looks like other people get it working over hours!?

**Comment by dgreif** [comment] 2021-01-29 16:40
I don't have a timeline, but one of my cameras is now using the new servers so it should be easier to for me to debug the issue.  You can subscribe to that other issue for updates.  Beyond that problem, are you all set with your RTSP setup?

**Comment by BAngel87** [comment] 2021-01-29 17:55
Yes, everything else is working

**Comment by dgreif** [comment] 2021-01-29 17:56
Sounds good. I'm going to close this issue in favor of the other one about streams ending early

**Closed by dgreif** 2021-01-29 17:56 UTC
Labels: discussion
