### ISSUE TITLE
No sound in live view -doorbell2

### ISSUE THREAD

**Issue by zilnik1234** [dgreif/ring#488] opened 2020-11-06 10:26 UTC
I have a ring doorbell 2 and it seems after the last update that i made on ring plugin for homebridge i'am not able to hear any sound from the doorbell in live mode. I have the speaker slider and everything..but no 
I'm using hoobs on latest version

**Comment by dgreif** [comment] 2020-11-06 16:41
Duplicate of #487

**Closed by dgreif** 2020-11-06 16:41 UTC
Labels: duplicate
