### ISSUE TITLE
Motion Detect on All Ring Cameras - Not Getting to HB or HK

### ISSUE THREAD

**Issue by MoTechnicalities** [dgreif/ring#1219] opened 2023-05-19 03:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I have 7 Ring Cameras and sadly Motion Detect is not passing through to _Homebridge_ or _HomeKit_.
I also have a Ring Mailbox Sensor and that still passes the motion detection.

I suspect Ring changed its Data Structure again and screwed us over in the same way as they started placing fake motion sensors on Ring Bulbs.

### To Reproduce

Just look at the Homebridge Accessories while moving in front of your camera. The Ring App gets the motion detection, but not Homebridge or HomeKit. Thus any HomeKit automation that uses Motion Detection from Ring cameras no longer runs! 

![image](https://github.com/dgreif/ring/assets/68468472/daaab30a-f766-412f-8385-e5b2c4549754)

### Expected behavior

The cameras should pass Motion to Homebridge so Homebridge can pass Motion to Homekit.

### Homebridge Ring Config

```shell
irrelevant.
```

### OS

Rasbian

### Node.js Version

v18.16.0 

### NPM Version

version

### Homebridge/HOOBs Version

v1.6.1 

### Homebridge Ring Plugin Version

v11.7.5

### Operating System

Rasbian

**Comment by benjackson1111** [comment] 2023-05-20 02:51
This also applies to the 'button' on the Ring Cameras. I have it set to automatically turn on a switch when the button is pressed, and in the last week or so (I think coinciding with the release of the homekit update with the new code) and no matter what I do (have tried to unbridge, resetting cam, wifi, homebridge etc), it will no longer show up in hb/homekit as a button press. Looking forward to this being fixed! Thank you.

**Comment by HydroCarbons** [comment] 2023-05-20 04:53
+1, It seems "camera.onNewNotification" is not triggering anymore.

**Comment by dgreif** [comment] 2023-05-20 13:32
This is a duplicate of #1218

**Closed by dgreif** 2023-05-20 13:32 UTC
Labels: bug
