### ISSUE TITLE
camera.onNewDing.subscribe not always triggering

### ISSUE THREAD

**Issue by ZerGo0** [dgreif/ring#648] opened 2021-05-13 18:02 UTC
# Bug Report

### Describe the Bug
Using camera.onNewDing.subscribe doesn't trigger all the time. It detects a new ding every now and then, but it is not reliable. I have noticed this a year or so ago, but I didn't have a way to verify/debug it, but I finally found one.

### To Reproduce
 - subscribe to camera.onNewDing
 - log every new ping
 - trigger a new ding

### Expected behavior
Console output for every new ding.

### Screenshots/Logs
![LOG](https://i.imgur.com/7IhGIFx.png)

### Additional context
Using ringApi.fetchActiveDings in a setInterval it triggers every time unlike camera.onNewDing.subscribe, you can see that in the screenshot above. I'm not sure if that is a issue with this library or ring themselves. I had this problem for a year or so now, I also made a report before, but couldn't really debug it reliably. I can do that now tho.

### Environment

 - OS: Ubuntu 20.04
 - Node.js: v14.17.0
 - NPM: 6.14.13
 - ring-client-api: 9.18.0

**Comment by dgreif** [comment] 2021-05-17 04:09
@ZerGo0 I can think of a couple reasons why you might be seeing this.  First, if you are running your debug setup in the same process, then both requests are happening with the same hardware id.  On the Ring servers, they only hand out dings _once_ per hardware id, unless a live stream is requested in which case you _might_ get the same ding again.  I'd encourage you to take a look at the ding ids as well.  It's possible that you are fetching the _same_ ding but the `onNewDing` is filtering it out because it has already seen that id.  I put a lot of time into ensuring dings were fetched properly early in the life of the library, but it's also possible that Ring has changed something on their end.  If you figure out something more concrete, I'd be happy to add a fix.  Thanks for digging into it!

**Comment by ZerGo0** [comment] 2021-05-17 07:40
> @ZerGo0 I can think of a couple reasons why you might be seeing this. First, if you are running your debug setup in the same process, then both requests are happening with the same hardware id. On the Ring servers, they only hand out dings _once_ per hardware id, unless a live stream is requested in which case you _might_ get the same ding again. 

Hey, I will check it after work, quick question tho, "one per hardware id" means that only one of the two functions (fetchActiveDings or onNewDing) can get that ding, right?

**Comment by dgreif** [comment] 2021-05-17 16:11
> "one per hardware id" means that only one of the two functions (fetchActiveDings or onNewDing) can get that ding, right?

Yeah, that should be the case (in theory).

**Comment by djm181** [comment] 2021-07-14 01:29
@ZerGo0 did you figure this out?

**Comment by dgreif** [comment] 2021-08-06 04:40
I think this was caused by issues with requests to the API, specifically #616.  Closing this in favor of the other issue as this is just a side-effect.

**Closed by dgreif** 2021-08-06 04:40 UTC
Labels: bug
