### ISSUE TITLE
myQ Integration

### ISSUE THREAD

**Issue by amurbain** [dgreif/ring#1372] opened 2023-12-03 08:59 UTC
### Description

Seeing as myQ has ripped away API access to the world, we can still add myQ devices to the Ring app. So, is there a way to integrate myQ items into this Ring plugin?

**Comment by tsightler** [comment] 2023-12-03 16:26
Duplicate of #1338.  Please search for duplicates before opening issues.

**Closed by tsightler** 2023-12-03 16:26 UTC
Labels: enhancement
