### ISSUE TITLE
Unable to Live Stream

### ISSUE THREAD

**Issue by Josech18** [dgreif/ring#1217] opened 2023-05-14 20:48 UTC
### Streaming Issue

Ring BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target

### Proposed Solution

Look at the error message provided. Seems to be an error with the Schema

### Environment

HOOBS

### What operating system are you on?

Other

### Relevant log output

```shell
5/14/2023, 3:43:55 PMRing BridgeRingStream Prepared for Front (0.415s)
5/14/2023, 3:43:55 PMRing BridgeRingActivating stream for Front (0.576s)
5/14/2023, 3:43:57 PMRing BridgeRingiceConnectionStateChange: completed
5/14/2023, 3:43:57 PMRing BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
5/14/2023, 3:43:57 PMRing BridgeRingconnectionStateChange: closed
5/14/2023, 3:43:57 PMRing BridgeRingiceConnectionStateChange: closed
5/14/2023, 3:43:57 PMRing BridgeRingERRORFailed to activate stream
5/14/2023, 3:43:57 PMRing BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
5/14/2023, 3:44:02 PMRing BridgeRingPreparing Live Stream for Front Door
5/14/2023, 3:44:02 PMRing BridgeRingStream Prepared for Front Door (0.391s)
5/14/2023, 3:44:02 PMRing BridgeRingActivating stream for Front Door (0.486s)
5/14/2023, 3:44:03 PMRing BridgeRingiceConnectionStateChange: completed
5/14/2023, 3:44:03 PMRing BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
5/14/2023, 3:44:03 PMRing BridgeRingconnectionStateChange: closed
5/14/2023, 3:44:03 PMRing BridgeRingiceConnectionStateChange: closed
5/14/2023, 3:44:03 PMRing BridgeRingERRORFailed to activate stream
5/14/2023, 3:44:03 PMRing BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
5/14/2023, 3:44:14 PMRing BridgeRingPreparing Live Stream for Backyard
5/14/2023, 3:44:15 PMRing BridgeRingStream Prepared for Backyard (0.439s)
5/14/2023, 3:44:15 PMRing BridgeRingActivating stream for Backyard (0.576s)
5/14/2023, 3:44:15 PMRing BridgeRingiceConnectionStateChange: completed
5/14/2023, 3:44:15 PMRing BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
5/14/2023, 3:44:15 PMRing BridgeRingconnectionStateChange: closed
5/14/2023, 3:44:15 PMRing BridgeRingiceConnectionStateChange: closed
5/14/2023, 3:44:15 PMRing BridgeRingERRORFailed to activate stream
5/14/2023, 3:44:15 PMRing BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment] 2023-05-15 16:38
This is a duplicate of https://github.com/dgreif/ring/issues/1108

**Closed by dgreif** 2023-05-15 16:38 UTC
Labels: live-streaming
