### ISSUE TITLE
Option to disable all but error logging

### ISSUE THREAD

**Issue by marksthomas** [dgreif/ring#919] opened 2022-04-19 12:01 UTC
The new beta logs contains lines like:-

'Front Door Detected Motion. Loading snapshot before sending event to HomeKit'

I don't need to know or care about logs except when there is an error.

Can I get an option to disable all buy critial/error logs?

**Comment by marksthomas** [comment] 2022-05-17 08:13
Any sign of this option happening?

**Comment by dgreif** [comment] 2022-05-22 14:05
This is a duplicate of #906

**Closed by dgreif** 2022-05-22 14:05 UTC
Labels: enhancement
