### ISSUE TITLE
Live Stream Fails - TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by macBender** [dgreif/ring#451] opened 2020-09-16 23:30 UTC
# Live Streaming Issue

### Describe the live streaming issue
 All working flawlessly until this morning.  I updated my Apple TV HD homekit hub and iPhone to ios 14 and homebrifge to 1.2.2.  Tried opening live video on the Home app which fails displaying 'No Response This camera is not responding' and red exclamation mark. 

I also tried Apple TV 4K w/ ios 13 as the hub and iPad air 2 with ios 13.6 with the same error.

I also tried rolling back to homebridge 1.2.1 and restarting the server to no avail.

Live video is working on the Ring app and camera status is healthy.

### Screenshots/Logs

m=video 35660 RTP/SAVPF 99
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42000a
a=rtcp:57384 IN IP4 13.236.23.198
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:M1iYAKOoE+acz11GSXIZe1QEIi8R0IHw8ucD2QzY
[9/17/2020, 9:21:23 AM] [Ring] Failed to prepare stream for Front Door (2.036s)
[9/17/2020, 9:21:23 AM] [Ring] TypeError: Cannot read property 'match' of undefined
    at getRtpDescription (/usr/lib/node_modules/homebridge-ring/lib/api/sip-call.js:24:54)
    at parseRtpDescription (/usr/lib/node_modules/homebridge-ring/lib/api/sip-call.js:36:16)
    at SipCall.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/sip-call.js:204:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### Recommended solution
 Could be ios 14 related.

### Environment

 - Ring Camera: Video Doorbell Pro
 - OS: Ubuntu v18.04.03
 - Node.js:  v10.20.1
 - NPM: v6.14.4
 - homebridge-ring: v9.9.0
 - homebridge (if applicable) v:1.2.2
 - hoobs (if applicable): n/a

### Network Environment
 
Camera: 2.4GHz WiFi to Apple Airport Extreme
Router: Intel based Pfsense with nat-pmp configured
Internet: FTTP with static IP
Homebrige: Ubuntu 18.04.03 VM running above software
Homekit hub: Apple TV HD w/ iPadOS 14, home app on iPhone 11 Pro w/ ios 14.

**Comment by dgreif** [comment] 2020-09-16 23:32
Duplicate of #438 and #447.  Good to know others are having issues.

**Closed by dgreif** 2020-09-16 23:32 UTC
Labels: Ring, bug, duplicate
