### ISSUE TITLE
no detection events ring app stays in live view perpetually

### ISSUE THREAD

**Issue by proznik** [dgreif/ring#1332] opened 2023-10-15 22:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

ring app shows only live view events, every 9 minutes live view times out, then re-opens again, infinitely. started oct 8 2023 2:19 pm
no motion or ding events can happen bc camera is in constant live view. (apparently not a design feature of Ring) HB status appears to init ring plugin OK after restrat or server restart but then I get
[15/10/2023, 16:22:51] [Ring] Found the following locations:
[15/10/2023, 16:22:51] [Ring]   locationId: 9tsjjz-jat5-0 - 720 home
[15/10/2023, 16:22:51] [Ring] Creating location socket.io connection - 720 home
[15/10/2023, 16:22:52] [Ring] Ring connected to socket.io server
[15/10/2023, 16:22:52] [Ring] Configuring 1 cameras and 18 devices for location "720 home" - locationId: 9tsjjz-jat5-0
[15/10/2023, 16:23:01] [Ring] Preparing Live Stream for 720 ring
[15/10/2023, 16:23:02] [Ring] Stream Prepared for 720 ring (0.332s)
[15/10/2023, 16:23:02] [Ring] Activating stream for 720 ring (0.439s)
[15/10/2023, 16:23:02] [Ring] iceConnectionStateChange: completed
[15/10/2023, 16:23:03] [Ring] connectionStateChange: connecting
[15/10/2023, 16:23:03] [Ring] iceConnectionStateChange: new
[15/10/2023, 16:23:03] [Ring] iceConnectionStateChange: checking
[15/10/2023, 16:23:03] [Ring] Activating Session
[15/10/2023, 16:23:03] [Ring] Streaming active for 720 ring (1.323s)
[15/10/2023, 16:23:03] [Ring] iceConnectionStateChange: new
[15/10/2023, 16:23:03] [Ring] iceConnectionStateChange: connected
[15/10/2023, 16:23:03] [Ring] connectionStateChange: connected
[15/10/2023, 16:23:03] [Ring] Received stream data from 720 ring (2.082s)
[15/10/2023, 16:23:04] [Ring] UNKNOWN MESSAGE
[15/10/2023, 16:23:04] [Ring] {
  body: {
    doorbot_id: 289246680,
    session_id: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IlJNUyIsInR5cCI6IkpXVCJ9.eyJhbGV4YV9wb3J0IjoxODQ0MywiYXBwX3Nlc3Npb25fdG9rZW4iOiJyLm1zLnZlY0tGcGxLTzMrWmF4NGk5eExzaTRHZFNjQUtmWTltIiwiZGluZ19pZCI6IjcyOTAzMTQzNDc5Mjg5ODA5NTIiLCJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjoyODkyNDY2ODAsImV4cCI6MTY5NzQwOTMwMiwiaXAiOiIzNC4yMTAuMjMyLjE1NSIsInBpbmdfaW50ZXJ2YWwiOjEwLCJwb3J0Ijo4NTU3LCJybXNfZnFkbiI6IjM0LTIxMC0yMzItMTU1Ljc0NjU5OTc1MDExOC51cy13ZXN0LTIucHJvZC5ybXMucmluZy5kZXZpY2VzLmEyei5jb20iLCJybXNfdmVyc2lvbiI6IjhjOTQwNWU0IiwicnNwX3BvcnQiOjg1NTcsInJ0c3BfcG9ydCI6NDQzLCJzZXNzaW9uX2lkIjoiMDQyMjYzNDUtOTJhMS00MjAyLWI2NGYtYjE5MjRiYjllNzMzIiwic2lwX3BvcnQiOjE1MDY0LCJ3ZWJydGNfcG9ydCI6OTAwMiwid3dyX3BvcnQiOjE5NDQzfQ.gS_RS79y_jKG0UJHXNtPGfKCTVklM9UR71FFGXY_R3w',
    radar_data: [ [Object] ]
  },
  dialog_id: 'cdd0b8b5-9030-4022-9d4b-b64d63af91d0',
  method: 'timed_metadata'
}
[15/10/2023, 16:23:04] [Ring] UNKNOWN MESSAGE
[15/10/2023, 16:23:04] [Ring] {
  body: {
    doorbot_id: 289246680,
    session_id: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IlJNUyIsInR5cCI6IkpXVCJ9.eyJhbGV4YV9wb3J0IjoxODQ0MywiYXBwX3Nlc3Npb25fdG9rZW4iOiJyLm1zLnZlY0tGcGxLTzMrWmF4NGk5eExzaTRHZFNjQUtmWTltIiwiZGluZ19pZCI6IjcyOTAzMTQzNDc5Mjg5ODA5NTIiLCJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjoyODkyNDY2ODAsImV4cCI6MTY5NzQwOTMwMiwiaXAiOiIzNC4yMTAuMjMyLjE1NSIsInBpbmdfaW50ZXJ2YWwiOjEwLCJwb3J0Ijo4NTU3LCJybXNfZnFkbiI6IjM0LTIxMC0yMzItMTU1Ljc0NjU5OTc1MDExOC51cy13ZXN0LTIucHJvZC5ybXMucmluZy5kZXZpY2VzLmEyei5jb20iLCJybXNfdmVyc2lvbiI6IjhjOTQwNWU0IiwicnNwX3BvcnQiOjg1NTcsInJ0c3BfcG9ydCI6NDQzLCJzZXNzaW9uX2lkIjoiMDQyMjYzNDUtOTJhMS00MjAyLWI2NGYtYjE5MjRiYjllNzMzIiwic2lwX3BvcnQiOjE1MDY0LCJ3ZWJydGNfcG9ydCI6OTAwMiwid3dyX3BvcnQiOjE5NDQzfQ.gS_RS79y_jKG0UJHXNtPGfKCTVklM9UR71FFGXY_R3w',
    radar_data: [ [Object] ]
  },
  dialog_id: 'cdd0b8b5-9030-4022-9d4b-b64d63af91d0',
  method: 'timed_metadata'
}
[15/10/2023, 16:23:05] [Ring] UNKNOWN MESSAGE
[15/10/2023, 16:23:05] [Ring] {
  body: {
    doorbot_id: 289246680,
    session_id: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IlJNUyIsInR5cCI6IkpXVCJ9.eyJhbGV4YV9wb3J0IjoxODQ0MywiYXBwX3Nlc3Npb25fdG9rZW4iOiJyLm1zLnZlY0tGcGxLTzMrWmF4NGk5eExzaTRHZFNjQUtmWTltIiwiZGluZ19pZCI6IjcyOTAzMTQzNDc5Mjg5ODA5NTIiLCJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjoyODkyNDY2ODAsImV4cCI6MTY5NzQwOTMwMiwiaXAiOiIzNC4yMTAuMjMyLjE1NSIsInBpbmdfaW50ZXJ2YWwiOjEwLCJwb3J0Ijo4NTU3LCJybXNfZnFkbiI6IjM0LTIxMC0yMzItMTU1Ljc0NjU5OTc1MDExOC51cy13ZXN0LTIucHJvZC5ybXMucmluZy5kZXZpY2VzLmEyei5jb20iLCJybXNfdmVyc2lvbiI6IjhjOTQwNWU0IiwicnNwX3BvcnQiOjg1NTcsInJ0c3BfcG9ydCI6NDQzLCJzZXNzaW9uX2lkIjoiMDQyMjYzNDUtOTJhMS00MjAyLWI2NGYtYjE5MjRiYjllNzMzIiwic2lwX3BvcnQiOjE1MDY0LCJ3ZWJydGNfcG9ydCI6OTAwMiwid3dyX3BvcnQiOjE5NDQzfQ.gS_RS79y_jKG0UJHXNtPGfKCTVklM9UR71FFGXY_R3w',
    radar_data: [ [Object] ]
  },
  dialog_id: 'cdd0b8b5-9030-4022-9d4b-b64d63af91d0',
  method: 'timed_metadata'
}

### To Reproduce

restart HB or resart server then wait for plugin status to immediately fail.
refresh token, re-auth'd to ring no difference
uninstalled plugin, restarted server, re-installed plugin, re-auth'd, same error

### Expected behavior

since this worked fine until 1400 hrs on OCT 8, I looked for events or hardware changes proximate. reset internet, router, and other devices work as expected.
Ring app records only live events, except they are not triggered by user action--appear to be spontaneous. since live view is constantly on, then ding and motion events never get generated, since app and plug in suspect you are actually watching live feed 24x7x365
please restore the non-continuous live view so motion and ding notifications can occur.

### Relevant log output

```shell
[15/10/2023, 16:22:51] [Ring] Found the following locations:
[15/10/2023, 16:22:51] [Ring]   locationId: 9tsjjz-jat5-0 - 720 home
[15/10/2023, 16:22:51] [Ring] Creating location socket.io connection - 720 home
[15/10/2023, 16:22:52] [Ring] Ring connected to socket.io server
[15/10/2023, 16:22:52] [Ring] Configuring 1 cameras and 18 devices for location "720 home" - locationId: 9tsjjz-jat5-0
[15/10/2023, 16:23:01] [Ring] Preparing Live Stream for 720 ring
[15/10/2023, 16:23:02] [Ring] Stream Prepared for 720 ring (0.332s)
[15/10/2023, 16:23:02] [Ring] Activating stream for 720 ring (0.439s)
[15/10/2023, 16:23:02] [Ring] iceConnectionStateChange: completed
[15/10/2023, 16:23:03] [Ring] connectionStateChange: connecting
[15/10/2023, 16:23:03] [Ring] iceConnectionStateChange: new
[15/10/2023, 16:23:03] [Ring] iceConnectionStateChange: checking
[15/10/2023, 16:23:03] [Ring] Activating Session
[15/10/2023, 16:23:03] [Ring] Streaming active for 720 ring (1.323s)
[15/10/2023, 16:23:03] [Ring] iceConnectionStateChange: new
[15/10/2023, 16:23:03] [Ring] iceConnectionStateChange: connected
[15/10/2023, 16:23:03] [Ring] connectionStateChange: connected
[15/10/2023, 16:23:03] [Ring] Received stream data from 720 ring (2.082s)
[15/10/2023, 16:23:04] [Ring] UNKNOWN MESSAGE
[15/10/2023, 16:23:04] [Ring] {
  body: {
    doorbot_id: 289246680,
    session_id: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IlJNUyIsInR5cCI6IkpXVCJ9.eyJhbGV4YV9wb3J0IjoxODQ0MywiYXBwX3Nlc3Npb25fdG9rZW4iOiJyLm1zLnZlY0tGcGxLTzMrWmF4NGk5eExzaTRHZFNjQUtmWTltIiwiZGluZ19pZCI6IjcyOTAzMTQzNDc5Mjg5ODA5NTIiLCJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjoyODkyNDY2ODAsImV4cCI6MTY5NzQwOTMwMiwiaXAiOiIzNC4yMTAuMjMyLjE1NSIsInBpbmdfaW50ZXJ2YWwiOjEwLCJwb3J0Ijo4NTU3LCJybXNfZnFkbiI6IjM0LTIxMC0yMzItMTU1Ljc0NjU5OTc1MDExOC51cy13ZXN0LTIucHJvZC5ybXMucmluZy5kZXZpY2VzLmEyei5jb20iLCJybXNfdmVyc2lvbiI6IjhjOTQwNWU0IiwicnNwX3BvcnQiOjg1NTcsInJ0c3BfcG9ydCI6NDQzLCJzZXNzaW9uX2lkIjoiMDQyMjYzNDUtOTJhMS00MjAyLWI2NGYtYjE5MjRiYjllNzMzIiwic2lwX3BvcnQiOjE1MDY0LCJ3ZWJydGNfcG9ydCI6OTAwMiwid3dyX3BvcnQiOjE5NDQzfQ.gS_RS79y_jKG0UJHXNtPGfKCTVklM9UR71FFGXY_R3w',
    radar_data: [ [Object] ]
  },
  dialog_id: 'cdd0b8b5-9030-4022-9d4b-b64d63af91d0',
  method: 'timed_metadata'
}
[15/10/2023, 16:23:04] [Ring] UNKNOWN MESSAGE
[15/10/2023, 16:23:04] [Ring] {
  body: {
    doorbot_id: 289246680,
    session_id: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IlJNUyIsInR5cCI6IkpXVCJ9.eyJhbGV4YV9wb3J0IjoxODQ0MywiYXBwX3Nlc3Npb25fdG9rZW4iOiJyLm1zLnZlY0tGcGxLTzMrWmF4NGk5eExzaTRHZFNjQUtmWTltIiwiZGluZ19pZCI6IjcyOTAzMTQzNDc5Mjg5ODA5NTIiLCJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjoyODkyNDY2ODAsImV4cCI6MTY5NzQwOTMwMiwiaXAiOiIzNC4yMTAuMjMyLjE1NSIsInBpbmdfaW50ZXJ2YWwiOjEwLCJwb3J0Ijo4NTU3LCJybXNfZnFkbiI6IjM0LTIxMC0yMzItMTU1Ljc0NjU5OTc1MDExOC51cy13ZXN0LTIucHJvZC5ybXMucmluZy5kZXZpY2VzLmEyei5jb20iLCJybXNfdmVyc2lvbiI6IjhjOTQwNWU0IiwicnNwX3BvcnQiOjg1NTcsInJ0c3BfcG9ydCI6NDQzLCJzZXNzaW9uX2lkIjoiMDQyMjYzNDUtOTJhMS00MjAyLWI2NGYtYjE5MjRiYjllNzMzIiwic2lwX3BvcnQiOjE1MDY0LCJ3ZWJydGNfcG9ydCI6OTAwMiwid3dyX3BvcnQiOjE5NDQzfQ.gS_RS79y_jKG0UJHXNtPGfKCTVklM9UR71FFGXY_R3w',
    radar_data: [ [Object] ]
  },
  dialog_id: 'cdd0b8b5-9030-4022-9d4b-b64d63af91d0',
  method: 'timed_metadata'
}
[15/10/2023, 16:23:05] [Ring] UNKNOWN MESSAGE
[15/10/2023, 16:23:05] [Ring] {
  body: {
    doorbot_id: 289246680,
    session_id: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IlJNUyIsInR5cCI6IkpXVCJ9.eyJhbGV4YV9wb3J0IjoxODQ0MywiYXBwX3Nlc3Npb25fdG9rZW4iOiJyLm1zLnZlY0tGcGxLTzMrWmF4NGk5eExzaTRHZFNjQUtmWTltIiwiZGluZ19pZCI6IjcyOTAzMTQzNDc5Mjg5ODA5NTIiLCJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjoyODkyNDY2ODAsImV4cCI6MTY5NzQwOTMwMiwiaXAiOiIzNC4yMTAuMjMyLjE1NSIsInBpbmdfaW50ZXJ2YWwiOjEwLCJwb3J0Ijo4NTU3LCJybXNfZnFkbiI6IjM0LTIxMC0yMzItMTU1Ljc0NjU5OTc1MDExOC51cy13ZXN0LTIucHJvZC5ybXMucmluZy5kZXZpY2VzLmEyei5jb20iLCJybXNfdmVyc2lvbiI6IjhjOTQwNWU0IiwicnNwX3BvcnQiOjg1NTcsInJ0c3BfcG9ydCI6NDQzLCJzZXNzaW9uX2lkIjoiMDQyMjYzNDUtOTJhMS00MjAyLWI2NGYtYjE5MjRiYjllNzMzIiwic2lwX3BvcnQiOjE1MDY0LCJ3ZWJydGNfcG9ydCI6OTAwMiwid3dyX3BvcnQiOjE5NDQzfQ.gS_RS79y_jKG0UJHXNtPGfKCTVklM9UR71FFGXY_R3w',
    radar_data: [ [Object] ]
  },
  dialog_id: 'cdd0b8b5-9030-4022-9d4b-b64d63af91d0',
  method: 'timed_metadata'
}
```

### Homebridge Ring Config

```shell
System Information
Timezone	GMT-0600
OS	Raspbian GNU/Linux Bullseye (11)
Hostname	homebridge-proz v 1.6.1
IPv4 (eth0)	192.168.x.xxx
IPv6 (eth0)	fd20:739d:c05c:46fc:9228:ef18:b2bd:xxxx
Node.js Version	v18.18.0
User	pi
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Plugin Path	/var/lib/homebridge/node_modules
Service Mode	Yes
```

### Additional context

Ring tech support aware of issue, had me disable HB and retest, no difference in ring output

### OS

Raspian Bullseye

### Node.js Version

18.18.0

### NPM Version

9.8.1

### Homebridge/HOOBs Version

1.6.1

### Homebridge Ring Plugin Version

12.0.1

### Operating System

Raspian Bullseye

**Comment by tsightler** [comment] 2023-10-15 23:05
This is almost certainly a duplicate of https://github.com/dgreif/ring/issues/1291. It's an issue with some of the newer versions of tvOS, specifically tvOS 17.  The summary version is, this plugin doesn't start streams on it's own, it starts streams when some device requests a stream, if a stream is constantly starting then something is requesting it and you have to stop whatever that is.  Apple added some features in tvOS 17 that seem to constantly requests streams in some cases, you'll have to address this there.

**Closed** 2023-10-15 23:05 UTC
Labels: bug
