### ISSUE TITLE
Fast battery drain since version 12

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#1302] opened 2023-08-22 16:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Since installing Version 12 my 2 doorbells batteries are drained from 100% to 0% in 36 hours

### To Reproduce

Changed batteries earlier today and already drained from 100% to 78%

### Expected behavior

Batteries usually last me at least 1 month before re charging

### Homebridge Ring Config

```shell
Not needed
```

### OS

Rasbian

### Node.js Version

Lastest

### NPM Version

Latest

### Homebridge/HOOBs Version

Latest

### Homebridge Ring Plugin Version

V12

### Operating System

Raspian

**Comment by tsightler** [comment] 2023-08-22 17:29
Without debug logs it's pretty much impossible to have any hope of understanding what might be causing this, however, there were no changes in the snapshot code that I'm aware of and no changes to streaming on the frontend, so it's difficult to see how anything could possibly cause this.  Please enable debug logging in the Homebridge Ring plugin and provide them as soon as possible.  Also, are you running any beta versions of anything like iOS, etc?

**Comment by adavison007** [comment] 2023-08-23 18:49
Hi, sure happy to enable to debug log, how do I do that?

Adam Davison
***@***.*** ***@***.***>
07748 761448

On 22 Aug 2023, at 18:30, tsightler ***@***.***> wrote:


Without debug logs it's pretty much impossible to have any hope of understanding what might be causing this, however, there were no changes in the snapshot code that I'm aware of and no changes to streaming on the frontend, so it's difficult to see how anything could possibly cause this. Please enable debug logging in the Homebridge Ring plugin and provide them as soon as possible. Also, are you running any beta versions of anything like iOS, etc?

**Comment by tsightler** [comment] 2023-08-23 18:57
Go to the plugin settings, open "Optional Configuration", put a check by "Debug Logging" and save the config, then restart Homebridge to active the new settings.

**Comment by adavison007** [comment] 2023-08-24 16:21
Thanks, it seems the battery drain has stopped today, must have been a ring issue or wifi challenge.

Adam Davison
***@***.*** ***@***.***>
07748 761448

On 23 Aug 2023, at 19:57, tsightler ***@***.***> wrote:


Go to the plugin settings, open "Optional Configuration", put a check by "Debug Logging" and save the config, then restart Homebridge to active the new settings.

**Comment by tsightler** [comment] 2023-08-24 16:37
OK, thanks for the update, I will close this for now.  If it comes back please be sure to enable debug logging and provide those logs when opening a new issue.  In the end, there's not much that homebridge-ring can do the eat battery other than taking snapshots too often or if for some reasons live streams stay active.  The latter would still not likely be caused by the plugin, but by something triggering the plugin.

**Closed by tsightler** 2023-08-24 16:37 UTC
Labels: bug
