### ISSUE TITLE
No snapshot, no stream

### ISSUE THREAD

**Issue by rgerr** [dgreif/ring#119] opened 2019-08-31 10:20 UTC
Keep on getting the following error when the doorbell rings. I cannot get a live stream either. I have a Ring 1 (first model) doorbell, hardwired. With sufficient WiFi coverage. Live streams and snapshots via Ring app work flawless.

Aug 31 12:15:48 raspberrypi homebridge[534]: [8/31/2019, 12:15:48 PM] [Ring] Snapshot for Front Door Requested
Aug 31 12:15:48 raspberrypi homebridge[534]: [8/31/2019, 12:15:48 PM] [Ring] Snapshot for Front Door Requested
Aug 31 12:15:49 raspberrypi homebridge[534]: [8/31/2019, 12:15:49 PM] [Ring] Snapshot for Front Door Requested
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Snapshot failed to refresh after 60 attempts
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Snapshot failed to refresh after 60 attempts
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Snapshot failed to refresh after 60 attempts
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/14141470
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Failed to retrieve snapshot for Front Door (40.003s).  The camera currently reports that is it online
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Error: Not found with response: no snapshot
Aug 31 12:16:28 raspberrypi homebridge[534]:     at RingRestClient.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:218:27)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at Generator.throw (<anonymous>:null:null)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at rejected (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:5:65)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/14141470
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Failed to retrieve snapshot for Front Door (39.788s).  The camera currently reports that is it online
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Error: Not found with response: no snapshot
Aug 31 12:16:28 raspberrypi homebridge[534]:     at RingRestClient.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:218:27)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at Generator.throw (<anonymous>:null:null)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at rejected (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:5:65)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/14141470
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Failed to retrieve snapshot for Front Door (40.029s).  The camera currently reports that is it online
Aug 31 12:16:28 raspberrypi homebridge[534]: [8/31/2019, 12:16:28 PM] [Ring] Error: Not found with response: no snapshot
Aug 31 12:16:28 raspberrypi homebridge[534]:     at RingRestClient.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:218:27)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at Generator.throw (<anonymous>:null:null)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at rejected (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:5:65)
Aug 31 12:16:28 raspberrypi homebridge[534]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Aug 31 12:16:30 raspberrypi homebridge[534]: [8/31/2019,

**Comment by dgreif** [comment] 2019-09-02 21:07
There are limitations with the battery powered cameras with snapshots.  Please see https://github.com/dgreif/ring/wiki/Battery-Cam-Snapshots.  As for live streams, read through https://github.com/dgreif/ring/wiki/Camera-Troubleshooting

**Comment by paqpaqpaq** [comment] 2019-09-05 07:18
I have the exact same issue since a few days...
Worked great before

**Comment by dgreif** [comment] 2019-09-05 13:14
Try rebooting the camera.  Let me know if that helps

**Comment by dgreif** [comment] 2019-09-05 23:00
I confirmed with another user that rebooting the camera fixes the snapshot issues.  Closing this since it's not a plugin issue

**Closed by dgreif** 2019-09-05 23:00 UTC
