### ISSUE TITLE
Streaming doorbell camera kills homebridge

### ISSUE THREAD

**Issue by EdwardChamberlain** [dgreif/ring#948] opened 2022-05-23 19:06 UTC
# Bug Report

### Describe the Bug
Homebridge starts fine, logs in fine, finds cameras fine. trying to view cameras causes my whole home bridge install to die and restart. 

### To Reproduce
 - Start Homebridge
 - Attempt to stream camera
 - See error

### Expected behavior
A camera will stream

### Screenshots/Logs
log:
```
[5/23/2022, 7:57:30 PM] [Ring] Found the following locations:
[5/23/2022, 7:57:30 PM] [Ring]   locationId: <id here> - <name here>
[5/23/2022, 7:57:31 PM] [Ring] Configuring 1 cameras and 1 devices for location "<location name>" - locationId: <location ID>
[5/23/2022, 7:59:20 PM] [Ring] Preparing Live Stream for Front Door
[5/23/2022, 7:59:20 PM] [Ring] Stream Prepared for Front Door (0.652s)
[5/23/2022, 7:59:21 PM] [Ring] Activating stream for Front Door (1.012s)
[5/23/2022, 7:59:21 PM] [Ring] iceConnectionStateChange: completed
5/23/2022, 7:59:21 PM] Error: Cannot get schema for 'Array' target
    at AsnSchemaStorage.get (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/schema.js:18:19)
    at Function.toASN (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:21:48)
    at Function.toAsnItem (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:140:33)
    at Function.toASN (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:46:46)
    at Function.serialize (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:14:21)
    at Function.serialize (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/asn1-schema/build/cjs/convert.js:10:43)
    at Function.create (/homebridge/node_modules/homebridge-ring/node_modules/@peculiar/x509/build/x509.cjs.js:1740:43)
    at Function.CipherContext.createSelfSignedCertificateWithKey (/homebridge/node_modules/homebridge-ring/node_modules/dtls/src/context/cipher.ts:111:18)
    at RTCDtlsTransport.setupCertificate (/homebridge/node_modules/homebridge-ring/node_modules/werift/src/transport/dtls.ts:71:9)
    at ensureCert (/homebridge/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:1065:34)
[5/23/2022, 7:59:21 PM] Got SIGTERM, shutting down Homebridge...
[5/23/2022, 7:59:21 PM] [Ring] Stopped Live Stream for Front Door
[5/23/2022, 7:59:21 PM] [Ring] connectionStateChange: closed
[5/23/2022, 7:59:21 PM] [Ring] iceConnectionStateChange: closed
[5/23/2022, 7:59:26 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/23/2022, 7:59:31 PM] [HB Supervisor] Restarting Homebridge...
[5/23/2022, 7:59:31 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[5/23/2022, 7:59:36 PM] [HB Supervisor] Started Homebridge v1.4.1 with PID: 2248

```
### Additional context
Started since updating. 

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
    "refreshToken": "token",
    "platform": "Ring"
}

```

### Environment

 - OS: Ubuntu Focal Fossa (20.04.4 LTS) (docker)
 - Node.js: v16.15.0
 - NPM: 8.5.5
 - homebridge-ring: v11.0.2
 - homebridge: v1.4.1

**Comment by Cardo1** [comment] 2022-05-24 09:10
Was just about to post the same issue.  Snapshots load fine, however as soon as a stream is attempted Homebridge goes down in flames with the above error.

This is on a RPi with HB 1.4.1, Node 16.15.0 and any version of HB-Ring 11 and above.  Reverting to 10.x causes it to work as expected.

**Comment by dgreif** [comment] 2022-05-28 22:51
This is a duplicate of #945

**Closed by dgreif** 2022-05-28 22:51 UTC
Labels: bug
