### ISSUE TITLE
Ring allows MyQ Garage Openers to be added on their Platform- Could We Control It From there?

### ISSUE THREAD

**Issue by tempotandrum** [dgreif/ring#1356] opened 2023-11-07 14:49 UTC
### Description

Recently, MyQ announced the discontinuation of third-party support and selected a few partners to collaborate with, including Ring. As a result, users can now integrate MyQ with Ring, allowing them to open their garages through the Ring app. It might be worth considering whether the garage could appear as a switch accessory in the Ring app after a couple of tweaks to the current plugin (which is incredible BTW). It would be an incredible, secure , workaround! Please let me know your thoughts!

**Comment by dgreif** [comment] 2023-11-07 14:54
Duplicate of https://github.com/dgreif/ring/issues/1338. Please check for duplicates before opening.

**Closed by dgreif** 2023-11-07 14:54 UTC
Labels: enhancement
