### ISSUE TITLE
Motion notifications not working on Doorbell cams

### ISSUE THREAD

**Issue by b5rt** [dgreif/ring#184] opened 2019-11-20 01:45 UTC
I’ve had this plugin installed for a few days and couldn’t be happier. My cameras were one of the only things  in my house without HomeKit support, so a big thanks for all the effort in developing it. 

That said, I’m having a small issue. I currently have 4 cameras - a Doorbell Pro, Doorbell 2, Floodlight, and Stick-up wired. I can get video from all 4. Motion notifications work fine with the Floodlight, but not for either doorbell. However, the notification when someone presses the doorbell does work and comes through with the snapshot just like the floodlight. The only difference is it reports it as a ring instead of motion. The notifications from the Ring app are working fine, so it doesn’t seem to be an issue with the cameras. I haven’t had any motion events on the stick-up cam since I set it up, so I’m not sure how it works. I’ll test and report back. 

Does anyone have any suggestions on where to start? I’ve triple checked the settings in the Home app and everything looks correct.

**Comment by dgreif** [comment] 2019-11-20 01:56
@b5rt I appreciate the thorough report, and it lines up exactly with behavior that others have been seeing.  This is a dupe of #181

**Closed by dgreif** 2019-11-20 01:56 UTC
Labels: Ring, duplicate, wontfix

**Comment by b5rt** [comment] 2019-11-20 02:01
Doh! My search skills are subpar this evening it appears. I’ll go check out #181.
