### ISSUE TITLE
UNBRIDGED CAMERA DOES NOT WORK

### ISSUE THREAD

**Issue by zzack1** [dgreif/ring#1525] opened 2024-11-17 20:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I am running ring v13.1.0

I have installed the ring pluing and checked unbridged, camera does not show and apple home does not find under add accessory more options (it does show the ring bridge)

If I run it without doing the unbridged option then it works, however need to get this fix to work as unbridged

### To Reproduce

install ring v13.1.0
login to ring
enter validation code
enable unbridge cameras
restart bridge
wait until loaded back up
go into apple home 
click the top right corner + button
click add accessory
click more options in orange
only ring bridge appears not camera

### Expected behavior

expected to see the camera in the more options from above...
other plugins (like camera ffmpeg) shows unbridged cameras there

### Relevant log output

```shell
log shows:

errorError: Service name is already in use on the network at Registry._onProbeComplete
```

### Homebridge Ring Config

```shell
{
    "refreshToken": "removed",
    "unbridgeCameras": true
}
```

### OS

rasb

### Node.js Version

18.17.1

### NPM Version

13.1.0

### Homebridge/HOOBs Version

1.8.4

### Homebridge Ring Plugin Version

13.1.0

### Operating System

rasb

**Comment by zzack1** [comment] 2024-11-17 20:27
Configured camera removed doorbell_v3 Front Door

**Comment by tsightler** [comment] 2024-11-21 17:54
> errorError: Service name is already in use on the network at Registry._onProbeComplete

This error indicates that there is already a device/service on the network with the same name.  I've generally only seen this when there are two instances of Homebridge running on the same network with the same devices.  If the problem persist, I would suggest trying a different mDNS option in Homebridge settings or maybe check if your firewall is offering mDNS services as another common issue are settings that reflect mDNS to mulitple interfaces.

Overall however, this is not likely to be a plugin issue.

**Comment by zzack1** [comment] 2024-11-22 16:41
why does the log repeat 
[homebridge-ring] disconnecting 2181

**Comment by subman656** [comment] 2024-11-22 19:17
How do you add an unabridged camera after changing the setting to unabridged in the plugin?

**Comment by zzack1** [comment] 2024-11-22 19:19
Open the apple home app, click on the top right corner + , click add accessory, click more options... (its in orange), click on the device you want to add

**Comment by subman656** [comment] 2024-11-22 19:20
Thanks, I did. I then get asked for a code. This I don't have?

**Comment by zzack1** [comment] 2024-11-22 19:31
The default code is 031-45-154

**Comment by zzack1** [comment] 2024-11-22 19:32
@tsightler are you able to hop on a quick screen share with me? 

If so please let me know when your available...

**Comment by subman656** [comment] 2024-11-22 19:36
> The default code is 031-45-154

Thank you

**Comment by tsightler** [comment] 2024-11-23 14:49
The code is displayed in the Homebridge UI and in the logs during startup.  It will be different for each person so I'm not sure what the post about default code really means.

I appreciate the request to screen share, however, I'm not technical support to help with whatever problems you have.  So far, there's a failure to demonstrate the issue is even with the plugin.  If you believe this is a plugin issue, please provide detailed plugin logs, ideally with debug enabled, to support this.

Also, I did notice you are old a pretty old version of NodeJS, probably worth updating as current plugin versions are mostly tested with NodeJS 22.

**Comment by zzack1** [comment] 2024-11-23 17:53
Below is a copy of the logs, with the config debug turned on, please note that it was showing my ring user name/password/token/... so I put what it was and put removed+ next to it, please let me know if I missed a security in the config so I can remove it :-)

It wouldnt be a network issue as unbridged accessories from cameraffmpeg, samsung tizen,... they all work just not the ring plugin


10:29:13 AMRing BridgeinfoLoaded plugin 'homebridge-ring'
10:29:13 AMRing BridgeinfoLoading 1 platforms...
10:29:14 AMRing BridgeinfoBridge is running on port 51826.
10:29:17 AMRing BridgeRinginfoFound the following locations:
10:29:17 AMRing BridgeRinginfo locationId: removed+
10:29:18 AMRing BridgeRinginfoLocation Mode: {"mode":"disabled","lastUpdateTimeMS":1614010569640,"securityStatus":{},"readOnly":true,"notYetParticipatingInMode":[],"responseTimestamp":1732382958000}
10:29:18 AMRing BridgeRinginfoConfiguring 1 cameras and 1 devices for location removed+
10:29:18 AMRing BridgeRinginfoConfigured camera removed+ doorbell_v3 Front Door
10:29:19 AMRing BridgeinfoFront Door 9B32 is running on port 43691.
10:29:19 AMRing BridgeinfoConfiguration change
10:29:19 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:29:19 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:29:20 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:29:20 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:29:20 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:29:20 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:29:20 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:44:12 AMRing BridgeinfoLoaded plugin 'homebridge-ring'
10:44:12 AMRing BridgeinfoLoading 1 platforms...
10:44:13 AMRing BridgeinfoBridge is running on port 51826.
10:44:15 AMRing BridgeRinginfoFound the following locations:
10:44:15 AMRing BridgeRinginfo locationId: removed+
10:44:15 AMRing BridgeRinginfoLocation Mode: {"mode":"disabled","lastUpdateTimeMS":1614010569640,"securityStatus":{},"readOnly":true,"notYetParticipatingInMode":[],"responseTimestamp":1732383855000}
10:44:15 AMRing BridgeRinginfoConfiguring 1 cameras and 1 devices for location removed+
10:44:15 AMRing BridgeRinginfoConfigured camera removed+ doorbell_v3 Front Door
10:44:16 AMRing BridgeinfoFront Door 9B32 is running on port 35337.
10:44:16 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:44:16 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:44:16 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:44:16 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:44:16 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:44:16 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:44:16 AMRing BridgeRinginfoIgnoring push notification received in first two seconds after starting up
10:44:16 AMRing BridgeinfoConfiguration change
01:32:25 PMHubinfoRing Bridge starting
01:32:42 PMHubinfo[homebridge-ring] Child process 5448 started
01:32:46 PMHubinfoMessage received {"action":"ready","payload":{"server":true}}
01:33:00 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:00 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:00 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:00 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:01 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:01 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:01 PMHubinfo[homebridge-ring] request received [{"action":"request","path":"/send-code","body":{"email":"ringusernameremoved+,"password":"passwordremoved+"},"requestId":"idremoved+"}]
01:33:01 PMHubinfo[homebridge-ring] sending data to child...
01:33:03 PMHubinfoMessage received {"action":"response","payload":{"requestId":"idremoved+","success":false,"data":{"message":"Failed to fetch oauth token from Ring. Verify that your email and password are correct. (error: access_denied)","error":{}}}}
01:33:07 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:07 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:07 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:08 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:08 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:09 PMHubinfo[homebridge-ring] disconnecting 5448
01:33:39 PMHubinfo[homebridge-ring] Child process 5801 started
01:33:43 PMHubinfoMessage received {"action":"ready","payload":{"server":true}}
01:34:04 PMHubinfo[homebridge-ring] request received [{"action":"request","path":"/send-code","body":{"email":"ringusernameremoved+","password":"passowordremoved+"},"requestId":"removed+"}]
01:34:04 PMHubinfo[homebridge-ring] sending data to child...
01:34:06 PMHubinfoMessage received {"action":"response","payload":{"requestId":"idremoved+","success":true,"data":{"codePrompt":"Please enter the code sent to +1xxxxxxxx50 via sms"}}}
01:34:20 PMHubinfo[homebridge-ring] request received [{"action":"request","path":"/token","body":{"email":"ringusernameremoved+","password":"passwordremoved+","code":"coderemoved+"},"requestId":"idremoved+"}]
01:34:20 PMHubinfo[homebridge-ring] sending data to child...
01:34:21 PMHubinfoMessage received {"action":"response","payload":{"requestId":"idremoved+","success":true,"data":{"refreshToken":"rokenremoved+"}}}
01:34:38 PMHubinforingbridge stopping
01:34:38 PMHubinforingbridge stopping
01:34:43 PMHubinfoRing Bridge starting
01:43:01 PMHubinfo[homebridge-ring] Child process 6681 started
01:43:04 PMHubinfoMessage received {"action":"ready","payload":{"server":true}}
01:43:12 PMHubinforingbridge stopping
01:43:12 PMHubinforingbridge stopping
01:43:18 PMHubinfoRing Bridge starting
01:44:09 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
01:44:10 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
03:26:48 PMHubinfo[homebridge-ring] disconnecting 6681
10:22:19 AMHubinfo[homebridge-ring] disconnecting 6681
10:22:19 AMHubinfo[homebridge-ring] disconnecting 6681

**Comment by tsightler** [comment] 2024-11-23 18:07
Apologies, but is this with debug enabled on the plugin?  Also, can you please update your NodeJS version to the latest?

**Comment by zzack1** [comment] 2024-11-23 19:55
It is, below is my config:

{
    "refreshToken": "tokenremoved+",
    "unbridgeCameras": true,
    "debug": true
}

**Comment by zzack1** [comment] 2024-11-27 17:01
@tsightler can you help me with this please...
Unbridged accessories works accross other plugins like camera ffmpeg & samsung tizen, so its not a network issue or those would not work. Only on the ring plugin does the unbridged devices not work

**Comment by tsightler** [comment] 2024-11-27 17:10
@zzack1 I asked you to take mulitple actions, like upgrading NodeJS, and you haven't responded.  I don't know how to help you if you will not even respond to requests.  The logs you posted look largely normal, although there is lots of missing information and it doesn't look 100% like native Homebridge (are you using HOOBS by chance?).  I don't really understand how your logs can look so different.

Regardless, I would suggest updating to 13.2.0 and NodeJS 22 to continue testing.

**Comment by zzack1** [comment] 2024-11-27 19:37
@tsightler 
Hello,

I am running it on Hoobs, I would like to set up a remote session with you so we can go over this issue. 

Thank you

**Comment by zzack1** [comment] 2024-12-01 18:55
@tsightler 
I am also running ring 13.2.0

**Comment by zzack1** [comment] 2024-12-06 17:58
@tsightler 
Its been a while have you been able to work on this issue?

**Comment by tsightler** [comment] 2024-12-06 19:22
@zzack1 There is nothing to work on, you haven't provided anything that indicates there is a problem with the plugin.  As you are using HOOBS, you should contact HOOBS support for any issues as they are your first line of support.  I'm going to close this issue, but we can consider reopening it if you work with HOOBS support and can provide proper logs showing an actual issue.

**Closed by tsightler** 2024-12-06 19:22 UTC
Labels: bug

**Comment by zzack1** [comment] 2024-12-07 19:49
@tsightler
