### ISSUE TITLE
Homepod as Chime

### ISSUE THREAD

**Issue by crossic84** [dgreif/ring#1510] opened 2024-10-19 20:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Homepod usage as a chime doesnt work anymore. It used to ring together with a regular chime, now it doesnt even I have it turned on

### Expected behavior

I would expect Homepod to ring as a chime when someone rings the doorbell

### Homebridge Ring Config

```shell
{
    "refreshToken": "myrefreshtoken",
    "unbridgeCameras": true,
    "hideDoorbellSwitch": true,
    "hideAlarmSirenSwitch": true,
    "_bridge": {
        "username": "myusername",
        "port": 51977
    },
    "platform": "Ring"
}
```

### OS

macOS, Windows, etc...

### Node.js Version

v20.18.0

### NPM Version

10.8.2

### Homebridge/HOOBs Version

v1.8.4

### Homebridge Ring Plugin Version

v13.1.0

### Operating System

Debian GNU/Linux Bookworm (12)

**Comment by tsightler** [comment] 2024-10-20 16:58
Please verify if you have followed the [Notification Troubleshooting](https://github.com/dgreif/ring/wiki/Notification-Troubleshooting) steps from the wiki as this should fix the issue in almost all cases.

**Comment by crossic84** [comment] 2024-10-20 17:27
Yes I did, it didnt help unfortunately :( I am gonna to put Ring itself to factory default and try to start from scratch again

**Comment by tsightler** [comment] 2024-10-20 18:43
Please create a ding event and check the plugin logs to see if you see it there.  If the event shows in the logs, but not in Homekit, then the problem is outside of the plugin.

**Comment by tsightler** [comment] 2024-11-08 00:51
As there has been no feedback from my last message I am closing this issue, however, perhaps it is related to the same issues as https://github.com/dgreif/ring/issues/1511 so you can potentially follow there.

**Closed by tsightler** 2024-11-08 00:51 UTC
Labels: bug
