### ISSUE TITLE
Live View Problem (Repost?)

### ISSUE THREAD

**Issue by volcore79** [dgreif/ring#444] opened 2020-09-03 08:21 UTC
# Bug Report

### Describe the Bug
Using a Ring Doorbell Pro and a Ring Spotlight Cam. Brought both via your HOOBS plugin to HomeKit, both show a Preview Picture. Ring Doorbell allows a Live View. Spotlight Cam Picture shows "No Response" when I try to open Live View. After closing the Live View the Preview Picture also shows "No Response" and no picture anymore. 

### To Reproduce
 - Place Ring Spotlight Cam in iOS Home Application
 - Try to open Live View for Spotlight Cam
 - Error "No Response"

### Expected behavior
 Should open Live View like it does with Ring Doorbell Pro.

### Screenshots/Logs
 
Start:
![IMG_1991](https://user-images.githubusercontent.com/8375773/92089426-6f070b80-edce-11ea-90d4-f512222ea7b7.png)
Click on Terrasse for Live View:
![IMG_1992](https://user-images.githubusercontent.com/8375773/92089482-7e865480-edce-11ea-9c62-63aa774334f2.png)
Back to Startpage / Close Live View:
![IMG_1993](https://user-images.githubusercontent.com/8375773/92089502-8514cc00-edce-11ea-869a-6ba67f49e695.png)

```
3.9.2020, 10:02:13 [Ring] Preparing Live Stream for Terrasse
3.9.2020, 10:02:14 [Ring] Failed to parse SDP from Ring
3.9.2020, 10:02:14 [Ring] v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4 
s=Wantajobinstead?
c=IN IP4 34.247.24.72
t=0 0

m=audio 28428 RTP/SAVPF 0
a=rtpmap:0 PCMU/8000
a=rtcp:42359 IN IP4 34.247.24.72
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:r9Zj9UGLvGcdOJK70NorzzYVnF0LYOLuu0wY9AUy
a=ptime:20

m=video 47254 RTP/SAVPF 99
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42000a
a=rtcp:54732 IN IP4 34.247.24.72
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:/x3qxBKfRx9qZdeGBkWB8DiaUjXIesNYEbeo19rj
3.9.2020, 10:02:14 [Ring] Failed to prepare stream for Terrasse (0.791s)
3.9.2020, 10:02:14 [Ring] TypeError: Cannot read property 'match' of undefined
    at getRtpDescription (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:24:54)
    at parseRtpDescription (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:36:16)
    at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:204:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

### Additional context
 Doorbell works perfectly in the same environment. I already went through the trouble shooting document for cameras without success.

### Environment

 - OS: Raspberry Pi 2, Hoobs Image downloaded yesterday from official source
 - Node.js: v12.16.3
 - NPM: 6.14.4
 - ring-client-api: 9.9.0

**Comment by bjornand1** [comment] 2020-09-03 17:14
I have had my Ring doorbell working flawlessly with the Homebridge plugin for months, but after the last upgrade I also get the error message that the camera is not responding. Did something change that means I have to adapt some settings?

**Comment by dgreif** [comment] 2020-09-03 20:12
@volcore79  thanks for providing all the info when you opened this issue. It is indeed a duplicate of #438, but it's good to know that others are seeing the same issue. I'm going to close your issue, but if you could post on the other issue, which camera model is reported if you open the home app then go into the settings for the camera that isn't working? Any other differences you can think of between the two cameras? Is one of them older by a significant amount?

**Closed** 2020-09-03 20:12 UTC
Labels: bug, duplicate
