### ISSUE TITLE
Ring 2FA

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#39] opened 2019-06-23 10:44 UTC
Does this work if you have the ring 2fa turned on? I was using a different ring plugin until last week, I turned on Ring 2FA and then the plugin could not authenticate. Please can you advise if yours works with the Ring 2FA enabled before I install, thanks in advance...

**Comment by dgreif** [comment] 2019-06-23 14:17
See #26 for previous discussion.  It might be reasonably doable depending on how refresh tokens work.  I'll look into it when I have time, but can't make any promises on a timeline.  I think 2FA is great and would like to get it implemented at some point.

**Comment by dgreif** [comment] 2019-07-07 17:49
@adavison007 @d0n4v4nb3ck3r I have added 2fa support for the api and the homebridge plugin.  See  https://github.com/dgreif/ring/tree/master/homebridge#2-factor-authentication-2fa for setup instructions.  I plan to add another method to get a `refreshToken` at some point, but it should be functional the way I have it set up now.  Let me know how it works for you!

**Comment by adavison007** [comment] 2019-07-08 13:35
Thank you for this, I’m running hoobs, so I guess I should see the request if I open the terminal? Or in logs?

**Comment by BradMcGonigle** [comment] 2019-07-08 14:52
@adavison007 looking at the Hoobs logs won't work because your need to enter the two factor code that Ring sends via SMS when homebridge starts up to get the `refreshToken`.

I'm only vaguely familiar with hoobs but it probably starts homebridge on boot so there is not method for entering the two factor SMS code that Ring sends.  You'd have to start homebridge manually in console to get the prompt to enter it I believe.

**Comment by adavison007** [comment] 2019-07-08 15:22
> @adavison007 looking at the Hoobs logs won't work because your need to enter the two factor code that Ring sends via SMS when homebridge starts up to get the `refreshToken`.
> 
> I'm only vaguely familiar with hoobs but it probably starts homebridge on boot so there is not method for entering the two factor SMS code that Ring sends. You'd have to start homebridge manually in console to get the prompt to enter it I believe.

Bugger!!! Just tried this and nothing appears in logs or terminal in hoobs.... everything from ring stopped working, so had to turn off 2FA again... let me know if you find an alternative option? I've attached a screen shot of the hoobs start up config? 
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/47482260/60822022-9186a000-a19c-11e9-9c1c-98fc10136f9a.png">

**Comment by adavison007** [comment] 2019-07-08 15:23
@BradMcGonigle I can separately ssh into hoobs, if that helps?

**Comment by dgreif** [comment] 2019-07-08 15:26
Sorry for the bad user experience on this. I got the main functionality working, but it could definitely be easier to get the refresh token. I’m planning to publish a cli tool to make it simple in the next few days.  You would have to ssh in and run homebridge manually right now. The problem is that the prompt for the 2fa code can easily get lost in the rest of the homebridge output.

**Comment by adavison007** [comment] 2019-07-08 15:28
> Sorry for the bad user experience on this. I got the main functionality working, but it could definitely be easier to get the refresh token. I’m planning to publish a cli tool to make it simple in the next few days. You would have to ssh in and run homebridge manually right now. The problem is that the prompt for the 2fa code can easily get lost in the rest of the homebridge output.

@BradMcGonigle Cool, let me know when you want me to test the CLI option, really appreciate the support on this. Then we need live stream for the cameras 🥇

**Comment by BradMcGonigle** [comment] 2019-07-08 15:39
> Sorry for the bad user experience on this. I got the main functionality working, but it could definitely be easier to get the refresh token. I’m planning to publish a cli tool to make it simple in the next few days. You would have to ssh in and run homebridge manually right now. The problem is that the prompt for the 2fa code can easily get lost in the rest of the homebridge output.

@dgreif please....thank you so much for your work on everything here.  The community to is  lucky to have fantastic contributors like yourself.  I'm always impressed with the speed and quality of the updates/releases you've been putting out lately.

If you need help testing the cli tool, I'd be happy to help.

**Comment by d0n4v4nb3ck3r** [comment] 2019-07-08 17:33
@dgreif 2fa works awesome!!! Thanks so much for implementing this! I wasn’t expecting it this soon. You are quick.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by adavison007** [comment] 2019-07-13 09:23
@dgreif Any news on the CLI command for 2FA? Sorry to chase, keen to use, massive thanks in advance.

**Comment by dgreif** [comment] 2019-07-15 17:43
@adavison007 sorry for the lack of info.  I'm almost done with the CLI, just working on how exactly I want to deploy it for use.  I should have it released in the next couple days

**Comment by adavison007** [comment] 2019-07-16 09:39
> @adavison007 sorry for the lack of info. I'm almost done with the CLI, just working on how exactly I want to deploy it for use. I should have it released in the next couple days

@dgreif Many thanks, let me know and I'll test straight away.

**Comment by dgreif** [comment] 2019-07-16 23:55
@adavison007 sorry for the long wait, but the `ring-auth-cli` has landed in v`4.2.0`.  See https://github.com/dgreif/ring/wiki/Two-Factor-Auth for details on how to use it. Let me know how it works for you 😄

**Comment by BradMcGonigle** [comment] 2019-07-17 00:40
@dgreif worked great for me.  Awesome work!

**Comment by adavison007** [comment] 2019-07-17 07:57
> @adavison007 sorry for the long wait, but the `ring-auth-cli` has landed in v`4.2.0`. See https://github.com/dgreif/ring/wiki/Two-Factor-Auth for details on how to use it. Let me know how it works for you 😄

@dgreif Awesome!  I will try tonight when home, thanks in advance.

**Comment by d0n4v4nb3ck3r** [comment] 2019-07-17 11:05
@dgreif works awesome!!

**Comment by adavison007** [comment] 2019-07-17 20:14
@dgreif BOOM! You the man, works a dream (used CLI in hoobs web UI)

**Comment by dgreif** [comment] 2019-07-17 20:15
Thanks @adavison007 and everyone else for your patience and testing on this!

**Closed by dgreif** 2019-07-17 20:15 UTC
Labels: enhancement
