### ISSUE TITLE
Unable to upgrade homebridge-ring to version 8

### ISSUE THREAD

**Issue by Venger2005** [dgreif/ring#308] opened 2020-05-03 23:34 UTC
# Bug Report

### Describe the Bug
 I'm unable to successfully upgrade the Ring plug-in to the new version 8.0.0 which was released within the last couple of hours. I've tried completely removing and reinstalling the plugin, with no change in outcome. FYI - I had followed the instructions to remove the old cameras from my Home app following the upgrade.

### To Reproduce
Attempting to upgrade the plugin to version 8 via the Hoobs interface.

### Expected behavior
Plugin would successfully update and cameras would show in the Home app - if I understand it correctly, now as bridged accessories rather than previously needing to be added manually.

### Logs
[Ring] Configuring 4 cameras and 4 devices for location "Home" - locationId: XXXXXX-XXXX-X
5/3/2020, 11:59:17 PM [Ring] Adding new accessory lpd_v2 Front Door
5/3/2020, 11:59:17 PM [Ring] Error connecting to API
5/3/2020, 11:59:17 PM [Ring] TypeError: accessory.configureController is not a function
    at new Camera (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/camera.js:20:19)
    at /home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:188:123
    at Array.forEach (<anonymous>)
    at RingPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:167:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Homebridge Ring Config
"platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "XXXXXXXX",
            "hideLightGroups": true,
            "hideDoorbellSwitch": false,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": false,
            "debug": false

### Environment
 - OS: Raspbian GNU/Linux 10 (buster)
 - Node.js: 12.16.2
 - NPM: 6.14.4
 - homebridge-ring: 8.0.0
 - homebridge: Hoobs 3.2.3

**Comment by donavanbecker** [comment] 2020-05-03 23:37
You need to be running homebridge v1.0.0 and higher and currently are running hoobs... Install [Homebridge](https://github.com/homebridge/homebridge/wiki).

**Comment by Venger2005** [comment] 2020-05-03 23:41
According to a Hoobs developer, starting with Hoobs version 3.2.0 it supports plugins written for homebridge version 1.0.0

**Comment by Supereg** [comment] 2020-05-03 23:46
Hoobs does not ship homebridge v1.0.0. They frankensteined something together to mimic the changes done in homebridge 1.0.0

Seems like they forgot something.

**Comment by Supereg** [comment] 2020-05-03 23:47
afaik there is still 0.4.x code running with some "adjustments" trying to match 1.0.0 behavior.

**Comment by Supereg** [comment] 2020-05-04 00:19
Issue can be closed here

**Comment by dgreif** [comment] 2020-05-04 01:28
Duplicate of #307

**Closed by dgreif** 2020-05-04 01:28 UTC
Labels: bug

**Comment by BobbySlope** [comment] 2020-05-05 10:34
Heres how you can install the Ring Plugin on HOOBS
https://plugins.hoobs.org/plugin/homebridge-ring
is an Workaround while we preparing the Update, once the update is released we will certify the newer version and update the readme
