### ISSUE TITLE
Platform not working on MacOS background server

### ISSUE THREAD

**Issue by kahnartist81** [dgreif/ring#172] opened 2019-11-05 18:14 UTC
Hello again,
So far, I love everything about this plugin, but something is not jiving right with my setup. I'm running my home bridge as a LaunchAgent server, so I don't have to keep Terminal open and running all day. When I do this, all "homebridge-ring" items go offline/no response. But when I launch Homebridge in Terminal manually, everything pops back online. Any idea what's going on here?

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>Label</key>
    <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/homebridge</string>
        <string>-I</string>
    </array>
    <key>StandardOutPath</key>
            <string>/Users/erickahn/Library/Logs/Homebridge/out.log</string>
    <key>StandardErrorPath</key>
            <string>/Users/erickahn/Library/Logs/Homebridge/error.log</string>
    <key>EnvironmentVariables</key>
    <dict>
            <key>PATH</key>
            <string>/usr/local/bin/:$PATH</string>
    </dict>
</dict>
</plist>
`

**Comment by dgreif** [comment] 2019-11-05 18:17
Sounds like your homebridge service isn't set up properly.  There is tons of documentation in https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi about setting up homebridge as a service.  Closing as this is not related to the plugin.  Good luck!

**Closed by dgreif** 2019-11-05 18:17 UTC
Labels: setup-issue

**Comment by kahnartist81** [comment] 2019-11-05 18:53
Sorry, I should have been more clear. My homebridge has been working just fine for the past 2 years. It's just the Ring items that don't work while it's running in the BG. I just installed the ring portion yesterday, and noticed it was the only thing not working, while all other parts of the homebridge continued to work.

**Comment by dgreif** [comment] 2019-11-05 18:57
That definitely helps knowing that it was working before and that the Ring plugin is the only part not working.  Which devices do you have?  Cameras/lighting/alarm?  Is there anything in the homebridge logs that could be used to debug? Does it get to a point where it says `Configuring xx cameras and xx devices...`?

**Comment by kahnartist81** [comment] 2019-11-05 19:11
Thanks for helping. Like I said, I really do appreciate the work you put in to this plugin. So I am running 4 cameras and the alarm. I'm attaching the log here for you to check out, but from what you asked, it does look like the cameras are being configured before the activation code for homebridge is setup.
[homebridge log.txt](https://github.com/dgreif/ring/files/3810790/homebridge.log.txt)

**Comment by dgreif** [comment] 2019-11-05 19:21
Thanks for including the logs, they look about like I expected.  It never reaches the point where it has discovered all of your Ring devices and prints the log I mentioned before.  The most likely cause of this is a failed websocket connection.  Websockets are used to communicated with the Ring servers about the alarm system.  The background process you are using must be limited in some way that is preventing the websocket connection.  You may be able to get more information by running the process with `DEBUG=*` as environment variable, in which case socket.io will log a whole bunch of info.

**Comment by kahnartist81** [comment] 2019-11-05 19:35
Which item would I want to point to for the debug? The original homebridge folder, or just a general debug?

**Comment by dgreif** [comment] 2019-11-05 19:37
You just need to set that environment variable somewhere that it gets picked up by your background process

**Comment by kahnartist81** [comment] 2019-11-05 19:58
Sorry, I'm very green when it comes to this stuff. If it's not out there as a "put exactly this" kind of a thing, I'm no good. Ha. But I did find this in the error log when trying to run the background script.

> SyntaxError: Unexpected token / in JSON at position 2
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:208:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
[2019-11-5 11:56:00] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed
[2019-11-5 11:56:00] [Ring] Error connecting to API
[2019-11-5 11:56:00] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:85:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:89:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:88:16)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:113:33)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)<

**Comment by dgreif** [comment] 2019-11-05 20:02
Looks like your `refreshToken` isn't valid.  Try generating a new one and updating your homebridge config.  It's possible that your homebridge config file is invalid in general based on the first half of that log

**Comment by kahnartist81** [comment] 2019-11-05 20:16
Ok, so, I tried both methods of retrieving a refresh token, and I'm getting the same error in the log for both global and not global. The initial error from the homebridge module has gone away. It's now only the Ring token error.

> [2019-11-5 12:14:06] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed
[2019-11-5 12:14:06] [Ring] Error connecting to API
[2019-11-5 12:14:06] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:85:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:89:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:4:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:88:16)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:113:33)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)

**Comment by kahnartist81** [comment] 2019-11-05 20:24
And here's what I get when I run homebridge manually from terminal, and all connections works as they should.

> [2019-11-5 12:22:46] Homebridge is running on port 51829.
[2019-11-5 12:22:46] [Wink Hub] Refreshing devices...
[2019-11-5 12:22:48] [Ring] Creating location socket.io connection
[2019-11-5 12:22:49] [Ring] Ring connected to socket.io server
[2019-11-5 12:22:49] [Ring] Configuring 5 cameras and 17 devices for location "Goldsmith" - locationId: 9q56wg-bdcc-0
[2019-11-5 12:22:49] [Ring] Adding new accessory doorbell_v4 Front Door
[2019-11-5 12:22:49] [Ring] Adding new accessory doorbell_portal Garage (inside)
[2019-11-5 12:22:49] [Ring] Adding new accessory hp_cam_v1 Garage
[2019-11-5 12:22:49] [Ring] Adding new accessory stickup_cam_elite Family Room
[2019-11-5 12:22:49] [Ring] Adding new accessory stickup_cam_v4 Backyard
[2019-11-5 12:22:49] Front Door is running on port 51158.
[2019-11-5 12:22:49] Garage (inside) is running on port 51159.
[2019-11-5 12:22:49] Garage is running on port 51160.
[2019-11-5 12:22:49] Family Room is running on port 51161.
[2019-11-5 12:22:49] Backyard is running on port 51162.

**Comment by kahnartist81** [comment] 2019-11-05 20:33
I fixed it! They updated the plist file that's required for automatic startup on Mac. I redid my plist file and now it's 100% working as a background service. I really appreciate your help. And for anyone else who might have this issue, here's a link for recreating the launch plist.

https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS

**Comment by smockle** [comment] 2019-11-05 20:40
Glad you figured it out @kahnartist81!

If anyone else runs into this, I believe it was a duplicate of https://github.com/dgreif/ring/issues/144.

From the original post in this issue, your original launchctl property list set `PATH` to `/usr/local/bin/:$PATH`. `$PATH` cannot be referenced as a variable in a launchctl property list (its value is `""`). So, `/usr/sbin` (where `ioreg` is located) was not in your service’s `PATH`.

**Comment by dgreif** [comment] 2019-11-05 20:48
Glad you got it fixed up!  Thanks for making that connection @smockle 🏆
