### ISSUE TITLE
[Streaming]: Updated thumbnails "Error: Cannot get schema for 'EcDsaSignature' target"

### ISSUE THREAD

**Issue by NickRivait** [dgreif/ring#1175] opened 2023-02-28 14:11 UTC
### Streaming Issue

HomeKit updates Thumbnail photos, but won't live stream. 

Hoobs Info:
Version: 4.3.0
Node: 16.191
Homebridge: 1.6.0

Ring: 11.7.2

<img width="783" alt="Screenshot 2023-02-27 at 8 53 58 PM" src="https://user-images.githubusercontent.com/75817378/221877684-090cbf46-ea1a-42d9-9021-be2686978376.png">

"Error: Cannot get schema for 'EcDsaSignature' target"

Legacy mode was already enabled on Ring website during last error. 

### Proposed Solution

NA

### Environment

HOOBS

### What operating system are you on?

Other

### Relevant log output

```shell
2/28/2023, 9:10:40 AMRingRingPreparing Live Stream for Front Door
2/28/2023, 9:10:40 AMRingRingStream Prepared for Front Door (0.455s)
2/28/2023, 9:10:41 AMRingRingActivating stream for Front Door (0.665s)
2/28/2023, 9:10:41 AMRingRingiceConnectionStateChange: completed
2/28/2023, 9:10:41 AMRingRingERRORError: Cannot get schema for 'EcDsaSignature' target
2/28/2023, 9:10:41 AMRingRingconnectionStateChange: closed
2/28/2023, 9:10:41 AMRingRingiceConnectionStateChange: closed
2/28/2023, 9:10:41 AMRingRingERRORFailed to activate stream
2/28/2023, 9:10:41 AMRingRingERRORError: Cannot get schema for 'EcDsaSignature' target
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment] 2023-02-28 14:23
This is a duplicate of https://github.com/dgreif/ring/issues/1108

**Closed by dgreif** 2023-02-28 14:23 UTC
Labels: duplicate, live-streaming
