### ISSUE TITLE
Cannot reach Ring auth server

### ISSUE THREAD

**Issue by jdanthinne** [dgreif/ring#1495] opened 2024-09-20 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Ring cannot connect anymore to Ring server for a few days now… I've tried unlinking and re-linking account, but logs are still the same.

### Expected behavior

No error in the logs, and Ring connected to Hoobs

### Relevant log output

```shell
20/09/2024 15:05:29Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
```

### Homebridge Ring Config

```shell
{
    "platform": "Ring",
    "refreshToken": "[REDACTED]",
    "debug": false
}
```

### OS

Rasbian

### Node.js Version

16.20.2

### NPM Version

?

### Homebridge/HOOBs Version

4.3.1

### Homebridge Ring Plugin Version

13.1.0

### Operating System

Rasbian

**Comment by dgreif** [comment] 2024-09-20 14:57
Please search for existing issues before opening a new one. This is a duplicate of #1459

**Closed by dgreif** 2024-09-20 14:57 UTC
Labels: bug
