### ISSUE TITLE
ring-auth-cli returning "refreshToken": "undefined"

### ISSUE THREAD

**Issue by ashdwells** [dgreif/ring#393] opened 2020-07-05 15:52 UTC
Hi

My Homerbridge Ring stopped working so I attempted to get a new token using ring-auth-cli. 

I run the command, enter username and password correctly, I enter the code from the email and I only get this back:

"refreshToken": "undefined"

Tried today as well and the same, please advise.

**Comment by dgreif** [comment] 2020-07-05 16:04
Ring must have changed something on their end.  Similar issues in #391.  Will look into it when I have time.  PRs welcome if anyone else is able to track it down.

**Comment by dgreif** [comment] 2020-07-07 15:55
@ashdwells which version of `node` are you using?  I'm wondering if this resolves if you use `12.18.2`.

**Comment by ashdwells** [comment] 2020-07-07 16:23
Hi
Terminal says:node -v
v14.1.0

**Comment by dgreif** [comment] 2020-07-07 17:07
Yeah, definitely give `12.18.2` a try.  Also note that Ring is having some login issues at the moment so you may encounter a different error stating that your password is incorrect even if you enter the correct password.  https://status.ring.com/incidents/ps54tsbpw7ny

**Comment by dgreif** [comment] 2020-07-08 13:22
Confirmed with others that switching to 12.18.2 or 14.5.0 works just fine.  I'm closing this since it is a duplicate of #391, but let me know if you still run into issues after updating node.

**Closed by dgreif** 2020-07-08 13:22 UTC
Labels: duplicate, setup-issue

**Comment by ashdwells** [comment] 2020-07-08 14:35
Hi, I have installed 14.5.0 and can confirm it works, thanks
