### ISSUE TITLE
Ring Camera doesnt show video with new Ring Alarm Pro Edge enabled

### ISSUE THREAD

**Issue by mdiskin** [dgreif/ring#876] opened 2022-02-07 14:10 UTC
# Bug Report

### Describe the Bug
Recently added a Ring Alarm Pro with memory card for local video storage. The Ring Camera preview no longer shows the live video stream on my homekit enabled TV.

### To Reproduce
https://support.ring.com/hc/en-us/articles/360054769672-Store-and-process-videos-locally-with-Ring-Edge
Switch to Pro Alarm with edge.

### Expected behavior
Work the same as without edge and cloud video storage.

### Additional context
Am a developer and open to helping.

### Homebridge Ring Config
default

### Environment

 - Windows 10
 - Node.js: 16.13.2
 - NPM: 8.3.2
 - homebridge-ring: 9.24
 - homebridge: 1.4
 - hoobs: NA

**Comment by lynxbat** [comment] 2022-02-08 16:22
I am a new Ring Pro with Edge user and I am getting an error also through directly executing ring-api and in home bridge. Curious what error messges you are getting. This is mine:

```
Preparing Live Stream for Front Door
err:  Error: connect ECONNREFUSED 192.168.4.20:15064
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.4.20',
  port: 15064
}
[2/8/2022, 11:20:04 AM] [Ring] sip INVITE request failed with status 503
[2/8/2022, 11:20:04 AM] [Ring] Failed to prepare stream for Front Door (0.507s)
[2/8/2022, 11:20:04 AM] [Ring] Error: sip INVITE request failed with status 503
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/sip-call.js:147:28
    at next (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip.js:1153:13)
    at searching (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip.js:1159:20)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/sip.js:1144:32
    at Object.message (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip.js:943:13)
    at Object.signal (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip.js:824:63)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/sip.js:1142:28)
    at TLSSocket.emit (node:events:532:35)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
```

For me it looks like the SIP URL it is directing to (X.X.4.20) isn't right.

**Comment by lynxbat** [comment] 2022-02-08 16:26
I can confirm that flipping Edge back off for cameras (doorbell and stickup) removes this error and streaming resumes. I am new to this api, but it appears Ring Edge breaks the SIP flow for streaming.

**Comment by lynxbat** [comment] 2022-02-08 16:26
Happy to help troubleshoot and capture logs.

**Comment by mdiskin** [comment] 2022-02-08 17:46
`[2/8/2022, 12:43:35 PM] [myQ] Home Garage Door: Opening.
[2/8/2022, 12:43:43 PM] [myQ] Home Garage Door: Open.
[2/8/2022, 12:43:43 PM] [Ring] Driveway Detected Motion
[2/8/2022, 12:43:43 PM] [Ring] No snapshot cached for Driveway
[2/8/2022, 12:43:43 PM] [Ring] Loading new snapshot into cache for Driveway
[2/8/2022, 12:43:43 PM] [Ring] No snapshot cached for Driveway
[2/8/2022, 12:43:44 PM] [Ring] Preparing Live Stream for Driveway
[2/8/2022, 12:43:46 PM] [Ring] Snapshot cached for Driveway (2.29s)
err:  Error: connect ECONNREFUSED 192.168.4.20:15064
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.4.20',
  port: 15064
}
[2/8/2022, 12:43:51 PM] [Ring] sip INVITE request failed with status 503
[2/8/2022, 12:43:51 PM] [Ring] Failed to prepare stream for Driveway (7.8s)
[2/8/2022, 12:43:51 PM] [Ring] Error: sip INVITE request failed with status 503
    at C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-call.js:147:28
    at next (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:1153:13)
    at searching (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:1159:20)
    at C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:1144:32
    at Object.message (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:943:13)
    at Object.signal (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:824:63)
    at TLSSocket.<anonymous> (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:1142:28)
    at TLSSocket.emit (node:events:402:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[2/8/2022, 12:43:52 PM] [Ring] Preparing Live Stream for Driveway
err:  Error: connect ECONNREFUSED 192.168.4.20:15064
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.4.20',
  port: 15064
}
[2/8/2022, 12:43:59 PM] [Ring] sip INVITE request failed with status 503
[2/8/2022, 12:43:59 PM] [Ring] Failed to prepare stream for Driveway (6.711s)
[2/8/2022, 12:43:59 PM] [Ring] Error: sip INVITE request failed with status 503
    at C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip-call.js:147:28
    at next (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:1153:13)
    at searching (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:1159:20)
    at C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:1144:32
    at Object.message (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:943:13)
    at Object.signal (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:824:63)
    at TLSSocket.<anonymous> (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-ring\lib\api\sip.js:1142:28)
    at TLSSocket.emit (node:events:402:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[2/8/2022, 12:43:59 PM] [Ring] Used cached snapshot for Driveway
[2/8/2022, 12:43:59 PM] [Ring] Loading new snapshot into cache for Driveway
[2/8/2022, 12:44:02 PM] [Ring] Snapshot cached for Driveway (3.077s)`

Same for me

**Comment by lynxbat** [comment] 2022-02-08 19:40
Still new to this, but theorizing that the `"sip_server_ip"` which would normally point towards a Ring API edge is instead pointing towards an internal IP reserved on the Ring Pro/Eero network. Since we both have the *exact* same IP listed it makes me think it is reserved. Also because Eero hides subnet/network topology.

I wonder if the local Ring box never exposes this port to the internal network, meaning it will never work.

**Comment by lynxbat** [comment] 2022-02-08 19:54
nmap scan of mine:

```
Starting Nmap 7.92 ( https://nmap.org ) at 2022-02-08 14:46 EST
Nmap scan report for 192.168.4.20
Host is up (0.0030s latency).
Not shown: 65530 closed tcp ports (conn-refused)
PORT      STATE SERVICE
443/tcp   open  https
5355/tcp  open  llmnr
8557/tcp  open  unknown
8558/tcp  open  unknown
22443/tcp open  unknown
```

I noticed elsewhere on the web that `8557` has been used for Ring devices for LiveView.

**Comment by lynxbat** [comment] 2022-02-08 20:19
I dropped some debug statements and it looks like edge on or off changes the IP

Edge on:
`192.168.4.20` - does not work

Edge off:
`192.168.4.22` - does work

**Comment by dgreif** [comment] 2022-02-14 18:54
Hey there, this is actually a duplicate of #818.  Ring Edge does indeed break live streaming currently, and I've been working on a new streaming setup that should hopefully get it working again.  I still have some discovery work to do, but I think I should be able to get it working again down the road.  Closing this issue, but feel free to track progress on #818

**Closed by dgreif** 2022-02-14 18:54 UTC
Labels: bug
