### ISSUE TITLE
Cannot get schema for 'EcDsaSignature' target

### ISSUE THREAD

**Issue by BinDevID** [dgreif/ring#1215] opened 2023-05-13 09:54 UTC
# Bug Report

### Describe the Bug
 Wont load ring streams get error: Failed to activate stream BridgeRingERRORError: Cannot get schema for 'EcDsaSignature' target. Snapshop images come up in homebridge but stream fails when opening camera to view stream in homebridge.

### To Reproduce
 - Start Homebridge
 - Open HOME app
 - All ring cameras correctly show snapshop video.
 - Open chamera to view stream and fails.
 - Ring  log: BridgeRingERRORError: Cannot get schema for 'EcDsaSignature
### Expected behavior
 Camera should load and stream

### Screenshots/Logs
NA

### Additional context
 NA

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

        {
            "platform": "Ring",
            "refreshToken": "XXXXX",
            "hideDoorbellSwitch": true,
            "hideCameraLight": true,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "hideLightGroups": true
        }

```

### Environment

 - OS: Hoobs

**Comment by dgreif** [comment] 2023-05-13 14:13
This is a duplicate of https://github.com/dgreif/ring/issues/1108

**Closed by dgreif** 2023-05-13 14:13 UTC
Labels: bug
