### ISSUE TITLE
Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.

### ISSUE THREAD

**Issue by BastiT87** [dgreif/ring#1480] opened 2024-08-23 17:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

My protocol tells me this:
Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...

### Expected behavior

No devices are shown in HomeKit

### Relevant log output

```shell
Failed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
```

### Homebridge Ring Config

```shell
{
    "platform": "Ring",
    "refreshToken": "eyJhbGciOiJSUzI1NiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZDc0YjNhMWUiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE3MjQ0MzU0NzMsImlzcyI6IlJpbmdPYXV0aFNlcnZpY2UtcHJvZDp1cy1lYXN0LTE6ZTY5Y2RjOTMiLCJvaWF0IjoxNzI0NDM1NDczLCJyZWZyZXNoX2NpZCI6InJpbmdfb2ZmaWNpYWxfYW5kcm9pZCIsInJlZnJlc2hfc2NvcGVzIjpbImNsaWVudCJdLCJyZWZyZXNoX3VzZXJfaWQiOjg1OTIxOTA5LCJybmQiOiJJeUszNHYydlZBIiwic2Vzc2lvbl9pZCI6IjJlM2UxNDAyLTY5NmMtNDJhZi05NDE0LWZhMzUyZDAyZDkwMCIsInR5cGUiOiJyZWZyZXNoLXRva2VuIn0.nhCdn_ZW7VoKxfWm1zhAe_Lct-QFq0xqTMnjSYyhUQiOiuVrgrqroM9RV_zP-7b0fuO8Bd4jHSy0-RGfBm-oB6oY5kFmXlM-Dm3uAb1Z6T5Ghhpz0NEA9wB8jzpU5_I40rmpatnN9GHqY5BcJV1M2bSf0wGSxANrylxUPjyUFEs1Hy0f7O42JboacW8P0NV-1mBBGbdWt1iUyoF_bkhBn3pSd_v325QcoMqFaqSPbnrFh2Lj5eFnNvzk8nLieQkWYQUhiR0gmiNvxtK6dMtJKr0UU_lMVYtIWoQ8mpBwywA4alk5ubciGS4yMyVsgn0nCzhS-QEpiNM3Bq2OTYRZPw"
}
```

### OS

macOS

### Node.js Version

v14.17.6

### NPM Version

v7.22.0

### Homebridge/HOOBs Version

v.4.3.1

### Homebridge Ring Plugin Version

13.1.0

### Operating System

Raspbian

**Comment by tsightler** [comment] 2024-08-23 18:03
Please use search prior to posting new issues.  This is a duplicate issue already covered in a dozen places.  You must update HOOBS as it is outdated and the plugin requires at least NodeJS v18 or newer.  Please reach out to HOOBS support for any further issues.

Duplicate of:  https://github.com/dgreif/ring/issues/1459, https://github.com/dgreif/ring/issues/1463, https://github.com/dgreif/ring/issues/1469, https://github.com/dgreif/ring/issues/1475, https://github.com/dgreif/ring/discussions/1472.

**Closed by tsightler** 2024-08-23 18:03 UTC
Labels: bug
