### ISSUE TITLE
Allow Node JS 18

### ISSUE THREAD

**Issue by theimo1221** [dgreif/ring#1048] opened 2022-09-10 08:16 UTC
# Bug Report

### Describe the Bug
Installation on a server with Node JS 18 fails due to ` "engines": {"node": "^16"}`

### To Reproduce
 Attempt to install on a server with NodeJS 18

### Expected behavior
Allow the user to run install in NodeJS 18

### Additional context

https://github.com/iobroker-community-adapters/ioBroker.ring/issues/345

**Comment by tsightler** [comment] 2022-09-12 22:26
This is a duplicate of https://github.com/dgreif/ring/issues/1013 and I'm going to guess the answer will be the same.

**Comment by theimo1221** [comment] 2022-09-15 07:17
While I understand the "recommendation" of Node JS 16 due to the dependencies we experienced that the functionallity of this library used within ioBroker Ring isn't reduced by node JS 18.
So I'm asking for a reconsideration of `enforcing` node 16. Personally I'd appreciate if the decision would be with the user by e.g. clearly recommending node 16.

**Closed** 2022-10-02 15:55 UTC
Labels: bug

**Comment by dgreif** [comment] 2022-10-02 15:57
Node 18 is supported in the latest version
