### ISSUE TITLE
Doorbell not responding

### ISSUE THREAD

**Issue by Montevideo** [dgreif/ring#473] opened 2020-10-08 14:28 UTC
Other ring cameras are fine. Gets the thumbnail, but can't view live. This is the error. Ring plugin is up to date on HOOBS. Thanks for any help.

m=video 64830 RTP/SAVPF 99
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42000a
a=rtcp:32237 IN IP4 44.228.242.30
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:iAPejL77lkP/MPLovLn52cbjxPzSk96RRpcIAS/4
10/8/2020, 8:26:05 AM [Ring] Failed to prepare stream for Front Door (0.489s)
10/8/2020, 8:26:05 AM [Ring] TypeError: Cannot read property 'match' of undefined
    at getRtpDescription (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:24:54)
    at parseRtpDescription (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:36:16)
    at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:204:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by dgreif** [comment] 2020-10-08 16:50
Duplicate of #447

**Closed by dgreif** 2020-10-08 16:50 UTC
Labels: duplicate
