### ISSUE TITLE
Snapshots Not Working

### ISSUE THREAD

**Issue by ksuclark** [dgreif/ring#913] opened 2022-04-08 15:31 UTC
# Bug Report

### Describe the Bug
 In iOS 15.4.1 (and a couple releases prior) the snapshot views are not updating without forcing a livestream view first. It used to auto pull a snapshot whenever you scrolled to the camera without entering live view.

### To Reproduce
 - Open iOS Home app
 - Add a camera as a favorite
 - Force close iOS Home app
 - Open iOS Home app
 - Scroll down to the camera and notice snapshots don't refresh
 - Open live view for your camera and wait for it to load
 - Close live view
 - Notice snapshots for the camera (and sometimes other ring cameras) start to do their snapshot refreshes

### Expected behavior
 Snapshots automatically load and refresh every ~30s without having to enter live view

### Screenshots/Logs

![IMG_1476](https://user-images.githubusercontent.com/67332940/162474251-44103d78-ee21-4771-8f41-f6ed6b9d2e74.PNG)
![IMG_1477](https://user-images.githubusercontent.com/67332940/162474232-421abc3c-8e5c-48d7-bd1c-50f60b195b88.PNG)
![IMG_1478](https://user-images.githubusercontent.com/67332940/162474237-239fef9e-4e34-4a74-ae6b-71d4ceea862f.PNG)

### Additional context
 N/A

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
{
    "bridge": {
        "name": "Homebridge FFE4",
        "username": "x",
        "port": 51812,
        "pin": "x",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "deep-purple",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "refreshToken": "x",
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideCameraLight": true,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "hideDeviceIds": [
                "x1",
                "x2",
                "x3",
                "x4",
                "x5",
                "x6",
                "x7"
            ],
            "platform": "Ring"
        }
    ]
}
```

### Environment

 - OS: Raspbian GNU/Linux Bullseye (11)
 - Node.js: v16.14.2 
 - NPM: v8.5.0 
 - homebridge-ring: homebridge-ring v9.24.0
 - homebridge: v1.4.0
 - hoobs: N/A

**Comment by dgreif** [comment] 2022-04-10 20:16
This seems like a duplicate of #909.  HomeKit 15.4 changed the duration between snapshot requests.  If you feel this is not correct, please let me know.

**Closed by dgreif** 2022-04-10 20:16 UTC
Labels: HomeKit

**Comment by esteban-mallen** [comment] 2022-04-10 20:21
Thanks for the reply. I'm experiencing this issue too, but only on my Ring cameras in Homebridge, RTSP cameras in Scrypted work as expected... check the following screenshots:

**Comment by Hackashaq666** [comment] 2022-04-12 11:39
> This seems like a duplicate of #909. HomeKit 15.4 changed the duration between snapshot requests. If you feel this is not correct, please let me know.

It seems the lack of quick snapshot update could be for other reason than ios/homekit version. I say this because camera-ffmpeg plugin provides initial snapshot updates very quickly and then every 15 seconds for my 3 rtsp cameras. Only the ring camera does not update snapshot unless livestream is opened, and then every 60 seconds. Thanks!
