### ISSUE TITLE
Ring Access Controller

### ISSUE THREAD

**Issue by Malonee93** [dgreif/ring#1220] opened 2023-05-21 17:11 UTC
### Description

It would be great if you could add access to “Ring’s Access Controller” which would give me access to relays switches I have setup in the ring app.

**Comment by dgreif** [comment] 2023-05-21 23:03
This is a duplicate of #384. See https://github.com/dgreif/ring/issues/384#issuecomment-660169540 for a full description of why we are not implementing this feature.

**Closed by dgreif** 2023-05-21 23:03 UTC
Labels: enhancement
