### ISSUE TITLE
repeatedly getting [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  connect ECONNREFUSED 127.0.0.1:443.  Trying again in 5 seconds...

### ISSUE THREAD

**Issue by dps098** [dgreif/ring#750] opened 2021-08-30 20:19 UTC
# Bug Report

### Describe the Bug
About a month ago, I started getting HomeKit not being able to reach the Ring Pro video.  I had stayed on an older version of the plugin for a long time. I decided to upgrade to latest (and generated a new refresh token).

Every 5 seconds I get this:
8/30/2021, 1:09:21 PM [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  connect ECONNREFUSED 127.0.0.1:443.  Trying again in 5 seconds...

I saw a similar error, but not with trying to connect to 127.0.0.1:443.  I don't know why it's trying to do that.

### To Reproduce
Install homebridge-ring 9.21.0  via HOOBS.
Create refresh token and add to configuration.
Save to restart HOOBs/homebridge. Get repeated errors.  Persists after Pi reboot.

### Expected behavior
normal functionality without error.

### Additional context
I have removed and re-added plugin, I have tried earlier versions of plugin.  Each version has some other odd problem.  Ultimately it's not working anymore with this consistent reproducible error now.

### Homebridge Ring Config
```

        {
            "refreshToken": "myTokenHere",
            "sendCameraMotionNotificationsToTv": true,
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "platform": "Ring",
            "hideDeviceIds": [],
            "locationIds": [],
            "onlyDeviceTypes": []
        }


```

### Environment

 - OS: Raspbian
 - Node.js: v12.14.1
 - NPM: 6.13.4
 - homebridge-ring: 9.21.0
 - homebridge: ?
 - hoobs: 3.3.12

Any help would be appreciated so I can use Ring again with my iOS devices and AppleTV.

**Comment by mcohen20** [comment] 2021-08-30 20:44
This is happening on my machine. I did read this may be an issue with Ring's servers from a previous issue ( #744 )

**Comment by tsightler** [comment] 2021-08-30 21:20
My first thought when I see this is that there is some type of DNS issue as there's no way that oauth.ring.com should be resolving to localhost, and I have no idea how this plugin could be causing that.  Any chance you have a pi-hole or some other DNS blocking tool which is inadvertently blocking Ring servers from resolving as I know some of those systems return 127.0.0.1 as their "blocked" mechanism, although I think pi-hole uses 0.0.0.0.

**Comment by dps098** [comment] 2021-08-30 21:37
@tsightler it's a fairly vanilla HOOBs setup.  Has been working great for a long time until a month ago.  I also can ping oauth.ring.com no problem from the shell, and had no problem getting the refreshToken with the 2FA code on the same machine/shell.   I really don't understand why it's trying to use 127.0.0.1.  I looked at my hosts file and it's super vanilla I think.

```
hoobs@hoobs:~ $ cat /etc/hosts
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
127.0.1.1		hoobs homebridge
hoobs@hoobs:~ $ 
```

**Comment by tsightler** [comment] 2021-08-31 00:40
I think more interesting would be what's in /etc/resolv.conf, but admittedly I know basically nothing about HOOBS.  I'm assuming HOOBS itself runs in Docker?  So is the ping above from the actualy container where the homebridge instance/ring-homebridge addon is actually running?

The thing is I know exactly where that error message is in the code, and the code is super simple, just making a HTTPS request to the specified URL using the "got" library.  It makes me think it almost has to be some type of very strange DNS issue, perhaps related to the way Docker uses DNS, but I don't know what it would be.

It probably broke a month ago because Ring made changes to the API that broke all versions prior to that point, but that doesn't explain why it wouldn't work now with the current version.  Hopefully @dgreif will have more ideas because I'm at a total loss on this one and, at least so far, I've had no such reports from users of ring-mqtt, which uses the same ring-client-api from this package underneath.

**Comment by dps098** [comment] 2021-08-31 19:36
I'm using HOOBs (prepackaged home bridge out of the box) on a Raspberry Pi, no Docker image.
/etc/resolv.conf:
hoobs@hoobs:~ $ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 192.168.1.1
hoobs@hoobs:~ $

That's the address of my home router (Orbi brand) no particularly special security settings.   Like I said I can ping oauth.ring.com from the host, as well as do the refreshToken without a problem.

**Comment by tsightler** [comment] 2021-08-31 20:04
Very interesting issue.  I wonder if it could somehow be related to the fairly old version of node installed there as I know some users had issues with Node 12 on HOOBS in other cases, however, those were mostly around HTTP2 which isn't used in the current code as far as I know.

I did some digging and I see some very similar reports on the got Github page, even some having to do with oauth, like https://github.com/sindresorhus/got/issues/1572 but these seems to be caused by conflicts with upstream packages hooking the global http.request function.  Maybe some upstream package has brought in a dependency which has broken this?

However, I'm not seeing the issue at all so probably I'm not going to be much help.  It seems clear it's not really DNS.

**Comment by dps098** [comment] 2021-09-01 01:48
If you have a recommendation on what I need to do to upgrade Node, or any other suggestions I'm happy to try it.  Would like to get my Ring working again as it used to work really smoothly.

**Comment by tsightler** [comment] 2021-09-01 02:18
Out of curiosity, have you added any other addons to HOOBs recently, say, before this issue started?  I don't know anything about Homebridge/HOOBS itself, so I'm mostly just trying to help based on my knowledge of ring-client-api.  The failure is happening in a really simple part of the code that is used by every person using both this project and the ring-mqtt project, and any other project build using ring-client-api, so I feel like it has to be something at least somewhat unique to the specific environments.

If I'm not mistaken, Homebridge runs are plugins are part of the same NodeJS process (someone that knows more about Homebridge can tell me if this is wrong), and the issues on the got page with similar problems indicate that common modules like node-agent-base or https-proxy-agent that hook http.request cause this problem.  If this is correct then it's possible that another plugin could bring in a dependency that would manage to break homebridge-ring. so I'm wondering if you could share anything about the other plugins that your are using.

Based on what I can read it is possible to update node in HOOBS via:

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

But honestly, it's probably better to ask on a HOOBS site or ask someone who actually knows something about HOOBS, which isn't me unfortunately.

**Comment by dps098** [comment] 2021-09-07 06:27
I tried the wget.  It upgraded NPM from 12 to 14.  Issue is not resolved.

**Comment by dps098** [comment] 2021-09-07 06:38
After the wget this is the config:
Node.js: v14.17.0
NPM: 7.22.0
homebridge-ring: 9.21.1
hoobs: 3.3.12

No change in problem. I reported this too hoobs support.

**Comment by mkellsy** [comment] 2021-09-07 13:58
I have done some extensive testing on this. I did this test with both the HOOBS image and the Homebidge image, both have the same issues with this plugin. The good news is, I found that this doesn't affect the operation of the plugin.

From what I can tell this plugin fetches a new refresh token on a timer. I think this can be slowed down because I think a refresh token is good for 14 days. A better approach, is to read the JWT token and find out when it expires. Then fetch a new refresh token if it is close to expiration. The downside of this is, if the device if off when the token expires the user will need to login again.

Anyway, I tested my network first. I always look at the network first as it is the most likely candidate to fail first. My network is a Amplifi Alien WiFi 6 mesh connected to a gigabit fiber. I checked trace routes to oauth.ring.com and looked for latency in any step along the way. I also tested latency on a loaded network vs an idle network (streaming Netflix of not). I found out that my network is fine, no issues here.

I then moved to the device its self. To test this I ran this plugin on a Pi 4, Pi 3 and a Debian VM. I noticed that I was getting the same results on Pi 4 and Pi 3, but not the Debian VM. Remember that I tested this on both HOOBS and Homebridge. This led me to believe it is something in the image because the Debian VM was setup from scratch. Now realize HOOBS and Homebridge are related, even when it comes to the image. Both HOOBS and Homebridge use the same Pi-Gen tool to make the images. It makes sense the two would act the same.

I started to look into the drivers on Raspbian from the Pi-Gen tool. I started to notice that I was getting intermittent network "brown-outs" where the WiFi would not see the outside world, but would remain connected. So I looked into resolv.conf, network-manager, dhcpd and all the other systems that control the network on the Pi. Everything was default. HOOBS and Homebridge don't modify the network out side of using WiFi-Connect, and both images use the same exact tool for this.

The only thing left is the Broadcom firmware its self. I have been building a new HOOBS image based on Debian directly (not Raspbian) and a completly different build process using vmdb2. Broadcom support has been added to the Linux kernel, and the firmware package that Raspbian uses is no longer needed. This new image is not ready yet, but I will update you all as soon as I am able to test it on my setup.

**Comment by dgreif** [comment] 2021-09-08 03:10
Hey @mkellsy, thanks for looking into this issue!  It's been on my radar, but seemed non-specific to the plugin so I wasn't sure where to start.  Hopefully your research leads to a new image with a fix!

Regarding the refresh token, the plugin does look at the `expires_in` field when a new auth token is received - https://github.com/dgreif/ring/blob/master/api/rest-client.ts#L115-L121.  It also watches for requests that fail authentication - https://github.com/dgreif/ring/blob/master/api/rest-client.ts#L328-L331.  Both of these mechanisms have worked reliably, and I don't think they are related to the issue at hand.

Also big thank you to @tsightler for carrying this conversation along.  I appreciate your help, especially given this is not directly related to your library 😄

**Comment by dps098** [comment] 2021-09-09 06:16
An older version of the ring plugin had been working until about 4-5 weeks ago.  I had this issue previously on a newer ring version, but had downgraded back and avoided upgrading until it could not longer work.  Is the :443 any clue here? Is it supposed to be trying on localhost SSL port to connect?  Is it not listening?  I'm on a Raspberry Pi 3b.

**Comment by dps098** [comment] 2021-09-09 06:18
I don't know if it matters, but my device is using some random brand Edimax mini wifi dongle that's always worked with it.  You mentioned Broadcom, but I"m not sure why?  The Raspberry Pi 3b doesn't come with a wifi dongle, only ethernet.  Mine is connected by Wifi.  Just sharing the tidbits in case it helps.

**Comment by tsightler** [comment] 2021-09-09 12:52
I still suspect the problem is somewhere in the node stack, based on the fact that the got package has so many similar issues opened, and all of those centered around authentication, just like the message here, and they all seemed to be related to packages that patch the node stack http.request method.

I wish I had a spare RPi to test with, but I don't right now.

**Comment by sschwetz** [comment] 2021-09-10 13:38
I have noticed that you are using systemd-resolved to configure your resolv.conf

try the following 

**sudo systemctl disable systemd-resolved
sudo systemctl stop systemd-resolved**

this will stop your machine from overwriting the resolv.conf file when it renews its dhcp scope. Now use your fav text editor to edited /etc/resolv.conf

**sudo nano /etc/resolv.conf**

remove any lines starting with nameserver  and replace them with cloudflare's dns servers

**nameserver 1.1.1.1
nameserver 1.0.0.1**

then save the file. Your networking stack will now use those dns servers, there is no need to reboot.

In my experience the DNS caching resolvers on routers often is worst than terrible. This will allow you to bypass them. 

to revert changes if there are any issues

**systemctl enable systemd-resolved
systemctl start systemd-resolved**

**Comment by dps098** [comment] 2021-09-10 19:21
I followed directions above.  After restart it still restored the /etc/resolv.conf.  I saw a message fly by during startup that mentioned something about resolve.conf being restored from a backup if forced shutdown, something about PPP.

I tried it twice.  Aside from this I modified the resolv.conf per your directions and restarted HOOBS (homebridge).  No change.  I also tried to flush the DNS cache manually and restart HOOBS (homebridge), no change.

I'm not entirely clear why DNS resolution would be the culprit, because I have no trouble pinging oauth.ring.com, nor using the client refresh tool.  Awaiting your suggestions.

**Comment by mkellsy** [comment] 2021-09-10 21:27
Systemd resolv.conf simply gets the nameservers from your router. Disabling this could cause issues. A better solution would be, set the name servers on your router instead.

however I don’t think DNS is the issue. I think the issue is in the firmware, or heat. I think the reason why some are seeing a fix is they restart or bounce the networking in the Pi.

I have been running this plug-in on a Debian arm64 build, and I haven’t had a single dropout. This leads me to believe the issue is in the Raspberry Pi firmware or their modified kernel.

**Comment by dps098** [comment] 2021-12-10 12:16
Just updating that this still remains an issue.  I have been unable to use ring integration for quite a while now.  It did used to work in one of the earlier versions. At some point I had to upgrade because Ring APIs must have changed requiring a higher level.  Hoping you can still address it or help me understand what to do to move past this.

**Comment by vannman** [comment] 2021-12-26 12:20
I am having the same issue on Mac OS Catalina, so likely not OS dependent. 

In my case it works briefly after restarting homebridge, but then this error Is logged:

[Ring]  Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  connect ECONNREFUSED 127.0.0.1:443.  Trying again in 5 seconds...

Followed by similar errors every 5 seconds where it appears that api.ring.com is resolving to 127.0.0.1.

**Comment by vannman** [comment] 2021-12-26 13:09
Ok, I now better understand how to recreate the bug:

- After restarting homebridge I can switch state in Home using the Ring device in Home, without triggering the bug.
- I can also switch state using automation by creating a trigger to change state when another device, for example a light, turns on and off.
- However, when I let an automation turn on or off the other device so that the Ring's state will change using the trigger automation without me having to confirm it – it fails and the log registers the errors due to resolving errors.

So somehow changing the state by letting an automation change the state of a light that it turns triggers an automation that changes the state of Ring triggers the bug.

**Comment by vannman** [comment] 2021-12-26 13:16
Now I also tried adding the Ring device directly into an automation that is triggered when I leave the apartment and it causes the bug as well.

**Comment by dgreif** [comment] 2021-12-26 22:06
@vannman thanks for the additional information.  I'm struggling to see how the automation triggering source could possibly cause this issue as the endpoint you referenced (dings/active) is related to the cameras, not the Ring alarm, and should not be called in succession to setting the alarm state.  Are you able to re-check your steps to verify that's the scenario that causes it?  Or might it have just been a coincidence?

**Comment by vannman** [comment] 2021-12-27 15:11
@dgreif After recreating the bug multiple times I am confident that the triggering source is causing the issue. I have shared a link to a screen recording to you FB account where you can see it happen. Let me know if I can share more information with you!

**Comment by dgreif** [comment] 2021-12-28 03:34
@vannman was kind enough to go some additional debugging and narrowed it down to the homebridge-notification plugin causing http requests to start failing. I found https://github.com/sergeturgeon/homebridge-notification/issues/6, which seems to describe a similar issue for a different plugin. I'll dig into the source code when I get a chance, but wanted to check if others experiencing this issue are also using the notifications plugin. If so, does it go away if you disable the notifications plugin?

**Comment by tsightler** [comment] 2021-12-28 04:19
@dgreif This aligns with my [comment above](https://github.com/dgreif/ring/issues/750#issuecomment-909812694) that these problems were most likely caused by use of other addons using outdated dependecies which were patching the NodeJS https functions and thus breaking got.

Taking a quick glance at homebridge-notification, it looks like it hasn't been updated in ~5 years and depends on iftttmaker which itself depends on an ancient version of https-proxy-agent which is [known to cause this error with got](https://github.com/sindresorhus/got/issues/1572#issuecomment-752240712).

**Comment by vannman** [comment] 2021-12-28 12:50
I migrated from homebridge-notification and now everything works as expected https://github.com/ilcato/homebridge-ifttt. homebridge-ifttt offers more functionality than homebridge-notification so there are no drawbacks, only advantages.

**Comment by traviscollins** [comment] 2022-01-15 18:17
I had the same issue (oauth.ring.com resolving to 127.0.01 in error logs). I upgraded my other home bridge plugins one by one and found that after upgrading the homebridge-smartthings plugin, the homebridge-ring functionality started working.

**Comment by dgreif** [comment] 2022-01-23 15:29
At this point there seems to be solid evidence that this issue is caused by _other_ plugins.  Thanks for all the help and patience everyone!

**Closed by dgreif** 2022-01-23 15:29 UTC
Labels: bug
