### ISSUE TITLE
snapshot combination with ring mode 

### ISSUE THREAD

**Issue by rickb100** [dgreif/ring#311] opened 2020-05-04 10:31 UTC
# Bug Report

### Describe the Bug
When a Ring mode is selected where live view is blocked, the homebridge plugin tries to get a snapshot for ~60 second. During that time homebridge is not responsive (for switching other lights for example). 

### To Reproduce
 - Start Homebridge
 - Set ring mode to block live view of certain camera's
 - See error

### Expected behavior
Is it possible to disable snapshots such that the homebridge system remains responsive?

### Screenshots/Logs
[Ring] Failed to retrieve snapshot for Woonkamer (59.643s).  The camera currently reports that is it online
[5/4/2020, 12:20:05 PM] [Ring] Woonkamer camera appears to be unable to upload snapshots.  This usually requires a physical restart of the camera.  Please turn off power to this camera by removing its battery or turning off the breaker for the circuit it is wired to.  Once power is cycled, snapshots should start working again.
[5/4/2020, 12:20:05 PM] [Ring] Error: Not found with response: no snapshot

    at RingRestClient.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:237:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Raspbian
 - Node.js: 12.16.3
 - NPM: 6.14.4
 - homebridge-ring: 8.0.0

**Comment by DMBlakeley** [comment] 2020-05-04 11:45
Experiencing same issue. Tried clearing accessory cache as well as getting a new Ring token. Snapshots and live stream work for a time and then receive this error again. Ring camera working this morning without any changes or reboot.

**Comment by Rubenfer** [comment] 2020-05-04 13:37
Same here. This is a complete log:

```
[5/4/2020, 3:35:05 PM] [Ring] Snapshot failed to refresh after 60 attempts
[5/4/2020, 3:35:06 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/xxxxxxxx
[5/4/2020, 3:35:06 PM] [Ring] Failed to retrieve snapshot for xxxxx (55.506s).  The camera currently reports that is it online
[5/4/2020, 3:35:06 PM] [Ring] xxxxx camera appears to be unable to upload snapshots.  This usually requires a physical restart of the camera.  Please turn off power to this camera by removing its battery or turning off the breaker for the circuit it is wired to.  Once power is cycled, snapshots should start working again.
[5/4/2020, 3:35:06 PM] [Ring] Error: Not found with response: no snapshot
    at RingRestClient.<anonymous> (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:237:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/homebridge-ring/lib/api/rest-client.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by dgreif** [comment] 2020-05-04 14:04
This is definitely an issue and I am looking into it.  There are two parts to this problem:

1. Modes will block requests for snapshots if live streaming is blocked.  There is no apparent error indicating this situation, so I'll have to dive more into Modes and determine when a specific camera has live viewing blocked

2. Now that cameras are bridged instead of external accessories, they are behaving a little different.  The main difference being that they appear to block the whole bridge while waiting for callbacks.  I've reached out to the homebridge collaborators to see what the best fix for this is

**Comment by rickb100** [comment] 2020-05-04 14:20
Thanks for the quick response! Looking forward to a solution. 
In the mean time, is it possible to disable snapshots or remove the camera image from apple home while it still receives motion notifications?

**Comment by DMBlakeley** [comment] 2020-05-04 14:26
Thanks also for looking into this issue!

**Comment by Rubenfer** [comment] 2020-05-04 14:44
@dgreif 
> Modes will block requests for snapshots if live streaming is blocked

Not just if live streaming is blocked. Also if motion detection is disabled and live streaming enabled. I noticed that you can check for `motion_detection_enabled` and if that is set to false the screenshots are disabled.

**Comment by ronzelver** [comment] 2020-05-07 18:12
I can confirm this, when Motion Detection is disabled (typically in At Home mode), then the camera feed stops, this is also visible in the Ring App. This happens regardless of the Live View setting.

**Comment by Rubenfer** [comment] 2020-05-09 09:33
@dgreif Any plan to release an update soon? Maybe only need to check motion_detection_enabled, and if false doesn't require the snapshot. Now homebridge is unresponsive sometimes and that's annoying.

**Comment by dgreif** [comment] 2020-05-09 22:14
@Rubenfer thanks for the info.  I just did a bunch of testing and can confirm that `motion_detection_enabled` is the right field to check to determine if the camera is able to take snapshots.  I need to make some additional changes, but hope to get an update for this out tomorrow

**Comment by dgreif** [comment] 2020-05-11 15:59
I've release some significant changes for snapshots in v`8.1.0` in an effort to handle some recent issues:

1. Modes settings can now easily disable motion detection, which prevents new snapshots from being captured
2. If snapshots are fetched in the `handleSnapshotRequest` method, HomeKit will _block_ the entire bridge until the snapshot response is sent.  This is a limitation of HomeKit, not homebridge.  This has always been the case, but wasn't as big of a deal when cameras were external accessories because only that one accessory was blocked while waiting for a snapshot.  Now that cameras are bridged, waiting for a snapshot means that your entire homebridge instance is blocked.  This, in combination with the modes issue, meant some users homebridge instances were virtually unusable from the Home app because snapshots were always blocking.
3. Most users will still want accurate snapshots from their cameras when motion/dings are detected.  This means we can't send the motion event until the snapshot is already downloaded and cached so that we can immediately respond when `handleSnapshotRequest` is triggered by the motion event

So here's how I'm handling these things
1.  I now check if `camera.settings.motion_detection_enabled === false` when refreshing snapshots.  This gives us an indication that Modes is blocking snapshots and we shouldn't keep trying to get a new one.  (Thanks for the suggestion on this one @Rubenfer)
2. `handleSnapshotRequest` will now return _immediately_ with the last cached snapshot, no matter what.  If there is no snapshot cached yet, it returns nothing.  It also causes a new snapshot to be fetched after releasing HomeKit, so that the next call (which is 10 seconds later if you keep the Home app open on the same network as your home hub) will have a new up-to-date snapshot
3. Motion and Ding events will now be delayed before they are passed to HomeKit.  When motion is detected, it will first fetch an updated snapshot, and _then_ pass the motion update to HomeKit.  HomeKit will then immediately call `handleSnapshotRequest` which can return the image that was just cached.  This does mean that motion/ding events will be delayed before showing notifications on your apple devices, but HomeKit was already doing that delay while it waited ~10 seconds for the snapshot to be returned before.  These events are _not delayed_ for battery powered devices as they will not return a snapshot while recording a motion/ding event.

My hope is that these changes will lead to an overall better experience for users, and prevent any issues where Ring causes your entire bridge to get blocked.  If you have any questions or feedback feel free to post them here

**Closed by dgreif** 2020-05-11 15:59 UTC
Labels: bug

**Comment by rickb100** [comment] 2020-05-11 16:14
Thanks for the update and the clear explanation!

**Comment by DMBlakeley** [comment] 2020-05-14 00:02
I am getting the following errors with Motion Notifications enabled for the Ring Doorbell in HomeKit. Should this be expected with the latest changes?

```
[5/13/2020, 7:10:15 PM] [Ring] Front Door Detected Motion
[5/13/2020, 7:10:44 PM] [Ring] Snapshot failed to refresh after 40 attempts
[5/13/2020, 7:10:44 PM] [Ring] Snapshot failed to refresh after 40 attempts
[5/13/2020, 7:10:44 PM] [Ring] Snapshot failed to refresh after 40 attempts
[5/13/2020, 7:10:44 PM] [Ring] Snapshot failed to refresh after 40 attempts
[5/13/2020, 7:10:45 PM] [Ring] 404 from endpoint https://api.ring.com/clients_api/snapshots/image/439xxxx
[5/13/2020, 7:10:45 PM] [Ring] Failed to cache snapshot for Front Door (29.211s), The camera currently reports that is it online
[5/13/2020, 7:10:45 PM] [Ring] Front Door camera appears to be unable to upload snapshots.  This can happen when your Ring Modes settings prevent motion detection or live view, which also prevents snapshots.  If Modes are not blocking snapshots, this can also happen if the camera has gotten into a bad state, which requires a physical restart of the camera.  If this happens, you will also not be able to retrieve snapshots via the Ring app for this camera.  In that case, please turn off power to this camera by removing its battery or turning off the breaker for the circuit it is wired to.  Once power is cycled, snapshots should start working again.

```
