### ISSUE TITLE
iOS 13 Beta Issue Log

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring#68] opened 2019-07-16 04:06 UTC
Figured if anyone is having issues in iOS 13 beta we could log them all in the same issue till iOS 13 comes out.

**Comment by d0n4v4nb3ck3r** [comment] 2019-07-16 04:15
So as you can tell I have iOS 13 beta installed on my phone.
   The image that has the snapshot for the Entryway Front Door is my wife's phone (iOS 12)
   
![IMG_AB111F22F4F2-1](https://user-images.githubusercontent.com/9875439/61265172-d4281980-a754-11e9-9262-e407cc6d991f.JPG)

The image without the snapshot and just motion at front door ring app notification is my phone (iOS 13), the snapshot is working for my Ring Floodlight Cam on iOS 13 but not the Ring Pro.

![IMG_0458](https://user-images.githubusercontent.com/9875439/61265171-d4281980-a754-11e9-89ef-29cc9ffbcc6d.PNG)

**Comment by krazyflipj** [comment] 2019-07-16 04:58
Motion notifications do not work on ring doorbell.

**Comment by itsgabraf** [comment] 2019-07-16 09:20
Happening for me too. Was working till I removed it (screwed up switching to V4) and added it back in.

**Comment by d0n4v4nb3ck3r** [comment] 2019-07-16 11:53
>Happening for me too. Was working till I removed it (screwed up switching to V4) and added it back in. 

@itsgabraf @krazyflipj I thought I was having these issues too, but that’s all iOS 13 not this plugin. I changed those settings on my Mac, and it started working on my iPhone.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by itsgabraf** [comment] 2019-07-16 12:00
What do you mean “changed those settings on my Mac”? 

I tried the following:

Removed plugin. Reinstalled plugin. Added camera back to HomeKit (on iOS 13 device)

Removed plugin. Reinstalled plugin. Added camera back to HomeKit (on iOS 12 device)

Reformatted Raspberry Pi SD card into a brand new system. Started from scratch. Added plugin/homebridge etc. Added camera again.

Basically all gave me a result of no motion notifications. I just figured it was iOS fault and the next beta update will fix it.

**Comment by d0n4v4nb3ck3r** [comment] 2019-07-16 12:26
>What do you mean “changed those settings on my Mac”?  ...

@itsgabraf it is iOS 13s fault. I changed the settings on the Home App on my Mac, to have snapshots and motion notifications and it is all working now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by itsgabraf** [comment] 2019-07-16 23:43
Yea, mine just magically fixed itself this morning. Didn’t change a thing. Must have been on the Apple side. Still don’t have it appear under “sensors” though but I assume that because under “cameras” that it asks for snapshots, that they’ve just grouped the settings all under the camera.

**Comment by krazyflipj** [comment] 2019-07-17 04:48
Interesting mine still doesn’t work.

**Comment by itsgabraf** [comment] 2019-07-19 11:08
Has anyone else’s “allow snapshots” disappeared from their Camera settings?

**Comment by krazyflipj** [comment] 2019-07-23 13:48
> Has anyone else’s “allow snapshots” disappeared from their Camera settings?

Yeah mine disappeared as well.

**Comment by EarthRise626** [comment] 2019-07-24 11:53
I am on iOS 13 and experiencing this issue as well. Motion alerts work perfectly for my Floodlight Cam but not the doorbells.

**Comment by d0n4v4nb3ck3r** [comment] 2019-07-24 15:37
> I am on iOS 13 and experiencing this issue as well. Motion alerts work perfectly for my Floodlight Cam but not the doorbells. 

Have you guys tried turning notifications off and then back on for each camera?

My Ring Pro and Floodlight both work awesome!!

**Comment by jahnkenneth** [comment] 2019-07-24 19:42
Not working for me.
«Allow snapshots» is not showing...

**Comment by dgreif** [comment] 2019-07-24 21:09
https://homekitnews.com/2019/07/03/changes-and-additions-to-the-home-app-in-ios13-beta-1/

> currently, in iOS12, you get a snapshot from the camera with a notification. Now in iOS13, you get a notification AND a live stream from the camera – even on the lock screen

Looks like they are moving to live stream _instead_ of snapshots 😮.  Still working on live streaming but getting _close_.  I just updated to iOS 13 beta so I will check it out too.

**Comment by dgreif** [comment] 2019-07-24 21:13
Just tried motion and ding on my Ring Pro, and motion on my Floodlight cam (same setup as @d0n4v4nb3ck3r).  Everything worked perfectly, including the snapshots in the notifications.  I'd suggest trying his approach of turning notifications off and back on for each camera..

**Comment by krazyflipj** [comment] 2019-07-24 21:39
Sometimes I get motion notifications and sometimes I don’t. As mentioned snapshots aren’t showing and the option is missing. I have a Ring 2

**Comment by EarthRise626** [comment] 2019-07-24 23:01
Odd! I’ve captured my current settings here:

https://imgur.com/a/wD0Gkhg

I turned the notifications off and back on again in both areas of the Home app. 

One thing of note is that these are both battery powered Doorbells, but I wouldn’t think that would be of consequence for the motion alerts!

Interesting to see the change from snapshots to streams. You deserve much praise if your are able to pull the SIP functionality off!

**Comment by dgreif** [comment] 2019-07-24 23:08
@EarthRise626 @krazyflipj it's interesting that you both are having issues with battery cameras.  I think I broke the timing for slow snapshots when i messed with it last week.  If it has been longer than 10 minutes since the last snapshot, it will now wait 30 seconds for a new one to come in.  I made the assumption that the new one would come in just as fast as wired cameras, but that could be entirely wrong.  The previous logic would only wait 5 seconds for a new snapshot on battery cameras, regardless of when the last snapshot was.  I think what it happening is HomeKit is requesting a snapshot and waiting around for it to come in before showing the notification.  On iOS 12 it would wait for ~15 seconds and then show the notification without a snapshot if it hadn't received one yet.  iOS 13 must be waiting longer, and for some reason not even showing the notification if it waits too long 😞.  I'll circle back to snapshots once I get live streams working. I'm at that critical "90%" mark where I feel like I have everything in place, but it's going to take me forever to get it to function correctly.  Haven't had a successful stream into HomeKit yet, but I have SIP communication in place and am receiving audio RTP packets.  For some reason it's not giving me video RTP which is what I'm trying to figure out right now.  Wish me luck 🤞

**Comment by EarthRise626** [comment] 2019-07-25 00:22
Your description of the issue makes a lot of sense. I’m guessing with the improvements to camera feeds they have implemented in iOS 13, they may have changed a lot under the hood to prefer constant, live feeds rather than snapshots.

I’m still very much an amateur when it comes to scripting, but do work with API’s enough to ride along!

**Comment by jahnkenneth** [comment] 2019-07-25 00:24
Mine is a Ring Pro, not battery powered...

**Comment by dgreif** [comment] 2019-07-28 19:53
I upgraded to iOS 13 beta last week so I could join you all in the fun.  I noticed right away that I was having a lot of trouble with snapshots even on wired cameras (only receiving snapshots ~10% of the time).  I found [this tread on reddit](https://www.reddit.com/r/homebridge/comments/c8gcg7/homebridge_camera_event_snapshots_on_ios13_beta/) which confirmed others are having issues, mainly with the ffmpeg plugin.  The last comment recommended upgrading your Apple TV to the beta version, which fixed the problem for me 🎉

**Comment by tronny87** [comment] 2019-07-29 06:26
Ring Pro working flawlessly food doorbell alerts and live streaming, but I have not been able to receive any notifications for motion alerts. If I look at the motion sensor accessory, I can see it being triggered, but there is no option anywhere to manage notifications for it. 

Hopefully an iOS 13 bug, that might be resolved with this week’s beta 5.

**Comment by krazyflipj** [comment] 2019-07-30 16:34
Updated iOS 13 to latest beta that was released yesterday. Still not getting motion alerts. Live streaming works fine

**Comment by jamesg311** [comment] 2019-07-30 16:46
Same here, though it’s not 100% either way. Sometimes they appear sometimes they don’t.

**Comment by dgreif** [comment] 2019-07-30 17:12
Mine appear to be working on Beta 5, but I did notice it has trouble saving the notification settings.  For example if I go into the camera and change the "People" option, then back out and go back into the settings, it does not save the changes that I just made.  Definitely some bugs to be worked out still, this is why they do betas :joy:

**Comment by tronny87** [comment] 2019-07-31 17:44
Motion notifications now work on iOS 13 beta 5. My one issue is that the motion snapshots are very small in the initial notification on the lock screen, and 3D touch/tapping the notification just brings up the live stream. Would be nice to see each respective snapshot, as it was in iOS 12!

**Comment by krazyflipj** [comment] 2019-07-31 17:46
@tronny87 weird mine still doesn’t work. I’ll try re-adding camera again

**Comment by krazyflipj** [comment] 2019-08-09 14:01
Beta 6 and I still don’t get motion notifications. Option to turn it on is still missing.

**Comment by tronny87** [comment] 2019-08-09 15:16
Motion notifications work when they want to. They come and they go. They weren't working when I first set up this plug-in, then they started working out of nowhere 3 days later, then they stopped for 2 days, and recently started up again. 

As dgreif has mentioned to myself and others many times, this is a HomeKit problem and we will have to hope Apple gets things stabilized before the final release of iOS 13.

**Comment by paqpaqpaq** [comment] 2019-08-10 08:19
> Motion notifications work when they want to. They come and they go. They weren't working when I first set up this plug-in, then they started working out of nowhere 3 days later, then they stopped for 2 days, and recently started up again.
> 
> As dgreif has mentioned to myself and others many times, this is a HomeKit problem and we will have to hope Apple gets things stabilized before the final release of iOS 13.

Yes, but I found that the motionsensor only trips when the ring button is pressed on the doorbell itself. Jumping up and down in front of the cam won't.

**Comment by krazyflipj** [comment] 2019-08-29 13:46
On Ring 2 live feed is hit or miss  sometimes it works and sometimes I get no response

**Comment by dgreif** [comment] 2019-08-29 14:37
@krazyflipj anything odd in your logs when it fails? like 480 sip response?

**Comment by krazyflipj** [comment] 2019-08-29 16:06
> @krazyflipj anything odd in your logs when it fails? like 480 sip response?

Nothing odd. See below. 
![F256915E-9F55-4FAC-AC12-31AA2A72B8E0](https://user-images.githubusercontent.com/10282165/63956938-4f5f3980-ca3c-11e9-92ff-60d570e02a92.jpeg)

**Comment by dgreif** [comment] 2019-08-29 16:55
@krazyflipj looks like your network isn't letting the packets in for some reason.  It's odd that it works sometimes, but there isn't anything else I know of to make it work better, sorry!

**Comment by krazyflipj** [comment] 2019-08-29 17:00
> @krazyflipj looks like your network isn't letting the packets in for some reason. It's odd that it works sometimes, but there isn't anything else I know of to make it work better, sorry!

It never works when I first try to load it but it works the second time. Really strange

**Comment by krazyflipj** [comment] 2019-09-01 01:02
It might be my VPN that’s causing the issue.

**Comment by d0n4v4nb3ck3r** [comment] 2019-09-19 00:42
iOS 13 tomorrow!!

**Comment by dgreif** [comment] 2019-09-19 19:33
Thanks for all the feedback everyone!  With iOS 13 out, I think it's a good time to close this one out.

**Closed by dgreif** 2019-09-19 19:33 UTC
Labels: HomeKit, discussion
