### ISSUE TITLE
12 Beta .1 - Breaks streaming

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#1292] opened 2023-08-15 16:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When trying to stream video in homekit it fails, snapshots work (worked fine in beta0)

### To Reproduce

Stremaing any ring cameras causes the issue

### Expected behavior

Video should work

### Relevant log output

```shell
[15/08/2023, 17:38:35] [homebridge-ring] Preparing Live Stream for Gate Camera
[15/08/2023, 17:38:35] [homebridge-ring] Stream Prepared for Gate Camera (0.556s)
[15/08/2023, 17:38:35] [homebridge-ring] Activating stream for Gate Camera (0.761s)
[15/08/2023, 17:38:36] [homebridge-ring] RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Function.padStart (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:972:13)
    at Function.encodeSignature (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:940:22)
    at Function.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/webcrypto/build/webcrypto.js:1575:54)
    at EcdsaProvider.onSign (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/webcrypto/build/webcrypto.js:1737:25)
    at EcdsaProvider.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:157:28)
    at SubtleCrypto.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:1405:39)
    at Function.create (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/x509/build/x509.cjs.js:2407:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.value [as createSelfSignedCertificateWithKey] (/usr/local/lib/node_modules/homebridge-ring/node_modules/dtls/src/context/cipher.ts:108:18)
[15/08/2023, 17:38:36] [homebridge-ring] connectionStateChange: closed
[15/08/2023, 17:38:36] [homebridge-ring] iceConnectionStateChange: closed
[15/08/2023, 17:38:45] [homebridge-ring] This plugin slows down Homebridge. The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Gate Camera 4315' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[15/08/2023, 17:38:45] [homebridge-ring] Stopped Live Stream for Gate Camera
```

### Homebridge Ring Config

```shell
.
```

### Additional context

.

### OS

RPI

### Node.js Version

Latest

### NPM Version

Latest

### Homebridge/HOOBs Version

Latest Homebridge

### Homebridge Ring Plugin Version

latest

### Operating System

Raspian

**Comment by dgreif** [comment] 2023-08-15 16:49
This is a duplicate of #1286

**Closed by dgreif** 2023-08-15 16:49 UTC
Labels: bug
