### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by Lui5Jacint0** [dgreif/ring#427] opened 2020-08-13 16:47 UTC
I have a Ring VideoDoorbell 2 hardwired, set the plugin to refresh after 20s (standard) but the battery won’t charge and keeps draining. Installed a fresh battery and keeps doing the same. Deleted the plugging from homebridge and started to charge again. Please fix this!

I’m running the latest versions.

**Comment by dgreif** [comment] 2020-08-13 17:01
Are you leaving the Home app open all of the time?  Fetching snapshots is the only thing I can think of that would drain a significant amount of battery, and snapshots are only fetched if you have the Home app open.  

You can also try setting the `cameraStatusPollingSeconds` much higher since it isn't extremely important, but as far as I know that number should have no impact on battery life.

**Comment by Lui5Jacint0** [comment] 2020-08-13 17:54
Yes i have an iPad as a hub wall mounted always on.

**Comment by dgreif** [comment] 2020-08-13 18:06
I recently made a change that allows battery cameras (like the doorbell 2) to fetch snapshots as frequently as they are requested by HomeKit.  Since you leave the app open all the time, a new snapshot is requested every 30 seconds (compared to the 10 minutes it was at before).  Those requests would explain the battery drain.  This was a significant improvement for most users since the 10 minute limitation meant snapshots were pretty much useless.  I'm not really sure what the right solution is since you have a pretty unique setup that is causing frequent and snapshot requests throughout the whole day.

**Comment by Lui5Jacint0** [comment] 2020-08-14 17:47
Do you know with version did you apply these changes so i can rollback?

**Comment by dgreif** [comment] 2020-08-14 17:50
That change was released in `9.4.0`.  The last version without that change was `9.3.6`, which is what you would want to roll back to

**Comment by Lui5Jacint0** [comment] 2020-08-14 18:05
Do you think if i change the value in camera status polling to like 600 seconds in the latest version solves my problem?

**Comment by dgreif** [comment] 2020-08-14 18:08
Nope.  Status polling doesn't impact the snapshot polling.  Snapshots are requested by the Home app if you have it open, and the newer versions will fetch a snapshot every time the Home app requests it.  Ring forces a 10 minute delay between snapshots from their app, but I worked around that in the plugin so that you can get them more frequently.  Battery drain is the negative side-effect of that.  I don't know of many users that leave the Home app open full time, so it isn't normally an issue.

**Comment by Lui5Jacint0** [comment] 2020-08-17 22:28
That version is working as intended.
Is it possible though to add snapshot pooling parameter to change in homebridge? So i can have the latest versions?
![FC9E15D2-1518-4C1C-A987-D1BCDEFC23D8](https://user-images.githubusercontent.com/930892/90450313-eb180880-e0d8-11ea-94dc-4e35e4ef7bcd.png)

**Comment by Lui5Jacint0** [comment] 2020-09-29 20:39
Any news on this subject?

**Comment by Arnaud-Albrecht** [comment] 2020-10-07 06:49
I have the exact same problem, with an Ipad mounted on the wall polling too frequently

**Comment by dgreif** [comment] 2020-10-12 04:39
Released `avoidSnapshotBatteryDrain` in v`9.11.0`. This will default back to the standard 10 minute interval for snapshots on battery cameras that Ring uses if you don't force snapshot updates.  Give it a try and let me know how it works for you.

**Comment by Lui5Jacint0** [comment] 2020-10-12 08:32
I’ve been testing for about an hour and half and my battery remain at 100%. I think you fixed it! 🙏🏻

**Closed** 2020-10-12 10:08 UTC

**Comment by jadametz** [comment] 2022-11-17 20:59
@dgreif what're the chances this has regressed? I've just started using Homebridge and this plugin recently, but it's pretty obvious with the Home app open on macOS that the cameras are continuously refreshing.

**Comment by dgreif** [comment] 2022-12-05 04:08
@jadametz there was indeed a regression on this. Should be fixed in `11.7.0-beta.3`, and I'm hoping to release `11.7.0` in the next day or two. Let me know if the beta fixes battery drain for you

**Comment by jadametz** [comment] 2022-12-15 00:52
@dgreif Thanks for the response! I just upgraded to 11.7.0 but at least from the Home app on my iPhone, I’m continuing to see the seconds indicator on the bottom left of the video feeds refreshing every ~10s.

Anything I need to do on my end? Disable/enable the setting? Is the seconds indicator superfluous and the feed isn’t actually updating that often?
