### ISSUE TITLE
Facial Recoginition?

### ISSUE THREAD

**Issue by KattyMan06** [dgreif/ring#398] opened 2020-07-09 18:39 UTC
# Feature Request

### Description
I was wondering if you could add facial recognition to the plugin because on ios 14 facial recognition is only supports on hsv video type

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
trying to run facial recognition on a separate ring stream but I cannot find the video stream url

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dxdc** [comment] 2020-07-10 13:47
Dupe of #385.

Somewhat doable with #290 (snapshots only), although I'll need some help figuring out how to train Google Vision/AWS Rekognition.

**Comment by dgreif** [comment] 2020-07-10 16:56
Yeah, I'd lean more toward using Node Red for something like this.  homebridge is intended to give HomeKit support for devices, not necessarily add really complex features that the manufacturer themself doesn't have

**Closed** 2020-07-11 16:16 UTC
Labels: enhancement, wontfix
