### ISSUE TITLE
Errors then crash

### ISSUE THREAD

**Issue by ScottBessel** [dgreif/ring#131] opened 2019-09-16 21:53 UTC
Just switched from the old non-video version and love this implementation, so thanks for that!

But it seems to crash daily.
Here is my latest log entry.

`[9/16/2019, 11:28:43 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[9/16/2019, 11:29:08 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:08 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:08 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:08 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:08 AM] Got SIGTERM, shutting down Homebridge...
[9/16/2019, 11:29:16 AM] [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Trying again in 5 seconds...
[9/16/2019, 11:29:23 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:23 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:23 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:23 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:24 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
[9/16/2019, 11:29:26 AM] Error: bind EADDRNOTAVAIL 0.0.0.0
    at state.handle.lookup (dgram.js:300:18)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at processTimers (timers.js:265:7)
`

**Comment by dgreif** [comment] 2019-09-16 21:58
Hmm, that's a new one.  It's odd that every time it happens, it's lead by a "Failed to reach Ring server".  I'm wondering if maybe your network adapter in that computer is freaking out, which would explain why it's unable to bind to local ports (which is what the `EADDRNOTAVAIL` is related to).  Does that computer have a weird network card in it?

**Comment by ScottBessel** [comment] 2019-09-16 22:01
Its a standard Mac Mini Server from Mid 2011.  No other issues and all other Homebridge items work.  The previous wink plug-in didn't have any issues.  Honestly this is my first time having Homebridge crash like this (barring json self-inflicted errors)

**Comment by dgreif** [comment] 2019-09-16 22:12
Yeah, it definitely _shouldn't_ be doing that.  However I'm not sure how to help from my end since I can't reproduce the issue.  If you have another computer or a raspberry pi laying around, maybe try running homebridge on there instead.  If you able to debug the code, I'd be happy to take a Pull Request or talk through the issue if you can figure out where exactly it is failing

**Comment by ScottBessel** [comment] 2019-09-17 21:25
I am at a loss as to what to do.  I am just an end user and don't have the ability nor access to setup test systems and debug.
All I do know is it did work on the other and now is doesn't.  My setup is rather basic.

**Comment by dgreif** [comment] 2019-09-17 23:03
It most likely worked before because there were not cameras in the old version.  It's the cameras that are trying to bind to network ports, which is what is causing those errors.  My guess is that it fails every time you try to do a live stream with the cameras.  Does that sound correct to you?

**Comment by ScottBessel** [comment] 2019-09-18 13:47
Actually it seems to work without issue.  Every once in a while I can't get live feeds form the cameras, but it does the same using the Ring app.
I can't see any real pattern.
It just likes to error and crash.

**Comment by ScottBessel** [comment] 2019-09-19 18:58
Further testing and there is nothing I can do to get it to crash.  It just does... Random times.
I do see that I can't get the cameras to stream, they all try for a few seconds and error on the device with a "No Response" message.
Log is not helpful here:
[9/19/2019, 11:56:23 AM] [Ring] Waiting for stream data from Front Door (0.828s)
[9/19/2019, 11:56:33 AM] [Ring] Stopped Live Stream for Front Door
Snapshots work perfectly.
I am still trying things, but I am running out of ideas.

**Comment by dgreif** [comment] 2019-09-19 19:32
That streaming issue is network related (see https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#check-your-logs-in-homebridge).  The crashing on the other hand..I'm not sure what I can do since you aren't able to reproduce it.  If you haven't already, I highly recommend you set up your homebridge to run as a service so that when it crashes, it automatically restarts.  Looks like there are some instructions in the homebridge wiki https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS#starting-homebridge-automatically-with-launchd.  Since you are the only one who has reported this `EADDRNOTAVAIL` issue, my gut tells me that it's something funky with the network card in that computer.  I'm going to close this issue, but if anyone else has the same problem please post it here and I can look into it more.  Thanks for all your troubleshooting @ScottBessel, hopefully running it as a service alleviates the pain of it crashing and you don't have to worry about it anymore

**Closed by dgreif** 2019-09-19 19:32 UTC

**Comment by ScottBessel** [comment] 2019-09-19 20:11
I can assure the network on my system is solid.  It has been running for years providing weather data externally every 2 seconds without a hiccup.
I also have another camera that streams perfectly. And they all snapshot without issue.

I stopped running it as a service because of the crashing/restarting was causing other issues with device updates.

Perhaps it is the way the network is being called that is different in the ring plug-in.

Scott

**Comment by dgreif** [comment] 2019-09-21 05:23
I'm sorry, I should have been more clear in my response. I was not trying to say you have a _bad_ network, but rather your network configuration is blocking access to the functionality being used by the ring plugin.  Every time you start a live video it binds to two random open ports on the host computer (in this case your mac mini), and then tells the Ring servers to send the video/audio streams to those ports.  It opens those ports through your NAT by sending packets _out_ to the server, which should allow the ring packets to come back in.  If you see `Waiting for stream data ` followed by `Stopped Live Stream`, that means that the ring packets were unable to reach your computer through your router/NAT/firewall/whatever else you have set up on your network.  I have done a lot of work to make it work in as many setups as possible, but I can't account for all network configurations (and some are simply impossible to get UDP to come in on a random port).

As for your original issue with `bind EADDRNOTAVAIL 0.0.0.0`, that looks like the plugin is trying to bind to a port on the computer but for some reason the computer itself rejects the action.  Node js is responsible for choosing the port and binding to it, and I have never seen it fail like this.  My best guess is that your network card in that mac mini is doing something funky, but I could be way off on that guess.   As I said before, I would try running homebridge on a different device to see if that issue goes away.  It sounds like it's very random that it happens, so I don't think we will be able to track it down and find a solution.

**Comment by ScottBessel** [comment] 2019-10-04 21:24
Not sure what was changed.

But I just updated to the latest version you posted and my streams are working without issue.

No other changes on my side.

Thanks!

Scott
