### ISSUE TITLE
Error 500 in Ring API on Homebridge

### ISSUE THREAD

**Issue by Bro-Rocket12** [dgreif/ring#1431] opened 2024-06-18 18:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Error 500 in Ring API. Ring plugin no longer works for this location. The entire homebridge crashed while I was viewing cams and not the ring plugin is stuck on this error for this location only. My other location id works fine. 

### Expected behavior

it should work

### Relevant log output

```shell
[6/18/2024, 11:05:09 AM] [homebridge-ring] Request to https://app.ring.com/api/v1/clap/tickets?locationID=4c21be7e-8ccd-4aab-9c44-d5eab8609575 failed with status 500. Response body: {"error":860004,"msg":"No available app brokers"}
[6/18/2024, 11:05:09 AM] [homebridge-ring] Error connecting to API
[6/18/2024, 11:05:09 AM] [homebridge-ring] HTTPError: Response code 500 (Server Error)
    at Request.<anonymous> (/volume1/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1718733909218,
    socket: 1718733909223,
    lookup: 1718733909237,
    connect: 1718733909278,
    secureConnect: 1718733909368,
    upload: 1718733909369,
    response: 1718733909464,
    end: 1718733909465,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 5,
      dns: 14,
      tcp: 41,
      tls: 90,
      request: 1,
      firstByte: 95,
      download: 1,
      total: 247
    }
  }
}
```

### OS

Homebridge/ Synology

### Node.js Version

v20.9.0

### NPM Version

n/a

### ring-client-api

n/a

### Operating System

n/a

**Comment by TepidAssassin** [comment] 2024-06-18 18:16
I am also experiencing the same issue after updating Homebridge today;

[18/06/2024, 19:08:04] [homebridge-ring] Request to https://app.ring.com/api/v1/clap/tickets?locationID=cc415c7-30c8-497f-b2c0-5bb94de8103d failed with status 500. Response body: {"error":860004,"msg":"No available app brokers"}
[18/06/2024, 19:08:04] [homebridge-ring] Error connecting to API
[18/06/2024, 19:08:04] [homebridge-ring] HTTPError: Response code 500 (Server Error)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1718734084301,
    socket: 1718734084303,
    lookup: 1718734084316,
    connect: 1718734084399,
    secureConnect: 1718734084570,
    upload: 1718734084571,
    response: 1718734084713,
    end: 1718734084713,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 13,
      tcp: 83,
      tls: 171,
      request: 1,
      firstByte: 142,
      download: 0,
      total: 412
    }
  }
}

**Comment by MystK** [comment] 2024-06-18 18:17
started happening to me today or recently also. Didn't do any updates in the last few weeks.

Node.js Version | v20.14.0
homebridge-ring | v12.1.0

**Comment by SlasherKG** [comment] 2024-06-18 18:19
Same error here.
No updates done recently.

Hopefully this can be fixed or is just temporary.

**Comment by MystK** [comment] 2024-06-18 18:28
Based on the http error code, it seems to be a Ring server-side issue. I researched and saw that this endpoint helps establish a socket connection. Maybe it'll fix itself over time. This probably isn't an issue with homebridge-ring, especially since @Bro-Rocket12 mentioned his other location works.

**Comment by ElCastillo1353** [comment] 2024-06-18 18:43
Same.... 

[6/18/2024, 1:33:17 PM] [Ring] Request to https://app.ring.com/api/v1/clap/tickets?locationID=baa71e2c-7986-44fa-744e-720cff98e320 failed with status 500. Response body: {"error":860004,"msg":"No available app brokers"}
[6/18/2024, 1:33:17 PM] [Ring] Error connecting to API
[6/18/2024, 1:33:17 PM] [Ring] HTTPError: Response code 500 (Server Error)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',

**Comment by Bro-Rocket12** [comment] 2024-06-18 18:48
Yeah it's definitely something sever side. Rolling back to previous version does not fix it unfortunately. Nor does setting it up as a child bridge. It is weird that my other location id works though, not sure why one works and the other does not. Hopefully whatever the issue is gets fixed soon.

**Comment by tsightler** [comment] 2024-06-18 19:19
Please don't post a lot of "me too" post here, if you are having the same issue and just feel the need to express yourself, a "thumbs up" on the initial post is enough.

It's quite clear that this is a Ring server side issue at this time, what is not clear is if it is a permanent change, or a temporary issue.  The ring-client-api is using `app.ring.com` to request tickets for opening a websocket connection.  Historically this URL load balanced requests to a pool of servers, but right now it is returning the error "No available app brokers".

The official Ring app appears to use `prd-api-us.prd.rings.solutions` and the Ring web console uses `account.ring.com/api` which is also used for requesting the ticket for the WebRTC control channel websocket as well.  These both seem to be working, so it's possible Ring is simply disabling the functionality on the old app pool.

We're likely in for a bumpy ride with the Ring API for the next few weeks as, due the the deprecation and imminent disabling of the legacy FCM APIs, we're also in the middle of migrating to FCM v1 for push notifications.  I just managed to get this working last night, but upgrading will require a complete re-authentication cycle, and perhaps more.

I've also noticed there are other changes happening, lots of backend APIs failing even in the official Ring app, my guess is they are doing some backend optimization and consolidation.  We'll do our best to keep up with the changes, at least so far I've not seen a move to block 3rd-party access, something I have long feared could happen, but providing 100% reliability for a reverse engineered API is simply not possible.

**Comment by tsightler** [comment] 2024-06-18 19:55
I have confirmed that replacing `app.ring.com` with `prd-api-us.prd.rings.solutions` seems to work around the issue.  As far as I can tell this is used only for ticket requests and for changing modes, so I need to investigate if mode changes work with this new URL as well, if so, it should be a simple change.

If any of you out there are interested in manually working around the issue, you can edit node_modules/ring-client-api/lib/rest-client.js and replace `appApiBaseUrl = 'https://app.ring.com/api/v1/'` with `appApiBaseUrl = 'https://prd-api-us.prd.rings.solutions/api/v1/'` on line 22.

**Comment by t-flow-sash** [comment] 2024-06-18 20:20
Just manually did the change. All statuses of all devices are back, camera streams work and Alarm status change including PIN challenge work. Awesome!

**Comment by tsightler** [comment] 2024-06-18 20:25
> Just manually did the change. All statuses of all devices are back, camera streams work and Alarm status change including PIN challenge work. Awesome!

Thanks for the confirmation, if someone out there happens to have a setup that uses modes, and can verify that the change doesn't break that, it would go a long way as I don't have an easy way to test this at the moment as I have an alarm at my location and I don't have any spare camera to setup a second site with no alarm.

**Comment by rorygallagher2024** [comment] 2024-06-18 20:34
Hi, I made the change to update 'appApiBaseUrl' and it also worked for me. @tsightler - By modes, do you mean just switching my alarm to Home/Away modes, using the buttons as shown in the screenshot? 

If so, that is working for me
<img width="385" alt="Screenshot 2024-06-18 at 21 34 13" src="https://github.com/dgreif/ring/assets/167408991/2e63819e-11ea-45ee-a8c7-e22a8681b5b9">

**Comment by t-flow-sash** [comment] 2024-06-18 20:35
> > Just manually did the change. All statuses of all devices are back, camera streams work and Alarm status change including PIN challenge work. Awesome!
> 
> 
> 
> Thanks for the confirmation, if someone out there happens to have a setup that uses modes, and can verify that the change doesn't break that, it would go a long way as I don't have an easy way to test this at the moment as I have an alarm at my location and I don't have any spare camera to setup a second site with no alarm.

What do you mean with "modes"? Happy to help in any way if I can. But don't get exactly what you mean with modes

**Comment by jamesonuk** [comment] 2024-06-18 20:36
Just going to add that I did worry about the US in that domain name and wondered if this was US specific but just checking DNS logs I can see that app in UK is still connecting to `prd-api-us.prd.rings.solutions` so would appear to be a global thing

**Comment by t-flow-sash** [comment] 2024-06-18 20:37
> > Just manually did the change. All statuses of all devices are back, camera streams work and Alarm status change including PIN challenge work. Awesome!
> 
> 
> 
> Please, can you explain me how to do it? ( i don't know how to edit the node modules)

I am using ring-mqtt in a docker container. Just jumped into the interactive shell of that container and followed the path given by @tsightler and did the change in line 22

**Comment by meeowgler** [comment] 2024-06-18 20:38
If you flush your client dns, you'll see that Ring has just added a DNS CNAME record that redirects app.ring.com to prdw-a-envproxy-use1.prd.rings.solutions.

**Comment by rorygallagher2024** [comment] 2024-06-18 20:39
Just in case it helps anyone, I am using the ring-mqtt docker image and was able to modify the URL as follow.

First I had to access the container's shell on my home assistant server:
`docker exec -it ring-mqtt /bin/sh`

Then I searched for the rest-client.js file and found it at this location
`/app/ring-mqtt/mode_modules/ring-client-api/lib/rest-client.js`

So I used vi to modify the file
` vi /app/ring-mqtt/mode_modules/ring-client-api/lib/rest-client.js`

and then proceeded to modify the `appApiBaseUrl` value to `https://prd-api-us.prd.rings.solutions/api/v1/`

**Comment by alessandroarosio1977** [comment] 2024-06-18 20:41
For how have HAOS?

**Comment by bditter** [comment] 2024-06-18 20:43
Or running on Raspberry Pi

**Comment by jacobhopkins117** [comment] 2024-06-18 20:43
> Just manually did the change. All statuses of all devices are back, camera streams work and Alarm status change including PIN challenge work. Awesome!

Confirmed the change to `appApiBaseUrl` is working for me. Changing modes works as well.

**Comment by ThaShadow00** [comment] 2024-06-18 20:45
> Just in case it helps anyone, I am using the ring-mqtt docker image and was able to modify the URL as follow.
> 
> First I had to access the container's shell on my home assistant server: `docker exec -it ring-mqtt /bin/sh`
> 
> Then I searched for the rest-client.js file and found it at this location `/app/ring-mqtt/mode_modules/ring-client-api/lib/rest-client.js`
> 
> So I used vi to modify the file `vi /app/ring-mqtt/mode_modules/ring-client-api/lib/rest-client.js`
> 
> and then proceeded to modify the `appApiBaseUrl` value to `https://prd-api-us.prd.rings.solutions/api/v1/`

is it possibile to do only using raspberry? Sorry for the question but i'm newbie in these things

**Comment by jrdwiz** [comment] 2024-06-18 20:52
If you are running HAOS, ring-mqtt is running in a protected docker container.

You can install Advanced SSH & Web Terminal from HACS, turn protective mode off, SSH into home assistant and then follow the same instructions above using the docker exec command.

**Comment by MystK** [comment] 2024-06-18 20:56
> > Just manually did the change. All statuses of all devices are back, camera streams work and Alarm status change including PIN challenge work. Awesome!
> 
> Please, can you explain me how to do it? ( i don't know how to edit the node modules)

1. Go to homebridge UI terminal: something like `http://192.168.1.11:8581/platform-tools/terminal`
2. look for Plugin Path in the terminal. Mine is `/var/lib/homebridge/node_modules`
3. type in `nano {PLUGIN_PATH}/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js`. Mine looks like `nano /var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js`
4. Use your arrow keys to go down to line 22. It looks like:
```
}, clientApiBaseUrl = 'https://api.ring.com/clients_api/', deviceApiBaseUrl = 'https://api.ring.com/devices/v1/', commandsApiBaseUrl = 'https://api.ring.com/commands/v1/', appApiBaseUrl = 'https://app.ring.com/api/v1/', apiVersion = 11;
```
5. Delete `appApiBaseUrl = 'https://app.ring.com/api/v1/'` and type in `appApiBaseUrl = 'https://prd-api-us.prd.rings.solutions/api/v1/'`
6. CTRL+X to Exit
7. Y to save
8. ENTER to confirm
9. Restart bomebridge-ring child process or main process and it look at logs to confirm it works

**Comment by alessandroarosio1977** [comment] 2024-06-18 20:57
Is it possible to have a new version of component with URL fixed? I’m not confident to make manually this edit with Advanced SSH in my HAOS

**Comment by t-flow-sash** [comment] 2024-06-18 20:59
> Is it possible to have a new version of component with URL fixed? I’m not confident to make manually this edit with Advanced SSH in my HAOS

I am pretty sure that this will come soon once confirmed that this change really has no negative side effects. It is clearly just a workaround to do this manually as a re-pull of the container image will undo this change anyway every time.

**Comment by r1si** [comment] 2024-06-18 21:01
> vi /app/ring-mqtt/mode_modules/ring-client-api/lib/rest-client.js

node_modules not mode_modules.
vi /app/ring-mqtt/node_modules/ring-client-api/lib/rest-client.js

**Comment by bockstone** [comment] 2024-06-18 21:06
> If you are running HAOS, ring-mqtt is running in a protected docker container.
> 
> You can install Advanced SSH & Web Terminal from HACS, turn protective mode off, SSH into home assistant and then follow the same instructions above using the docker exec command.

I'm getting an error, the container doesn't exist..

```
 # docker exec -it ring-mqtt /bin/sh
Error response from daemon: No such container: ring-mqtt


~ # sudo docker exec -it ring-mqtt bash
Error response from daemon: No such container: ring-mqtt
```

**Comment by tFC-Styles** [comment] 2024-06-18 21:07
Spent a fair while doing the usual troubleshooting on this before I came across this thread a few hours ago. And having seen the comments thought I’d leave. 

Since all the traffic of you guys making changes etc, I figured I’d do a full server reboot. As it looks like a DNS change on ring’a end, rather than anything else. (Server OS reboot not just service/app)

This appears to have fixed the issue for me. 

Using raspberry pi running homebridge OS

**Comment by tsightler** [comment] 2024-06-18 21:07
Folks, if you don't know how to edit files, then that solution is not for you, newbies will have to wait for an official fix, having everybody post here will just add confusion.  I will be deleting messages asking for help editing files, Google can help you, or you can go to discussions groups, but this is not the place for that, this thread is about researching and solving the issue.

**Comment by neilmartin83** [comment] 2024-06-18 21:08
Home Assistant: Confirmed working in the UK, using a Ring account that is not the "master" either. On HAOS, I made the edits and restarted the docker container.

1. Install the Advanced SSH & Terminal add-on and configure it correctly (with a password)
2. Disable Protected mode on the add-on config
3. Launch the add-on and run: `docker exec -it $(docker ps | grep ring-mqtt | awk '{print $1}') /bin/sh`
4. Edit this file: `vi /app/ring-mqtt/node_modules/ring-client-api/lib/rest-client.js`

If you're new to `vi`, use the cursor arrow keys to navigate towards the end of line 22, type `a` then replace `appApiBaseUrl = 'https://app.ring.com/api/v1/'` with `appApiBaseUrl = 'https://prd-api-us.prd.rings.solutions/api/v1/'` then press `esc` followed by entering `wq` and press `enter` to save.

5. Log out of the container with `ctrl + d`
6. Restart the container, preserving your changes with: `docker restart $(docker ps | grep ring-mqtt | awk '{print $1}')`

**Comment by tsightler** [comment] 2024-06-18 21:10
> Just going to add that I did worry about the US in that domain name and wondered if this was US specific but just checking DNS logs I can see that app in UK is still connecting to `prd-api-us.prd.rings.solutions` so would appear to be a global thing

Thanks, I had this concern too, but I scoured the app source code and could not find any other reference to a non-US URL so I suspected it was not a problem.

**Comment by ThaShadow00** [comment] 2024-06-18 21:11
> > > Just manually did the change. All statuses of all devices are back, camera streams work and Alarm status change including PIN challenge work. Awesome!
> > 
> > 
> > Please, can you explain me how to do it? ( i don't know how to edit the node modules)
> 
> 1. Go to homebridge UI terminal: something like `http://192.168.1.11:8581/platform-tools/terminal`
> 2. look for Plugin Path in the terminal. Mine is `/var/lib/homebridge/node_modules`
> 3. type in `nano {PLUGIN_PATH}/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js`. Mine looks like `nano /var/lib/homebridge/node_modules/homebridge-ring/node_modules/ring-client-api/lib/rest-client.js`
> 4. Use your arrow keys to go down to line 22. It looks like:
> 
> ```
> }, clientApiBaseUrl = 'https://api.ring.com/clients_api/', deviceApiBaseUrl = 'https://api.ring.com/devices/v1/', commandsApiBaseUrl = 'https://api.ring.com/commands/v1/', appApiBaseUrl = 'https://app.ring.com/api/v1/', apiVersion = 11;
> ```
> 
> 5. Delete `appApiBaseUrl = 'https://app.ring.com/api/v1/'` and type in `appApiBaseUrl = 'https://prd-api-us.prd.rings.solutions/api/v1/'`
> 6. CTRL+X to Exit
> 7. Y to save
> 8. ENTER to confirm
> 9. Restart bomebridge-ring child process or main process and it look at logs to confirm it works

THANK YOU, it works

**Comment by r1si** [comment] 2024-06-18 21:14
Proposal:
But what if we set a url we, which automatically links to the correct API url? 
That way in a situation with today's, we could globally change the url and the whole thing would be solved, without requiring a new plugin update

**Comment by neildsb** [comment] 2024-06-18 21:15
this worked - https://github.com/tsightler/ring-mqtt/issues/861#issuecomment-2176974877

**Comment by Tofusito** [comment] 2024-06-18 21:17
I made another workaround without changing the source code, I changed the `/etc/hosts` and added this line:

`app.ring.com         prd-api-us.prd.rings.solutions`

Restarted the complement and all is working fine for me. Alarm, sensor, etc..

**Comment by tsightler** [comment] 2024-06-18 21:19
> Proposal: But what if we set a url we, which automatically links to the correct API url? That way in a situation with today's, we could globally change the url and the whole thing would be solved, without requiring a new plugin update

I appreciate the suggestion, but the Ring API is complex, it's not just a single URL, there are at least a dozen different URLs listed in the code, it makes zero sense to try to expose them all.  Many times when they change the API itself also changes, what headers are needed, what authentication they use, etc.

**Comment by tsightler** [comment] 2024-06-18 21:20
> I made another workaround without changing the source code, I changed the `/etc/hosts` and added this line:
> 
> `app.ring.com prd-api-us.prd.rings.solutions`
> 
> Restarted the complement and all is working fine for me. Alarm, sensor, etc..

Good idea and nice workaround for the interim.

**Comment by nicks123** [comment] 2024-06-18 21:20
If your running Pihole can change the CNAME record to redirect

**Comment by jimloki** [comment] 2024-06-18 21:22
Everything is working again, with no modifications. I just restarted the addon in Home Assistant

**Comment by Tofusito** [comment] 2024-06-18 21:23
> Everything is working again, with no modifications. I just restarted the addon in Home Assistant

No change in the hosts file or in the code? Maybe ring recover the previous url?

**Comment by broyuken** [comment] 2024-06-18 21:23
yep works for me again too, just restarted the addon and it's good again

**Comment by jimloki** [comment] 2024-06-18 21:23
> > Everything is working again, with no modifications. I just restarted the addon in Home Assistant
> 
> No change in the hosts file or in the code? Maybe ring recover the previous url?

Yes, I think so

**Comment by Tofusito** [comment] 2024-06-18 21:29
> > > Everything is working again, with no modifications. I just restarted the addon in Home Assistant
> > 
> > 
> > No change in the hosts file or in the code? Maybe ring recover the previous url?
> 
> Yes, I think so

Yup, I reverted my change, restarted the addon and it's working! No change in the code needed I guess

**Comment by tsightler** [comment] 2024-06-18 21:31
As I stated earlier, it was quite likely the problem was temporary on the Ring side, the service errored with a message indicating a backend problem, not that it didn't exist or anything like that, it seemed likely to be temporary.  That being said, it doesn't mean we shouldn't update the URL at some point to use the same one the Ring app leverages.

**Comment by qoodanny** [comment] 2024-06-18 21:55
Rollling Back To v 11.8.1 solve the issue

**Comment by tsightler** [comment] 2024-06-18 21:58
> Rollling Back To v 11.8.1 solve the issue

No it won't, it's just that the outage is over and Ring has corrected the issue.

**Comment by jimloki** [comment] 2024-06-18 22:24
Here we go again! It does not work anymore...

**Comment by TNOTA** [comment] 2024-06-18 22:25
I did the modification to the file and everything works perfectly, in fact my Ring cameras come up instantly in HomeKit now. 

BUT I tried going back to the pre modified rest-client.js file when others said it was working again, and I am still getting error 500. 

So I went back again to the modified file and it all works. So this issue may not be cleared on Rings end of things.

**Comment by tsightler** [comment] 2024-06-18 22:31
Yes, there have been several periods of time where it worked or didn't work throughout the day.  I guess we'll see if it stabilizes and, if not, we'll have to push out an update.

**Comment by tomiy1** [comment] 2024-06-18 22:59
I restarted HB plugin, disabled and re-enabled it... no go still here. Am i supposed to do something else? thanks in advance!

**Comment by tsightler** [comment] 2024-06-18 23:15
There is nothing to do until Ring either fixes the issue, or we push out a new version to work around the problem, unless you are able to implement one of the workarounds already posted in this thread.

**Comment by tomiy1** [comment] 2024-06-18 23:17
which workaround is the "goto" atm? thank ya @tsightler !

**Comment by tsightler** [comment] 2024-06-18 23:26
Yes, that is probably the easiest and has no negative side effects, setting a DNS alias for app.ring.com to resolve to prd-api-us.prd.rings.solutions is probably the easiest, using either hosts file, perhaps DNS on your local router, etc.

**Comment by tomiy1** [comment] 2024-06-18 23:29
/etc/hosts is easy enough, ill give that a shot! Thanks @tsightler

**Comment by tsightler** [comment] 2024-06-19 00:43
12.1.1 has been released with a fix for this issue.

**Closed** 2024-06-19 12:27 UTC
Labels: bug
