### ISSUE TITLE
Ring doorbell is being kept active, draining battery overnight

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [dgreif/ring#1348] opened 2023-10-31 19:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I noticed recently - unfortunately have been out of the country so "recently" is the best i can do - that our Ring Doorbell 2 was dead. Charged, and it again died on low battery overnight. Also noticed the LED on the doorbell was active continuously.  

Disabled homebridge-ring and the doorbell works as expected.

In the logs there is a continual stream of activity, I believe a bug is keeping the doorbell streaming continuously thus draining the battery.

### To Reproduce

Install versions as noted, with ring video doorbell 2

### Expected behavior

Work per previous versions of this fine plugin :-)

### Relevant log output

```shell
[31/10/2023, 8:15:28 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:15:28 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:15:57 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:15:58 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:15:59 pm] [homebridge-ring] Stream Prepared for Front Door (1.019s)
[31/10/2023, 8:15:59 pm] [homebridge-ring] Activating stream for Front Door (1.123s)
[31/10/2023, 8:16:00 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:16:01 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:16:01 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:16:01 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:16:01 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:16:01 pm] [homebridge-ring] Streaming active for Front Door (2.397s)
[31/10/2023, 8:16:01 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:16:01 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:16:02 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:16:03 pm] [homebridge-ring] Received stream data from Front Door (4.536s)
[31/10/2023, 8:16:31 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:16:31 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:16:31 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:16:33 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:16:34 pm] [homebridge-ring] Stream Prepared for Front Door (0.98s)
[31/10/2023, 8:16:34 pm] [homebridge-ring] Activating stream for Front Door (1.079s)
[31/10/2023, 8:16:35 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:16:35 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:16:35 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:16:35 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:16:35 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:16:35 pm] [homebridge-ring] Streaming active for Front Door (2.016s)
[31/10/2023, 8:16:35 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:16:35 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:16:35 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:16:36 pm] [homebridge-ring] Received stream data from Front Door (2.286s)
[31/10/2023, 8:17:04 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:17:04 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:17:04 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:17:08 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:17:09 pm] [homebridge-ring] Stream Prepared for Front Door (0.927s)
[31/10/2023, 8:17:09 pm] [homebridge-ring] Activating stream for Front Door (1.027s)
[31/10/2023, 8:17:10 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:17:10 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:17:10 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:17:10 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:17:10 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:17:10 pm] [homebridge-ring] Streaming active for Front Door (2.101s)
[31/10/2023, 8:17:10 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:17:10 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:17:10 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:17:11 pm] [homebridge-ring] Received stream data from Front Door (3.305s)
[31/10/2023, 8:17:41 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:17:41 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:17:41 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:17:49 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:17:50 pm] [homebridge-ring] Stream Prepared for Front Door (0.97s)
[31/10/2023, 8:17:50 pm] [homebridge-ring] Activating stream for Front Door (1.075s)
[31/10/2023, 8:17:50 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:17:51 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:17:51 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:17:51 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:17:51 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:17:51 pm] [homebridge-ring] Streaming active for Front Door (2.064s)
[31/10/2023, 8:17:51 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:17:51 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:17:51 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:17:51 pm] [homebridge-ring] Received stream data from Front Door (2.378s)
[31/10/2023, 8:28:02 pm] [homebridge-ring] Video stream closed
[31/10/2023, 8:28:02 pm] [homebridge-ring] {
  doorbot_id: 74240381,
  session_id: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IlJNUyIsInR5cCI6IkpXVCJ9.eyJhbGV4YV9wb3J0IjoxODQ0MywiYXBwX3Nlc3Npb25fdG9rZW4iOiJyLm1zLldQZjR4UlFTMDZqalB0VE9yRWo4MXQ4ZkdaenJzZjlmIiwiZGluZ19pZCI6IjcyOTYwMTc5Njk3OTM3ODIxNDEiLCJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjo3NDI0MDM4MSwiZXhwIjoxNjk4NzM3MjgwLCJpcCI6IjEzLjIzNi4yNDMuMjMzIiwicGluZ19pbnRlcnZhbCI6MTAsInBvcnQiOjg1NTcsInJtc19mcWRuIjoiMTMtMjM2LTI0My0yMzMuMzgyNTgwMTQyODI2LmFwLXNvdXRoZWFzdC0yLnByb2Qucm1zLnJpbmcuZGV2aWNlcy5hMnouY29tIiwicm1zX3ZlcnNpb24iOiI4Yzk0MDVlNCIsInJzcF9wb3J0Ijo4NTU3LCJydHNwX3BvcnQiOjQ0Mywic2Vzc2lvbl9pZCI6IjA1Zjc5YWUwLWRjOGYtNDc0NS05M2Q1LTk5NWJjZDFhOGM0MCIsInNpcF9wb3J0IjoxNTA2NCwic3J0cF94b3IiOiJ0OEZXRUZQVlIwUFNRUmhuWmE5bFJ3PT0iLCJ3ZWJydGNfcG9ydCI6OTAwMiwid3dyX3BvcnQiOjE5NDQzfQ.L7Qt_lluzvfPdi37Dvw1t4p-AB-iPxAG0Lj7rQft3V8',
  reason: { code: 10, text: 'answered_timeout' }
}
[31/10/2023, 8:28:02 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:28:02 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:28:32 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:28:33 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:28:34 pm] [homebridge-ring] Stream Prepared for Front Door (1.052s)
[31/10/2023, 8:28:34 pm] [homebridge-ring] Activating stream for Front Door (1.151s)
[31/10/2023, 8:28:35 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:28:35 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:28:35 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:28:35 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:28:35 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:28:35 pm] [homebridge-ring] Streaming active for Front Door (2.176s)
[31/10/2023, 8:28:35 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:28:35 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:28:38 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:28:39 pm] [homebridge-ring] Received stream data from Front Door (5.955s)
[31/10/2023, 8:29:06 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:29:06 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:29:06 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:29:08 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:29:09 pm] [homebridge-ring] Stream Prepared for Front Door (0.941s)
[31/10/2023, 8:29:09 pm] [homebridge-ring] Activating stream for Front Door (1.038s)
[31/10/2023, 8:29:10 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:29:10 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:29:10 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:29:10 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:29:10 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:29:10 pm] [homebridge-ring] Streaming active for Front Door (2.021s)
[31/10/2023, 8:29:10 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:29:10 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:29:10 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:29:10 pm] [homebridge-ring] Received stream data from Front Door (2.261s)
[31/10/2023, 8:29:41 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:29:41 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:29:41 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:29:45 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:29:46 pm] [homebridge-ring] Stream Prepared for Front Door (1s)
[31/10/2023, 8:29:46 pm] [homebridge-ring] Activating stream for Front Door (1.1s)
[31/10/2023, 8:29:47 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:29:47 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:29:47 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:29:47 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:29:47 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:29:47 pm] [homebridge-ring] Streaming active for Front Door (2.346s)
[31/10/2023, 8:29:47 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:29:47 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:29:48 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:29:50 pm] [homebridge-ring] Received stream data from Front Door (4.46s)
[31/10/2023, 8:30:15 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:30:15 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:30:15 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:30:23 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:30:24 pm] [homebridge-ring] Stream Prepared for Front Door (0.743s)
[31/10/2023, 8:30:24 pm] [homebridge-ring] Activating stream for Front Door (0.845s)
[31/10/2023, 8:30:25 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:30:25 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:30:25 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:30:25 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:30:25 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:30:25 pm] [homebridge-ring] Streaming active for Front Door (2.037s)
[31/10/2023, 8:30:26 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:30:26 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:30:26 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:30:28 pm] [homebridge-ring] Received stream data from Front Door (4.117s)
[31/10/2023, 8:37:09 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:37:09 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:37:09 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:37:10 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:37:11 pm] [homebridge-ring] Stream Prepared for Front Door (0.959s)
[31/10/2023, 8:37:11 pm] [homebridge-ring] Activating stream for Front Door (1.061s)
[31/10/2023, 8:37:11 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:37:12 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:37:12 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:37:12 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:37:12 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:37:12 pm] [homebridge-ring] Streaming active for Front Door (2.33s)
[31/10/2023, 8:37:12 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:37:12 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:37:12 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:37:14 pm] [homebridge-ring] Received stream data from Front Door (4.039s)
[31/10/2023, 8:40:38 pm] [homebridge-ring] Video stream closed
[31/10/2023, 8:40:38 pm] [homebridge-ring] {
  doorbot_id: 74240381,
  session_id: 'eyJhbGciOiJIUzI1NiIsImtpZCI6IlJNUyIsInR5cCI6IkpXVCJ9.eyJhbGV4YV9wb3J0IjoxODQ0MywiYXBwX3Nlc3Npb25fdG9rZW4iOiJyLm1zLjAzZk51VkdhZFNzODZhNXhUUmxKY1FKNHNzZTVkdk1hIiwiZGluZ19pZCI6IjcyOTYwMjEyMTI0OTQwOTA2MjEiLCJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjo3NDI0MDM4MSwiZXhwIjoxNjk4NzM4MDM1LCJpcCI6IjEzLjIzNi4yNDMuMjMzIiwicGluZ19pbnRlcnZhbCI6MTAsInBvcnQiOjg1NTcsInJtc19mcWRuIjoiMTMtMjM2LTI0My0yMzMuMzgyNTgwMTQyODI2LmFwLXNvdXRoZWFzdC0yLnByb2Qucm1zLnJpbmcuZGV2aWNlcy5hMnouY29tIiwicm1zX3ZlcnNpb24iOiI4Yzk0MDVlNCIsInJzcF9wb3J0Ijo4NTU3LCJydHNwX3BvcnQiOjQ0Mywic2Vzc2lvbl9pZCI6ImMyZWZhMDZkLTUyNjktNDUzZi04YjU3LTdmNWI5M2Y1ZDU4YyIsInNpcF9wb3J0IjoxNTA2NCwic3J0cF94b3IiOiJLZXBEL0cvN3VvdWZxc1JlbHVHM0t3PT0iLCJ3ZWJydGNfcG9ydCI6OTAwMiwid3dyX3BvcnQiOjE5NDQzfQ.EwpxLWWn2xth60sHJqBCLnWC4IRbidG4qi-EXaaC4no',
  reason: { code: 10, text: 'answered_timeout' }
}
[31/10/2023, 8:40:38 pm] [homebridge-ring] connectionStateChange: closed
[31/10/2023, 8:40:38 pm] [homebridge-ring] iceConnectionStateChange: closed
[31/10/2023, 8:41:08 pm] [homebridge-ring] Stopped Live Stream for Front Door
[31/10/2023, 8:41:09 pm] [homebridge-ring] Preparing Live Stream for Front Door
[31/10/2023, 8:41:10 pm] [homebridge-ring] Stream Prepared for Front Door (0.99s)
[31/10/2023, 8:41:10 pm] [homebridge-ring] Activating stream for Front Door (1.095s)
[31/10/2023, 8:41:11 pm] [homebridge-ring] iceConnectionStateChange: completed
[31/10/2023, 8:41:12 pm] [homebridge-ring] connectionStateChange: connecting
[31/10/2023, 8:41:12 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:41:12 pm] [homebridge-ring] iceConnectionStateChange: checking
[31/10/2023, 8:41:12 pm] [homebridge-ring] Activating Session
[31/10/2023, 8:41:12 pm] [homebridge-ring] Streaming active for Front Door (2.366s)
[31/10/2023, 8:41:12 pm] [homebridge-ring] iceConnectionStateChange: new
[31/10/2023, 8:41:12 pm] [homebridge-ring] iceConnectionStateChange: connected
[31/10/2023, 8:41:13 pm] [homebridge-ring] connectionStateChange: connected
[31/10/2023, 8:41:15 pm] [homebridge-ring] Received stream data from Front Door (5.696s)
[31/10/2023, 8:46:50 pm] [Homebridge UI] [homebridge-ring] Terminating child process...
[31/10/2023, 8:46:50 pm] [Homebridge UI] [homebridge-ring] Child process ended
[31/10/2023, 8:47:06 pm] [Homebridge UI] Changes to config.json saved.
```

### Homebridge Ring Config

```shell
{
            "refreshToken": "00000",
            "hideDoorbellSwitch": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "avoidSnapshotBatteryDrain": true,
            "cameraStatusPollingSeconds": 600,
            "locationModePollingSeconds": 0,
            "_bridge": {
                "username": "0000000",
                "port": 37615
            },
            "platform": "Ring"
```

### Additional context

homebridge-ring is running in a child bridge. In my Ring.com account i see the hundreds of video clips from overnight, so the doorbell really is starting to record video every few minutes, which makes sense as to why the battery gets drained.

### OS

Linux

### Node.js Version

18.13.00

### NPM Version

8.19.3

### Homebridge/HOOBs Version

v1.6.1 (HAP v0.11.1)

### Homebridge Ring Plugin Version

12.0.1

### Operating System

Linux

**Comment by tsightler** [comment] 2023-10-31 19:34
Duplicate of https://github.com/dgreif/ring/issues/1291, please see discussions there.  This is not likely related to the plugin itself and there's nothing we can do.

**Closed by tsightler** 2023-10-31 19:34 UTC
Labels: bug

**Comment by YouCanNotBeSerious** [comment] 2023-10-31 19:51
> Duplicate of #1291, please see discussions there. This is not likely related to the plugin itself and there's nothing we can do.

Well, my searching for this as an existing issue was not up to par, was it :-). Thank you.
