### ISSUE TITLE
ring intercom notifications and some other issues

### ISSUE THREAD

**Issue by fate8383** [dgreif/ring#1136] opened 2023-01-11 11:32 UTC
# Bug Report

Before I start please don't send me to integration issue page :) I have read it inside out several times. 
Issues:
1. Cannot turn off notifications in home app, this is inconvenient when I have also ring app notification, as homebridge plugin does not support audio so I have to use ring app for those. I am getting double notified. Is there a way to disable home app notification? toggle off does not work. My goal is to use home app for self automate open the door via the switch button you have in the plugin. but actual door intercom I have to use ring app for the audio calls.
2. Homepad chime on/off, there is no such a toggle, either I add as child bridge nor add normally the HomePod chimes always. Is there a way to control this?
3. Battery status, it works when homebridge restarts, but then not accurate until next restart of the HB, home app reopen does not retrieve the actual battery status.
4. This is the ultimate question might cover 1 issue, is there any hope two way audio will be integrated? I have an intercom literally only opens the door if it is rung and I answered then I can open the door. No idea how this works of course, but I cannot just hit open the door and that would open the door. Audio call is essential.

Ring intercom is revolutionary for europeans in my opinion :) we are all going to have it soon, especially two story apartments or big enough that you don't have enough time to run and open the building door, it helps a lot and I really would like to use fully in the home app some day.

Anything I can help you from my side I am available.

Thanks

### Environment

all latest stable versions, RPI4b, homebridge, HomePod and Ring plugin

**Comment by dgreif** [comment] 2023-01-29 15:13
1. There should be a notifications section in the settings for the intercom in the Home app
2. You can turn off the doorbell in Home, but the setting is really hard to find. You have to go into the settings for the HomePod (within the Home app) and find the "chime on doorbell" option (something like that, can't remember the exact name 
3. This should have been resolved by https://github.com/dgreif/ring/commit/40559b874740858cbb8bfd85125b7bf07680be2d. Are you on the latest version of the plugin?
4. I do not personally plan to add audio support as streaming is significantly harder to build/maintain. I'm open to taking a Pull Request if someone else wants to invest the time to make it work.

**Comment by fate8383** [comment] 2023-01-31 13:54
1. I think this was iOS bug, new version fixed it. Otherwise regardless I turned off notification it was still notifying.
2. I am absolutely sure there is no setting for this, only asked when I added and that was all but I can live with it 😃 
3. I also suspect iOS version was buggy so it is working now.
4. I am sad about this but I hope someone will do PR for it.

Thanks a lot!

**Comment by rachedamer** [comment] 2023-02-02 15:40
I would also love audio support for the Ring Intercom. Being able to use it with the Homepod Mini intercom would be a killer feature! Just out of curiosity: Since the Ring Cameras already have audio support in homebridge-ring, why is it so much harder with Ring Intercom?

**Comment by dgreif** [comment] 2023-02-02 16:08
@rachedamer part of the problem is that HomeKit only has support for _cameras_, and not an audio-only. I'm honestly not sure there is any way to connect the audio from a camera to a Homepod, even if I did get streaming working. There's also the issue that I don't have an intercom, and streaming can only be initiated when someone rings the bell, so figuring out how Ring does the streaming would be almost impossible for me. I'm open to taking a PR for it if someone else want to figure all this out, but it's just not something I have the bandwidth for.

**Comment by mgoeppl** [comment] 2023-02-15 01:36
My theory is that using a static image made to a video (e.g. a black jpg at 1920x1080px) using ffmpeg (which is used anyways for other purposes within the plug-in if I understand it correctly) exposed to HomeKit as a “camera” should work. You already support 2-way audio for Ring cameras, do you think this might be possible?

**Comment by dgreif** [comment] 2023-02-25 21:57
@mgoeppl I totally agree with your idea, that's what I had in mind as well. Just not sure how well it will work or how different the streaming apis are. Without a device to test with, I don't personally have a way to move this forward.

**Comment by salemsayed** [comment] 2023-03-05 12:34
> 

understand of course, just wanted to let you know that I'd be happy to share access with you again if you're ever willing to research this further

**Comment by salemsayed** [comment] 2023-04-19 10:23
Hello,

Did any one find a way to stop the notification of "[device name] doorbell rang"? I don't have any notifications enabled for the lock accessory or the button but I still get notified whenever the intercom button is pressed

**Comment by fate8383** [comment] 2023-04-19 10:46
> Hello,
> 
> 
> 
> Did any one find a way to stop the notification of "[device name] doorbell rang"? I don't have any notifications enabled for the lock accessory or the button but I still get notified whenever the intercom button is pressed

I really cannot stop it ;) I am waiting scrypted to come on top of it one day so I can use that instead :)

**Comment by dgreif** [comment] 2023-05-13 15:09
I do not plan to add audio support for the Intercom at this time. I'm happy to take a PR, but unfortunately it's not something I have time to implement myself. I think I've addressed everything else that I can on this issue, and the remaining problems with disabling notifications seem to be Home app related.

**Closed by dgreif** 2023-05-13 15:09 UTC
Labels: discussion
