### ISSUE TITLE
Ring motion sensors not working after IOS 18 update

### ISSUE THREAD

**Issue by Jpassar099** [dgreif/ring#1499] opened 2024-09-26 17:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Ring motion sensors no longer work since IOS 18 update

### To Reproduce

Typically when a Ring device detected motion, it would trigger an automation in Home app (turn on lights). Since IOS update this no longer happens

### Expected behavior

I expect the Ring sensors to work like they always did.

### Screenshots

![IMG_4247](https://github.com/user-attachments/assets/1b0c6499-bd17-4065-a6f1-5ace465ecafd)

### Homebridge Ring Config

```shell
5 seconds...
2024-09-22, 6:47:50 PMRing BridgeConfiguration change
2024-09-22, 10:46:51 PMRing BridgeConfiguration change
2024-09-23, 2:45:59 AMRing BridgeConfiguration change
2024-09-23, 6:45:01 AMRing BridgeConfiguration change
2024-09-23, 10:44:09 AMRing BridgeConfiguration change
2024-09-23, 2:43:13 PMRing BridgeConfiguration change
2024-09-23, 6:42:22 PMRing BridgeConfiguration change
2024-09-23, 10:41:32 PMRing BridgeConfiguration change
2024-09-24, 2:40:44 AMRing BridgeConfiguration change
2024-09-24, 6:39:51 AMRing BridgeConfiguration change
2024-09-24, 10:39:03 AMRing BridgeConfiguration change
2024-09-24, 2:38:13 PMRing BridgeConfiguration change
2024-09-24, 6:37:19 PMRing BridgeConfiguration change
2024-09-24, 10:36:27 PMRing BridgeConfiguration change
2024-09-25, 2:35:32 AMRing BridgeConfiguration change
2024-09-25, 6:34:39 AMRing BridgeConfiguration change
2024-09-25, 10:33:40 AMRing BridgeConfiguration change
2024-09-25, 2:32:50 PMRing BridgeConfiguration change
2024-09-25, 6:31:56 PMRing BridgeConfiguration change
2024-09-25, 10:31:09 PMRing BridgeConfiguration change
2024-09-26, 2:30:10 AMRing BridgeConfiguration change
2024-09-26, 6:29:16 AMRing BridgeConfiguration change
2024-09-26, 7:00:22 AMRing BridgeRingERRORFailed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/f25ee2-322oa-0. Timeout awaiting 'request' for 20000ms. Trying again in 5 seconds...
2024-09-26, 7:03:39 AMRing BridgeRingERRORRequest to https://prd-api-us.prd.rings.solutions/api/v1/mode/location/f25ee2-322oa-0 failed with status 500. Response body: {"error":200000,"errors":[200000],"msg":"Unhandled error"}
2024-09-26, 7:03:39 AMRing BridgeWARNINGunhandled rejection: HTTPError: Response code 500 (Server Error)
2024-09-26, 10:28:19 AMRing BridgeConfiguration change
```

### Additional context

None

### OS

Raspian (HOOBs app)

### Node.js Version

16.20.2

### NPM Version

1.70

### Homebridge/HOOBs Version

4.31

### Homebridge Ring Plugin Version

12.1.1.

### Operating System

Raspian

**Comment by tsightler** [comment] 2024-09-26 18:24
Please clarify, are you referring to the motion sensor feature for cameras, or for alarm motion sensors?  I don't think this issue is likely to be caused by iOS 18, but rather the fact that you are using old version of the plugin due to being on HOOBS which can't support the newer versions due to outdated NodeJS.

**Comment by Jpassar099** [comment] 2024-09-26 18:27
Thx. It is for motion sensors. You are correct that HOOBs has issues with
newer version and have asked that I use older version.

I will share your comments with HOOBs.

**Comment by tsightler** [comment] 2024-09-26 22:17
If it is alarm based motion sensors, I would expect those to remain working even with the older plugin versions but admittedly, these version are no longer tested or maintained.  I just verified that alarm motion sensors are working fine on my iOS 18 devices, so I don't believe this is a plugin or iOS issue.

**Comment by Jpassar099** [comment] 2024-09-26 22:26
Thanks. In my case it is not the Alarm based sensors. It is the camera
based sensors that I use to trigger automation in Home app.

I reached out to HOOBs and they said they will be pushing an update soon to
ensure we can use the latest version of Ring plugin.

Thanks.

**Comment by tsightler** [comment] 2024-09-26 23:16
Right, so camera based sensors require push notifications and, back in July, Firebase started decommissioning the legacy FCM API servers so old style push notifications used by plugin versions prior to v13 will no longer work.  That's most likely the cause of the issue.

The work in v13 was mostly around using the newer push-receiver updates that leverage the new FCM HTTP v1 APIs and that upstream library requires NodeJS v20 (v18 might work if forced, but officially v20 is required).  Until HOOBS pushes an update with a recent NodeJS push notifications are unlikely work reliably or at all.

As this issue is not a plugin issue, I'm going to close this for now.  Hopefully the HOOBS team will be able to eventually push this update.

**Closed by tsightler** 2024-09-26 23:16 UTC
Labels: HOOBS
