### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by chicagofire** [dgreif/ring#557] opened 2021-01-20 22:16 UTC
# Bug Report

### Describe the Bug
DNS error triggers an unhandled promise rejection error which seems to prevent all timers from processing thereafter as I no longer see periodic status updates for my august locks following the first instance of this error in the logs.

### To Reproduce

Unclear. It looks like DNS queries crapped out for a bit last night as I was updating firmware on various network components.

### Expected behavior
"proper" handling of the error condition. Not exactly sure of the implementation details, but, losing network / dns momentarily isn't entirely unlikely.

### Screenshots/Logs
[1/19/2021, 10:24:12 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/clap/tickets?locationID=4d652d7c-705f-4c65-405f-00c4e00fe3ba.  getaddrinfo ENOTFOUND app.ring.com.  Trying again in 5 seconds...
(node:83289) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND app.ring.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
(node:83289) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 38)
(node:83289) UnhandledPromiseRejectionWarning: Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/usr/local/lib/node_modules/homebridge-ring/node_modules/p-cancelable/index.js:46:12)
    at makeRequest (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (events.js:422:26)
    at Request.emit (events.js:315:20)
    at Timeout.retry (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:1261:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

### Additional context
None

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "refreshToken": "xxx",
            "alarmOnEntryDelay": true,
            "hideLightGroups": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "nightModeBypassFor": "all",
            "avoidSnapshotBatteryDrain": true,
            "platform": "Ring"
        }
```

### Environment

 - OS: MacOS 10.15.4
 - Node.js: 14.15.3
 - NPM: 6.14.9
 - homebridge-ring: 9.14.1
 - homebridge: 1.1.7
 - hoobs: N/A

**Comment by dgreif** [comment] 2021-01-27 04:57
@chicagofire although the error says it's an unhandled rejection, it is handled inside a retry timer and should try again every 5 seconds until it succeeds.  If you are able to still control your locks after that point, then it's connected properly.  I've had intermittent issues with my August locks not relaying status back properly, so it may be a different issue with the locks themselves.  If you can come up with a reliable way to reproduce this issue, I'm happy to look into it.  Are you still seeing this happen occasionally, or was it just the one time?

**Comment by tjridge** [comment] 2021-01-27 15:32
Same problem here. Works for a while after reboot then starts running into error. Cameras don't work, but locks and other ring devices seem to work fine.

**Comment by dgreif** [comment] 2021-01-28 14:07
@tjridge your issue sounds like it may be unrelated.  See https://github.com/dgreif/ring/issues/548#issuecomment-760288703 as that is most likely what you are experiencing.  You just need to install the latest version of node.

**Comment by chicagofire** [comment] 2021-01-28 15:49
> @chicagofire although the error says it's an unhandled rejection, it is handled inside a retry timer and should try again every 5 seconds until it succeeds. If you are able to still control your locks after that point, then it's connected properly. I've had intermittent issues with my August locks not relaying status back properly, so it may be a different issue with the locks themselves. If you can come up with a reliable way to reproduce this issue, I'm happy to look into it. Are you still seeing this happen occasionally, or was it just the one time?

@dgreif I can give it a shot this weekend. I'll have to mess with DNS to replicate.

**Comment by dgreif** [comment] 2021-04-17 14:39
@chicagofire are you still seeing this issue?

**Comment by washcroft** [comment] 2021-04-28 12:08
I just experienced this last night, when some of my network infrastructure had firmware updates.

Syslog is full of:

```
Apr 28 02:32:40 raspberrypi-main homebridge[602]: [28/04/2021, 02:32:40] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/gcw83t-1hjh3-0.  getaddrinfo EAI_AGAIN app.ring.com.  Trying again in 5 seconds...
```

```
Apr 28 02:32:41 raspberrypi-main homebridge[602]: (node:602) UnhandledPromiseRejectionWarning: Error: The `onCancel` handler was attached after the promise settled.
Apr 28 02:32:41 raspberrypi-main homebridge[602]:     at onCancel (/usr/lib/node_modules/homebridge-ring/node_modules/p-cancelable/index.js:48:12)
Apr 28 02:32:41 raspberrypi-main homebridge[602]:     at makeRequest (/usr/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:38:13)
Apr 28 02:32:41 raspberrypi-main homebridge[602]:     at Request.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/got/dist/source/as-promise/index.js:143:17)
Apr 28 02:32:41 raspberrypi-main homebridge[602]:     at Object.onceWrapper (events.js:422:26)
Apr 28 02:32:41 raspberrypi-main homebridge[602]:     at Request.emit (events.js:315:20)
Apr 28 02:32:41 raspberrypi-main homebridge[602]:     at Timeout.retry (/usr/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:1264:30)
Apr 28 02:32:41 raspberrypi-main homebridge[602]:     at listOnTimeout (internal/timers.js:554:17)
Apr 28 02:32:41 raspberrypi-main homebridge[602]:     at processTimers (internal/timers.js:497:7)
```

```
Apr 28 02:32:41 raspberrypi-main homebridge[602]: (node:602) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 33264)
```

When the network returned, the errors stop, but the plugin wasn't working until I restarted homebridge.

**Comment by dgreif** [comment] 2021-05-08 14:01
@washcroft your logs match #616.  Closing this issue since there hasn't been any updates from OP.

**Closed by dgreif** 2021-05-08 14:01 UTC
Labels: bug
