### ISSUE TITLE
[Streaming]: CODEC issue

### ISSUE THREAD

**Issue by sergiom38** [dgreif/ring#1149] opened 2023-02-03 13:53 UTC
### Streaming Issue

Since a couple of days, I'm no longer able to see my Ring Cam into Home application.
Hoobs log reports a Codec issue with a systematic reboot every time I'm trying to access the cam from Home application. From RING application, so not using Hoobs, it's working fine.
Thanks for your support

<img width="816" alt="Ring issue" src="https://user-images.githubusercontent.com/76838387/216619205-f4000f2c-3284-4af5-9a84-ffe0143d28d7.PNG">

### Proposed Solution

I reinstalled RINGHomebridge plugin with same result

### Environment

Homebridge

### What operating system are you on?

Linux

### Relevant log output

```shell
03/02/2023, 14:33:09HOOBSRingPreparing Live Stream for Portillon
03/02/2023, 14:33:09HOOBSRingStream Prepared for Portillon (0.754s)
03/02/2023, 14:33:10HOOBSRingActivating stream for Portillon (0.906s)
03/02/2023, 14:33:10HOOBSERRORError: negotiate codecs failed.
    at RTCPeerConnection.setRemoteRTP (/var/lib/hoobs/hoobs/node_modules/werift/src/peerConnection.ts:1022:13)
    at /var/lib/hoobs/hoobs/node_modules/werift/src/peerConnection.ts:890:14
    at Array.map (<anonymous>)
    at RTCPeerConnection.setRemoteDescription (/var/lib/hoobs/hoobs/node_modules/werift/src/peerConnection.ts:855:38)
    at WeriftPeerConnection.createAnswer (/var/lib/hoobs/hoobs/node_modules/ring-client-api/lib/streaming/peer-connection.js:116:23)
    at WebrtcConnection.handleMessage (/var/lib/hoobs/hoobs/node_modules/ring-client-api/lib/streaming/webrtc-connection.js:29:46)
    at /var/lib/hoobs/hoobs/node_modules/ring-client-api/lib/streaming/streaming-connection-base.js:38:25
    at doInnerSub (/var/lib/hoobs/hoobs/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/var/lib/hoobs/hoobs/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/var/lib/hoobs/hoobs/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/var/lib/hoobs/hoobs/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at WebSocket.handler (/var/lib/hoobs/hoobs/node_modules/rxjs/src/internal/observable/fromEvent.ts:288:52)
    at callListener (/var/lib/hoobs/hoobs/node_modules/ring-client-api/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/var/lib/hoobs/hoobs/node_modules/ring-client-api/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/var/lib/hoobs/hoobs/node_modules/ring-client-api/node_modules/ws/lib/websocket.js:1180:20)
03/02/2023, 14:33:11HOOBSRingStopped Live Stream for Portillon
03/02/2023, 14:33:11HOOBSRingconnectionStateChange: closed
03/02/2023, 14:33:11HOOBSRingiceConnectionStateChange: closed
03/02/2023, 14:33:20HOOBS starting
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment] 2023-02-03 14:54
This is a duplicate of https://github.com/dgreif/ring/issues/1145

**Closed by dgreif** 2023-02-03 14:54 UTC
Labels: live-streaming
