### ISSUE TITLE
Ring video doorbell PRO - Not respond at Home app

### ISSUE THREAD

**Issue by iANGELgr** [dgreif/ring#466] opened 2020-10-02 23:54 UTC
# Bug Report

### Describe the Bug
I just receive the hoobs and im happy. Today I install the homebridge-ring plugin and I wrote the Refresh token. Everything is perfect. I saw 2 cameras window at Home app.
I have one indoor ring cam and one Ring video doorbell PRO!
The indoor window have the message: Snapshots Blocked - Motion detection is disable but when I click that windows Im watching the live feed of indoor. For this camera I prefered to have screenshot of the room ;)

The 2nd big problem is the video doorbell PRO!! I have the same message but when I click the window I receive message NOT RESPOND :( (I have ON both settings at doorbell's disarmed mode, motion detection & Live view BUT dont works at Home app.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_

            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "xxxxxxx",
            "hideDeviceIds": [],
            "locationIds": [],
            "onlyDeviceTypes": []
        },

And the following is from the log

03/10/2020, 02:44:26 HOOBS listening on port 80.
03/10/2020, 02:44:33 Loaded plugin "homebridge-ring".
03/10/2020, 02:44:33 Loaded plugin "homebridge-sensibo-ac".
03/10/2020, 02:44:33 [Ring] Configuring cached accessory xxxxxxx Front Door
03/10/2020, 02:44:33 [Ring] Configuring cached accessory xxxxxxx Living room
03/10/2020, 02:44:33 [Ring] Configuring cached accessory xxxxxxx Hallway
03/10/2020, 02:44:33 [Ring] Configuring cached accessory xxxxxxxx Είσοδος
03/10/2020, 02:44:33 [Ring] Configuring cached accessory xxxxxxx Athens Mode
03/10/2020, 02:44:33 Bridge is running on port 51826.
03/10/2020, 02:44:40 [Ring] Configuring 2 cameras and 5 devices for location "Athens" - locationId: xxxxxx
03/10/2020, 02:46:46 [Ring] Preparing Live Stream for Front Door
03/10/2020, 02:46:48 [Ring] Failed to parse SDP from Ring
03/10/2020, 02:46:48 [Ring] v=0
o=Wantajobinstead? 1529310922 1529310923 IN IP4 
s=Wantajobinstead?
c=IN IP4 54.195.223.83
t=0 0

m=audio 33712 RTP/SAVPF 0
a=rtpmap:0 PCMU/8000
a=rtcp:62573 IN IP4 54.195.223.83
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:xxxxxx
a=ptime:20

m=video 30154 RTP/SAVPF 99
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42000a
a=rtcp:20789 IN IP4 54.195.223.83
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:xxxxxxxxxxx
03/10/2020, 02:46:48 [Ring] Failed to prepare stream for Front Door (1.395s)
03/10/2020, 02:46:48 [Ring] TypeError: Cannot read property 'match' of undefined
    at getRtpDescription (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:24:54)
    at parseRtpDescription (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:36:16)
    at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:204:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Environment

 - OS: [ Raspbian]
 - Node.js: [12.16.2] 
 - NPM: [6.14.4] 
 - homebridge-ring: [9.10.0]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [3.2.6]

**Comment by dgreif** [comment] 2020-10-03 01:57
Duplicate of #447.  Please follow the discussion there.  I'm working on a solution, but no guarantees on when it will be released

**Closed by dgreif** 2020-10-03 01:57 UTC
Labels: bug
