### ISSUE TITLE
Failed to reach ring server

### ISSUE THREAD

**Issue by aberthil** [dgreif/ring#1508] opened 2024-10-15 17:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Keep getting the error message since a few days ago:
ailed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...

### Expected behavior

No more error

### Homebridge Ring Config

```shell
{
    "bridge": {
        "name": "Homebridge 953D",
        "username": "0E:14:DE:BF:95:3D",
        "port": 51905,
        "pin": "633-96-040",
        "advertiser": "avahi",
        "bind": [
            "eth0",
            "wlan0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "refreshToken": "eyJydCI6ImV5SmhiR2NpT2lKU1V6STFOaUlzSW1wcmRTSTZJaTl2WVhWMGFDOXBiblJsY201aGJDOXFkMnR6SWl3aWEybGtJam9pWkRjMFlqTmhNV1VpTENKMGVYQWlPaUpLVjFRaWZRLmV5SnBZWFFpT2pFM01qa3dNRGt3TWpVc0ltbHpjeUk2SWxKcGJtZFBZWFYwYUZObGNuWnBZMlV0Y0hKdlpEcDFjeTFsWVhOMExURTZZak0xTUdFNU5XVWlMQ0p2YVdGMElqb3hOekk1TURBNU1ESTFMQ0p5WldaeVpYTm9YMk5wWkNJNkluSnBibWRmYjJabWFXTnBZV3hmWVc1a2NtOXBaQ0lzSW5KbFpuSmxjMmhmYzJOdmNHVnpJanBiSW1Oc2FXVnVkQ0pkTENKeVpXWnlaWE5vWDNWelpYSmZhV1FpT2pRMk9EVXhOVElzSW5KdVpDSTZJbUozZFZKTFV6SjBjRElpTENKelpYTnphVzl1WDJsa0lqb2lNakZqWXpNME5qUXROamczT0MwME1tTTNMV0kwWVdNdE56SXlOakEzTVdWbFpUWm1JaXdpZEhsd1pTSTZJbkpsWm5KbGMyZ3RkRzlyWlc0aWZRLkM4MDR1QnB4eEptMFkwdDVMNlJ2eF84Y3htcVlmWlNjbkxNc1dKMkVLQ2hVYTBCOUZCT3M1QjZ1aVZkbERSVlk5T1ZadnR0bU04djZzRmFLaHltd0dtSkFEa3Vrck96bkFQYTdCS0g0SGVoM0JyUzdBYndoMF9vTUFKZ3pLTG55NWxyQjR3RUF1Y1R6Zk5Oa2JPZ1NtckNQcm56aFdnM3ZjTWIxR2x0X3Vxb3BJdW9uOWhuRkc3a1lfSDgyME9oVFV1dy0yLS0tbW1XbV94SURBM2t4QWhmWUpSZ2ROMFJKa0Y1bEE5MVQ4V2JPOUcxX0EwcnppYXVaLTVwUVVHMGNyVFQ2OUVlSUJnTEdjY0tFMEh2aU9wZFRzdF95VGhxZmd1NFlZd1VFTHZMZFZoZFRBZkJJMU9DdEtkQXdRcVZBRDJjSWdUNE1PR0hFbWh1NkF1dENxZyIsImhpZCI6ImJmZmFjMzljLTU3MmItNTczMi05OTEyLTg4MmM0YjQ2MjJjYiIsInBuYyI6eyJrZXlzIjp7InByaXZhdGVLZXkiOiJGSmNWLXdkWE54SlI5ck95ZDc0ZEd3OHZWdzMtVmNpSi03X2ItMTU4QXJzIiwicHVibGljS2V5IjoiQkpFbXplckl1RmNMRkFGWmhMUUxqVjdoSy02bldZc2FYSDIzWmtfS194Sm1US0thb0hTQXhnaW1ubFh3VmZwaVdtZWZtLUFWZVNZVXFPRU9qY2NNSUNFIiwiYXV0aFNlY3JldCI6IjJLV2RZTmtCU2dqT3diUEdfZzQzbGcifSwiZ2NtIjp7InRva2VuIjoiZGIyVXo3YnNSVUU6QVBBOTFiRkJUTFNsaml4MUFiS3JwVDh2cVZQTkpiMEZIMEI3cjRwcWtLT0U1ek1NM1FRNUdkbDg5ZF8xTXFUcm1JWXRDTThZQVVwcG1ia0tXTXJ1T1dfVzdxVmViZnVrbmZrWEY1dnF1M1ZYLXdrTmtPMXp3aHlZeUd1NTBuZVNEd1Y3NUlHNDlFb24iLCJhbmRyb2lkSWQiOiI1MDQwMjA1NjU3NDYyOTM5NzAzIiwic2VjdXJpdHlUb2tlbiI6IjkyMjMwODE0NjI3Mzk3MTE0OTAiLCJhcHBJZCI6IndwOnJlY2VpdmVyLnB1c2guY29tIzU3NGU3MGI5LTI4ZjAtNDQ5YS04NWFiLWI2ZTdjNDFlMDA2ZSJ9LCJmY20iOnsidG9rZW4iOiJkVkNkWmdObzZPRXExdTZVLXp2aXZHOkFQQTkxYkVWZVMwRGJDRF9GYUpyamNNenRjMjNWVmFWdkhaNml0TXRuODNpWWFObDZZZWpSX3RoZjE2b2xueExiMXZySlBBVTNPbF9WeER5REJOYzlTU3VacGhrc2NBQm9peWQ4R19NTVhFZUpHVDZKNTRxMzNGTWdHSFdyd05FVlBxOG1HVG1NSnNjIiwiaW5zdGFsbGF0aW9uIjp7InRva2VuIjoiZXlKaGJHY2lPaUpGVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhjSEJKWkNJNklqRTZPRGMyTXpFek9EVTVNekkzT21GdVpISnZhV1E2WlRFd1pXTTJaR1JpTTJNNE1XWXpPU0lzSW1WNGNDSTZNVGN5TXpRM01qWTVOU3dpWm1sa0lqb2laRlpEWkZwblRtODJUMFZ4TVhVMlZTMTZkbWwyUnlJc0luQnliMnBsWTNST2RXMWlaWElpT2pnM05qTXhNemcxT1RNeU4zMC5BQjJMUFY4d1JnSWhBTWVCVDVCNmlLWmpqamM2bS1rNlQ5ZnZ1WEZXSEp5OWVfOERMdy1wYi1TTkFpRUF1enI5dTM2bjVaZ2VlOENtc09MRTlBdjBJcEdReHR5c3lFa1F6QmxmLTdFIiwiY3JlYXRlZEF0IjoxNzIyODY3ODk1NzUyLCJleHBpcmVzSW4iOjYwNDgwMDAwMCwicmVmcmVzaFRva2VuIjoiM19BUzNxZndMbkxQbG45ZXJTWDBGbzVZSXU1ZS11eDkyT0lULUJfTGJpc3NScGpxLWczWU5sQ3dYcEZmRXRJYTNXWmNOQUJHYk9tTWVnTHA2MUs2MFg5THdaU1hqNlJqUVJ4VndKUnpZZGt5RlZNdlkiLCJmaWQiOiJkVkNkWmdObzZPRXExdTZVLXp2aXZHIn19LCJjb25maWciOnsiYnVuZGxlSWQiOiJyZWNlaXZlci5wdXNoLmNvbSIsInByb2plY3RJZCI6InJpbmctMTc3NzAiLCJ2YXBpZEtleSI6IiJ9fX0=",
            "platform": "Ring",
            "_bridge": {
                "username": "0E:FC:43:B7:C7:80",
                "port": 36591
            }
```

### OS

Debian GNU/Linux Bookworm (12) 

### Node.js Version

v20.18.0 

### NPM Version

v9.2.0

### Homebridge/HOOBs Version

v1.8.4

### Homebridge Ring Plugin Version

v13.1.0 

### Operating System

Debian GNU/Linux Bookworm (12)

**Comment by aberthil** [comment] 2024-10-15 17:16
[15/10/2024, 09:04:41] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:07:28] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:07:43] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:16:51] [homebridge-ring] Restarting child bridge...
[15/10/2024, 09:16:51] Got SIGTERM, shutting down child bridge process...
[15/10/2024, 09:16:56] [homebridge-ring] Child bridge process ended
[15/10/2024, 09:16:56] [homebridge-ring] Process Ended. Code: 143, Signal: null
[15/10/2024, 09:17:03] [homebridge-ring] Restarting Process...
[15/10/2024, 09:17:04] [homebridge-ring] Launched child bridge with PID 778417
[15/10/2024, 09:17:05] Registering platform 'homebridge-ring.Ring'
[15/10/2024, 09:17:05] [homebridge-ring] Loaded homebridge-ring v13.1.0 child bridge successfully
[15/10/2024, 09:17:05] Loaded 4 cached accessories from cachedAccessories.0EFC43B7C780.
[15/10/2024, 09:17:05] [homebridge-ring] Configuring cached accessory 47fde78d-c43e-4045-ac11-3bb24c702eb2 Dinning
[15/10/2024, 09:17:05] [homebridge-ring] Configuring cached accessory f525a38c-33d2-4155-a4aa-75d045c9666c Hallway
[15/10/2024, 09:17:05] [homebridge-ring] Configuring cached accessory edf87faa-bf50-48a7-a71d-154c95ee7959 Hallway Pro
[15/10/2024, 09:17:05] [homebridge-ring] Configuring cached accessory 3fcae8cb-a058-464d-a52c-16e80d028d48 Dining Pro
[15/10/2024, 09:17:05] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-ring) is running on port 36591.
[15/10/2024, 09:17:05] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[15/10/2024, 09:17:06] [homebridge-ring] Found the following locations:
[15/10/2024, 09:17:06] [homebridge-ring]   locationId: 9q9htg-4evb0-0 - Mountain View
[15/10/2024, 09:17:06] [homebridge-ring] Configuring 0 cameras and 4 devices for location "Mountain View" - locationId: 9q9htg-4evb0-0
[15/10/2024, 09:17:56] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:22:56] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:25:13] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:41:49] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:41:54] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:04] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:09] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:09] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:19] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:24] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:24] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:29] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:34] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:39] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:39] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:44] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:49] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:49] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:54] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:54] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:42:59] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:04] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:04] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:09] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:09] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:09] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:14] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:19] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:19] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:24] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:24] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:24] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:29] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:29] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:34] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:34] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:39] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:39] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:39] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:44] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:44] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:49] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...
[15/10/2024, 09:43:49] [homebridge-ring] Failed to reach Ring server at https://prd-api-us.prd.rings.solutions/api/v1/mode/location/9q9htg-4evb0-0.  fetch failed.  Trying again in 5 seconds...

**Comment by tsightler** [comment] 2024-10-20 17:02
Thanks for providing logs.  Please make sure all of your Ring devices are online as any offline devices can lead to API timeouts.

**Comment by tsightler** [comment] 2024-10-25 01:35
Closing as duplicate of https://github.com/dgreif/ring/issues/1506, please feel free to participate in that conversation.

**Closed by tsightler** 2024-10-25 01:35 UTC
Labels: bug
