### ISSUE TITLE
Failure to Reconnect Following macOS Reboot

### ISSUE THREAD

**Issue by SSutherland94** [dgreif/ring#374] opened 2020-06-21 15:23 UTC
# Bug Report

### Describe the Bug
I have my Mac Mini reboot nightly in order to keep it running fresh daily. I recently started moving my Homebridge operation from FreeNAS to macOS. However, apparently when I reboot my Mac, the plugin fails to reconnect to Ring's servers until I manually restart Homebridge again.

### To Reproduce
Reboot macOS
View logs

### Expected behavior
I expected the plugin to connect properly following the reboot.

### Screenshots/Logs
[6/21/2020, 11:14:54 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
This, but every 5 seconds

### Homebridge Ring Config
My config only has my refresh token. I haven't made any changes to any components.

### Environment

 - OS: macOS 10.15.5
 - Node.js: 12.16.3
 - NPM: [e.g 6.13.4] 6.14.4
 - homebridge-ring: 9.3.2
 - homebridge: 1.1.1
 - hoobs: N/A

**Comment by dgreif** [comment] 2020-06-21 20:41
This is likely related to #373. Once that is resolved, you can reopen this issue if you are still having problems

**Comment by SSutherland94** [comment] 2020-06-21 20:46
This issue predates #373. I have been dealing with this for two daily reboots now. This was resolved with a restart of the Homebridge service, but yesterday I didn't get onto my Mac until almost 6pm, so my log was 12 hours of that same log entry every 5 seconds. I truly do not believe the two are related given the circumstances, but hopefully #373 resolves itself tonight so I can find out in the morning when my Mac reboots next.

**Comment by dgreif** [comment] 2020-06-21 20:51
Gotcha, sorry for the assumption on my part. There have been a few other GitHub issues related to dns recently, so you might be able to find a solution by looking through those. It will definitely be hard for you to test until 373 is resolved tho :(

**Comment by SSutherland94** [comment] 2020-06-21 20:56
No worries, assumption was fair given the clamoring in #373! If it helps, it *might* (spoiler: not a dev 🤣) have something to do with a comms related initialization situation. I had a similar issue with the homebridge-switchbot-for-mac plugin, where on reboot, my Switchbots wouldn't connect because the plugin started before my BT service initialized, which was resolved by the dev adding an option to delay the initialization of the plugin for a few seconds in order to allow the Bluetooth to initialize first. Maybe it's something related here, but naturally tied to initialization of the network card?

**Comment by dgreif** [comment] 2020-06-21 21:10
Check out #345 which was a similar issue on startup. You may be able to add a delay to your service startup after a reboot to avoid the issue

**Comment by SSutherland94** [comment] 2020-06-21 21:16
Thanks! I’ll have to do some research to figure out how that translates to macOS, but that’s the exact issue I’m having! I’ll test it out when that main issue is resolved and let you know how it goes

**Comment by dgreif** [comment] 2020-06-21 23:00
#373 should be fixed in 9.3.3 if you want to continue debugging

**Comment by SSutherland94** [comment] 2020-06-22 00:11
Yup, that's fixed for sure, I'll update tomorrow morning, EST, with what happens post-reboot. I think I added the right string in the LaunchDaemon plist, so we'll see what happens in the morning. I'll update you then. And at least if it doesn't work this time, I'll be able to pull logs for you  since my log won't be overrun with that every 5 second error!

**Comment by SSutherland94** [comment] 2020-06-22 14:00
Okay, so that didn't work. Here's a snippet of the log before it becomes overrun with the error message
`(node:498) UnhandledPromiseRejectionWarning: Error: send ENETUNREACH 255.255.255.255:987
    at doSend (dgram.js:697:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at afterDns (dgram.js:643:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
(node:498) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:498) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[37m[6/22/2020, 6:10:52 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://oauth.ring.com/oauth/token.  getaddrinfo ENOTFOUND oauth.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:10:53 AM] [39m[36m[Spidey PS4] [39mFound device [Spidey PS4]
[37m[6/22/2020, 6:10:53 AM] [39m[36m[Spidey PS4] [39mFinish searching accessories
[37m[6/22/2020, 6:11:01 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:11:01 AM] [39m[36m[Blinds] [39mWoHand (cf:a4:99:de:b5:88) was discovered
[37m[6/22/2020, 6:11:02 AM] [39m[36m[Blinds] [39mWoHand (c4:f2:1c:59:52:0c) was discovered
[37m[6/22/2020, 6:11:09 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:11:17 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:11:26 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:11:34 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:11:42 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:11:51 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:11:59 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:12:07 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:12:15 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:12:24 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
[37m[6/22/2020, 6:12:32 AM] [39m[36m[Ring] [39m[31mFailed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...[39m
`
That error repeats until I manually restart Homebridge again, so in this case, every 5 seconds for about 4 hours.

**Comment by dgreif** [comment] 2020-06-23 17:32
@SSutherland94 it looks like the plugin is receiving a bad DNS record that doesn't expire and isn't correct.  Do you have some sort of DNS caching set up that could be causing this issue?  Maybe on your router?

**Comment by SSutherland94** [comment] 2020-06-24 03:01
Didn’t see anything funny in my router, flushed my Mac’s DNS, and (maybe?) increased homebridge’s start delay, assuming ThrottleInterval actually works. I’ll report back in the morning

**Comment by dgreif** [comment] 2020-06-28 14:59
@SSutherland94 everything working after your changes?

**Comment by SSutherland94** [comment] 2020-06-28 16:15
No luck unfortunately. Still the same issue

**Comment by dxdc** [comment] 2020-06-30 12:25
Do you think this could be an issue with dns still?

Also, wondering about the `maxTtl` parameter @dgreif? By default it's set to Infinity. If some wrong value gets cached early (255.255.255.255) maybe this will cause a continual failure. So, maybe reducing ttl to something a lot shorter, like 1 or 5 min?
e.g.
```
new CacheableLookup({maxTtl: 60});
```

**Comment by dxdc** [comment] 2020-06-30 12:28
btw, @SSutherland94 are you using DHCP for your network settings? Also wondering if you have 2 possible network interfaces? E.g., if it connects to one network, can't get a connection then tries the other one.

**Comment by SSutherland94** [comment] 2020-06-30 23:48
@dxdc DHCP, yes, and absolutely only one network interface. More than one is just a disaster imo.

**Comment by dgreif** [comment] 2020-07-01 13:51
@SSutherland94 I added the config that @dxdc suggested, along with an error check that should help the plugin recover in these situations.  Can you give v`9.3.6` a try tonight?

**Comment by SSutherland94** [comment] 2020-07-01 13:53
Sure thing. I’ve recently moved 95% of my Homebridge setup to Raspberry Pi, but I still have one plugin left on my Mac, so I’ll drop the Ring plugin back on there and let you know how it goes

**Comment by SSutherland94** [comment] 2020-07-02 12:08
Here's what I woke up to
`[7/2/2020, 6:10:52 AM] [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  getaddrinfo ENOTFOUND oauth.ring.com.  Trying again in 5 seconds...
[7/2/2020, 6:10:52 AM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status undefined. Response body: undefined
[7/2/2020, 6:10:52 AM] [Ring] Error connecting to API
[7/2/2020, 6:10:52 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:116:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:120:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:119:16)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:143:33)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:25:65)`

**Comment by dgreif** [comment] 2020-07-02 14:15
Looks like your refresh token got invalidated some how.  Try generating a new one and replacing it in your config

**Comment by SSutherland94** [comment] 2020-07-05 17:42
Generated a new refresh token, so it's working now, I'll update following my late-night reboot

**Comment by SSutherland94** [comment] 2020-07-06 14:09
Failed again on reboot

**Comment by dgreif** [comment] 2020-07-06 14:18
Can you post logs from this morning?

**Comment by SSutherland94** [comment] 2020-07-06 14:25
`[7/6/2020, 6:10:53 AM] [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  getaddrinfo ENOTFOUND oauth.ring.com.  Trying again in 5 seconds...
[7/6/2020, 6:10:53 AM] [Ring] Request to https://app.ring.com/rhq/v1/devices/v1/locations failed with status undefined. Response body: undefined
[7/6/2020, 6:10:53 AM] [Ring] Error connecting to API
[7/6/2020, 6:10:53 AM] [Ring] Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens
    at RingRestClient.getGrantData (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:116:15)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:120:36)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:23:12)
    at RingRestClient.getAuth (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:119:16)
    at RingRestClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:143:33)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:25:65)`
Looks like the same thing I got last time

**Comment by dgreif** [comment] 2020-07-06 14:28
Interesting...this seems like it may be related to #393.  Something weird is happening with refresh tokens, but I haven't been able to pin it down yet.

**Comment by dxdc** [comment] 2020-07-06 14:49
@dgreif I have a thought, and agree, related to #393.

```js
export class RingApi {
  public readonly restClient = new RingRestClient(this.options)
```

`RingRestClient` is called here, but how are exceptions handled? E.g., if you just shut off your network connection, you should be able to reproduce this behavior. (Btw, if this isn't the cause then, there is some place where the exception isn't being caught)

Also, in `RingRestClient`:
```
throw new Error(
      'Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens'
    )
```

**Comment by dgreif** [comment] 2020-07-06 15:12
Great call @dxdc! Disconnecting from the network helped me track it down.  I had added some debug logs to print out what the dns cache had on hand for specific host names if a request failed.  What I didn't take into consideration is that the query lookup could also throw an error.  I'm now catching that in v`9.4.1`.  @SSutherland94 you should be able to update and try it again tonight.  If all goes well, it should fall into a retry loop and successfully connect once your network layer is available.

**Comment by SSutherland94** [comment] 2020-07-07 14:06
So it seems somehow I've reverted back to the original error that brought me here in the first place

**Comment by dgreif** [comment] 2020-07-07 22:34
@SSutherland94 can you post some logs?  Also, can you reproduce this more quickly by just rebooting the computer, rather than waiting for a nightly restart?

**Comment by SSutherland94** [comment] 2020-07-07 22:39
`[7/7/2020, 9:56:46 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:56:54 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:57:02 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:57:11 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:57:19 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:57:28 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:57:36 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:57:44 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:57:53 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:58:01 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:58:10 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:58:18 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:58:26 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:58:35 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:58:43 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:58:52 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:59:00 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:59:08 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:59:17 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:59:25 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:59:34 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:59:42 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:59:50 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 9:59:58 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:00:07 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:00:15 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:00:24 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:00:32 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:00:41 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:00:49 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:00:57 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:01:06 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:01:14 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:01:23 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:01:31 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:01:40 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:01:48 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:01:56 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:02:05 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:02:13 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:02:22 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:02:30 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:02:38 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:02:47 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:02:55 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:03:04 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:03:12 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:03:20 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:03:29 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:03:37 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:03:46 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:03:54 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:04:02 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:04:11 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:04:19 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:04:27 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:04:36 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:04:44 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:04:52 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:05:00 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:05:09 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 10:05:17 AM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...`
That's from this morning's log. Just a snippet because if I give you from 6am to the server restart, it'll probably make the browser panic 🤣

**Comment by dgreif** [comment] 2020-07-07 22:44
@SSutherland94 can you set `"debug": true` in your ring platform config and try it again?  It should log more info about what is currently in your dns cache

**Comment by SSutherland94** [comment] 2020-07-08 00:07
`[7/7/2020, 8:06:36 PM] [Ring] DNS Cache for app.ring.com: [{"address":"34.239.83.149","ttl":8,"family":4,"expires":1594166801670},{"address":"34.205.51.174","ttl":8,"family":4,"expires":1594166801670},{"address":"50.19.89.44","ttl":8,"family":4,"expires":1594166801670}]
[7/7/2020, 8:06:45 PM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 8:06:45 PM] [Ring] RequestError: cacheableLookup ENOTFOUND app.ring.com
    at PromisableRequest._makeRequest (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:1025:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CacheableLookup.lookupAsync (/usr/local/lib/node_modules/homebridge-ring/node_modules/cacheable-lookup/source/index.js:183:18) {
  code: 'ENOTFOUND',
  timings: undefined
}
[7/7/2020, 8:06:45 PM] [Ring] DNS Cache for app.ring.com: [{"address":"50.19.89.44","ttl":10,"family":4,"expires":1594166811932},{"address":"34.239.83.149","ttl":10,"family":4,"expires":1594166811932},{"address":"34.205.51.174","ttl":10,"family":4,"expires":1594166811932}]
[7/7/2020, 8:06:53 PM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 8:06:53 PM] [Ring] RequestError: cacheableLookup ENOTFOUND app.ring.com
    at PromisableRequest._makeRequest (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:1025:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CacheableLookup.lookupAsync (/usr/local/lib/node_modules/homebridge-ring/node_modules/cacheable-lookup/source/index.js:183:18) {
  code: 'ENOTFOUND',
  timings: undefined
}
[7/7/2020, 8:06:53 PM] [Ring] DNS Cache for app.ring.com: [{"address":"50.19.89.44","ttl":20,"family":4,"expires":1594166831221},{"address":"34.239.83.149","ttl":20,"family":4,"expires":1594166831221},{"address":"34.205.51.174","ttl":20,"family":4,"expires":1594166831221}]
[7/7/2020, 8:07:01 PM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...
[7/7/2020, 8:07:01 PM] [Ring] RequestError: cacheableLookup ENOTFOUND app.ring.com
    at PromisableRequest._makeRequest (/usr/local/lib/node_modules/homebridge-ring/node_modules/got/dist/source/core/index.js:1025:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CacheableLookup.lookupAsync (/usr/local/lib/node_modules/homebridge-ring/node_modules/cacheable-lookup/source/index.js:183:18) {
  code: 'ENOTFOUND',
  timings: undefined
}`

**Comment by dxdc** [comment] 2020-07-08 00:15
Maybe a random idea @SSutherland94, but can you repeat the experiment except turning your Mac Firewall off (and/or, confirming the Firewall Options are set correctly). Also, are you running any antivirus software or network monitoring software on your Mac?

<img width="673" alt="Screen Shot 2020-07-07 at 7 12 36 PM" src="https://user-images.githubusercontent.com/7200365/86858206-d8e08e80-c085-11ea-8dd8-a414c722569e.png">

Lastly can you share the details of your plist (blurring any relevant details), and what path you have that in? I'm wondering if this isn't a Catalina-related block.

**Comment by dgreif** [comment] 2020-07-12 12:29
@SSutherland94 this feels like it is a DNS issue similar to another one that popped up yesterday. 
 Can you follow the instructions from this comment and post the results: https://github.com/dgreif/ring/issues/397#issuecomment-657139720

**Comment by dgreif** [comment] 2020-08-01 02:13
@SSutherland94 any updates?  I'd really like to get this solved for you, but it seems like this issue is really only showing up for you at this point.

**Comment by SSutherland94** [comment] 2020-08-02 16:36
Honestly, I migrated over to Raspberry Pi a couple of weeks ago and completely forgot about this. But if I'm the only one with this issue, it's probably something oddly specific to me and my networking setup, so don't drive yourself crazy over it. I haven't had any issues on the Pi besides it being slow because I cheaped out and got a Zero W, so if this is only affecting me, feel free to close it up.

**Comment by dgreif** [comment] 2020-08-02 16:38
Sounds good, glad you have a working setup now!

**Closed by dgreif** 2020-08-02 16:39 UTC
Labels: setup-issue

**Comment by proactivematter** [comment] 2020-09-11 18:22
I have noticed I have also been getting bursts of this error, seemingly at ramdom.

`[9/11/2020, 1:47:39 PM] [Ring] Failed to reach Ring server at https://app.ring.com/rhq/v1/devices/v1/locations.  cacheableLookup ENOTFOUND app.ring.com.  Trying again in 5 seconds...`

However, I have not noticed it impacting functionality. All it does (as far as I can tell so far) is flood my logs with it.
