### ISSUE TITLE
Feature to expose person-detection

### ISSUE THREAD

**Issue by rwgunther** [dgreif/ring#506] opened 2020-11-28 13:51 UTC
# Feature Request

### Description
 Ring has added a feature that can notify you when a person is detected by a camera. This is different than motion detection, which can be set off by any number of events—animals, vehicles, etc. I’d love to be able to trigger an event in HomeKit based on a person being detected vs motion.

### Describe the solution you'd like
 I imagine a Person sensor service, similar to the sensors for Ring motion detection, would be a good way to expose this in HomeKit. I have no idea whether it’s possible to access person detection on the Ring side.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by dxdc** [comment] 2020-12-09 04:05
Dupe of #263

**Closed** 2020-12-09 15:29 UTC
Labels: duplicate
