### ISSUE TITLE
Failed to reach Ring server Refresh Token :

### ISSUE THREAD

**Issue by Stewart06** [dgreif/ring#1479] opened 2024-08-23 09:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Bonjour,

Depuis la dernière mise à jour du plugin RING, j'ai l'erreur suivante qui se produit :

23/08/2024 à 11:15:49Ring Bridge starting
23/08/2024 à 11:15:55Ring BridgeLoaded plugin 'homebridge-ring'
23/08/2024 à 11:15:55Ring BridgeRegistering platform 'homebridge-ring.Ring'
23/08/2024 à 11:15:55Ring BridgeLoading 1 platforms...
23/08/2024 à 11:15:55Ring BridgeRingdidFinishLaunching
23/08/2024 à 11:15:55Ring BridgeSetup URI 'X-HM://0023MW5F03NRM'
23/08/2024 à 11:15:55Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
23/08/2024 à 11:15:55Ring BridgeBridge is running on port 51856.
23/08/2024 à 11:16:00Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
23/08/2024 à 11:16:05Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
23/08/2024 à 11:16:10Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
23/08/2024 à 11:16:15Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
23/08/2024 à 11:16:20Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
23/08/2024 à 11:16:25Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
23/08/2024 à 11:16:30Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...
23/08/2024 à 11:16:35Ring BridgeRingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not

J'ai toute essayé, déconnecté le plugin et de me reconnecter, désinstaller le plugin, redémarrer le RPi et reinstaller le plugin me reconnecter à nouveau et toujours la meme erreur, je n'arrive plus a avoir ma ring door view cam.

Je precise encore une fois, qu'avant la mise à jour tout fonctionné !

### Expected behavior

*****

### Homebridge Ring Config

```shell
{
    "platform": "Ring",
    "refreshToken": "************"
}
```

### OS

Rasbian

### Node.js Version

16.20.2

### NPM Version

0

### Homebridge/HOOBs Version

Hoobs 4.3.1

### Homebridge Ring Plugin Version

13.1.0

### Operating System

Rasbian

**Comment by tsightler** [comment] 2024-08-23 13:49
Please use search prior to posting new issues.  This is a duplicate issue already covered in a dozen places.  You must update HOOBS as it is outdated.  Please reach out to HOOBS support.

Duplicate of:  https://github.com/dgreif/ring/issues/1459, https://github.com/dgreif/ring/issues/1463, https://github.com/dgreif/ring/issues/1469, https://github.com/dgreif/ring/issues/1475, https://github.com/dgreif/ring/discussions/1472.

**Closed by tsightler** 2024-08-23 13:49 UTC
Labels: setup-issue, HOOBS
