### ISSUE TITLE
Peephole Camera Randomly Opening Stream

### ISSUE THREAD

**Issue by F-Kafka** [dgreif/ring#1326] opened 2023-10-10 16:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

This has been happening for sometime but I've been attempting to trace the issue backwards to determine when it started & how I can reproduce it. 

Since the v.12 update the battery level of my peephole camera suddenly drains rapidly. It can go for several days and then overnight it drains from 95% to a level where I receive a low battery warning. I even installed a brand new battery and the result was the same. This does not happen every time but the attached screen capture are the last lines of the logs after rebooting Homebridge. If I read this correctly a video stream is being opened even though there's been no motion detection. Even without rebooting I've seen this identical behavior at random points in time. 
[Screen Shot 2023-10-10 at 10.47.08 AM.pdf](https://github.com/dgreif/ring/files/12859215/Screen.Shot.2023-10-10.at.10.47.08.AM.pdf)

### To Reproduce

It's been random so I haven't figured out a reliable way to reproduce. 

### Expected behavior

Don't expect video streams to be opened without detecting motion. 

### Screenshots

[Screen Shot 2023-10-10 at 10.47.08 AM.pdf](https://github.com/dgreif/ring/files/12859220/Screen.Shot.2023-10-10.at.10.47.08.AM.pdf)

### Homebridge Ring Config

```shell
Version 12.0.1

{
    "refreshToken": "[REMOVED]",
    "platform": "Ring"
}
```

### OS

Raspbian GNU/Linux Bullseye (11)

### Node.js Version

V18.17.1

### NPM Version

v9.8.1

### Homebridge/HOOBs Version

v1.6.1

### Homebridge Ring Plugin Version

V12.0.1

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by dgreif** [comment] 2023-10-10 16:18
This sounds like a duplicate of https://github.com/dgreif/ring/issues/1291. It's an issue with some of the newer versions of tvOS

**Closed by dgreif** 2023-10-10 16:18 UTC
Labels: bug

**Comment by F-Kafka** [comment] 2023-10-10 16:23
You're correct. Sorry for the dup. Somehow I managed to miss that one. Thanks.
