### ISSUE TITLE
Not able to stream video

### ISSUE THREAD

**Issue by grantdray** [dgreif/ring#1460] opened 2024-08-07 00:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I get this error when trying to view live video - 8/6/2024, 8:36:21 PMRing BridgeERROR[Ring Bridge 579E@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Kitchen' didn't respond at all!. Please check that you properly call the callback!

### To Reproduce

Just watching live video

### Expected behavior

I expect video to work and be able to view.

### Relevant log output

```shell
8/6/2024, 8:36:21 PMRing BridgeERROR[Ring Bridge 579E@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Kitchen' didn't respond at all!. Please check that you properly call the callback!
```

### Homebridge Ring Config

```shell
{
    "platform": "Ring",
    "alarmOnEntryDelay": false,
    "sendDoorbellMotionNotificationsToTv": true,
    "sendCameraMotionNotificationsToTv": true,
    "hideUnsupportedServices": false,
    "avoidSnapshotBatteryDrain": false,
    "hideCameraLight": false,
    "nightModeBypassFor": "all",
    "refreshToken":
```

### OS

Rasbian

### Node.js Version

v22.6.0

### NPM Version

v10.8.2

### Homebridge/HOOBs Version

v1.7.0/v4.3.1

### Homebridge Ring Plugin Version

v13.0.0

### Operating System

Rasbian

**Comment by tsightler** [comment] 2024-08-07 01:25
Not a lot to go on there I assume there must be more entries in the log than that.  Regardless, I note that you are using bridge cameras.  This is deprecated and it is highly recommended to move to unbridged cameras by setting `unbridgeCameras` option to true and then adding cameras individually to Homekit as individual accessories.

**Comment by tsightler** [comment] 2024-08-28 17:03
Closing due to no additional logs provided and cannot reproduce.

**Closed by tsightler** 2024-08-28 17:03 UTC
Labels: bug
