### ISSUE TITLE
Chime on Homepod Function Does not work

### ISSUE THREAD

**Issue by shurikm97** [dgreif/ring#457] opened 2020-09-22 20:51 UTC
# Bug Report

### Describe the Bug
When enabling chime on Homepod feature within Homekit receive "Could Not complete Operation" error

### To Reproduce
Enable feature on Home app under Doorbells

### Expected behavior
Feature enablement should work.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
![image](https://user-images.githubusercontent.com/32882962/93936264-e526d000-fcf3-11ea-8573-84a271ff9af3.png)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment] 2020-09-22 20:59
This is a duplicate of #453.  It's a bug with the HomePod and HomeKit, not with the plugin.  Hopefully apple releases an update for the HomePod soon.

**Closed by dgreif** 2020-09-22 20:59 UTC
Labels: bug
