### ISSUE TITLE
New Ring Intercom Support?

### ISSUE THREAD

**Issue by salemsayed** [dgreif/ring#1097] opened 2022-11-14 08:28 UTC
# Feature Request

### Description
 A clear and concise description of the problem or missing capability...
Is there a plan to support the new announced Ring Intercom (released in UK only)
### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here
The item can be found here:
https://en-uk.ring.com/products/intercom-charging-station-qrbp

**Comment by dgreif** [comment] 2022-11-14 17:31
Duplicate of #1083

**Closed by dgreif** 2022-11-14 17:31 UTC
Labels: duplicate, enhancement
