### ISSUE TITLE
Ring and HomeKit Notification Bug

### ISSUE THREAD

**Issue by jacc** [dgreif/ring#100] opened 2019-08-08 23:20 UTC
Hey there @dgreif,

I'm a very big believer in DIY, and I thought that I would love to integrate homebridge-ring into my Homebridge setup. My parents are not fully willing to migrate, but I noticed that only one app gets notifications, usually the Home app gets alerts and not the actual Ring app.

Is there any way to use both side by side?

Thanks so much!

**Comment by Sunoo** [comment] 2019-08-08 23:33
Oh, is that the issue I’m having? I only get notifications through Ring, not Home. Should I try disabling the Ring ones? I assumed that would stop the device from tracking motion.

**Comment by dgreif** [comment] 2019-08-08 23:41
@jacc they are supposed to work side by side.  Make sure that you have notifications for the cameras properly turned on in the Home app.  Because of all the changes between iOS 12 and 13 beta, I can't give you great instructions for that off the top of my head.  I'll turn my ring notifications back on to verify that they work together, but I know they did in the past.

**Comment by jacc** [comment] 2019-08-08 23:54
@dgreif thanks for the fast reply. I'll check it out tonight, but I was pressing the physical doorbell button and it came up on the Home app but my parents didn't get a notification.

**Comment by Sunoo** [comment] 2019-08-09 16:10
Update: I've just discovered that there are 2 motion sensors exposed from Ring for some reason? One as a separate device, which doesn't work. And one integrated with the camera, which does. I still don't get notifications though.

**Comment by odenisenko** [comment] 2019-08-10 17:11
^^^^^^^
guys.  JFYI after last update (from ring) 
https://api.ring.com/clients_api/dings/active returns nothing, juts empty JSON
[]
i'm thinking it's "hello from ring" again.

**Comment by dgreif** [comment] 2019-08-10 17:15
@odenisenko my active dings are working just fine, just tried it with motion on my doorbell.  Are you using this api, or just sending HTTP requests?

**Comment by odenisenko** [comment] 2019-08-11 15:39
1st magically it was fixed tonight (crazy and fsck ring company
2nd yes I am using own small lib for accessing motion/ring status and grabbing pic for FIBARO HA
![image](https://user-images.githubusercontent.com/44768566/62835999-51b54b80-bc67-11e9-886d-c5a2746e1042.png)

**Comment by dgreif** [comment] 2019-08-11 20:15
@jacc @Sunoo I think motion/ding notifications are working exactly as expected at this point.  There should be no conflict with Ring notifications, and they should be working reliably through HomeKit.  If you are not receiving notifications, it is most likely an issue with your settings in the Ring app or Home app, or it may be a bug in HomeKit (which is likely with iOS 13 beta going on right now).  If you are able to give me steps to reproduce an issue I am happy to help, but I am not seeing any issues in my setup.  Closing this issue for now since I don't see anything wrong with the plugin.

**Closed by dgreif** 2019-08-11 20:15 UTC
