### ISSUE TITLE
Ring Intercom Integration

### ISSUE THREAD

**Issue by AdminMBL** [dgreif/ring#1085] opened 2022-10-29 15:27 UTC
Any chance that some can **integrate** the brand new **Ring Intercom Device**, which is a door opener. Would be nice to manage the device via Homekit.
KR
Markus 

# Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by Lucleonhart** [comment] 2022-10-29 16:18
For information: the data discovery does not give out anything for the intercom, seems to be a new category:

`{"locations":[{"name":"Willich","cameras":[],"chimes":[],"devices":[]}],"amazonKeyLocks":[]} `

**Comment by AdminMBL** [comment] 2022-10-29 16:21
`{„locations“:[{„name“ : „NN“, „cameras“: [ ], „chimes“ : [ ] , „devices“ : [ ] : [ ] } ], „amazonKeyLocks“ : [ ]}`
nothing in as it is only shown as new device in Ring App

**Comment by AdminMBL** [comment] 2022-10-29 16:23
@Lucleonhart : thx, was working that out simultaneously

**Comment by dgreif** [comment] 2022-10-31 20:39
This is a duplicate of #1083

**Closed by dgreif** 2022-10-31 20:39 UTC
Labels: enhancement
