### ISSUE TITLE
Motion Sensors Not Showing iOS 13.2

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#161] opened 2019-10-28 20:17 UTC
Hi, when clicking on camera in homekit and say "show as separate tiles" I only get the light button appear, not the motion sensor?

**Comment by dgreif** [comment] 2019-10-28 20:38
I'm updating now and will give it a try.  My guess is they are just keeping the sensor tied to the camera, but it should still work.  Sorry I don't have any control over how HomeKit displays everything 😞

**Comment by adavison007** [comment] 2019-10-28 20:54
> I'm updating now and will give it a try. My guess is they are just keeping the sensor tied to the camera, but it should still work. Sorry I don't have any control over how HomeKit displays everything 😞

In the beat it showed the sensor, but now on public realise it does not, so probably just code... in the settings for the camera you see the light control, motion was their until public realise of 16.2

**Comment by dgreif** [comment] 2019-10-28 21:10
I just tried it out and mine shows the motion sensor if I separate them into individual tiles on 13.2 (public release).  Maybe try re-grouping them and then separate them again.  If that doesn't work, remove the camera from HomeKit and re-add.  Let me know how it goes

**Comment by adavison007** [comment] 2019-10-28 22:19
> I just tried it out and mine shows the motion sensor if I separate them into individual tiles on 13.2 (public release). Maybe try re-grouping them and then separate them again. If that doesn't work, remove the camera from HomeKit and re-add. Let me know how it goes

Ok, so, put them as single tile, then separated again... no luck.... removed camera and re added.. no luck... Strange...

When I re added, it only showed the camera and light as an option....
![IMG_0261](https://user-images.githubusercontent.com/47482260/67722437-04788880-f9d1-11e9-8d69-603fcb09f034.PNG)

**Comment by dgreif** [comment] 2019-10-28 22:31
One last thing you can try, remove the camera and follow the steps in https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#cannot-add-camera-from-home to completely remove that camera from HomeKit, then re-add.  It's possible it's keeping some residual info for it...

**Comment by adavison007** [comment] 2019-10-28 22:44
> One last thing you can try, remove the camera and follow the steps in https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#cannot-add-camera-from-home to completely remove that camera from HomeKit, then re-add. It's possible it's keeping some residual info for it...

Just done this and no joy... strange...... looks like i'm going to have to delete the plugin and start all over... if I do that will i also need to reinstall the jMPG plug info video?

**Comment by dgreif** [comment] 2019-10-28 22:58
I don't think reinstalling the plugin should be necessary.  You can remove the plugin from your homebridge config and then add it back.  No need to reinstall ffmpeg either.

**Comment by adavison007** [comment] 2019-10-29 19:57
Ok, I deleted all cameras from homekit, deleted the Accessories from the persist file and now nothing, can't see the cameras when hitting add accessory? thoughts, ideas?

**Comment by adavison007** [comment] 2019-10-29 21:26
I'm on Hoobs and it now only lets me install 5.8.3 published 10/6/2019 as a hoobs certified plugin in, going backwards rapidly

**Comment by dgreif** [comment] 2019-10-29 22:08
Yeah, their release cycle is gonna always be behind based on how they do certification.  You may be able to find the non-certified version of the plugin, but i haven't used their interface so idk for sure. Regarding your previous issue, I'm not sure why you wouldn't be able to re-add the cameras after you removed the persist files.  Maybe just need to restart homebridge and ensure you are on the same network as your homebridge server

**Comment by adavison007** [comment] 2019-10-29 23:59
OK, after numerous installs and deleting of caches I have got to the point where in the logs I see the ring cameras, it says to add manually, but when saying add accessories in homekit they don't appear, thoughts? 

<img width="853" alt="image" src="https://user-images.githubusercontent.com/47482260/67818151-19741b00-faa8-11e9-9529-87d4a9584f0c.png">

**Comment by dgreif** [comment] 2019-10-30 03:22
Ensure you are on the same network and that your phone can see the homebridge server (not a guest network, etc.).  If that is all good, then try adding the camera from another device like an iPad or mac book.

**Comment by adavison007** [comment] 2019-10-30 07:53
I’ve tried on another iOS device no joy... I don’t think you can add an accessory from a HomeKit on Mac? If you can please let me know how?

**Comment by dgreif** [comment] 2019-10-30 22:39
Looks like there is _not_ an option to add devices from mac (just automations and scenes).  So you are able to add the homebridge "bridge" device, but can't see the cameras to add them?  The only other thing I can think of is the camera homebridge ports being blocked somehow on your homebridge server

**Comment by adavison007** [comment] 2019-10-31 09:44
> Looks like there is _not_ an option to add devices from mac (just automations and scenes). So you are able to add the homebridge "bridge" device, but can't see the cameras to add them? The only other thing I can think of is the camera homebridge ports being blocked somehow on your homebridge server

- Thanks, are these ports on the local network or inbound/outbound on router? I rebuilt the whole of my home bridge last night as I destroyed it deleting files.  Still have the same issue :( weirdly, it all worked fine other than not showing motion sensors... now I've ended up here :(

**Comment by adavison007** [comment] 2019-10-31 15:19
Thanks, I have not changed this setting, where do you get to the port setting?

Sorry to be a pain.

**Comment by adavison007** [comment] 2019-11-01 19:03
Ok, so a complete rebuilt of homebridge (HoobS) to get cameras added again... and unfortunately no option for motion sensors.. only options for lights....

<img width="1224" alt="Screenshot 2019-11-01 at 19 00 52" src="https://user-images.githubusercontent.com/47482260/68049216-3e4fd480-fcda-11e9-9715-aa61712cbc95.png">
<img width="408" alt="Screenshot 2019-11-01 at 19 01 41" src="https://user-images.githubusercontent.com/47482260/68049221-43148880-fcda-11e9-9f65-3491f6004bdb.png">

**Comment by adavison007** [comment] 2019-11-02 11:37
@dgreif So the only additional item that appears when turning on all settings in Homebrige is the light button for turning on the ring lights... nothing else...

As I have rebuilt my homebridge multiple times now I am 100% ure this is not a config or install issue my end...

The only thing it may be (just remembered) is I am running beta code on my ring camera at the moment.... so I'll wait until the beta is over to see if motion returns, stay tuned....

**Comment by dgreif** [comment] 2019-11-17 16:57
@adavison007 did you ever get this sorted out?

**Comment by adavison007** [comment] 2019-11-18 09:45
> @adavison007 did you ever get this sorted out?

Nope, no idea why.... motion simply no longer appears as an option for my cameras in Homekit :( used to work a treat...

**Comment by adavison007** [comment] 2019-12-06 17:03
@dgreif Still not joy on latest version, see settings, please confirm they are correct? any ideas why motion does not show as a separate tile? in the camera settings I does not show the motion sensor, thus not showing ability to show separate tiles... I only see the light as a separate item

<img width="798" alt="Screenshot 2019-12-06 at 17 00 26" src="https://user-images.githubusercontent.com/47482260/70341202-51f6d980-184a-11ea-9458-6eed20656c9f.png">

**Comment by dgreif** [comment] 2019-12-07 20:40
@adavison007 your config all looks good.  I don't use HOOBS myself, but I think I've seen that you can hide accessories from their UI.  Is it possible that you hid the motion sensors on the HOOBS side?

**Comment by adavison007** [comment] 2019-12-08 08:46
@dgreif Thanks for the feedback, no they are not hidden, and after testing just now, if you hide a hoobs accessory it only hides in hoobs, it still appears in Homekit.... basically for some reason, the motion sensors are not recognised in my system..... The only thing I can possibly think of is I am doing a beta of motion for ring at the moment, so maybe it is affecting the API? I've requested to be removed from the beta... and will report back if that happens

**Comment by adavison007** [comment] 2019-12-08 08:56
@dgreif Not sure if this helps, the log shows added accessories, then asks to add them? wondering if it has not added motions??? If I say add accessory in homekit they do not appear... remember video and cameras are working fine as is the light buttons.... wondering if there is an issue it's having with adding motion?

<img width="1702" alt="Untitled 3" src="https://user-images.githubusercontent.com/47482260/70387081-9db79900-1998-11ea-850f-c08e9390cf04.png">

**Comment by parkesjm75** [comment] 2019-12-13 02:55
I had the same problem and finally was able to fix by removing all the settings for Ring that Hoobs had put in the config.json. I just left platform and my refresh token. Restarted Hoobs and my sensor appeared!

**Comment by dgreif** [comment] 2019-12-13 04:04
@parkesjm75 thanks for the comment.  Now I'm thinking there is a good chance your config is messed up @adavison007.  This option _looks_ correct in the image you sent, but HOOBS could be storing an odd value for `hideCameraMotionSensor`.  Could you post your config for `homebridge-ring` (minus refreshToken/password)?

**Comment by adavison007** [comment] 2019-12-13 08:05
> @parkesjm75 thanks for the comment. Now I'm thinking there is a good chance your config is messed up @adavison007. This option _looks_ correct in the image you sent, but HOOBS could be storing an odd value for `hideCameraMotionSensor`. Could you post your config for `homebridge-ring` (minus refreshToken/password)?

@dgreif Thanks, see attached
<img width="681" alt="Ring" src="https://user-images.githubusercontent.com/47482260/70782613-56a61b00-1d7f-11ea-804a-17ad9a5dffc7.png">

**Comment by dgreif** [comment] 2019-12-13 14:51
@adavison007 The issue is revealed at last!!  Each of those config options should be `true` or `false` instead of `"true"`/`"false"`.  The way javascript evaluates `"false"` is as a "truthy" value, meaning it thinks it's `true` for settings purposes.  Effectively, you have all of those settings turned on, including `hideCameraMotionSensor` which hides the motion sensors for the cameras.  If you remove the quotes on all of those and restart homebridge, you should get your motion sensors back 😅

Now I'm really curious if this is a bug in HOOBS.  Did you copy/paste this config from the server that first started having issues before you wiped it?  Did you input these values by hand, or just set the config options through HOOBS UI?

**Comment by adavison007** [comment] 2019-12-13 14:55
Awesome! I will try when home and confirm.

The config was totally build from hoobs UI, not from me doing the JSON.

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 13 Dec 2019, at 14:51, Dusty Greif <notifications@github.com> wrote:

@adavison007 <https://github.com/adavison007> The issue is revealed at last!! Each of those config options should be true or false instead of "true"/"false". The way javascript evaluates "false" is as a "truthy" value, meaning it thinks it's true for settings purposes. Effectively, you have all of those settings turned on, including hideCameraMotionSensor which hides the motion sensors for the cameras. If you remove the quotes on all of those and restart homebridge, you should get your motion sensors back 😅

Now I'm really curious if this is a bug in HOOBS. Did you copy/paste this config from the server that first started having issues before you wiped it? Did you input these values by hand, or just set the config options through HOOBS UI?

**Comment by adavison007** [comment] 2019-12-13 19:02
Ok, so if I remove the “ “ thenafter reboot it adds them again (does this on all plugins)….

If I remove all setting sand just leave the refresh code, motion appears… If I then set motion to appear, it adds false with the explanation marks and fails….

So looks like your plugin only has an issue with hoobs….. you are the only hoobs authorised one I use…. I am going to remove this and add your plugin as apposed to the authorised one and see what happens…

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 13 Dec 2019, at 14:51, Dusty Greif <notifications@github.com> wrote:

@adavison007 <https://github.com/adavison007> The issue is revealed at last!! Each of those config options should be true or false instead of "true"/"false". The way javascript evaluates "false" is as a "truthy" value, meaning it thinks it's true for settings purposes. Effectively, you have all of those settings turned on, including hideCameraMotionSensor which hides the motion sensors for the cameras. If you remove the quotes on all of those and restart homebridge, you should get your motion sensors back 😅

Now I'm really curious if this is a bug in HOOBS. Did you copy/paste this config from the server that first started having issues before you wiped it? Did you input these values by hand, or just set the config options through HOOBS UI?

**Comment by dgreif** [comment] 2019-12-13 19:07
@adavison007 thanks for the update, glad it works!!  I let the HOOBS team know that the issue is there so hopefully they can get it fixed on their end soon.  For now, removing the `"`s should be all you need to do.    So glad we finally got this resolved.  Thanks for your patience @adavison007, and @parkesjm75 for your valuable comment!

**Closed by dgreif** 2019-12-13 19:07 UTC
Labels: setup-issue

**Comment by adavison007** [comment] 2019-12-13 20:13
so your skill does not work in hoobs now, you have to use their version of your skill… their version does not work for the individual settings

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 13 Dec 2019, at 19:07, Dusty Greif <notifications@github.com> wrote:

@adavison007 <https://github.com/adavison007> thanks for the update, glad it works!! I let the HOOBS team know that the issue is there so hopefully they can get it fixed on their end soon. For now, removing the "s should be all you need to do. So glad we finally got this resolved. Thanks for your patience @adavison007 <https://github.com/adavison007>, and @parkesjm75 <https://github.com/parkesjm75> for your valuable comment!

**Comment by adavison007** [comment] 2019-12-14 15:25
Hers the info I have submitted to hoobs…

If you configure the ring features via the hoobs UI some work, some don't the one I know definitely does not work is Motion sensors.... so If I set "Hide Motion Sensors" to false, they do not appear... If I leave it blank and delete that line in the JSON, they do appear.


Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 13 Dec 2019, at 20:13, Adam Davison <adavison@me.com> wrote:

so your skill does not work in hoobs now, you have to use their version of your skill… their version does not work for the individual settings

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 13 Dec 2019, at 19:07, Dusty Greif <notifications@github.com <mailto:notifications@github.com>> wrote:

@adavison007 <https://github.com/adavison007> thanks for the update, glad it works!! I let the HOOBS team know that the issue is there so hopefully they can get it fixed on their end soon. For now, removing the "s should be all you need to do. So glad we finally got this resolved. Thanks for your patience @adavison007 <https://github.com/adavison007>, and @parkesjm75 <https://github.com/parkesjm75> for your valuable comment!
