### ISSUE TITLE
Configuration Not loading

### ISSUE THREAD

**Issue by wahart77399** [dgreif/ring#1547] opened 2024-12-16 14:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I've loaded a valid token refresh but I still get the following:
Warn Plugin is not configured. Yet I have a valid configuration - token key not shown:
![Screenshot 2024-12-16 at 8 23 54 AM](https://github.com/user-attachments/assets/2aacf733-330d-4947-87a9-721b7efd78e0)
![Screenshot 2024-12-16 at 8 24 16 AM](https://github.com/user-attachments/assets/bc71acec-c903-4c22-b097-7e86bf6a0127)

### To Reproduce

![Screenshot 2024-12-16 at 8 21 54 AM](https://github.com/user-attachments/assets/1ecc1135-43b5-4ee1-9c12-3b1f32da8f77)

### Expected behavior

My ring devices should have been loaded

### Screenshots

![Screenshot 2024-12-16 at 8 24 16 AM](https://github.com/user-attachments/assets/c0e59f4a-41b0-4e4b-b0ec-1c3bba39afe6)
![Screenshot 2024-12-16 at 8 23 54 AM](https://github.com/user-attachments/assets/193b2cf0-9de3-43ef-b1bc-1ebfc8a0da09)
![Screenshot 2024-12-16 at 8 21 54 AM](https://github.com/user-attachments/assets/b5d87bcc-2172-4428-9c5c-f2ada8539537)
![Screenshot 2024-12-16 at 9 20 49 AM](https://github.com/user-attachments/assets/27eab194-37e2-4429-9a81-833e617732d0)
![Screenshot 2024-12-16 at 9 20 49 AM](https://github.com/user-attachments/assets/83448ce5-6a6d-4032-b5b2-f4efed5aa925)
![Screenshot 2024-12-16 at 8 24 16 AM](https://github.com/user-attachments/assets/dc6d7cf6-e409-436c-b7cc-c394a03c5bdd)
![Screenshot 2024-12-16 at 8 23 54 AM](https://github.com/user-attachments/assets/8a0f6093-1784-48d0-b10c-ce955f6f74a0)
![Screenshot 2024-12-16 at 8 21 54 AM](https://github.com/user-attachments/assets/d47b29e6-aef8-45f8-b6b9-d92b05f97861)

### Homebridge Ring Config

```shell
{
    "platforms": [
        {
            "platform": "Ring",
            "refreshToken": "not loaded here"
       }
    ]
}
```

### OS

Linux 6.6.62-current-sunxi

### Node.js Version

20.5.1

### NPM Version

v9.8.0

### Homebridge/HOOBs Version

1.8.4/5.1.8

### Homebridge Ring Plugin Version

13.2.1

### Operating System

Linux 6.6.62-current-sunxi

**Comment by tsightler** [comment] 2024-12-16 16:39
OK, went through the trouble of installing clean HOOBS 5.1.8 image on an old RPi4 I had lying around, installed latest plugin, testing all functionality with cameras and alarm devices, and everything worked perfectly, 100% configured through the HOOBS client UI.

However, I was able to reproduce your issue based on the information you have provided, and is because you are trying to provide an entire Homebridge platform configuration to the plugin config, you state you have this:
```
{
    "platforms": [
        {
            "platform": "Ring",
            "refreshToken": "not loaded here"
       }
    ]
}
```
Indeed, this is not a valid plugin configuration, this section could only include the options specific to this plugin, so it should simply be:
```
{
  "refreshToken": "not loaded here"
}
```
Not sure why you wouldn't just use the UI to authenticate but hopefully this will help.

**Comment by wahart77399** [comment] 2024-12-16 18:04
that worked - not sure why the page says to do what I did, but it does

**Comment by tsightler** [comment] 2024-12-16 18:06
What page are you talking about?

**Comment by wahart77399** [comment] 2024-12-16 18:08
https://github.com/dgreif/ring/tree/main/packages/homebridge-ring#homebridge-ring

**Comment by tsightler** [comment] 2024-12-16 18:21
That page is describing how to add the plugin to Homebridge configuration manually, for example, if you are using pure Homebridge via the command line.  You are not doing this, you are using HOOBS, which is a third-party UI/management plane wrapped around base Homebridge with their own way of doing things, this is why HOOBS support is your first contact when using HOOBS.  

You do no need to do any manual configuration via config files when using HOOBS or even other UIs, like official Homebridge UI, I mean, that's pretty much the point of these UIs, to avoid from users having to manually edit config files in JSON.  I would suggest that you just go back to Visual mode and use the UI completely, but glad you got it working.  I will close this issue.

**Closed by tsightler** 2024-12-16 18:21 UTC
Labels: HOOBS
