### ISSUE TITLE
Double ding notification 

### ISSUE THREAD

**Issue by podycust** [dgreif/ring#944] opened 2022-05-21 13:49 UTC
# Bug Report

### Describe the Bug
Every time doorbell is rang I get two chimes from HomePod which I didn’t get before version 11

### To Reproduce
 Ring doorbell

### Expected behavior
Chime just once

### Environment

 - OS: [e.g. Raspbian] Debian 1a
 - Node.js: [e.g. 12.14.1] 16.15
 - NPM: 8.8.0
 - homebridge-ring: 11.0.1
 - homebridge: 1.4.1
 - hoobs: n/a

**Comment by dgreif** [comment] 2022-05-21 17:37
Interesting. Would you posting the logs from homebridge when this happens?

**Comment by nashnix** [comment] 2022-05-26 05:35
I've also had the same experience @dgreif - you're not going to like it, but all I was able to beat the log into yielding was this:

> 26/05/2022, 15:25:23 _Ring Bridge_ **Ring** Front Door Doorbell Pressed

I pressed the doorbell once, but it has sent through two chimes (and not in sync - it's a gamble which HomePod will sound off first, but they all will do at least twice).  As well as two chimes, I sometimes get two notifications in the Home app (this is not consistent). An earlier test had the log record two presses, though it was only pressed once, but with the same lack of detail.

That said, the Ring app only ever registers one press and only sends one alert.

This behaviour has been observed in the 11.0, 11.0.1, and 11.0.2 versions of the plugin; all software is currently fully up to date.

### Environment

- OS: Raspbian 11 (Bullseye)
- Node.js: 16.15.0
- NPM: 8.10.0
- homebridge-ring: 11.0.2
- homebridge: 1.4.1
- hoobs: 4.2.5

**Comment by dgreif** [comment] 2022-05-27 04:48
@nashnix that line is what I was looking for from the logs.  Big question - does that line show _twice_ when you press the button once?

**Comment by nashnix** [comment] 2022-05-27 08:25
Sorry @dgreif - but that line only appears in the log once. I have found is that the iPhone sends two alerts; once just a simple "Someone rang the doorbell", once with "Someone is at your door" and a captured still from the camera.

I tried turning off - in the ring app - the capturing of the snapshots to see if that would fix it. Still got the double chime on the homepods (again, not in sync), and double ping on the home app, though now it's just two "Someone is at your door" notifications".

I repeated this with `"debug": true` set to see if I could get the log to yield more information - nothing else appeared in the HomeBridge log I'm afraid.

But; a few months ago I got frustrated with the Home app and got ControllerForHomeKit, which logs HomeKit events, and I've just pulled the logs from that to see if there was more information there. For each one press of the doorbell the logs look like this:

![ControllerForHomeKit - log screencap](https://user-images.githubusercontent.com/104119201/170660212-2874fed6-66a3-4c70-8538-db93aa2eb27a.png)

The bell symbol is called "Doorbell" in the log exports, and the other one is a "Stateless Programmable Switch". The log is in reverse chronological order; the Doorbell event comes first, the Stateless Programmable Switch event comes second. For each press of the physical button, there's two pairs of events being registered in HomeKit - which seems to translate to HomeKit thinking the doorbell is being double-pressed.

In this screencap, it's registered them as being in the same second - 18:05:26 - which is one second after it shows up in the HomeBridge log (18:05:25). An earlier test had the two pairs appear a second apart though.

**Comment by theimo1221** [comment] 2022-06-02 16:37
> Mine was doing this until the latest version. It no longer sends any notifications now...

So it's not just me recieving no notifications....

Subscribing to `onMotionDetected` I get an initial `false` and then nothing after that. Same for `onNewNotification`.

But `onData` is triggered frequently so there still is a connection.

**Comment by nashnix** [comment] 2022-06-16 05:29
@dgreif I'm happy, albeit puzzled, to report that as of the update to v11.0.5, the behaviour seems to have stopped. I did initially avoid updating from 11.0.2 until now because of the report from @jedis00 and @theimo1221 - but forgot about that and ordered the homebridge to update everything and, well, there you go.

I'm puzzled because it's noticeably slower than it used to be - I get the notification from the Ring app up to five seconds before the HomePods chime, with the notification on the HomeKit app coming in between. A reboot of devices, including network, doesn't seem to alter this. But maybe that's just while it's sorting itself out and it'll be good in a few days.

But that's all a side issue; mostly I'm happy now because the intensely irritating multiple chimes-out-of-sync-with-each-other bug seems to have been squished, and that was the important thing.

**Comment by dgreif** [comment] 2022-06-17 16:16
@podycust are you still seeing this issue after the latest update?  It's also possible that Apple made some changes on the homepod to only have it ding once

**Comment by podycust** [comment] 2022-06-20 09:17
@dgreif Hi yes am still getting the same issue. my HomePods/ iOS devices are all running the latest software.

I get this in the log when the doorbell is pressed..
[19/06/2022, 16:18:17] [Ring] Front Door Doorbell Pressed
[19/06/2022, 16:18:19] [Ring] Front Door Doorbell Pressed. Loading snapshot before sending event to HomeKit

**Comment by nashnix** [comment] 2022-06-20 09:20
@dgreif Bad news. As of a minute ago, the double ring is back :(

**Comment by alexlewer** [comment] 2022-06-21 22:46
Same here.

**Comment by nashnix** [comment] 2022-07-17 02:28
Hi @dgreif,

Hope you've been well. I'm just checking in because I had a homebridge upset a few days ago and ended up having to go the radical route of wiping the SD card and reinstalling everything. It occurred to me that maybe something funny had arisen in the old setup, and that could be the cause, so I did a test of things again, with the debug logging active (and controller for HomeKit collecting logs there too) to try to catch as much info as I could.

In a word; inconsistent.

Here's what I found:
1. Controller for HomeKit is sometimes recording multiple "Single Press" incidents of the doorbell for just one physical press of the actual button, and sometimes only records one. These appear to have no relation how many times the chimes are heard.
2. In all cases, this line (with differing timestamps of course) appears **once** in the HomeBridge logs:

> 17/07/2022, 12:07:09 pm _Ring Bridge_ **Ring** Front Door Doorbell Pressed

3. Sometimes the HomePods chime twice (always out of sync with each other), other times they chime once (in perfect sync).
4. When the HomePods chime twice, the Home App on my iPhone sends multiple alerts, but when they chime once it only sends one alert.
5. The Ring App records only one Ring instance for each physical press of the button.
6. The Ring App only sends one alert.
7. Whether the HomePods are playing music or not doesn't affect how many times the chime happens.

There was no heavy network traffic at the time (i.e., nothing downloading, streaming, or having an in-depth conversation with anything else).

So; sometimes it behaves as expected and desired, sometimes it decides to sing to me the song of its people.

### Environment
- OS: Raspbian 11 (Bullseye)
- Node.js: 16.16.0
- NPM: 8.11.0
- homebridge-ring: 11.0.7
- homebridge: 1.4.1
- hoobs: 4.2.5

Ring is running on a child bridge, and the advertiser is Ciao (it was Bonjour previously, but I took advantage of the wipe to migrate everything up).

**Comment by podycust** [comment] 2022-07-18 09:26
it might worth adding on my iPhone and iPad I also get two notifications.

**Comment by dgreif** [comment] 2022-08-27 17:04
I think this all comes down to the Push Notifications that I added in v11. I think the solution is to go back to polling for dings, but use push notifications as a trigger to pull dings _immediately_, and also stash the associated snapshot. This is how I plan to fix #933, but is should fix the double ding as well. I'm going to close this issue, and you can subscribe to #933 to follow progress on that fix. I'm not sure exactly when I'll get to it, but I appreciate your patience so far!

**Closed** 2022-08-27 17:04 UTC
Labels: bug

**Comment by dgreif** [comment] 2022-08-28 16:44
After looking into it more, I decided to add a fix specifically for double ding notifications for now. I still may refactor how notifications are handled in general, but this was an easy fix to get in now. Basically I just void sending more than 1 ding every 15 seconds. Give v 11.2.1 a try and let me know how it works for you!
