### ISSUE TITLE
Error Loading Homebridge-Ring plugin on Hoobs

### ISSUE THREAD

**Issue by darthgrogu9510** [dgreif/ring#1367] opened 2023-11-24 02:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When I updated my Ring plugin on Hoobs to 12.0.1, none of my cameras would load. Looking in the log, every time the bridge starts, I receive an "ERROR loading plugin "homebridge-ring" I have uninstalled, reinstalled, tried previous versions, and even did a factory reset on Hoobs, but I continue getting the same error.

### To Reproduce

Updated to 12.0.1

### Expected behavior

Load plugin and pull camera feeds to Hoobs

### Screenshots

![Screenshot 2023-11-23 at 9 07 02 PM](https://github.com/dgreif/ring/assets/151892910/4dc6933f-b4a9-4e2a-83c2-e108260a64b8)

### Homebridge Ring Config

```shell
Everything is left as default
```

### OS

Rasbian (Hoobs)

### Node.js Version

16.20.2

### NPM Version

unknown

### Homebridge/HOOBs Version

1.6/4.3

### Homebridge Ring Plugin Version

12.0.1

### Operating System

Rasbian

**Comment by tsightler** [comment] 2023-11-24 02:50
Most likely you will need to contact HOOBS support.  One thing, the plugin no longer officially supports NodeJS 16, so you may need to update your node version.  You should be able to click the bug icon in the HOOBS log UI to get more information as there's nothing actionable in that log.

**Comment by Hinder6** [comment] 2023-11-29 03:18
I'm having a similar issue. Plugin stopped working as soon as I updated and the error message I get is "Ring xxxxx is offline or on cellular backup.  Waiting for status to change"

**Comment by tsightler** [comment] 2023-11-29 03:34
> I'm having a similar issue. Plugin stopped working as soon as I updated and the error message I get is "Ring xxxxx is offline or on cellular backup. Waiting for status to change"

I'm not sure how this could be classified as a similar issue when the message is completely different, clearly the plugin is loading in your case.  I would ask in the future that you please not mix unrelated issues.

You need to check in the Ring app and verify that there are no offline devices on any account the plugin has access to, otherwise the plugin will wait for the device to come online.  You almost certainly have some offline device as that's what causes this message.

**Comment by Hinder6** [comment] 2023-11-29 03:56
My apologies. I actually read his original error message wrong.

Also, I already checked my ring app and all devices are online and working correctly. It's only the plugin that is showing the error which is confusing the hell out of me. The only change that has happened recently was the update to 12.0.1. Coincidently, it gave me the error as soon as the bridge rebooted from the update.

**Comment by tsightler** [comment] 2023-11-29 04:07
@Hinder6 That message is from ring-client-api and the logic in that part of the code is unchanged for probably 5 years.  I've seen it reported dozens of times here and in the ring-mqtt project and it is always caused by an device offline because that's what the code that produces that message checks for.  The "xxxx" is the ID of the device in question so it should be pretty easy to figure out which one.  I would ask that you please check thoroughly with the Ring app and web UI and be sure to check all shared locations and devices, including any smart lighting or anything else.

I'm going to close this issue because this is off-topic and the OP has not replied further.  You can open a new issue and provide complete logs if you need additional help.

**Closed by tsightler** 2023-11-29 04:07 UTC
Labels: bug
