### ISSUE TITLE
sip INVITE request failed with status 503 when streaming live feed from home app if Ring Edge feature is enabled on cameras

### ISSUE THREAD

**Issue by adrianguanipa** [dgreif/ring#830] opened 2021-12-02 15:57 UTC
# Bug Report

### Describe the Bug
This plugin was working fine until recently, the cameras are operating normally, I can open them with no issues from the Ring's app, but from HomeKit is a different story. The Camera Snapshots are working in the Home app, but when opening the live feed on one of the cameras from any of my Apple devices I get a no response and this error in the log.

The only thing that changed recently in my network is that I switched from the first-gen Ring Alarm Base Station to the all-new Ring Alarm Pro which has the option to store the camera recordings locally. I did try turning this feature off temporarily to see if it would make a difference, but nothing, the error persists. All Apple devices are on the latest versions and have been rebooted. I did also removed the plugin from HomeBridge and installed and authenticated it again with the same result. HomeBridge and plugins are running the latest versions too.

Can someone offer some help, please?

Thank you.

### To Reproduce
 - Start Homebridge
 - You'll need to use the new Ring Edge feature, for this go to the new Ring Pro Alarm settings in the Ring app (Pro Plan is required to use the Ring Edge feature) and Enrolled Cameras and enable all Ring cameras.
 - Reopen the Home app and try to launch a live feed from one of the cameras, if the Ring Edge feature is enabled on all cameras, then the live feeds on the Home app works as expected.

### Expected behavior
Camera live feeds should open.

### Screenshots/Logs
![image](https://user-images.githubusercontent.com/64798434/144454912-3f5f3e2c-f54b-4b34-8299-b52b59752f67.png)

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

        {
            "refreshToken": "XXXXXXXXXXXXXXXXXXX",
            "hideInHomeDoorbellSwitch": true,
            "hideUnsupportedServices": true,
            "platform": "Ring"
        }

```

### Environment
 - OS: Raspbian
 - Node.js: v14.17.1
 - NPM: v7.17.0
 - homebridge-ring: v9.23.0
 - homebridge: v4.41.3

**Comment by adrianguanipa** [comment] 2021-12-02 17:24
So it seems the issue is in fact related to the new Ring Edge Storage feature, I just tried turning the new recording feature off on all cameras instead of just one camera which is what I've tried before. Please let me know if you need additional details to fix this, in the meantime I'll keep the local recording option off for now, since the new Ring Alarm Pro (with eero 6 Built-in) was just released not long ago it may be the reason why you don't see many reports of this issue.

**Comment by dgreif** [comment] 2021-12-02 19:52
Duplicate of #818.  I now have a Ring Alarm Pro and have looked into it a little bit, but it's going to require a lot of work to get it functioning.  Keep an eye on that other issue for updates, no promises on when/if I'll make it happen

**Closed by dgreif** 2021-12-02 19:52 UTC
Labels: bug

**Comment by adrianguanipa** [comment] 2021-12-02 20:16
Thank you. @dgreif
