### ISSUE TITLE
Snapshots in Home app not updating

### ISSUE THREAD

**Issue by SlasherKG** [dgreif/ring#1342] opened 2023-10-27 15:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Snapshots are not updating in the Home app on my iPhone 15 Pro Max running iOS 17.1.
If I click the camera to activate a live stream, once I exit the snapshot is updated at that moment, but never afterward still.

### To Reproduce

Open Home app and view camera list.

### Expected behavior

Snapshots should update.

### Relevant log output

```shell
[10/27/2023, 9:41:31 AM] [Ring] No snapshot cached for Garage
[10/27/2023, 9:41:31 AM] [Ring] Loading new snapshot into cache for Garage
[10/27/2023, 9:41:31 AM] [Ring] No snapshot cached for Storage Room
[10/27/2023, 9:41:31 AM] [Ring] Loading new snapshot into cache for Storage Room
[10/27/2023, 9:41:31 AM] [Ring] No snapshot cached for Kitchen
[10/27/2023, 9:41:31 AM] [Ring] Loading new snapshot into cache for Kitchen
[10/27/2023, 9:41:31 AM] [Ring] No snapshot cached for Living Room
[10/27/2023, 9:41:31 AM] [Ring] Loading new snapshot into cache for Living Room
[10/27/2023, 9:41:31 AM] [Ring] No snapshot cached for Dining Room
[10/27/2023, 9:41:31 AM] [Ring] Loading new snapshot into cache for Dining Room
[10/27/2023, 9:41:32 AM] [Ring] Snapshot cached for Storage Room (0.674s)
[10/27/2023, 9:41:32 AM] [Ring] Snapshot cached for Living Room (0.607s)
[10/27/2023, 9:41:32 AM] [Ring] Snapshot cached for Garage (0.794s)
[10/27/2023, 9:41:32 AM] [Ring] Snapshot cached for Kitchen (0.84s)
[10/27/2023, 9:41:32 AM] [Ring] Snapshot cached for Dining Room (0.725s)
[10/27/2023, 9:41:33 AM] [Ring] No snapshot cached for Front Door
[10/27/2023, 9:41:33 AM] [Ring] Loading new snapshot into cache for Front Door
[10/27/2023, 9:41:33 AM] [Ring] Snapshot cached for Front Door (0.284s)
[10/27/2023, 9:41:41 AM] [Ring] Used cached snapshot for Garage
[10/27/2023, 9:41:41 AM] [Ring] Loading new snapshot into cache for Garage
[10/27/2023, 9:41:41 AM] [Ring] Used cached snapshot for Storage Room
[10/27/2023, 9:41:41 AM] [Ring] Loading new snapshot into cache for Storage Room
[10/27/2023, 9:41:41 AM] [Ring] Used cached snapshot for Kitchen
[10/27/2023, 9:41:41 AM] [Ring] Loading new snapshot into cache for Kitchen
[10/27/2023, 9:41:42 AM] [Ring] Snapshot cached for Garage (0.546s)
[10/27/2023, 9:41:42 AM] [Ring] Snapshot cached for Storage Room (0.593s)
[10/27/2023, 9:41:42 AM] [Ring] Snapshot cached for Kitchen (0.591s)
[10/27/2023, 9:41:43 AM] [Ring] Used cached snapshot for Front Door
[10/27/2023, 9:41:43 AM] [Ring] Loading new snapshot into cache for Front Door
[10/27/2023, 9:41:44 AM] [Ring] Snapshot cached for Front Door (0.42s)
[10/27/2023, 9:41:46 AM] [Ring] Front Door Detected Motion. Loading snapshot before sending event to HomeKit
[10/27/2023, 9:41:46 AM] [Ring] Loading new snapshot into cache for Front Door by uuid
[10/27/2023, 9:41:47 AM] [Ring] Snapshot cached for Front Door by uuid (0.406s)
[10/27/2023, 9:41:58 AM] [Ring] Used cached snapshot for Dining Room
[10/27/2023, 9:41:58 AM] [Ring] Loading new snapshot into cache for Dining Room
[10/27/2023, 9:41:58 AM] [Ring] Used cached snapshot for Living Room
[10/27/2023, 9:41:58 AM] [Ring] Loading new snapshot into cache for Living Room
[10/27/2023, 9:41:58 AM] [Ring] No snapshot cached for Office
[10/27/2023, 9:41:58 AM] [Ring] Loading new snapshot into cache for Office
[10/27/2023, 9:41:59 AM] [Ring] No snapshot cached for Cat Room
[10/27/2023, 9:41:59 AM] [Ring] Loading new snapshot into cache for Cat Room
[10/27/2023, 9:41:59 AM] [Ring] Snapshot cached for Living Room (0.425s)
[10/27/2023, 9:41:59 AM] [Ring] Snapshot cached for Dining Room (0.542s)
[10/27/2023, 9:41:59 AM] [Ring] Snapshot cached for Office (0.749s)
[10/27/2023, 9:42:00 AM] [Ring] Snapshot cached for Cat Room (1.13s)
[10/27/2023, 9:42:00 AM] [Ring] Cat Room Detected Motion. Loading snapshot before sending event to HomeKit
[10/27/2023, 9:42:00 AM] [Ring] Loading new snapshot into cache for Cat Room by uuid
[10/27/2023, 9:42:00 AM] [Ring] Snapshot for Cat Room is still within its life time (0.699s old)
[10/27/2023, 9:42:00 AM] [Ring] Snapshot cached for Cat Room by uuid (0.004s)
[10/27/2023, 9:42:02 AM] [Ring] Used cached snapshot for Kitchen
[10/27/2023, 9:42:02 AM] [Ring] Loading new snapshot into cache for Kitchen
[10/27/2023, 9:42:03 AM] [Ring] Snapshot cached for Kitchen (0.232s)
[10/27/2023, 9:42:03 AM] [Ring] Living Room Detected Motion. Loading snapshot before sending event to HomeKit
[10/27/2023, 9:42:03 AM] [Ring] Loading new snapshot into cache for Living Room by uuid
[10/27/2023, 9:42:03 AM] [Ring] Kitchen Detected Motion. Loading snapshot before sending event to HomeKit
[10/27/2023, 9:42:03 AM] [Ring] Loading new snapshot into cache for Kitchen by uuid
[10/27/2023, 9:42:04 AM] [Ring] Snapshot cached for Living Room by uuid (0.432s)
[10/27/2023, 9:42:04 AM] [Ring] Snapshot cached for Kitchen by uuid (0.394s)
[10/27/2023, 9:42:09 AM] [Ring] Used cached snapshot for Office
[10/27/2023, 9:42:09 AM] [Ring] Loading new snapshot into cache for Office
[10/27/2023, 9:42:09 AM] [Ring] Used cached snapshot for Cat Room
[10/27/2023, 9:42:09 AM] [Ring] Used cached snapshot for Dining Room
[10/27/2023, 9:42:09 AM] [Ring] Loading new snapshot into cache for Dining Room
[10/27/2023, 9:42:09 AM] [Ring] Used cached snapshot for Living Room
[10/27/2023, 9:42:10 AM] [Ring] Snapshot cached for Office (0.646s)
[10/27/2023, 9:42:10 AM] [Ring] Snapshot cached for Dining Room (0.764s)
[10/27/2023, 9:42:39 AM] [Ring] Dining Room Detected Motion. Loading snapshot before sending event to HomeKit
[10/27/2023, 9:42:39 AM] [Ring] Loading new snapshot into cache for Dining Room by uuid
[10/27/2023, 9:42:39 AM] [Ring] Snapshot cached for Dining Room by uuid (0.689s)
[10/27/2023, 9:43:35 AM] [Ring] Used cached snapshot for Office
[10/27/2023, 9:43:35 AM] [Ring] Loading new snapshot into cache for Office
[10/27/2023, 9:43:35 AM] [Ring] Used cached snapshot for Kitchen
[10/27/2023, 9:43:35 AM] [Ring] Loading new snapshot into cache for Kitchen
[10/27/2023, 9:43:35 AM] [Ring] Used cached snapshot for Cat Room
[10/27/2023, 9:43:35 AM] [Ring] Loading new snapshot into cache for Cat Room
[10/27/2023, 9:43:35 AM] [Ring] Used cached snapshot for Living Room
[10/27/2023, 9:43:35 AM] [Ring] Loading new snapshot into cache for Living Room
[10/27/2023, 9:43:35 AM] [Ring] Used cached snapshot for Dining Room
[10/27/2023, 9:43:35 AM] [Ring] Loading new snapshot into cache for Dining Room
[10/27/2023, 9:43:35 AM] [Ring] Snapshot cached for Kitchen (0.428s)
[10/27/2023, 9:43:35 AM] [Ring] Snapshot cached for Living Room (0.618s)
[10/27/2023, 9:43:36 AM] [Ring] Snapshot cached for Office (0.799s)
[10/27/2023, 9:43:36 AM] [Ring] Snapshot cached for Dining Room (1.151s)
[10/27/2023, 9:43:36 AM] [Ring] Used cached snapshot for Garage
[10/27/2023, 9:43:36 AM] [Ring] Loading new snapshot into cache for Garage
[10/27/2023, 9:43:36 AM] [Ring] Used cached snapshot for Storage Room
[10/27/2023, 9:43:36 AM] [Ring] Loading new snapshot into cache for Storage Room
[10/27/2023, 9:43:36 AM] [Ring] Used cached snapshot for Front Door
[10/27/2023, 9:43:36 AM] [Ring] Loading new snapshot into cache for Front Door
[10/27/2023, 9:43:36 AM] [Ring] Snapshot cached for Storage Room (0.238s)
[10/27/2023, 9:43:36 AM] [Ring] Snapshot cached for Front Door (0.246s)
[10/27/2023, 9:43:36 AM] [Ring] Snapshot cached for Garage (0.466s)
[10/27/2023, 9:43:37 AM] [Ring] Snapshot cached for Cat Room (1.78s)
[10/27/2023, 9:43:39 AM] [Ring] Used cached snapshot for Kitchen
[10/27/2023, 9:43:39 AM] [Ring] Loading new snapshot into cache for Kitchen
[10/27/2023, 9:43:39 AM] [Ring] Snapshot cached for Kitchen (0.204s)
[10/27/2023, 9:43:47 AM] [Ring] Used cached snapshot for Garage
[10/27/2023, 9:43:47 AM] [Ring] Loading new snapshot into cache for Garage
[10/27/2023, 9:43:47 AM] [Ring] Used cached snapshot for Storage Room
[10/27/2023, 9:43:47 AM] [Ring] Loading new snapshot into cache for Storage Room
[10/27/2023, 9:43:47 AM] [Ring] Used cached snapshot for Front Door
[10/27/2023, 9:43:47 AM] [Ring] Loading new snapshot into cache for Front Door
[10/27/2023, 9:43:48 AM] [Ring] Snapshot cached for Front Door (0.525s)
[10/27/2023, 9:43:48 AM] [Ring] Snapshot cached for Garage (0.775s)
[10/27/2023, 9:43:48 AM] [Ring] Snapshot cached for Storage Room (0.813s)
[10/27/2023, 9:43:50 AM] [Ring] Used cached snapshot for Kitchen
[10/27/2023, 9:43:50 AM] [Ring] Loading new snapshot into cache for Kitchen
[10/27/2023, 9:43:50 AM] [Ring] Snapshot cached for Kitchen (0.819s)
[10/27/2023, 9:44:47 AM] [Ring] Front Door Detected Motion. Loading snapshot before sending event to HomeKit
[10/27/2023, 9:44:47 AM] [Ring] Loading new snapshot into cache for Front Door by uuid
[10/27/2023, 9:44:48 AM] [Ring] Snapshot cached for Front Door by uuid (0.603s)
```

### Screenshots

![IMG_8988](https://github.com/dgreif/ring/assets/11238501/fad0d715-de9f-4cd4-b945-2455be6ea3ff)

### Homebridge Ring Config

```shell
{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51075,
        "pin": "XXX-XX-XXX",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode-blue",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "refreshToken": "<REDACTED>",
            "hideDoorbellSwitch": true,
            "hideCameraLight": true,
            "debug": true,
            "hideDeviceIds": [
                "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
                "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
                "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
            ],
            "name": "Ring",
            "_bridge": {
                "username": "XX:XX:XX:XX:XX:XX",
                "port": 59886
            },
            "platform": "Ring"
        }
    ],
    "disabledPlugins": [
        "homebridge-litter-robot-connect"
    ]
}
```

### Additional context

I've tried restarting my apple TV hub, restarting homebridge, changing the mDNS Advertiser and even deleting a camera and re-adding it back but it still won't update automatically in the Home app.

### OS

Raspbian

### Node.js Version

20.9.0

### NPM Version

10.1.0

### Homebridge/HOOBs Version

1.6.1

### Homebridge Ring Plugin Version

12.0.1

### Operating System

Raspbian (Debian GNU/Linux Bullseye (11))

**Comment by tsightler** [comment] 2023-10-27 20:29
I don't think there is anything that can be done about this from the plugin side.  In the end, it is up to the Home app to request and display snapshots, this plugin simply provides a function which Homekit calls when a snapshot but the plugin has no control over how often Homekit requests a snapshot, or what it does with it.  Unless the function is failing, there's not much that can be done and the logs appear to show that everything is working as expected on the plugin side, so you will most likely have to look elsewhere.  Since you say this is with iOS 17.1, it could be yet another new bug with Homekit as that is what 95% of these issues turn out to be.

I will double check this weekend to see if the issue is noticed on my iOS 17.1 devices but, historically, these issues are related to network or Homekit/Homebridge vs anything in the plugin.

**Comment by SlasherKG** [comment] 2023-10-27 22:05
OK, thank you.
I kind of figured that would be the case, but thought it was worth submitting just in case.

Hopefully it can be resolved at some point whichever end.

Thank you for all your hard work on this plug-in.

**Comment by SlasherKG** [comment] 2023-10-29 02:21
So I did some more troubleshooting and found when I was at home it was updating normally but not remotely.
I rebooted my router, appletv and homebridge and it seems to be working remotely now as well so who knows.

Thanks again.

**Comment by tsightler** [comment] 2023-10-29 02:26
No big surprise, as I mentioned, snapshots are always controlled by Homekit.  Will close this now.

**Closed by tsightler** 2023-10-29 02:26 UTC
Labels: bug
