### ISSUE TITLE
Ring Doorbell no longer responding

### ISSUE THREAD

**Issue by thesteev** [dgreif/ring#326] opened 2020-05-19 01:46 UTC
# Bug Report

### Describe the Bug
Upgraded from 8.1.0 to 8.2.0 and Doorbell camera became unresponsive in Home app

### To Reproduce
 - Start Homebridge
 - Upgraded to 8.2.0
 - Restared Homebridge
 - Opened Home App
 - Noticed camera became unresponsive. 

### Expected behavior
Expected the camera to be active after upgrade. 

### Homebridge Ring Config

        {
            "refreshToken": "...",
            "locationIds": [
                "..."
            ],
            "platform": "Ring"
        },

### Environment
 - OS: Raspbian GNU/Linux Stretch (9)
 - Node.js: v12.16.2
 - NPM: v6.14.4
 - homebridge-ring: 8.2.0
 - homebridge: 1.1.0

**Comment by lherlitz** [comment] 2020-05-20 03:23
`5/19/2020, 11:22:19 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Trying again in 5 seconds...`

**Comment by dgreif** [comment] 2020-05-20 17:41
Duplicate of #325

**Closed by dgreif** 2020-05-20 17:41 UTC
Labels: bug, duplicate
