### ISSUE TITLE
Streaming in HomeKit on iPhone/iPad

### ISSUE THREAD

**Issue by Poldone** [dgreif/ring#1371] opened 2023-12-02 09:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Requesting live view for Cameras on iPhone, after a while return a Camera disconnected error, but the preview is correctly working

### Expected behavior

live streaming correctly showing

### Relevant log output

```shell
2/12/2023, 10:42:25Ring BridgeRingStreaming active for Cancellino (3.921s)
2/12/2023, 10:42:26Ring BridgeRingiceConnectionStateChange: new
2/12/2023, 10:42:26Ring BridgeRingiceConnectionStateChange: connected
2/12/2023, 10:42:26Ring BridgeRingFrom Ring (Cancellino): [udp @ 0xb6f68f60] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[udp @ 0xb6f68ec0] attempted to set receive buffer to size 393216 but it only ended up set as 360448
2/12/2023, 10:42:26Ring BridgeRingReturn Audio (Cancellino): [udp @ 0xb6f13f50] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[udp @ 0xb6f13eb0] attempted to set receive buffer to size 393216 but it only ended up set as 360448
2/12/2023, 10:42:27Ring BridgeRingconnectionStateChange: connected
2/12/2023, 10:42:27Ring BridgeRingreceived first audio packet
2/12/2023, 10:42:27Ring BridgeRingFrom Ring (Cancellino): Input #0, sdp, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: opus, 48000 Hz, stereo, s16
Stream mapping:
  Stream #0:0 -> #0:0 (opus (libopus) -> aac (libfdk_aac))
Output #0, rtp, to 'rtp://127.0.0.1:41545?pkt_size=376':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Audio: aac (ELD), 16000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc60.3.100 libfdk_aac
size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
2/12/2023, 10:42:27Ring BridgeRingReceived stream data from Cancellino (5.636s)
2/12/2023, 10:42:27Ring BridgeRingreceived first video packet
2/12/2023, 10:42:28Ring BridgeRingFrom Ring (Cancellino): size=       4kB time=00:00:01.19 bitrate=  27.2kbits/s speed=1.93x    
2/12/2023, 10:42:28Ring BridgeRingFrom Ring (Cancellino): size=       6kB time=00:00:01.87 bitrate=  26.4kbits/s speed=1.53x    
2/12/2023, 10:42:29Ring BridgeRingFrom Ring (Cancellino): size=       8kB time=00:00:02.47 bitrate=  26.7kbits/s speed=1.37x    
2/12/2023, 10:42:30Ring BridgeRingFrom Ring (Cancellino): size=      10kB time=00:00:03.05 bitrate=  26.1kbits/s speed=1.04x    
2/12/2023, 10:42:31Ring BridgeRingFrom Ring (Cancellino): size=      11kB time=00:00:03.34 bitrate=  26.3kbits/s speed=0.927x    
2/12/2023, 10:42:31Ring BridgeRingFrom Ring (Cancellino): size=      11kB time=00:00:03.53 bitrate=  26.3kbits/s speed=0.858x    
2/12/2023, 10:42:32Ring BridgeRingFrom Ring (Cancellino): size=      12kB time=00:00:03.69 bitrate=  26.5kbits/s speed=0.792x    
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 6 packets
2/12/2023, 10:42:32Ring BridgeRingFrom Ring (Cancellino): [sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 2 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 2 packets
size=      15kB time=00:00:04.66 bitrate=  25.7kbits/s speed=0.901x    
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 2 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 3 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 2 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 3 packets
size=      19kB time=00:00:06.33 bitrate=  24.3kbits/s speed=1.11x    
2/12/2023, 10:42:33Ring BridgeRingFrom Ring (Cancellino): size=      21kB time=00:00:06.90 bitrate=  24.7kbits/s speed=1.09x    
2/12/2023, 10:42:34Ring BridgeRingFrom Ring (Cancellino): size=      23kB time=00:00:07.64 bitrate=  24.7kbits/s speed=1.12x    
2/12/2023, 10:42:35Ring BridgeRingFrom Ring (Cancellino): size=      25kB time=00:00:08.15 bitrate=  24.8kbits/s speed=1.08x    
2/12/2023, 10:42:35Ring BridgeRingFrom Ring (Cancellino): size=      27kB time=00:00:08.73 bitrate=  24.9kbits/s speed=1.07x    
2/12/2023, 10:42:36Ring BridgeRingFrom Ring (Cancellino): size=      29kB time=00:00:09.40 bitrate=  25.1kbits/s speed=1.08x    
2/12/2023, 10:42:36Ring BridgeRingReturn Audio (Cancellino): Input #0, sdp, from 'pipe:':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: N/A
  Stream #0:0: Audio: aac, 16000 Hz, mono, s16
Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> opus (libopus))
2/12/2023, 10:42:36Ring BridgeRingFrom Ring (Cancellino): size=      31kB time=00:00:10.04 bitrate=  25.0kbits/s speed=1.08x    
2/12/2023, 10:42:37Ring BridgeRingFrom Ring (Cancellino): size=      33kB time=00:00:10.61 bitrate=  25.1kbits/s speed=1.07x    
2/12/2023, 10:42:38Ring BridgeRingFrom Ring (Cancellino): size=      35kB time=00:00:11.25 bitrate=  25.3kbits/s speed=1.07x    
2/12/2023, 10:42:38Ring BridgeRingFrom Ring (Cancellino): size=      37kB time=00:00:11.89 bitrate=  25.4kbits/s speed=1.07x    
2/12/2023, 10:42:39Ring BridgeRingFrom Ring (Cancellino): size=      39kB time=00:00:12.53 bitrate=  25.4kbits/s speed=1.05x    
2/12/2023, 10:42:40Ring BridgeRingFrom Ring (Cancellino): size=      41kB time=00:00:13.30 bitrate=  25.5kbits/s speed=1.05x    
2/12/2023, 10:42:40Ring BridgeRingFrom Ring (Cancellino): size=      44kB time=00:00:14.04 bitrate=  25.4kbits/s speed=1.05x    
2/12/2023, 10:42:41Ring BridgeRingFrom Ring (Cancellino): size=      45kB time=00:00:14.58 bitrate=  25.4kbits/s speed=1.05x    
2/12/2023, 10:42:41Ring BridgeRingFrom Ring (Cancellino): size=      47kB time=00:00:15.00 bitrate=  25.5kbits/s speed=1.04x    
2/12/2023, 10:42:42Ring BridgeRingFrom Ring (Cancellino): size=      49kB time=00:00:15.73 bitrate=  25.5kbits/s speed=1.04x    
2/12/2023, 10:42:43Ring BridgeRingFrom Ring (Cancellino): [sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
size=      51kB time=00:00:16.21 bitrate=  25.6kbits/s speed=1.03x    
2/12/2023, 10:42:44Ring BridgeRingFrom Ring (Cancellino): size=      53kB time=00:00:17.10 bitrate=  25.5kbits/s speed=1.03x    
2/12/2023, 10:42:44Ring BridgeRingFrom Ring (Cancellino): size=      56kB time=00:00:17.96 bitrate=  25.6kbits/s speed=1.04x    
2/12/2023, 10:42:45Ring BridgeRingFrom Ring (Cancellino): [sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
2/12/2023, 10:42:45Ring BridgeRingFrom Ring (Cancellino): size=      58kB time=00:00:18.69 bitrate=  25.6kbits/s speed=1.03x    
2/12/2023, 10:42:46Ring BridgeRingFrom Ring (Cancellino): size=      59kB time=00:00:19.01 bitrate=  25.6kbits/s speed=1.02x    
2/12/2023, 10:42:46Ring BridgeRingReturn Audio (Cancellino): Error demuxing input file 0: Operation timed out
pipe:: Operation timed out
Output #0, rtp, to 'rtp://127.0.0.1:33888':
  Metadata:
    title           : Talk
    encoder         : Lavf60.3.100
  Stream #0:0: Audio: opus, 24000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc60.3.100 libopus
size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
2/12/2023, 10:42:46Ring BridgeRingFrom Ring (Cancellino): size=      63kB time=00:00:20.03 bitrate=  25.6kbits/s speed=1.04x    
2/12/2023, 10:42:46Ring BridgeRingReturn Audio (Cancellino): stopped gracefully
2/12/2023, 10:42:47Ring BridgeRingFrom Ring (Cancellino): size=      65kB time=00:00:20.57 bitrate=  25.7kbits/s speed=1.03x    
2/12/2023, 10:42:47Ring BridgeRingFrom Ring (Cancellino): size=      67kB time=00:00:21.34 bitrate=  25.7kbits/s speed=1.04x    
2/12/2023, 10:42:48Ring BridgeRingFrom Ring (Cancellino): size=      68kB time=00:00:21.66 bitrate=  25.7kbits/s speed=1.02x    
2/12/2023, 10:42:49Ring BridgeRingFrom Ring (Cancellino): size=      69kB time=00:00:22.01 bitrate=  25.7kbits/s speed=0.987x    
2/12/2023, 10:42:49Ring BridgeRingFrom Ring (Cancellino): [sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 18 packets
2/12/2023, 10:42:51Ring BridgeRingFrom Ring (Cancellino): size=      69kB time=00:00:22.47 bitrate=  25.3kbits/s speed=0.95x    
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 6 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
size=      70kB time=00:00:22.73 bitrate=  25.3kbits/s speed=0.939x    
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 4 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 2 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 2 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 3 packets
2/12/2023, 10:42:52Ring BridgeRingFrom Ring (Cancellino): [sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 3 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 3 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 2 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 4 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 6 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
[sdp @ 0xb6f7ac20] max delay reached. need to consume packet
[sdp @ 0xb6f7ac20] RTP: missed 1 packets
size=      75kB time=00:00:24.87 bitrate=  24.6kbits/s speed=1.01x    
2/12/2023, 10:42:52Ring BridgeRingFrom Ring (Cancellino): size=      78kB time=00:00:26.02 bitrate=  24.7kbits/s speed=1.03x    
2/12/2023, 10:42:53Ring BridgeRingFrom Ring (Cancellino): size=      80kB time=00:00:26.50 bitrate=  24.6kbits/s speed=1.03x    
2/12/2023, 10:42:53Ring BridgeRingFrom Ring (Cancellino): size=      81kB time=00:00:27.01 bitrate=  24.7kbits/s speed=1.03x    
2/12/2023, 10:42:54Ring BridgeRingFrom Ring (Cancellino): size=      84kB time=00:00:27.72 bitrate=  24.7kbits/s speed=1.03x    
2/12/2023, 10:42:54Ring BridgeRingStopped Live Stream for Cancellino
2/12/2023, 10:42:54Ring BridgeRingconnectionStateChange: closed
2/12/2023, 10:42:54Ring BridgeRingiceConnectionStateChange: closed
2/12/2023, 10:43:04Ring BridgeRingFrom Ring (Cancellino): stopped gracefully
2/12/2023, 10:43:04Ring BridgeRingFrom Ring (Cancellino): Error demuxing input file 0: Operation timed out
pipe:: Operation timed out
2/12/2023, 10:43:04Ring BridgeRingFrom Ring (Cancellino): size=      85kB time=00:00:28.07 bitrate=  24.8kbits/s speed=0.755x    
video:0kB audio:78kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 9.319956%
2/12/2023, 10:43:04Ring BridgeRingFrom Ring (Cancellino): Exiting normally, received signal 15.
```

### Homebridge Ring Config

```shell
"platform": "Ring",
    "refreshToken": "***",
    "nightModeBypassFor": "some",
    "cameraDingsPollingSeconds": 2,
    "cameraStatusPollingSeconds": 20,
    "locationModePollingSeconds": 0,
    "hideUnsupportedServices": true,
    "debug": true
```

### OS

Hoobs Box

### Node.js Version

hoobs box latest update

### NPM Version

hoobs box latest update

### Homebridge/HOOBs Version

hoobs box latest update

### Homebridge Ring Plugin Version

hoobs box latest update

### Operating System

hoobs box latest update

**Comment by tsightler** [comment] 2024-02-02 19:50
Everything here would strongly indicate a networking issue as the code is working but RTP backups are being dropped.  Unfortunately, as there are no obvious code issues, I will have to close this issue as can't reproduce.

**Closed by tsightler** 2024-02-02 19:50 UTC
Labels: bug

**Comment by PvdGulik** [comment] 2024-02-02 22:37
Same problem here on iPhone. Not on iPad and MacBook.

**Comment by cryptoer-satoshi** [comment] 2024-05-10 12:46
I have the same problem ``
![Screenshot 2024-05-10 at 4 15 59 PM](https://github.com/dgreif/ring/assets/85187125/60446d84-1f36-4e1e-b9d6-a87f29e804ab)
